// Deutsch (Hauptsprache, Vorlage für alle anderen). f = Frage, a = Antworten (nur wenn nicht in meta.mjs), e = Erklärung nach der Auswertung.
export default {
  q01: { f: "Was musst du an diesem Zeichen tun?",
    a: ["Langsam weiterfahren, ohne anzuhalten", "Nur anhalten, wenn ein anderes Auto kommt", "Anhalten, auch wenn niemand kommt"],
    e: "Zeichen 206 („Halt! Vorfahrt gewähren“): Du musst anhalten und der kreuzenden Straße die Vorfahrt lassen, auch wenn kein anderes Fahrzeug zu sehen ist." },
  q02: { f: "Was bedeutet dieses Zeichen?",
    a: ["Ich habe Vorfahrt", "Ich muss die Vorfahrt der kreuzenden Straße beachten", "Ich muss hier immer anhalten"],
    e: "Zeichen 205 („Vorfahrt gewähren“): Du musst Fahrzeugen auf der kreuzenden Straße die Vorfahrt lassen. Anhalten musst du nur, wenn es nötig ist." },
  q03: { f: "Du siehst dieses Zeichen. Was gilt für dich?",
    a: ["Ich habe an den folgenden Kreuzungen und Einmündungen Vorfahrt", "Ich muss an der nächsten Kreuzung warten", "An der nächsten Kreuzung gilt rechts vor links"],
    e: "Zeichen 306 („Vorfahrtstraße“): Du hast an den folgenden Kreuzungen und Einmündungen Vorfahrt, bis ein Zeichen die Vorfahrtstraße beendet." },
  q04: { f: "Was bedeutet dieses Zeichen?",
    a: ["Ich habe hier Vorfahrt", "Ich darf hier nicht einfahren", "Ich darf hier nur langsam fahren"],
    e: "Zeichen 267 („Verbot der Einfahrt“) steht meist am Ende einer Einbahnstraße, gegen die Fahrtrichtung. Du darfst nicht einfahren." },
  q05: { f: "Was gilt an diesem Zeichen?",
    a: ["Ich darf hier bis zu 3 Minuten halten", "Ich darf hier nur parken, aber nicht halten", "Ich darf hier nicht halten"],
    e: "Zeichen 283 („Absolutes Haltverbot“): Du darfst dort nicht halten, auch nicht kurz. Parken ist damit erst recht verboten." },
  q06: { f: "Was gilt an diesem Zeichen?",
    a: ["Ich darf hier bis zu 3 Minuten halten, aber nicht parken", "Ich darf hier nie halten", "Ich darf hier beliebig lange parken"],
    e: "Zeichen 286 („Eingeschränktes Haltverbot“): Du darfst dort nur bis zu 3 Minuten halten. Parken ist verboten." },
  q07: { f: "Was bedeutet dieses Zeichen?",
    a: ["Mindestgeschwindigkeit 30 km/h", "Ende aller Geschwindigkeitsbegrenzungen", "Beginn einer Zone mit höchstens 30 km/h"],
    e: "Zeichen 274.1 („Tempo-30-Zone“): In der ganzen Zone sind höchstens 30 km/h erlaubt, bis ein Zeichen die Zone beendet." },
  q08: { f: "Du willst in diesen Kreisverkehr einfahren. Davor steht das Zeichen „Vorfahrt gewähren“. Wer hat Vorfahrt?",
    a: ["Die Fahrzeuge, die gerade einfahren wollen", "Die Fahrzeuge, die schon im Kreisverkehr fahren", "Das größte Fahrzeug"],
    e: "Zeichen 215 zeigt den Kreisverkehr. Mit dem Zeichen „Vorfahrt gewähren“ davor musst du den Fahrzeugen im Kreis die Vorfahrt lassen." },
  q09: { f: "Was bedeutet dieses Zeichen?",
    a: ["Einbahnstraße: Fahrzeuge dürfen nur in Pfeilrichtung fahren", "Vorfahrtstraße: Ich habe immer Vorfahrt", "Hier endet die Straße"],
    e: "Zeichen 220 („Einbahnstraße“): Fahrzeuge dürfen die Straße nur in Pfeilrichtung befahren. In die Gegenrichtung ist sie gesperrt." },
  q10: { f: "Ein Fußgänger will an diesem Zeichen die Straße überqueren. Was tust du?",
    a: ["Ich hupe, damit er wartet", "Ich fahre zuerst, wenn ich schnell genug bin", "Ich lasse ihn gehen und halte wenn nötig an"],
    e: "Zeichen 350 („Fußgängerüberweg“): Fußgänger, die den Überweg erkennbar benutzen wollen, haben Vorrang. Du musst vorsichtig heranfahren und wenn nötig anhalten." },
  q11: { f: "Was bedeutet dieses Zeichen?",
    a: ["Ich muss anhalten", "Gefahrstelle: Ich muss besonders aufmerksam fahren", "Ich habe Vorfahrt"],
    e: "Zeichen 101 („Gefahrstelle“) warnt vor einer Gefahr. Fahre aufmerksam und achte auf ein Zusatzzeichen, das die Gefahr nennt." },
  q12: { f: "Darf ein Auto auf dem Weg mit diesem Zeichen fahren?",
    a: ["Nein, der Weg ist für Radfahrer", "Ja, wenn die Straße frei ist", "Ja, aber nur mit Warnblinker"],
    e: "Zeichen 237 („Radweg“): Der Weg ist für Radfahrer. Autos dürfen dort nicht fahren." },
  q13: { f: "Was bedeutet dieses Zeichen?",
    a: ["Verbot der Einfahrt", "Nur für Anlieger frei", "Verbot für Fahrzeuge aller Art"],
    e: "Zeichen 250 („Verbot für Fahrzeuge aller Art“): Fahrzeuge, auch Fahrräder, dürfen hier nicht fahren." },
  q14: { f: "Was bedeutet dieses Zeichen?",
    a: ["Ein Haltverbot beginnt", "Alle bisherigen Streckenverbote enden", "Die Autobahn beginnt"],
    e: "Zeichen 282 („Ende sämtlicher Streckenverbote“) hebt vorher angeordnete Streckenverbote auf, zum Beispiel ein Tempolimit oder ein Überholverbot." },
  q15: { f: "Wie schnell darfst du innerorts als Pkw höchstens fahren, wenn kein Schild etwas anderes zeigt?",
    e: "Innerhalb geschlossener Ortschaften gilt für Pkw 50 km/h, wenn kein Zeichen etwas anderes anordnet." },
  q16: { f: "Wie schnell darfst du außerorts als Pkw ohne Anhänger auf einer Landstraße höchstens fahren, wenn kein Schild etwas anderes zeigt?",
    e: "Außerhalb von Ortschaften gilt für Pkw ohne Anhänger auf Landstraßen 100 km/h, wenn kein Zeichen etwas anderes anordnet." },
  q17: { f: "Welche Richtgeschwindigkeit gilt auf Autobahnen?",
    e: "Die Richtgeschwindigkeit von 130 km/h ist eine Empfehlung, kein Gebot. Wer schneller fährt, geht aber ein höheres Risiko ein." },
  q18: { f: "Du kommst an eine Kreuzung ohne Schilder und ohne Ampel. Von rechts nähert sich ein Auto. Was gilt?",
    a: ["Ich muss ihm die Vorfahrt lassen", "Ich habe Vorfahrt", "Wer schneller ist, fährt zuerst"],
    e: "„Rechts vor links“: Ohne Schilder und ohne Ampel hat Vorfahrt, wer von rechts kommt." },
  q19: { f: "Darfst du während der Fahrt das Handy in die Hand nehmen?",
    a: ["Ja, wenn ich langsam fahre", "Nein, das ist verboten", "Ja, aber nur zum Telefonieren"],
    e: "Ein Handy darf während der Fahrt nicht in die Hand genommen werden. Telefonieren geht nur mit Freisprecheinrichtung." },
  q20: { f: "Wer muss im Pkw grundsätzlich angeschnallt sein?",
    a: ["Nur der Fahrer", "Der Fahrer und der Beifahrer", "Alle Personen im Auto, auch hinten"],
    e: "Alle Insassen müssen den Sicherheitsgurt anlegen, auch auf den hinteren Sitzen." },
  q21: { f: "Wie müssen Kinder unter 12 Jahren, die kleiner als 150 cm sind, im Auto gesichert sein?",
    a: ["In einem passenden Kindersitz", "Mit dem normalen Gurt auf dem Beifahrersitz, ohne Kindersitz", "Auf dem Schoß eines Erwachsenen"],
    e: "Kinder unter 12 Jahren, die kleiner als 150 cm sind, brauchen im Auto ein passendes Kinderrückhaltesystem, also einen Kindersitz." },
  q22: { f: "Was gilt für Fahranfänger in der Probezeit und für alle Fahrer unter 21 Jahren beim Alkohol?",
    a: ["0,3 Promille sind erlaubt", "Kein Alkohol (0,0 Promille)", "0,5 Promille sind erlaubt"],
    e: "Für Fahranfänger in der Probezeit und für Fahrer unter 21 Jahren gilt ein absolutes Verbot für Alkohol und für Cannabis (THC) beim Fahren." },
  q23: { f: "Wie lange dauert die Probezeit für Fahranfänger?",
    a: ["6 Monate", "1 Jahr", "2 Jahre"],
    e: "Die Probezeit dauert 2 Jahre ab Erteilung der Fahrerlaubnis." },
  q24: { f: "Welcher Abstand zum Vordermann ist richtig?",
    a: ["Eine Autolänge", "So groß, dass ich auch bei plötzlichem Bremsen rechtzeitig anhalten kann", "Immer genau 10 Meter"],
    e: "Der Abstand muss so groß sein, dass du auch hinter dem Vordermann halten kannst, wenn er plötzlich bremst. Faustregel: Der Abstand in Metern sollte mindestens der halbe Tachowert sein." },
  q25: { f: "Wie lang ist der Bremsweg bei 50 km/h nach der Faustformel auf trockener Straße?",
    e: "Bremsweg = (Geschwindigkeit : 10) × (Geschwindigkeit : 10). Bei 50 km/h sind das 5 × 5 = 25 m. Der Anhalteweg ist länger, weil die Reaktion noch dazukommt." },
  q26: { f: "Du fährst doppelt so schnell. Wie lang wird der Bremsweg?",
    a: ["Doppelt so lang", "Dreimal so lang", "Viermal so lang"],
    e: "Der Bremsweg wächst mit dem Quadrat der Geschwindigkeit: Doppeltes Tempo bedeutet vierfachen Bremsweg." },
  q27: { f: "Wie lang ist der Reaktionsweg bei 50 km/h nach der Faustformel?",
    e: "Reaktionsweg = (Geschwindigkeit : 10) × 3. Bei 50 km/h sind das 5 × 3 = 15 m, die du fährst, bevor du bremst." },
  q28: { f: "Wo darfst du auf keinen Fall überholen?",
    a: ["Vor einer unübersichtlichen Kurve", "Auf einer geraden, freien Landstraße", "Auf der linken Spur einer Autobahn"],
    e: "Überholen darf nur, wer die Strecke einsehen kann. Vor einer unübersichtlichen Kurve oder einer Kuppe ist Überholen verboten." },
  q29: { f: "Du überholst innerorts einen Radfahrer. Welchen seitlichen Abstand musst du mindestens einhalten?",
    e: "Beim Überholen von Radfahrern, Fußgängern und E-Scootern gilt innerorts mindestens 1,5 m, außerorts mindestens 2 m Seitenabstand." },
  q30: { f: "Bis zu wie viel Metern vor einer Kreuzung ist das Parken verboten, wenn rechts neben der Fahrbahn kein Radweg angelegt ist?",
    e: "Vor und hinter Kreuzungen und Einmündungen ist Parken bis zu je 5 m von den Schnittpunkten der Fahrbahnkanten verboten. Ist rechts neben der Fahrbahn ein Radweg baulich angelegt, sind es vor der Kreuzung bis zu 8 m. Die 15 m gelten für Haltestellen (Zeichen 224), nicht für Kreuzungen." },
  q31: { f: "Wie weit vor und hinter einem Haltestellenschild (Bushaltestelle) ist Parken verboten?",
    e: "Vor und hinter dem Haltestellenschild (Zeichen 224) darfst du bis zu je 15 m nicht parken." },
  q32: { f: "Auf einer Autobahn mit drei Fahrstreifen pro Richtung staut sich der Verkehr. Wo bildest du die Rettungsgasse?",
    a: ["Auf dem Standstreifen", "Zwischen dem mittleren und dem rechten Fahrstreifen", "Zwischen dem linken und dem mittleren Fahrstreifen"],
    e: "Die Rettungsgasse entsteht zwischen dem linken und den anderen Fahrstreifen: Fahrzeuge auf der linken Spur weichen nach links aus, alle anderen nach rechts." },
  q33: { f: "Ein Rettungswagen mit Blaulicht und Martinshorn nähert sich von hinten. Was tust du?",
    a: ["Ich fahre schneller, damit er nicht überholen muss", "Ich schaffe sofort freie Bahn", "Ich fahre normal weiter"],
    e: "Bei Blaulicht und Martinshorn musst du sofort freie Bahn schaffen, zum Beispiel an den Rand fahren und wenn nötig anhalten." },
  q34: { f: "Die Ampel schaltet auf Gelb, und du kannst noch sicher anhalten. Was musst du tun?",
    a: ["Anhalten", "Noch schnell durchfahren", "Schneller fahren"],
    e: "Gelb ordnet an, vor der Kreuzung auf das nächste Zeichen zu warten." },
  q35: { f: "Die Ampel zeigt Rot, daneben hängt ein Schild mit grünem Pfeil nach rechts. Was gilt, wenn du rechts abbiegen willst?",
    a: ["Ich darf ohne Halt abbiegen", "Ich darf nur bei Grün abbiegen", "Ich darf nach dem Anhalten abbiegen, wenn ich niemanden gefährde oder behindere"],
    e: "Beim Grünpfeil musst du zuerst anhalten. Dann darfst du nach rechts abbiegen, wenn du niemanden gefährdest oder behinderst, vor allem keine Fußgänger und Radfahrer. Du darfst auch warten, bis die Ampel Grün zeigt." },
  q36: { f: "Ein Polizist regelt die Kreuzung mit Handzeichen. Die Ampel zeigt für dich Grün. Was gilt?",
    a: ["Die Ampel gilt", "Die Zeichen des Polizisten gehen vor", "Ich entscheide selbst"],
    e: "Zeichen und Weisungen von Polizisten gehen Ampeln und Verkehrszeichen vor." },
  q37: { f: "Du biegst rechts ab. Fußgänger wollen die Straße überqueren, in die du abbiegst. Was gilt?",
    a: ["Ich muss sie durchlassen und wenn nötig warten", "Sie müssen warten, weil ich abbiege", "Wer zuerst da ist, hat Vorrang"],
    e: "Wer abbiegt, muss Fußgänger durchlassen, die die Straße überqueren, in die er einbiegt, und wenn nötig warten." },
  q38: { f: "Du willst links abbiegen. Ein Auto kommt dir entgegen und fährt geradeaus. Wer hat Vorfahrt?",
    a: ["Ich", "Das schnellere Auto", "Das Auto, das geradeaus fährt"],
    e: "Wer links abbiegt, muss entgegenkommende Fahrzeuge durchlassen, die geradeaus fahren oder rechts abbiegen." },
  q39: { f: "Du fährst auf einem Beschleunigungsstreifen auf die Autobahn auf. Wer hat Vorfahrt?",
    a: ["Der Verkehr auf der durchgehenden Fahrbahn", "Ich, weil ich beschleunige", "Wer weiter rechts fährt"],
    e: "Auf der Autobahn hat Vorfahrt, wer auf der durchgehenden Fahrbahn fährt. Du passt deine Geschwindigkeit an und fädelst dich ein, ohne andere zu behindern." },
  q40: { f: "Dein Auto hat auf einer Landstraße eine Panne. In welcher Entfernung hinter dem Auto stellst du das Warndreieck etwa auf?",
    e: "Außerorts stellst du das Warndreieck etwa 100 m hinter dem Fahrzeug auf, innerorts etwa 50 m, damit andere Fahrer früh genug gewarnt werden." },
  q41: { f: "Wie schnell darfst du in einem verkehrsberuhigten Bereich (Zeichen 325.1) fahren?",
    a: ["30 km/h", "50 km/h", "Schrittgeschwindigkeit"],
    e: "Im verkehrsberuhigten Bereich ist nur Schrittgeschwindigkeit erlaubt. Fußgänger dürfen die ganze Straße nutzen und dürfen nicht behindert werden." },
  q42: { f: "Du fährst vom Fahrbahnrand an. Was ist richtig?",
    a: ["Hupen reicht aus", "Blinken und mich vergewissern, dass ich niemanden gefährde", "Der fließende Verkehr muss mich durchlassen"],
    e: "Wer anfahren will, muss sich so verhalten, dass andere nicht gefährdet werden: in den Spiegel und über die Schulter schauen und blinken." },
  q43: { f: "Wann gilt in Deutschland die Winterreifenpflicht?",
    a: ["Bei Glatteis, Schneeglätte, Schneematsch, Eis- oder Reifglätte", "Vom 1. Oktober bis zum 31. März", "Nur in den Bergen"],
    e: "Eine feste Jahreszeit gibt es nicht: Bei Glatteis, Schneeglätte, Schneematsch, Eis- oder Reifglätte brauchst du Winterreifen." },
  q44: { f: "Du darfst die Nebelschlussleuchte nur einschalten, wenn die Sichtweite durch Nebel unter … liegt.",
    e: "Die Nebelschlussleuchte blendet andere Fahrer. Sie darf nur bei Sichtweiten unter 50 m an sein und muss danach wieder aus." },
  q45: { f: "Was bedeutet dieses Zeichen?",
    a: ["Überholverbot für Kraftfahrzeuge aller Art", "Ende des Überholverbots", "Überholverbot nur für Lastwagen"],
    e: "Zeichen 276 („Überholverbot für Kraftfahrzeuge aller Art“): Kraftfahrzeuge dürfen mehrspurige Kraftfahrzeuge nicht überholen, bis ein Zeichen das Verbot beendet." },
  q46: { f: "Was zeigt dieses Zeichen an?",
    a: ["Hier endet die Vorfahrtstraße", "An der nächsten Kreuzung muss ich anhalten", "An der nächsten Kreuzung oder Einmündung habe ich Vorfahrt"],
    e: "Zeichen 301 („Vorfahrt“) zeigt an, dass du an der nächsten Kreuzung oder Einmündung Vorfahrt hast. Zeichen 306 („Vorfahrtstraße“) gilt dagegen über mehrere Kreuzungen." },
  q47: { f: "Was bedeutet dieses Zeichen?",
    a: ["Fußgänger und Radfahrer dürfen diesen Weg benutzen", "Nur Fußgänger dürfen diesen Weg benutzen", "Hier beginnt eine Fußgängerzone"],
    e: "Zeichen 239 („Gehweg“): Der Weg ist für Fußgänger. Anderer Verkehr darf ihn nicht benutzen, außer ein Zusatzzeichen erlaubt es." },
  q48: { f: "Was bedeutet dieses Zeichen?",
    a: ["Ich muss rechts vorbeifahren", "Ich muss hier nach rechts abbiegen", "Ich darf hier rechts parken"],
    e: "Zeichen 222 („Rechts vorbei“): Du musst an dem Hindernis, zum Beispiel einer Verkehrsinsel, rechts vorbeifahren." },
  q49: { f: "Was bedeutet dieses Zeichen?",
    a: ["Ich habe nach rechts Vorfahrt", "Rechts ist die Straße gesperrt", "Ich darf nur nach rechts fahren"],
    e: "Zeichen 209 („Vorgeschriebene Fahrtrichtung: rechts“): Du musst hier nach rechts fahren. Geradeaus oder nach links zu fahren ist nicht erlaubt." },
  q50: { f: "Was bedeutet dieses Zeichen?",
    a: ["Achtung Kinder: Ich muss besonders aufmerksam fahren und bremsbereit sein", "Ich muss hier anhalten", "Kinder haben hier immer Vorfahrt"],
    e: "Zeichen 136 („Kinder“) warnt vor Kindern auf oder an der Straße. Fahre langsam und bremsbereit. Das Zeichen verlangt kein Anhalten und gibt Kindern keine Vorfahrt." },
  q51: { f: "Du willst in einen Kreisverkehr einfahren. Davor stehen die Zeichen „Vorfahrt gewähren“ und „Kreisverkehr“. Was gilt für den Blinker beim Einfahren?",
    a: ["Ich muss rechts blinken", "Ich darf nicht blinken", "Ich muss links blinken"],
    e: "Bei der Einfahrt in einen solchen Kreisverkehr ist der Fahrtrichtungsanzeiger unzulässig. Du darfst beim Einfahren also nicht blinken." },
  q52: { f: "Wie weit vor einer Gefahrstelle stehen Gefahrzeichen außerhalb von Ortschaften im Allgemeinen?",
    e: "Außerhalb von Ortschaften stehen Gefahrzeichen im Allgemeinen 150 bis 250 m vor der Gefahrstelle. Innerhalb von Ortschaften stehen sie kurz vor der Gefahrstelle. Ein Zusatzzeichen kann eine geringere Entfernung nennen." },
  q53: { f: "Bis zu wie viel Metern vor einer Ampel darfst du nicht halten, wenn du sie dadurch verdeckst?",
    e: "Wer ein Fahrzeug führt, darf bis zu 10 m vor einem Lichtzeichen nicht halten, wenn es dadurch verdeckt wird. So können alle die Ampel sehen." },
  q54: { f: "Die Sichtweite beträgt wegen Nebel weniger als 50 m. Wie schnell darfst du höchstens fahren?",
    e: "Beträgt die Sichtweite durch Nebel, Schneefall oder Regen weniger als 50 m, darf nicht schneller als 50 km/h gefahren werden, wenn nicht eine geringere Geschwindigkeit geboten ist. Oft ist langsamer fahren klüger." },
  q55: { f: "Du näherst dich einem Fußgängerüberweg (Zebrastreifen). Vor dir fährt langsam ein Auto. Darfst du es dort überholen?",
    a: ["Ja, wenn kein Fußgänger zu sehen ist", "Ja, wenn ich dabei hupe", "Nein, an Fußgängerüberwegen darf nicht überholt werden"],
    e: "An Fußgängerüberwegen darf nicht überholt werden, auch wenn gerade niemand über die Straße geht." },
  q56: { f: "Der Verkehr stockt. Deine Ampel zeigt Grün, aber hinter der Kreuzung ist kein Platz für dein Auto. Was gilt?",
    a: ["Ich darf nicht einfahren, wenn ich auf der Kreuzung warten müsste", "Ich fahre ein, weil ich Grün habe", "Ich fahre ein und hupe, damit die anderen Platz machen"],
    e: "Stockt der Verkehr, darf trotz Grün nicht in die Kreuzung eingefahren werden, wenn dort gewartet werden müsste. So bleibt die Kreuzung für den Querverkehr frei." },
  q57: { f: "Du fährst auf einer Landstraße mit einem Fahrstreifen je Richtung. Wo musst du grundsätzlich fahren?",
    a: ["In der Mitte der Fahrbahn", "Nur bei Gegenverkehr möglichst weit rechts", "Möglichst weit rechts"],
    e: "Es ist immer möglichst weit rechts zu fahren, nicht nur bei Gegenverkehr, beim Überholtwerden, an Kuppen, in Kurven oder bei Unübersichtlichkeit." },
  q58: { f: "Wo ist schon das Halten (nicht nur das Parken) verboten?",
    a: ["Am rechten Fahrbahnrand einer breiten, übersichtlichen Straße", "An engen und unübersichtlichen Straßenstellen", "Auf einem gekennzeichneten Parkstreifen"],
    e: "Das Halten ist unter anderem an engen und an unübersichtlichen Straßenstellen unzulässig, ebenso im Bereich scharfer Kurven und auf Bahnübergängen." },
  q59: { f: "Du willst rechts abbiegen. Wo ordnest du dich rechtzeitig ein?",
    a: ["Möglichst weit rechts", "In der Mitte der Fahrbahn", "Möglichst weit links"],
    e: "Wer nach rechts abbiegen will, ordnet sein Fahrzeug rechtzeitig möglichst weit rechts ein. Wer nach links abbiegen will, ordnet sich bis zur Mitte ein, auf Fahrbahnen für eine Richtung möglichst weit links." },
  q60: { f: "Du fährst nachts auf einer Straße mit durchgehender, ausreichender Beleuchtung. Welches Licht benutzt du?",
    a: ["Nur das Standlicht", "Das Fernlicht", "Das Abblendlicht"],
    e: "Mit Standlicht allein darf nicht gefahren werden. Auf Straßen mit durchgehender, ausreichender Beleuchtung darf auch nicht mit Fernlicht gefahren werden. Du fährst also mit Abblendlicht." },
};
