// English. Traffic rules are the German ones (StVO); sign numbers are the German sign numbers.
export default {
  q01: { f: "What must you do at this sign?",
    a: ["Drive on slowly without stopping", "Stop only if another car is coming", "Stop, even if nobody is coming"],
    e: "Sign 206 (“Stop! Give way”): you must stop and give way to the crossing road, even if no other vehicle is in sight." },
  q02: { f: "What does this sign mean?",
    a: ["I have the right of way", "I must give way to traffic on the crossing road", "I must always stop here"],
    e: "Sign 205 (“Give way”): you must let vehicles on the crossing road go first. You only have to stop if necessary." },
  q03: { f: "You see this sign. What applies to you?",
    a: ["I have the right of way at the following crossings and junctions", "I must wait at the next crossing", "At the next crossing, priority to the right applies"],
    e: "Sign 306 (“Priority road”): you have the right of way at the following crossings and junctions until a sign ends the priority road." },
  q04: { f: "What does this sign mean?",
    a: ["I have the right of way here", "I must not enter here", "I may only drive slowly here"],
    e: "Sign 267 (“No entry”) usually stands at the end of a one-way street, facing against the direction of travel. You must not enter." },
  q05: { f: "What applies at this sign?",
    a: ["I may stop here for up to 3 minutes", "I may park here, but not stop", "I must not stop here"],
    e: "Sign 283 (“No stopping”): you must not stop there, not even briefly. Parking is of course forbidden as well." },
  q06: { f: "What applies at this sign?",
    a: ["I may stop here for up to 3 minutes, but not park", "I may never stop here", "I may park here for as long as I like"],
    e: "Sign 286 (“Limited no stopping”): you may only stop there for up to 3 minutes. Parking is forbidden." },
  q07: { f: "What does this sign mean?",
    a: ["Minimum speed 30 km/h", "End of all speed limits", "Start of a zone with a maximum of 30 km/h"],
    e: "Sign 274.1 (“30 km/h zone”): in the whole zone the maximum speed is 30 km/h until a sign ends the zone." },
  q08: { f: "You want to enter this roundabout. The “Give way” sign stands before it. Who has the right of way?",
    a: ["Vehicles that want to enter now", "Vehicles that are already in the roundabout", "The biggest vehicle"],
    e: "Sign 215 shows the roundabout. With the “Give way” sign before it, you must let the vehicles in the circle go first." },
  q09: { f: "What does this sign mean?",
    a: ["One-way street: vehicles may only drive in the direction of the arrow", "Priority road: I always have the right of way", "The road ends here"],
    e: "Sign 220 (“One-way street”): vehicles may only use the road in the direction of the arrow. In the opposite direction it is closed." },
  q10: { f: "A pedestrian wants to cross the road at this sign. What do you do?",
    a: ["I honk so that he waits", "I go first if I am fast enough", "I let him cross and stop if necessary"],
    e: "Sign 350 (“Pedestrian crossing”): pedestrians who clearly want to use the crossing have priority. You must approach carefully and stop if necessary." },
  q11: { f: "What does this sign mean?",
    a: ["I must stop", "Danger spot: I must drive with extra care", "I have the right of way"],
    e: "Sign 101 (“Danger spot”) warns of a hazard. Drive carefully and look for an additional sign that names the danger." },
  q12: { f: "May a car drive on the path with this sign?",
    a: ["No, the path is for cyclists", "Yes, if the road is clear", "Yes, but only with hazard lights"],
    e: "Sign 237 (“Cycle path”): the path is for cyclists. Cars must not drive there." },
  q13: { f: "What does this sign mean?",
    a: ["No entry", "Access only for residents", "No vehicles of any kind"],
    e: "Sign 250 (“No vehicles of any kind”): vehicles, bicycles included, must not drive here." },
  q14: { f: "What does this sign mean?",
    a: ["A no-stopping zone begins", "All previous restrictions on the road section end", "The motorway begins"],
    e: "Sign 282 (“End of all restrictions”) cancels restrictions ordered earlier along the road, for example a speed limit or a no-overtaking rule." },
  q15: { f: "What is the maximum speed for a car in a built-up area if no sign shows anything else?",
    e: "Inside built-up areas, cars may drive 50 km/h unless a sign orders something else." },
  q16: { f: "What is the maximum speed for a car without a trailer on a country road outside built-up areas if no sign shows anything else?",
    e: "Outside built-up areas, cars without a trailer may drive 100 km/h on country roads unless a sign orders something else." },
  q17: { f: "What is the recommended speed on German motorways?",
    e: "The recommended speed of 130 km/h is a recommendation, not a rule. But driving faster means a higher risk." },
  q18: { f: "You reach a crossing with no signs and no traffic lights. A car approaches from the right. What applies?",
    a: ["I must give way to it", "I have the right of way", "Whoever is faster goes first"],
    e: "“Priority to the right”: with no signs and no traffic lights, the vehicle coming from the right has the right of way." },
  q19: { f: "May you pick up your mobile phone while driving?",
    a: ["Yes, if I drive slowly", "No, it is forbidden", "Yes, but only to make a call"],
    e: "You must not pick up a mobile phone while driving. Calling is only allowed with a hands-free system." },
  q20: { f: "Who must generally wear a seat belt in a car?",
    a: ["Only the driver", "The driver and the front passenger", "Everyone in the car, in the back too"],
    e: "All occupants must wear a seat belt, in the back seats too." },
  q21: { f: "How must children under 12 who are shorter than 150 cm be secured in a car?",
    a: ["In a suitable child seat", "With the normal belt on the front seat, without a child seat", "On an adult’s lap"],
    e: "Children under 12 who are shorter than 150 cm need a suitable child restraint system in the car, that is, a child seat." },
  q22: { f: "What applies to novice drivers in the probation period and to all drivers under 21 regarding alcohol?",
    a: ["0.3 per mille is allowed", "No alcohol at all (0.0 per mille)", "0.5 per mille is allowed"],
    e: "For novice drivers in the probation period and for drivers under 21, there is an absolute ban on alcohol and on cannabis (THC) while driving." },
  q23: { f: "How long does the probation period for novice drivers last?",
    a: ["6 months", "1 year", "2 years"],
    e: "The probation period lasts 2 years from the day the driving licence is issued." },
  q24: { f: "Which distance to the vehicle in front is correct?",
    a: ["One car length", "Large enough that I can stop in time even if it brakes suddenly", "Always exactly 10 metres"],
    e: "The distance must be large enough that you can stop behind the vehicle in front even if it brakes suddenly. Rule of thumb: the distance in metres should be at least half the speedometer reading." },
  q25: { f: "How long is the braking distance at 50 km/h by the rule of thumb on a dry road?",
    e: "Braking distance = (speed : 10) × (speed : 10). At 50 km/h that is 5 × 5 = 25 m. The stopping distance is longer because your reaction time comes on top." },
  q26: { f: "You drive twice as fast. How long does the braking distance become?",
    a: ["Twice as long", "Three times as long", "Four times as long"],
    e: "The braking distance grows with the square of the speed: double the speed means four times the braking distance." },
  q27: { f: "How long is the reaction distance at 50 km/h by the rule of thumb?",
    e: "Reaction distance = (speed : 10) × 3. At 50 km/h that is 5 × 3 = 15 m that you travel before you start to brake." },
  q28: { f: "Where must you never overtake?",
    a: ["Before a blind bend", "On a straight, clear country road", "In the left lane of a motorway"],
    e: "You may only overtake if you can see the road ahead. Before a blind bend or the top of a hill, overtaking is forbidden." },
  q29: { f: "You overtake a cyclist in a built-up area. What is the minimum sideways distance you must keep?",
    e: "When overtaking cyclists, pedestrians and e-scooters, you must keep at least 1.5 m in built-up areas and at least 2 m outside them." },
  q30: { f: "Up to how many metres before a crossing is parking forbidden if there is no cycle path next to the road on the right?",
    e: "Before and after crossings and junctions, parking is forbidden for up to 5 m each, measured from the points where the kerb lines meet. If a built cycle path runs along the right of the road, it is up to 8 m before the crossing. The 15 m apply to bus stops (sign 224), not to crossings." },
  q31: { f: "How far before and after a bus stop sign is parking forbidden?",
    e: "You must not park up to 15 m before and after the bus stop sign (sign 224)." },
  q32: { f: "Traffic is jammed on a motorway with three lanes in each direction. Where do you form the emergency lane?",
    a: ["On the hard shoulder", "Between the middle lane and the right lane", "Between the left lane and the middle lane"],
    e: "The emergency lane is formed between the left lane and the other lanes: vehicles in the left lane move to the left, all others move to the right." },
  q33: { f: "An ambulance with blue lights and siren approaches from behind. What do you do?",
    a: ["I drive faster so that it does not have to overtake", "I make way at once", "I drive on as normal"],
    e: "When you see blue lights and hear a siren, you must make way at once, for example by pulling over to the side and stopping if necessary." },
  q34: { f: "The traffic light turns amber and you can still stop safely. What must you do?",
    a: ["Stop", "Drive through quickly", "Drive faster"],
    e: "Amber orders you to wait before the crossing for the next signal." },
  q35: { f: "The traffic light shows red, and next to it is a sign with a green arrow pointing right. What applies if you want to turn right?",
    a: ["I may turn without stopping", "I may only turn on green", "After stopping I may turn if I endanger or obstruct nobody"],
    e: "At a green arrow you must stop first. Then you may turn right if you endanger or obstruct nobody, above all no pedestrians or cyclists. You may also wait until the light shows green." },
  q36: { f: "A police officer directs the crossing with hand signals. The traffic light is green for you. What applies?",
    a: ["The traffic light applies", "The officer’s signals come first", "I decide for myself"],
    e: "Signals and instructions from police officers take priority over traffic lights and traffic signs." },
  q37: { f: "You turn right. Pedestrians want to cross the road you are turning into. What applies?",
    a: ["I must let them cross and wait if necessary", "They must wait because I am turning", "Whoever is there first has priority"],
    e: "A turning driver must let pedestrians cross the road he is turning into, and wait if necessary." },
  q38: { f: "You want to turn left. A car comes towards you and goes straight on. Who has the right of way?",
    a: ["I do", "The faster car", "The car that goes straight on"],
    e: "A driver turning left must let oncoming vehicles go first that go straight on or turn right." },
  q39: { f: "You are on an acceleration lane joining the motorway. Who has the right of way?",
    a: ["Traffic on the through carriageway", "I do, because I am accelerating", "Whoever drives further to the right"],
    e: "On the motorway, traffic on the through carriageway has the right of way. You adjust your speed and merge without hindering others." },
  q40: { f: "Your car breaks down on a country road. At roughly what distance behind the car do you put up the warning triangle?",
    e: "Outside built-up areas you put the warning triangle up about 100 m behind the vehicle, in built-up areas about 50 m, so that other drivers are warned early enough." },
  q41: { f: "How fast may you drive in a traffic-calmed area (sign 325.1)?",
    a: ["30 km/h", "50 km/h", "Walking pace"],
    e: "In a traffic-calmed area only walking pace is allowed. Pedestrians may use the whole street and must not be hindered." },
  q42: { f: "You pull away from the kerb. What is right?",
    a: ["Honking is enough", "Signal and make sure I endanger nobody", "Passing traffic has to let me in"],
    e: "A driver pulling away must behave so that others are not endangered: check the mirror, look over your shoulder and signal." },
  q43: { f: "When does the winter tyre rule apply in Germany?",
    a: ["With black ice, snow-covered roads, slush, ice or frost", "From 1 October to 31 March", "Only in the mountains"],
    e: "There is no fixed season: with black ice, snow-covered roads, slush, ice or frost, you need winter tyres." },
  q44: { f: "You may only switch on the rear fog light if visibility through fog is below …",
    e: "The rear fog light dazzles other drivers. It may only be on when visibility is below 50 m and must be switched off afterwards." },
  q45: { f: "What does this sign mean?",
    a: ["No overtaking for all motor vehicles", "End of the overtaking ban", "No overtaking for lorries only"],
    e: "Sign 276 (“No overtaking for motor vehicles of all kinds”): motor vehicles must not overtake multi-track motor vehicles until a sign ends the ban." },
  q46: { f: "What does this sign show?",
    a: ["The priority road ends here", "I must stop at the next crossing", "I have the right of way at the next crossing or junction"],
    e: "Sign 301 (“Right of way”) shows that you have the right of way at the next crossing or junction. Sign 306 (“Priority road”), on the other hand, applies over several crossings." },
  q47: { f: "What does this sign mean?",
    a: ["Pedestrians and cyclists may use this path", "Only pedestrians may use this path", "A pedestrian zone begins here"],
    e: "Sign 239 (“Footpath”): the path is for pedestrians. Other traffic must not use it unless an additional sign allows it." },
  q48: { f: "What does this sign mean?",
    a: ["I must pass on the right", "I must turn right here", "I may park on the right here"],
    e: "Sign 222 (“Pass on the right”): you must pass the obstacle, for example a traffic island, on the right." },
  q49: { f: "What does this sign mean?",
    a: ["I have the right of way to the right", "The road is closed to the right", "I may only drive to the right"],
    e: "Sign 209 (“Compulsory direction: right”): you must go right here. Going straight on or turning left is not allowed." },
  q50: { f: "What does this sign mean?",
    a: ["Caution, children: I must drive extra carefully and be ready to brake", "I must stop here", "Children always have the right of way here"],
    e: "Sign 136 (“Children”) warns of children on or beside the road. Drive slowly and be ready to brake. The sign does not require you to stop and gives children no right of way." },
  q51: { f: "You want to enter a roundabout. In front of it are the signs “Give way” and “Roundabout”. What applies to your indicator when entering?",
    a: ["I must indicate right", "I must not indicate", "I must indicate left"],
    e: "When entering such a roundabout, using the indicator is not allowed. So you must not indicate when you enter." },
  q52: { f: "How far before a danger spot are warning signs generally placed outside built-up areas?",
    e: "Outside built-up areas, warning signs generally stand 150 to 250 m before the danger spot. Inside built-up areas they stand shortly before it. An additional sign can show a shorter distance." },
  q53: { f: "Up to how many metres before a traffic light must you not stop if you would hide it?",
    e: "A driver must not stop within 10 m before a traffic light if it would be hidden by the vehicle. This way everyone can see the light." },
  q54: { f: "Because of fog, visibility is less than 50 m. What is the highest speed you may drive?",
    e: "If visibility through fog, snowfall or rain is less than 50 m, you must not drive faster than 50 km/h, unless an even lower speed is called for. Driving slower is often wiser." },
  q55: { f: "You are approaching a pedestrian crossing (zebra crossing). A car is driving slowly ahead of you. May you overtake it there?",
    a: ["Yes, if no pedestrian is in sight", "Yes, if I sound my horn", "No, overtaking is not allowed at pedestrian crossings"],
    e: "Overtaking is not allowed at pedestrian crossings, even when nobody is crossing the road at that moment." },
  q56: { f: "Traffic is at a standstill. Your light is green, but there is no room for your car beyond the crossing. What applies?",
    a: ["I must not enter if I would have to wait on the crossing", "I enter because I have green", "I enter and sound my horn so the others make room"],
    e: "If traffic is at a standstill, you must not enter the crossing even on green if you would have to wait on it. This keeps the crossing free for cross traffic." },
  q57: { f: "You are driving on a country road with one lane in each direction. Where must you drive as a rule?",
    a: ["In the middle of the road", "Keep as far right as possible only when there is oncoming traffic", "As far to the right as possible"],
    e: "You must always keep as far right as possible, not only with oncoming traffic, when being overtaken, at crests, in bends or when visibility is poor." },
  q58: { f: "Where is even stopping (not only parking) forbidden?",
    a: ["At the right edge of a wide road with a clear view", "At narrow places and places with poor visibility", "In a marked parking bay"],
    e: "Stopping is not allowed, among other places, at narrow places and places with poor visibility, in sharp bends and on level crossings." },
  q59: { f: "You want to turn right. Where do you position yourself in good time?",
    a: ["As far to the right as possible", "In the middle of the road", "As far to the left as possible"],
    e: "If you want to turn right, you position your vehicle in good time as far to the right as possible. If you want to turn left, you position yourself up to the middle, or as far left as possible on one-way roads." },
  q60: { f: "You are driving at night on a road with continuous, sufficient street lighting. Which lights do you use?",
    a: ["Only the sidelights", "The main beam", "The dipped beam"],
    e: "You must not drive with sidelights alone. On roads with continuous, sufficient lighting you must not use the main beam either. So you drive with dipped beam." },
};
