// Español. Las normas son las alemanas (StVO); los números de las señales son los de las señales alemanas.
export default {
  q01: { f: "¿Qué tienes que hacer en esta señal?",
    a: ["Seguir despacio sin parar", "Parar solo si viene otro coche", "Parar, aunque no venga nadie"],
    e: "Señal 206 («¡Stop! Ceda el paso»): tienes que parar y ceder el paso a la calle que cruza, aunque no se vea ningún otro vehículo." },
  q02: { f: "¿Qué significa esta señal?",
    a: ["Tengo prioridad de paso", "Tengo que ceder el paso a los vehículos de la calle que cruza", "Tengo que parar siempre aquí"],
    e: "Señal 205 («Ceda el paso»): tienes que dejar pasar primero a los vehículos de la calle que cruza. Solo tienes que parar si es necesario." },
  q03: { f: "Ves esta señal. ¿Qué te corresponde?",
    a: ["Tengo prioridad en los siguientes cruces e intersecciones", "Tengo que esperar en el próximo cruce", "En el próximo cruce rige la prioridad de la derecha"],
    e: "Señal 306 («Calle con prioridad»): tienes prioridad en los siguientes cruces e intersecciones hasta que una señal termine la calle con prioridad." },
  q04: { f: "¿Qué significa esta señal?",
    a: ["Aquí tengo prioridad", "No puedo entrar aquí", "Aquí solo puedo ir despacio"],
    e: "Señal 267 («Entrada prohibida») suele estar al final de una calle de sentido único, en contra del sentido de la marcha. No puedes entrar." },
  q05: { f: "¿Qué rige en esta señal?",
    a: ["Puedo detenerme aquí hasta 3 minutos", "Puedo aparcar aquí, pero no detenerme", "No puedo detenerme aquí"],
    e: "Señal 283 («Parada prohibida»): no puedes detenerte allí, ni siquiera un momento. Aparcar queda prohibido con mayor razón." },
  q06: { f: "¿Qué rige en esta señal?",
    a: ["Puedo detenerme aquí hasta 3 minutos, pero no aparcar", "Nunca puedo detenerme aquí", "Puedo aparcar aquí todo el tiempo que quiera"],
    e: "Señal 286 («Parada limitada»): solo puedes detenerte allí hasta 3 minutos. Aparcar está prohibido." },
  q07: { f: "¿Qué significa esta señal?",
    a: ["Velocidad mínima 30 km/h", "Fin de todos los límites de velocidad", "Comienzo de una zona con máximo 30 km/h"],
    e: "Señal 274.1 («Zona 30»): en toda la zona la velocidad máxima es 30 km/h hasta que una señal termine la zona." },
  q08: { f: "Quieres entrar en esta rotonda. Antes hay una señal de «Ceda el paso». ¿Quién tiene prioridad?",
    a: ["Los vehículos que quieren entrar ahora", "Los vehículos que ya circulan por la rotonda", "El vehículo más grande"],
    e: "La señal 215 muestra la rotonda. Con la señal «Ceda el paso» delante, tienes que dejar pasar a los vehículos que ya están en el círculo." },
  q09: { f: "¿Qué significa esta señal?",
    a: ["Calle de sentido único: los vehículos solo pueden circular en la dirección de la flecha", "Calle con prioridad: siempre tengo prioridad", "Aquí termina la calle"],
    e: "Señal 220 («Sentido único»): los vehículos solo pueden usar la calle en la dirección de la flecha. En sentido contrario está cerrada." },
  q10: { f: "Un peatón quiere cruzar la calle en esta señal. ¿Qué haces?",
    a: ["Toco el claxon para que espere", "Paso primero si soy lo bastante rápido", "Le dejo cruzar y me detengo si hace falta"],
    e: "Señal 350 («Paso de peatones»): los peatones que quieren usar claramente el paso tienen prioridad. Debes acercarte con cuidado y detenerte si hace falta." },
  q11: { f: "¿Qué significa esta señal?",
    a: ["Tengo que parar", "Peligro: tengo que conducir con especial atención", "Tengo prioridad"],
    e: "Señal 101 («Peligro») avisa de un peligro. Conduce con atención y busca un panel adicional que indique cuál es el peligro." },
  q12: { f: "¿Puede circular un coche por el camino con esta señal?",
    a: ["No, el camino es para ciclistas", "Sí, si la vía está libre", "Sí, pero solo con las luces de emergencia"],
    e: "Señal 237 («Vía ciclista»): el camino es para ciclistas. Los coches no pueden circular por allí." },
  q13: { f: "¿Qué significa esta señal?",
    a: ["Entrada prohibida", "Solo para residentes", "Circulación prohibida a vehículos de todo tipo"],
    e: "Señal 250 («Circulación prohibida a vehículos de todo tipo»): los vehículos, incluidas las bicicletas, no pueden circular aquí." },
  q14: { f: "¿Qué significa esta señal?",
    a: ["Empieza una prohibición de parada", "Terminan todas las prohibiciones anteriores del tramo", "Empieza la autopista"],
    e: "Señal 282 («Fin de todas las prohibiciones del tramo») anula las prohibiciones ordenadas antes, por ejemplo un límite de velocidad o una prohibición de adelantar." },
  q15: { f: "¿Cuál es la velocidad máxima de un turismo en población si ninguna señal indica otra cosa?",
    e: "Dentro de poblaciones los turismos pueden ir a 50 km/h si ninguna señal ordena otra cosa." },
  q16: { f: "¿Cuál es la velocidad máxima de un turismo sin remolque en una carretera fuera de poblaciones si ninguna señal indica otra cosa?",
    e: "Fuera de poblaciones, los turismos sin remolque pueden ir a 100 km/h en carreteras convencionales si ninguna señal ordena otra cosa." },
  q17: { f: "¿Qué velocidad recomendada rige en las autopistas alemanas?",
    e: "La velocidad recomendada de 130 km/h es una recomendación, no una obligación. Pero ir más rápido aumenta el riesgo." },
  q18: { f: "Llegas a un cruce sin señales ni semáforo. Se acerca un coche por la derecha. ¿Qué rige?",
    a: ["Tengo que cederle el paso", "Tengo prioridad", "Pasa primero el que sea más rápido"],
    e: "«Prioridad de la derecha»: sin señales ni semáforo, tiene prioridad el que viene por la derecha." },
  q19: { f: "¿Puedes coger el móvil con la mano mientras conduces?",
    a: ["Sí, si voy despacio", "No, está prohibido", "Sí, pero solo para llamar"],
    e: "No se puede coger el móvil mientras se conduce. Llamar solo está permitido con manos libres." },
  q20: { f: "¿Quién tiene que llevar puesto el cinturón de seguridad en un coche, por regla general?",
    a: ["Solo el conductor", "El conductor y el acompañante", "Todos los ocupantes, también atrás"],
    e: "Todos los ocupantes tienen que llevar el cinturón de seguridad, también en los asientos traseros." },
  q21: { f: "¿Cómo tienen que ir sujetos en el coche los niños menores de 12 años que miden menos de 150 cm?",
    a: ["En una silla infantil adecuada", "Con el cinturón normal en el asiento delantero, sin silla infantil", "En el regazo de un adulto"],
    e: "Los niños menores de 12 años que miden menos de 150 cm necesitan en el coche un sistema de retención infantil adecuado, es decir, una silla infantil." },
  q22: { f: "¿Qué rige para los conductores noveles en periodo de prueba y para todos los conductores menores de 21 años respecto al alcohol?",
    a: ["Se permiten 0,3 por mil", "Nada de alcohol (0,0 por mil)", "Se permiten 0,5 por mil"],
    e: "Para los conductores noveles en periodo de prueba y para los menores de 21 años rige una prohibición absoluta de alcohol y de cannabis (THC) al conducir." },
  q23: { f: "¿Cuánto dura el periodo de prueba de los conductores noveles?",
    a: ["6 meses", "1 año", "2 años"],
    e: "El periodo de prueba dura 2 años desde la concesión del permiso de conducir." },
  q24: { f: "¿Qué distancia respecto al vehículo de delante es correcta?",
    a: ["La longitud de un coche", "Tan grande que pueda parar a tiempo aunque frene de golpe", "Siempre exactamente 10 metros"],
    e: "La distancia debe ser tan grande que puedas parar detrás del vehículo de delante aunque frene de golpe. Regla práctica: la distancia en metros debería ser al menos la mitad de la velocidad que marca el velocímetro." },
  q25: { f: "¿Cuánto mide la distancia de frenado a 50 km/h según la regla práctica en carretera seca?",
    e: "Distancia de frenado = (velocidad : 10) × (velocidad : 10). A 50 km/h son 5 × 5 = 25 m. La distancia de detención es mayor porque se suma el tiempo de reacción." },
  q26: { f: "Vas el doble de rápido. ¿Cuánto se alarga la distancia de frenado?",
    a: ["El doble", "El triple", "Cuatro veces más"],
    e: "La distancia de frenado crece con el cuadrado de la velocidad: el doble de velocidad significa cuatro veces la distancia de frenado." },
  q27: { f: "¿Cuánto mide la distancia de reacción a 50 km/h según la regla práctica?",
    e: "Distancia de reacción = (velocidad : 10) × 3. A 50 km/h son 5 × 3 = 15 m que recorres antes de empezar a frenar." },
  q28: { f: "¿Dónde no debes adelantar en ningún caso?",
    a: ["Antes de una curva sin visibilidad", "En una carretera recta y despejada", "En el carril izquierdo de una autopista"],
    e: "Solo puedes adelantar si ves el tramo que tienes delante. Antes de una curva sin visibilidad o de un cambio de rasante, adelantar está prohibido." },
  q29: { f: "Adelantas a un ciclista en población. ¿Qué distancia lateral mínima tienes que dejar?",
    e: "Al adelantar a ciclistas, peatones y patinetes eléctricos hay que dejar al menos 1,5 m dentro de poblaciones y al menos 2 m fuera de ellas." },
  q30: { f: "¿Hasta cuántos metros antes de un cruce está prohibido aparcar si a la derecha de la calzada no hay carril bici?",
    e: "Antes y después de cruces e intersecciones está prohibido aparcar hasta 5 m a cada lado, medidos desde los puntos donde se unen los bordes de la calzada. Si a la derecha hay un carril bici construido, son hasta 8 m antes del cruce. Los 15 m valen para las paradas de autobús (señal 224), no para los cruces." },
  q31: { f: "¿Hasta qué distancia antes y después de la señal de una parada de autobús está prohibido aparcar?",
    e: "No puedes aparcar hasta 15 m antes y después de la señal de parada de autobús (señal 224)." },
  q32: { f: "El tráfico está parado en una autopista con tres carriles por sentido. ¿Dónde formas el pasillo de emergencia?",
    a: ["En el arcén", "Entre el carril central y el derecho", "Entre el carril izquierdo y el central"],
    e: "El pasillo de emergencia se forma entre el carril izquierdo y los demás: los vehículos del carril izquierdo se apartan hacia la izquierda y todos los demás hacia la derecha." },
  q33: { f: "Una ambulancia con luces azules y sirena se acerca por detrás. ¿Qué haces?",
    a: ["Acelero para que no tenga que adelantarme", "Le abro paso de inmediato", "Sigo conduciendo con normalidad"],
    e: "Con luces azules y sirena tienes que abrir paso de inmediato, por ejemplo apartándote al borde y deteniéndote si hace falta." },
  q34: { f: "El semáforo pasa a ámbar y todavía puedes parar con seguridad. ¿Qué tienes que hacer?",
    a: ["Parar", "Pasar rápido", "Acelerar"],
    e: "El ámbar ordena esperar antes del cruce hasta la siguiente señal." },
  q35: { f: "El semáforo está en rojo y al lado hay una señal con una flecha verde hacia la derecha. ¿Qué rige si quieres girar a la derecha?",
    a: ["Puedo girar sin parar", "Solo puedo girar con luz verde", "Después de parar puedo girar si no pongo en peligro ni molesto a nadie"],
    e: "Con la flecha verde tienes que parar primero. Después puedes girar a la derecha si no pones en peligro ni molestas a nadie, sobre todo a peatones y ciclistas. También puedes esperar hasta que el semáforo se ponga en verde." },
  q36: { f: "Un policía regula el cruce con gestos. El semáforo está en verde para ti. ¿Qué rige?",
    a: ["Vale el semáforo", "Las señales del policía tienen preferencia", "Decido yo mismo"],
    e: "Las señales y las instrucciones de los agentes de policía tienen preferencia sobre los semáforos y las señales de tráfico." },
  q37: { f: "Giras a la derecha. Unos peatones quieren cruzar la calle a la que giras. ¿Qué rige?",
    a: ["Tengo que dejarles cruzar y esperar si hace falta", "Ellos tienen que esperar porque yo giro", "Tiene preferencia el que llegue primero"],
    e: "Quien gira tiene que dejar cruzar a los peatones que atraviesan la calle a la que entra, y esperar si hace falta." },
  q38: { f: "Quieres girar a la izquierda. Un coche viene de frente y sigue recto. ¿Quién tiene prioridad?",
    a: ["Yo", "El coche más rápido", "El coche que va recto"],
    e: "Quien gira a la izquierda tiene que dejar pasar primero a los vehículos que vienen de frente y van recto o giran a la derecha." },
  q39: { f: "Estás en un carril de aceleración para incorporarte a la autopista. ¿Quién tiene prioridad?",
    a: ["El tráfico de la calzada principal", "Yo, porque estoy acelerando", "El que va más a la derecha"],
    e: "En la autopista tiene prioridad quien circula por la calzada principal. Adaptas tu velocidad y te incorporas sin molestar a los demás." },
  q40: { f: "Tu coche se avería en una carretera. ¿A qué distancia aproximada detrás del coche pones el triángulo de emergencia?",
    e: "Fuera de poblaciones pones el triángulo unos 100 m detrás del vehículo y en población unos 50 m, para que los demás conductores se enteren con tiempo." },
  q41: { f: "¿A qué velocidad puedes ir en una zona de tráfico calmado (señal 325.1)?",
    a: ["30 km/h", "50 km/h", "A paso de peatón"],
    e: "En una zona de tráfico calmado solo se permite ir a paso de peatón. Los peatones pueden usar toda la calle y no se les debe molestar." },
  q42: { f: "Arrancas desde el borde de la calzada. ¿Qué es correcto?",
    a: ["Basta con tocar el claxon", "Poner el intermitente y asegurarme de que no pongo en peligro a nadie", "El tráfico que circula tiene que dejarme pasar"],
    e: "Quien arranca tiene que comportarse de modo que no ponga en peligro a otros: mirar el retrovisor y por encima del hombro y poner el intermitente." },
  q43: { f: "¿Cuándo rige en Alemania la obligación de neumáticos de invierno?",
    a: ["Con hielo negro, nieve en la calzada, aguanieve, hielo o escarcha", "Del 1 de octubre al 31 de marzo", "Solo en las montañas"],
    e: "No hay una época fija: con hielo negro, nieve en la calzada, aguanieve, hielo o escarcha necesitas neumáticos de invierno." },
  q44: { f: "Solo puedes encender la luz antiniebla trasera si la visibilidad por la niebla es inferior a …",
    e: "La luz antiniebla trasera deslumbra a otros conductores. Solo puede estar encendida con visibilidad inferior a 50 m y después hay que apagarla." },
  q45: { f: "¿Qué significa esta señal?",
    a: ["Prohibido adelantar para todos los vehículos de motor", "Fin de la prohibición de adelantar", "Prohibido adelantar solo para camiones"],
    e: "Señal 276 («Adelantamiento prohibido para vehículos de motor de todo tipo»): los vehículos de motor no pueden adelantar a vehículos de motor de varias huellas hasta que una señal ponga fin a la prohibición." },
  q46: { f: "¿Qué indica esta señal?",
    a: ["Aquí termina la carretera con prioridad", "En el próximo cruce tengo que parar", "En el próximo cruce o intersección tengo prioridad"],
    e: "La señal 301 («Prioridad») indica que tienes prioridad en el próximo cruce o intersección. La señal 306 («Carretera con prioridad»), en cambio, vale para varios cruces." },
  q47: { f: "¿Qué significa esta señal?",
    a: ["Peatones y ciclistas pueden usar este camino", "Solo los peatones pueden usar este camino", "Aquí empieza una zona peatonal"],
    e: "Señal 239 («Camino para peatones»): el camino es para peatones. Otro tráfico no puede usarlo, salvo que una señal adicional lo permita." },
  q48: { f: "¿Qué significa esta señal?",
    a: ["Tengo que pasar por la derecha", "Aquí tengo que girar a la derecha", "Aquí puedo aparcar a la derecha"],
    e: "Señal 222 («Paso obligatorio por la derecha»): tienes que pasar el obstáculo, por ejemplo una isleta, por la derecha." },
  q49: { f: "¿Qué significa esta señal?",
    a: ["Tengo prioridad hacia la derecha", "A la derecha la calle está cortada", "Solo puedo ir hacia la derecha"],
    e: "Señal 209 («Dirección obligatoria: derecha»): aquí tienes que ir a la derecha. Seguir recto o girar a la izquierda no está permitido." },
  q50: { f: "¿Qué significa esta señal?",
    a: ["Atención niños: tengo que conducir con especial cuidado y estar listo para frenar", "Aquí tengo que parar", "Aquí los niños siempre tienen prioridad"],
    e: "La señal 136 («Niños») advierte de niños en la calzada o junto a ella. Conduce despacio y listo para frenar. La señal no exige parar ni da prioridad a los niños." },
  q51: { f: "Quieres entrar en una rotonda. Delante están las señales «Ceda el paso» y «Rotonda». ¿Qué rige para el intermitente al entrar?",
    a: ["Tengo que poner el intermitente a la derecha", "No puedo poner el intermitente", "Tengo que poner el intermitente a la izquierda"],
    e: "Al entrar en una rotonda así, el intermitente no está permitido. Por tanto, no puedes poner el intermitente al entrar." },
  q52: { f: "¿A qué distancia antes de un punto peligroso suelen estar las señales de peligro fuera de poblado?",
    e: "Fuera de poblado, las señales de peligro suelen estar a 150 a 250 m antes del punto peligroso. Dentro de poblado están justo antes de él. Una señal adicional puede indicar una distancia menor." },
  q53: { f: "¿Hasta cuántos metros antes de un semáforo no puedes detenerte si lo tapas?",
    e: "Quien conduce un vehículo no puede detenerse hasta 10 m antes de un semáforo si lo tapa con el vehículo. Así todos pueden ver el semáforo." },
  q54: { f: "Por la niebla, la visibilidad es de menos de 50 m. ¿A qué velocidad máxima puedes ir?",
    e: "Si la visibilidad por niebla, nieve o lluvia es de menos de 50 m, no se puede ir a más de 50 km/h, a menos que haga falta una velocidad aún menor. A menudo es más prudente ir más despacio." },
  q55: { f: "Te acercas a un paso de peatones (cebra). Delante de ti va un coche despacio. ¿Puedes adelantarlo allí?",
    a: ["Sí, si no se ve a ningún peatón", "Sí, si toco la bocina", "No, en los pasos de peatones no se puede adelantar"],
    e: "En los pasos de peatones no se puede adelantar, aunque en ese momento no cruce nadie." },
  q56: { f: "El tráfico está parado. Tu semáforo está en verde, pero detrás del cruce no hay sitio para tu coche. ¿Qué rige?",
    a: ["No puedo entrar si tuviera que esperar en el cruce", "Entro porque tengo verde", "Entro y toco la bocina para que los demás hagan sitio"],
    e: "Si el tráfico está parado, no se puede entrar en el cruce ni con verde si habría que esperar en él. Así el cruce queda libre para el tráfico transversal." },
  q57: { f: "Circulas por una carretera con un carril por sentido. ¿Por dónde debes ir en principio?",
    a: ["Por el centro de la calzada", "Lo más a la derecha posible solo si viene tráfico de frente", "Lo más a la derecha posible"],
    e: "Siempre hay que ir lo más a la derecha posible, no solo con tráfico de frente, cuando te adelantan, en cambios de rasante, en curvas o con poca visibilidad." },
  q58: { f: "¿Dónde está prohibido incluso detenerse (no solo aparcar)?",
    a: ["En el borde derecho de una calle ancha y con buena visibilidad", "En tramos estrechos y con poca visibilidad", "En una banda de aparcamiento señalizada"],
    e: "Detenerse no está permitido, entre otros lugares, en tramos estrechos y con poca visibilidad, en curvas cerradas y en pasos a nivel." },
  q59: { f: "Quieres girar a la derecha. ¿Dónde te colocas con antelación?",
    a: ["Lo más a la derecha posible", "En el centro de la calzada", "Lo más a la izquierda posible"],
    e: "Quien quiere girar a la derecha coloca su vehículo a tiempo lo más a la derecha posible. Quien quiere girar a la izquierda se coloca hasta el centro, y en calzadas de un solo sentido lo más a la izquierda posible." },
  q60: { f: "Conduces de noche por una vía con alumbrado continuo y suficiente. ¿Qué luces usas?",
    a: ["Solo las luces de posición", "Las luces de carretera", "Las luces de cruce"],
    e: "No se puede circular solo con luces de posición. En vías con alumbrado continuo y suficiente tampoco se pueden usar las luces de carretera. Por tanto, circulas con luces de cruce." },
};
