// Kurdî (Kurmancî). Rêgez rêgezên trafîkê yên Almanyayê ne (StVO); hejmarên nîşanan hejmarên nîşanên Almanî ne. (Ji aliyê axaftvanekî ve hê nehatiye kontrolkirin.)
export default {
  q01: { f: "Li vê nîşanê divê tu çi bikî?",
    a: ["Hêdî berdewam bikim bêyî ku raweste", "Tenê heke erebeyek din were rawestim", "Rawestim, heta heke kes neyê jî"],
    e: "Nîşana 206 («Raweste! Rê bide»): divê tu rawestî û rê bidî rêya ku derbas dibe, heta heke ti wesayîtek din neyê dîtin jî." },
  q02: { f: "Ev nîşan çi tê wateyê?",
    a: ["Mafê min ê pêşiyê heye", "Divê ez rê bidim wesayîtên li ser rêya ku derbas dibe", "Li vir divê ez her tim rawestim"],
    e: "Nîşana 205 («Rê bide»): divê tu bila wesayîtên li ser rêya ku derbas dibe pêşî derbas bibin. Tenê heke pêwîst be rawestî." },
  q03: { f: "Tu vê nîşanê dibînî. Çi ji bo te derbasdar e?",
    a: ["Li çarrêyan û girêdanên jêrîn mafê min ê pêşiyê heye", "Divê ez li çarrêya pêş bisekinim", "Li çarrêya pêş qaîdeya «rast beriya çep» derbasdar e"],
    e: "Nîşana 306 («Rêya sereke»): li çarrêyan û girêdanên jêrîn mafê te yê pêşiyê heye heta ku nîşanek rêya sereke biqedîne." },
  q04: { f: "Ev nîşan çi tê wateyê?",
    a: ["Li vir mafê min ê pêşiyê heye", "Ez nikarim li vir bikevim", "Li vir tenê hêdî dikarim biajom"],
    e: "Nîşana 267 («Ketin qedexe ye») bi piranî li dawiya kolaneke yekalî ye, berevajî alîyê çûnê. Tu nikarî bikevî." },
  q05: { f: "Li vê nîşanê çi derbasdar e?",
    a: ["Li vir heta 3 hûrdeman dikarim bisekinim", "Li vir dikarim park bikim, lê nikarim bisekinim", "Li vir nikarim bisekinim"],
    e: "Nîşana 283 («Sekinîn bi temamî qedexe ye»): tu nikarî li wir bisekinî, heta bi kurtî jî. Park kirin hê bêtir qedexe ye." },
  q06: { f: "Li vê nîşanê çi derbasdar e?",
    a: ["Li vir heta 3 hûrdeman dikarim bisekinim, lê nikarim park bikim", "Li vir tu carî nikarim bisekinim", "Li vir dikarim çiqas bixwazim park bikim"],
    e: "Nîşana 286 («Sekinîna sînorkirî»): tu tenê heta 3 hûrdeman dikarî li wir bisekinî. Park kirin qedexe ye." },
  q07: { f: "Ev nîşan çi tê wateyê?",
    a: ["Leza herî kêm 30 km/h", "Dawiya hemû sînorkirinên lezê", "Destpêka herêmeke ku leza wê ya herî zêde 30 km/h ye"],
    e: "Nîşana 274.1 («Herêma 30 km/h»): di tevahiya herêmê de leza herî zêde 30 km/h ye heta ku nîşanek herêmê biqedîne." },
  q08: { f: "Tu dixwazî têkevî vê dorhêlê. Li pêşiya wê nîşana «Rê bide» heye. Mafê pêşiyê yê kê ye?",
    a: ["Yê wesayîtên ku niha dixwazin bikevin", "Yê wesayîtên ku jixwe di dorhêlê de diçin", "Yê wesayîta herî mezin"],
    e: "Nîşana 215 dorhêlê nîşan dide. Gava nîşana «Rê bide» li pêşiya wê ye, divê tu rê bidî wesayîtên di dorê de." },
  q09: { f: "Ev nîşan çi tê wateyê?",
    a: ["Kolana yekalî: wesayît tenê li alîyê tîrê dikarin biçin", "Rêya sereke: mafê min ê pêşiyê her tim heye", "Rê li vir diqede"],
    e: "Nîşana 220 («Kolana yekalî»): wesayît tenê li alîyê tîrê dikarin vê kolanê bi kar bînin. Alîyê berevajî girtî ye." },
  q10: { f: "Peya dixwaze li vê nîşanê kolanê derbas bike. Tu çi dikî?",
    a: ["Qirrînê lêdidim da ku bisekine", "Ez pêşî diçim heke têra xwe bilez bim", "Ez dihêlim derbas bibe û heke pêwîst be disekinim"],
    e: "Nîşana 350 («Derbasgeha peyayan»): peyayên ku bi eşkereyî dixwazin derbasgehê bi kar bînin pêşiyê hene. Divê tu bi baldarî nêzik bibî û heke pêwîst be bisekinî." },
  q11: { f: "Ev nîşan çi tê wateyê?",
    a: ["Divê ez rawestim", "Cihê metirsîdar: divê ez bi baldariya taybet biajom", "Mafê min ê pêşiyê heye"],
    e: "Nîşana 101 («Cihê metirsîdar») li ser metirsiyekê hişyar dike. Bi baldarî biajo û li tabloya zêde binêre ku metirsiyê dide nasîn." },
  q12: { f: "Gelo erebe dikare li ser rêya bi vê nîşanê biçe?",
    a: ["Na, rê ji bo bisiklêtvanan e", "Erê, heke rê vala be", "Erê, lê tenê bi çirayên tehlûkeyê"],
    e: "Nîşana 237 («Rêya bisiklêtê»): rê ji bo bisiklêtvanan e. Erebe li wir nikarin biçin." },
  q13: { f: "Ev nîşan çi tê wateyê?",
    a: ["Ketin qedexe ye", "Tenê ji bo niştecihan", "Derbasbûna hemû cureyên wesayîtan qedexe ye"],
    e: "Nîşana 250 («Derbasbûna hemû cureyên wesayîtan qedexe ye»): wesayît, bisiklêt jî di nav de, li vir nikarin biçin." },
  q14: { f: "Ev nîşan çi tê wateyê?",
    a: ["Qedexeya sekinînê dest pê dike", "Hemû qedexeyên berê yên rêyê diqedin", "Otobana dest pê dike"],
    e: "Nîşana 282 («Dawiya hemû qedexeyên rêyê») qedexeyên ku berê hatine danîn, wek sînora lezê an qedexeya derbaskirinê, radike." },
  q15: { f: "Heke tu nîşanek tiştekî din nîşan nede, leza herî zêde ya erebeyeke siwarî li navenda bajêr çiqas e?",
    e: "Di nav bajar û gundan de erebeyên siwarî dikarin bi 50 km/h biçin, heke nîşanek tiştekî din nefermîne." },
  q16: { f: "Heke tu nîşanek tiştekî din nîşan nede, leza herî zêde ya erebeyeke siwarî bê pêvek li ser rêyeke li derveyî bajêr çiqas e?",
    e: "Li derveyî bajêr erebeyên siwarî bê pêvek li ser rêyên asayî dikarin bi 100 km/h biçin, heke nîşanek tiştekî din nefermîne." },
  q17: { f: "Li otobanan kîjan leza pêşniyarkirî derbasdar e?",
    e: "Leza pêşniyarkirî ya 130 km/h pêşniyarek e, ne mecbûrî ye. Lê bilez ajotin xetereyê zêde dike." },
  q18: { f: "Tu digihîjî çarrêyeke bê nîşan û bê çiraya trafîkê. Ji rastê erebeyek nêzik dibe. Çi derbasdar e?",
    a: ["Divê ez rê bidim wê erebeyê", "Mafê min ê pêşiyê heye", "Yê bileztir pêşî diçe"],
    e: "«Rast beriya çep»: bê nîşan û bê çiraya trafîkê, yê ji rastê tê mafê pêşiyê heye." },
  q19: { f: "Gelo tu dikarî di dema ajotinê de têlefona desta bigirî destê xwe?",
    a: ["Erê, heke hêdî biajom", "Na, qedexe ye", "Erê, lê tenê ji bo telefonkirinê"],
    e: "Di dema ajotinê de têlefon nayê girtin destê xwe. Telefonkirin tenê bi amûra destazad (hands-free) destûr e." },
  q20: { f: "Di erebeyeke siwarî de bi gelemperî kî divê kemera ewlehiyê girê bide?",
    a: ["Tenê ajovan", "Ajovan û rêwiyê pêş", "Hemû kesên di erebeyê de, li paş jî"],
    e: "Hemû rêwî divê kemera ewlehiyê girê bidin, li kursiyên paş jî." },
  q21: { f: "Zarokên di bin 12 salî de yên ji 150 cm kurttir, di erebeyê de çawa divê werin parastin?",
    a: ["Di kursiyeke zarokan a minasib de", "Bi kemera asayî li kursiya pêş, bê kursiya zarokan", "Li ser çokê mirovekî mezin"],
    e: "Zarokên di bin 12 salî de yên ji 150 cm kurttir di erebeyê de pergaleke minasib a parastina zarokan, yanî kursiya zarokan, hewce dikin." },
  q22: { f: "Ji bo ajovanên nû di dema ceribandinê de û hemû ajovanên di bin 21 salî de derbarê alkolê de çi derbasdar e?",
    a: ["0,3 di hezarî de destûr e", "Qet alkol (0,0 di hezarî de)", "0,5 di hezarî de destûr e"],
    e: "Ji bo ajovanên nû di dema ceribandinê de û ajovanên di bin 21 salî de qedexeya mutleq a alkol û kannabîsê (THC) di dema ajotinê de heye." },
  q23: { f: "Dema ceribandinê ji bo ajovanên nû çiqas dewam dike?",
    a: ["6 meh", "1 sal", "2 sal"],
    e: "Dema ceribandinê ji roja dayîna ruhsata ajotinê 2 sal dewam dike." },
  q24: { f: "Kîjan dûrahî ji wesayîta pêş rast e?",
    a: ["Dirêjahiya erebeyekê", "Ewqas mezin ku ez karibim bi dem rawestim, heta heke ew ji nişkê ve fren bike", "Her tim tam 10 metre"],
    e: "Divê dûrahî ewqas mezin be ku tu karibî li pişt wesayîta pêş rawestî, heta heke ew ji nişkê ve fren bike. Qaîdeya hêsan: dûrahî bi metre divê herî kêm nîvê hejmara lezpîvanê be." },
  q25: { f: "Li ser rêya zuha, li gorî formûla hêsan, rêya frenê di 50 km/h de çiqas e?",
    e: "Rêya frenê = (lez : 10) × (lez : 10). Di 50 km/h de ev 5 × 5 = 25 m e. Rêya rawestinê dirêjtir e ji ber ku dema bertekê jî lê zêde dibe." },
  q26: { f: "Tu du carî bileztir diajoyî. Rêya frenê çiqas dibe?",
    a: ["Du caran dirêjtir", "Sê caran dirêjtir", "Çar caran dirêjtir"],
    e: "Rêya frenê bi çargoşeya lezê zêde dibe: leza du caran tê wateya rêya frenê ya çar caran." },
  q27: { f: "Li gorî formûla hêsan, rêya bertekê di 50 km/h de çiqas e?",
    e: "Rêya bertekê = (lez : 10) × 3. Di 50 km/h de ev 5 × 3 = 15 m e ku tu beriya destpêkirina frenê diçî." },
  q28: { f: "Li kû tu bi tu awayî nikarî derbas bikî?",
    a: ["Beriya zivirînekê ya ku nayê dîtin", "Li ser rêyeke rast û vala ya derveyî bajêr", "Li rêzika çepê ya otobanekê"],
    e: "Tu tenê dikarî derbas bikî heke rêya li pêşiya xwe bibînî. Beriya zivirînekê an serê girekî yê ku nayê dîtin derbaskirin qedexe ye." },
  q29: { f: "Tu li navenda bajêr bisiklêtvanekî derbas dikî. Herî kêm kîjan dûrahiya alî divê tu bihêlî?",
    e: "Di dema derbaskirina bisiklêtvan, peya û skûterên elektrîkî de, divê herî kêm 1,5 m li nav bajêr û herî kêm 2 m li derveyî bajêr dûrahî were hiştin." },
  q30: { f: "Heta çend metre beriya çarrêyekê park kirin qedexe ye, heke li milê rastê yê rêyê rêya bisiklêtê tune be?",
    e: "Beriya çarrêyan û girêdanan û piştî wan park kirin heta 5 m li her alî qedexe ye, ji xalên ku keviyên rêyê li hev digihîjin tê pîvandin. Heke li milê rastê yê rêyê rêyeke bisiklêtê ya avakirî hebe, beriya çarrêyê heta 8 m e. 15 m ji bo rawestgehên otobusê (nîşana 224) derbasdar e, ne ji bo çarrêyan." },
  q31: { f: "Çiqas beriya tabloya rawestgeha otobusê û piştî wê park kirin qedexe ye?",
    e: "Tu nikarî heta 15 m beriya tabloya rawestgeha otobusê (nîşana 224) û piştî wê park bikî." },
  q32: { f: "Trafîk li otobanekê bi sê rêzikan di her alî de rawestiyaye. Tu rêya ewlehiyê li kû çêdikî?",
    a: ["Li ser kêleka rêyê", "Di navbera rêzika navîn û ya rastê de", "Di navbera rêzika çepê û ya navîn de"],
    e: "Rêya ewlehiyê di navbera rêzika çepê û rêzikên din de çêdibe: wesayîtên rêzika çepê ber bi çepê ve diçin, hemû yên din ber bi rastê ve." },
  q33: { f: "Ambulansek bi çiraya şîn û sîrenê ji paş ve nêzik dibe. Tu çi dikî?",
    a: ["Bileztir diajom da ku neçar nebe derbas bike", "Yekser rê vedikim", "Wekî her tim berdewam dikim"],
    e: "Gava çiraya şîn û sîren hebe, divê tu yekser rê vekî, mînak bi çûna kêleka rêyê û heke pêwîst be sekinîn." },
  q34: { f: "Çiraya trafîkê dibe zer û tu hê jî dikarî bi ewlehî rawestî. Divê tu çi bikî?",
    a: ["Bisekinim", "Zû derbas bibim", "Bileztir bibim"],
    e: "Zer dihêle ku tu beriya çarrêyê li benda nîşana din bimînî." },
  q35: { f: "Çiraya trafîkê sor e û li tenişta wê tabloyek bi tîreke kesk ber bi rastê heye. Heke tu bixwazî ber bi rastê bizivirî çi derbasdar e?",
    a: ["Ez dikarim bêyî sekinînê bizivirim", "Ez tenê dikarim di çiraya kesk de bizivirim", "Piştî sekinînê ez dikarim bizivirim heke kesî nexim xetereyê û nehêlim kesî"],
    e: "Li tîra kesk divê tu pêşî rawestî. Paşê tu dikarî ber bi rastê bizivirî heke tu kesî nexî xetereyê û kesî asteng nekî, bi taybetî peya û bisiklêtvanan. Her wiha tu dikarî li bendê bimînî heta çira kesk bibe." },
  q36: { f: "Polîsek çarrêyê bi destan rêve dibe. Çira ji bo te kesk e. Çi derbasdar e?",
    a: ["Çira derbasdar e", "Nîşanên polîs pêşiyê hene", "Ez bi xwe biryar didim"],
    e: "Nîşan û fermanên polîsan ji çirayên trafîkê û nîşanên rê pêştir in." },
  q37: { f: "Tu ber bi rastê dizivirî. Peya dixwazin kolana ku tu têda dizivirî derbas bikin. Çi derbasdar e?",
    a: ["Divê ez bihêlim derbas bibin û heke pêwîst be bisekinim", "Divê ew bisekinin ji ber ku ez dizivirim", "Yê pêşî bigihîje pêşiyê heye"],
    e: "Yê ku dizivire divê peyayên ku kolana ku têda dizivire derbas dikin bihêle derbas bibin û heke pêwîst be bisekine." },
  q38: { f: "Tu dixwazî ber bi çepê bizivirî. Erebeyek rû bi rû tê û rast diçe. Mafê pêşiyê yê kê ye?",
    a: ["Yê min", "Yê erebeya bileztir", "Yê erebeya ku rast diçe"],
    e: "Yê ku ber bi çepê dizivire divê pêşî wesayîtên rû bi rû bihêle derbas bibin ên ku rast diçin an ber bi rastê dizivirin." },
  q39: { f: "Tu li rêzika lezgirkirinê yî û dikevî otobanê. Mafê pêşiyê yê kê ye?",
    a: ["Yê trafîka li ser rêya sereke", "Yê min, ji ber ku ez lez dikim", "Yê ku bêtir li rastê diçe"],
    e: "Li otobanê, yê ku li ser rêya sereke diçe mafê pêşiyê heye. Tu lezê xwe li hev dikî û bêyî asteng kirina yên din dikevî nav trafîkê." },
  q40: { f: "Erebeya te li ser rêyeke derveyî bajêr xera bû. Tu sêgoşeya hişyariyê nêzîkî çiqas li pişt erebeyê datînî?",
    e: "Li derveyî bajêr tu sêgoşeya hişyariyê nêzîkî 100 m li pişt wesayîtê datînî, li nav bajêr nêzîkî 50 m, da ku ajovanên din di wextê xwe de werin hişyarkirin." },
  q41: { f: "Li herêmeke trafîk-aram (nîşana 325.1) tu çiqas bilez dikarî biajoyî?",
    a: ["30 km/h", "50 km/h", "Bi lezeke gavavêtinê"],
    e: "Li herêmeke trafîk-aram tenê leza gavavêtinê destûr e. Peya dikarin tevahiya kolanê bi kar bînin û nabe ku werin astengkirin." },
  q42: { f: "Tu ji kêleka rêyê dest bi çûnê dikî. Çi rast e?",
    a: ["Qirrîn bes e", "Rênîşander didim û piştrast dibim ku kesî naxim xetereyê", "Trafîka ku diçe divê min bihêle derbas bibim"],
    e: "Yê ku dest bi çûnê dike divê wisa tevbigere ku yên din nekevin xetereyê: li neynikê û li ser milê xwe binêre û rênîşander bide." },
  q43: { f: "Li Almanyayê mecbûriya lastîkên zivistanê kengî derbasdar e?",
    a: ["Di dema cemed, berfa li ser rê, berfa şil, qeşa an cemedê de", "Ji 1ê Cotmehê heta 31ê Adarê", "Tenê li çiyan"],
    e: "Demsala sabît tune ye: di dema cemed, berfa li ser rê, berfa şil, qeşa an cemedê de lastîkên zivistanê hewce ne." },
  q44: { f: "Tu tenê dikarî çiraya mijê ya paşîn vêxî heke ji ber mijê dîtin ji … kêmtir be.",
    e: "Çiraya mijê ya paşîn çavê ajovanên din digire. Divê tenê dema dîtin ji 50 m kêmtir be vêketî be û paşê were vemirandin." },
  q45: { f: "Ev nîşan çi tê wateyê?",
    a: ["Qedexeya derbaskirinê ji bo hemû wesayîtên motordar", "Dawiya qedexeya derbaskirinê", "Qedexeya derbaskirinê tenê ji bo barhilgiran"],
    e: "Nîşana 276 («Qedexeya derbaskirinê ji bo hemû cureyên wesayîtên motordar»): wesayîtên motordar nikarin wesayîtên motordar ên çend-şopî derbas bikin heta ku nîşanek qedexeyê biqedîne." },
  q46: { f: "Ev nîşan çi nîşan dide?",
    a: ["Li vir rêya pêşîn diqede", "Li çarrêya piştî vê divê ez bisekinim", "Li çarrê an girêdana piştî vê pêşiya min heye"],
    e: "Nîşana 301 («Pêşî») nîşan dide ku li çarrê an girêdana piştî vê pêşiya te heye. Nîşana 306 («Rêya pêşîn») berovajî vê li ser çend çarrêyan derbasdar e." },
  q47: { f: "Ev nîşan çi tê wateyê?",
    a: ["Peya û bisiklêtvan dikarin vê rêyê bi kar bînin", "Tenê peya dikarin vê rêyê bi kar bînin", "Li vir herêmeke peyayan dest pê dike"],
    e: "Nîşana 239 («Rêya peyayan»): rê ji bo peyayan e. Trafîka din nikare wê bi kar bîne, heya ku tabloyeke zêde destûrê bide." },
  q48: { f: "Ev nîşan çi tê wateyê?",
    a: ["Divê ez ji aliyê rastê ve derbas bibim", "Li vir divê ez ber bi rastê bizivirim", "Li vir ez dikarim li rastê park bikim"],
    e: "Nîşana 222 («Ji rastê ve derbas bibe»): divê tu ji astengiyê, mînak girava trafîkê, ji aliyê rastê ve derbas bibî." },
  q49: { f: "Ev nîşan çi tê wateyê?",
    a: ["Ber bi rastê pêşiya min heye", "Li rastê rê girtî ye", "Ez tenê dikarim ber bi rastê biçim"],
    e: "Nîşana 209 («Alîyê mecbûrî: rast»): divê tu li vir ber bi rastê biçî. Rasterast çûyîn an zivirîna ber bi çepê ne destûr e." },
  q50: { f: "Ev nîşan çi tê wateyê?",
    a: ["Hişyar bin zarok: divê ez bi baldariya taybet bajom û ji bo frenê amade bim", "Li vir divê ez bisekinim", "Zarok li vir her dem pêşiya wan heye"],
    e: "Nîşana 136 («Zarok») ji zarokên li ser rê an li kêleka rê hişyar dike. Hêdî bajo û ji bo frenê amade be. Nîşan sekinînê naxwaze û pêşiyê nade zarokan." },
  q51: { f: "Tu dixwazî têkevî dorpêçekê. Li pêşiya wê nîşanên «Pêşiyê bide» û «Dorpêç» hene. Di dema têketinê de ji bo îşaretê çi derbasdar e?",
    a: ["Divê ez îşareta rastê bidim", "Nabe ku ez îşaretê bidim", "Divê ez îşareta çepê bidim"],
    e: "Dema têketina dorpêçeke bi vî awayî, bikaranîna îşareta zivirînê ne destûr e. Ji ber vê yekê di dema têketinê de nabe ku tu îşaretê bidî." },
  q52: { f: "Li derveyî bajaran nîşanên tehlûkeyê bi giştî çiqas beriya cihê tehlûkeyê datînin?",
    e: "Li derveyî bajaran nîşanên tehlûkeyê bi giştî 150 heta 250 m beriya cihê tehlûkeyê disekinin. Li hundirê bajaran piçekî beriya cihê tehlûkeyê disekinin. Tabloyeke zêde dikare dûrahiyeke kêmtir bide nîşan." },
  q53: { f: "Heta çend metre beriya çiraya trafîkê nabe ku tu bisekinî, heke tu wê bipêçî?",
    e: "Yê ku wesayîtê dajo nabe ku heta 10 m beriya çiraya trafîkê bisekine, heke wesayît wê bipêçe. Bi vî awayî her kes dikare çirayê bibîne." },
  q54: { f: "Ji ber mijê dîtin ji 50 m kêmtir e. Herî zêde bi çi leza dikarî bajoî?",
    e: "Heke ji ber mij, berf an baranê dîtin ji 50 m kêmtir be, nabe ku ji 50 km/h zûtir were ajotin, heya ku lezeke hê kêmtir hewce be. Gelek caran hêdîtir ajotin biaqiltir e." },
  q55: { f: "Tu nêzîkî derbasgeha peyayan (zebra) dibî. Li pêşiya te erebeyek hêdî diçe. Gelo li wir dikarî wê derbas bikî?",
    a: ["Erê, heke peya neyê dîtin", "Erê, heke qirrînê bidim", "Na, li derbasgehên peyayan derbaskirin ne destûr e"],
    e: "Li derbasgehên peyayan derbaskirin ne destûr e, tevî ku di wê gavê de kes ji kolanê derbas nabe." },
  q56: { f: "Trafîk disekine. Çiraya te kesk e, lê li pişt çarrêyê cih ji bo erebeya te tune. Çi derbasdar e?",
    a: ["Heke bibe ku divê ez li ser çarrêyê li bendê bimînim, nabe ez têkevim", "Ez têdikevim ji ber ku çiraya min kesk e", "Ez têdikevim û qirrînê lêdidim da ku yên din cih vekin"],
    e: "Heke trafîk bisekine, tewra di çiraya kesk de jî nabe ku were çarrêyê heke li wir divê were li bendê mayîn. Bi vî awayî çarrê ji bo trafîka berevaj vala dimîne." },
  q57: { f: "Tu li ser rêyeke derveyî bajêr diçî ku li her alî rêzikeke wê heye. Bi prensîbî divê tu li kû biçî?",
    a: ["Li navbera rêyê", "Tenê dema trafîka hevrû heye heya ku pêkan be li rastê", "Heya ku pêkan be li rastê"],
    e: "Her dem divê heya ku pêkan be li rastê were çûn, ne tenê dema trafîka hevrû heye, dema tu têyî derbaskirin, li serê girekî, li zivirînan an dema dîtin xirab e." },
  q58: { f: "Li kû tewra sekinîn (ne tenê park kirin) qedexe ye?",
    a: ["Li devê rastê yê kolaneke fireh û vekirî", "Li cihên teng û nediyar ên rêyê", "Li ser şerîta parkê ya nîşankirî"],
    e: "Sekinîn, di nav cihên din de, li cihên teng û nediyar ên rêyê, li zivirînên tûj û li ser derbasgehên trênê ne destûr e." },
  q59: { f: "Tu dixwazî ber bi rastê bizivirî. Tu di wextê xwe de xwe li kû datînî?",
    a: ["Heya ku pêkan be li rastê", "Li navbera rêyê", "Heya ku pêkan be li çepê"],
    e: "Yê ku dixwaze ber bi rastê bizivire, di wextê xwe de wesayîta xwe heya ku pêkan be li rastê datîne. Yê ku dixwaze ber bi çepê bizivire heta navberê xwe datîne, li ser rêyên yek alî heya ku pêkan be li çepê." },
  q60: { f: "Tu şevê li ser rêyeke bi ronahiya domdar û têrker diçî. Kîjan ronahiyê bi kar tînî?",
    a: ["Tenê çirayên sekinînê", "Ronahiya dûr", "Ronahiya nêzik"],
    e: "Nabe ku tenê bi çirayên sekinînê were ajotin. Li ser rêyên bi ronahiya domdar û têrker nabe ku bi ronahiya dûr jî were ajotin. Ji ber vê yekê tu bi ronahiya nêzik dajoî." },
};
