// Tarifit (tira Tilatinit, wafqa n lǧerman). Ur ttwaẓṛa ara sɣur win i yettmeslayen tutlayt-a, ilaq ad tettwaɛawed tɣuri. (Von keinem Muttersprachler geprüft.)
// Tisenfa d tisenfa n ṭṭeṛafik n Lalman (StVO); iṭṭuṭen n tlɛalamin d iṭṭuṭen n tlɛalamin n Lalman.
export default {
  q01: { f: "Acu ilaq ad txedmeḍ ɣer lɛalama-a?",
    a: ["Ad ddeɣ s unezzu ur ḥebseɣ ara", "Ad ḥebseɣ kan ma d-yusa ṭṭumubil nniḍen", "Ad ḥebseɣ, ula ɣer ur d-yusi ula d yiwen"],
    e: "Lɛalama 206 («Ḥbes! Ɛṭi ubrid»): yessefk ad tḥebseḍ u ad teǧǧeḍ abrid i d-ɛeddin, ula ɣer ur d-ibin ula d yiwen n umkkin nniḍen." },
  q02: { f: "Acu tɛni lɛalama-a?",
    a: ["Ɣur-i lḥeqq n ɛeddi", "Yessefk ad eǧǧeɣ imekkinen n ubrid i d-ɛeddin ad ɛeddin zik", "Dagi yessefk ad ḥebseɣ yal tikkelt"],
    e: "Lɛalama 205 («Ɛṭi ubrid»): yessefk ad teǧǧeḍ imekkinen n ubrid i d-ɛeddin ad ɛeddin zik. Yessefk ad tḥebseḍ kan ma yella lḥağa." },
  q03: { f: "Tẓṛeḍ lɛalama-a. Acu i k-yeɛnan?",
    a: ["Ɣur-i lḥeqq n ɛeddi di tilintiyin d ubrid yeḍfaren", "Yessefk ad rǧuɣ ɣer tilintit yeḍfaren", "Deg tilintit yeḍfaren yella lḥeqq n lyemmin"],
    e: "Lɛalama 306 («Abrid s lḥeqq n ɛeddi»): ɣur-k lḥeqq n ɛeddi di tilintiyin d ubrid yeḍfaren ar ad yekfu abrid s lɛalama." },
  q04: { f: "Acu tɛni lɛalama-a?",
    a: ["Dagi ɣur-i lḥeqq n ɛeddi", "Ur zemṛeɣ ara ad kcmeɣ dagi", "Dagi zemṛeɣ ad ddeɣ kan s unezzu"],
    e: "Lɛalama 267 («Mmenɛen ad tkecmeḍ») tella s waṭas di taggara n ubrid n yiwen n yiɣil, ɣer ujehha n waddar. Ur tzemṛeḍ ara ad tkecmeḍ." },
  q05: { f: "Acu yella ɣer lɛalama-a?",
    a: ["Zemṛeɣ ad ḥebseɣ dagi ar 3 n tdeqiqin", "Zemṛeɣ ad pareqeɣ dagi, maca ur zemṛeɣ ara ad ḥebseɣ", "Ur zemṛeɣ ara ad ḥebseɣ dagi"],
    e: "Lɛalama 283 («Mmenɛen lḥebs ula d yiwen»): ur tzemṛeḍ ara ad tḥebseḍ dinna, ula d s tazart. Tpareqit mmenɛen ula d nețța." },
  q06: { f: "Acu yella ɣer lɛalama-a?",
    a: ["Zemṛeɣ ad ḥebseɣ dagi ar 3 n tdeqiqin, maca ur zemṛeɣ ara ad pareqeɣ", "Ur zemṛeɣ ara ad ḥebseɣ dagi ula d yiwen n lweqt", "Zemṛeɣ ad pareqeɣ dagi achal i xseɣ"],
    e: "Lɛalama 286 («Lḥebs yettwahaddan»): tzemṛeḍ ad tḥebseḍ dinna kan ar 3 n tdeqiqin. Tpareqit mmenɛen." },
  q07: { f: "Acu tɛni lɛalama-a?",
    a: ["Sseṛɛa tamẓẓyant 30 km/h", "Taggara n meṛṛa tuḥdiwin n sseṛɛa", "Tazwara n tmnaṭ s sseṛɛa tameqqrant 30 km/h"],
    e: "Lɛalama 274.1 («Tamnaṭ 30 km/h»): deg tmnaṭ meṛṛa, sseṛɛa tameqqrant d 30 km/h ar ad tefk lɛalama taggara n tmnaṭ." },
  q08: { f: "Tebɣiḍ ad tkecmeḍ ɣer teɣrurt-a. Zdat-s tella lɛalama «Ɛṭi ubrid». Anwa ɣur-s lḥeqq n ɛeddi?",
    a: ["Imekkinen i yebɣan ad kecmen tura", "Imekkinen i ɣer ddan deg teɣrurt", "Ṭṭumubil ameqqran"],
    e: "Lɛalama 215 tebin teɣrurt. S lɛalama «Ɛṭi ubrid» zdat-s, yessefk ad teǧǧeḍ imekkinen n teɣrurt ad ɛeddin zik." },
  q09: { f: "Acu tɛni lɛalama-a?",
    a: ["Abrid n yiwen n ujehha: imekkinen ddan kan ɣer ujehha n tneccabt", "Abrid s lḥeqq n ɛeddi: ɣur-i lḥeqq n ɛeddi yal tikkelt", "Abrid yekfa dagi"],
    e: "Lɛalama 220 («Abrid n yiwen n ujehha»): imekkinen zemṛen ad sexdmen abrid kan ɣer ujehha n tneccabt. Deg ujehha nniḍen yeqqen." },
  q10: { f: "Yiwen n uẓenzu yebɣa ad yeɛdi abrid ɣer lɛalama-a. Acu txedmeḍ?",
    a: ["Ad ssusmeɣ ṭṭuṭ akken ad yerǧu", "Ad ɛeddiɣ zik ma zzerreɣ", "Ad t-eǧǧeɣ ad yeɛdi u ad ḥebseɣ ma yella lḥağa"],
    e: "Lɛalama 350 («Tilist n yiẓenzuyen»): iẓenzuyen i yebɣan ad sexdmen tilist s wudem ibanen ɣur-sen lḥeqq n ɛeddi. Yessefk ad tqerbeḍ s lḥeḍra u ad tḥebseḍ ma yella lḥağa." },
  q11: { f: "Acu tɛni lɛalama-a?",
    a: ["Yessefk ad ḥebseɣ", "Amkan n lxuf: yessefk ad ddeɣ s lḥeḍra yaṭṭan", "Ɣur-i lḥeqq n ɛeddi"],
    e: "Lɛalama 101 («Amkan n lxuf») tessawel ɣef lxuf. Dd s lḥeḍra u ẓeṛ tilɣa nniḍen i yeqqaren acu d lxuf." },
  q12: { f: "Yezmer ṭṭumubil ad yedd ɣer ubrid s lɛalama-a?",
    a: ["Ala, abrid i yimarkuben n tbaskilin", "Ih, ma yella abrid d ilem", "Ih, maca kan s tfeṛṛunin n lxuf"],
    e: "Lɛalama 237 («Abrid n tbaskilin»): abrid i yimarkuben n tbaskilin. Ṭṭumubilat ur zemṛent ara ad ddent dinna." },
  q13: { f: "Acu tɛni lɛalama-a?",
    a: ["Mmenɛen ad tkecmeḍ", "I yimezdaɣ kan", "Mmenɛen meṛṛa imekkinen"],
    e: "Lɛalama 250 («Mmenɛen meṛṛa imekkinen»): imekkinen, d tibaskilin, ur zemṛen ara ad ddin dagi." },
  q14: { f: "Acu tɛni lɛalama-a?",
    a: ["Tebda tmnaṭ n lḥebs mmenɛen", "Ttkfan meṛṛa tuḥdiwin yezwaren n ubrid", "Yebda otoṛut"],
    e: "Lɛalama 282 («Taggara n meṛṛa tuḥdiwin») tekkes tuḥdiwin i yettwaɛṭan zik ɣef ubrid, am tuḥdiwt n sseṛɛa neɣ n uɛeddi." },
  q15: { f: "Ma ur d-tbin ula d yiwet n lɛalama, achal n sseṛɛa tameqqrant n ṭṭumubil di tmnaṭ yettwasken?",
    e: "Deg tmnaṭ yettwasken, ṭṭumubilat zemṛent ad ddent s 50 km/h ma ur tefki ula d yiwet n lɛalama waxxa nniḍen." },
  q16: { f: "Ma ur d-tbin ula d yiwet n lɛalama, achal n sseṛɛa tameqqrant n ṭṭumubil ur nesɛi ara aẓeṭṭa ɣer ubrid ɣer berra n tmnaṭ yettwasken?",
    e: "Berra n tmnaṭ yettwasken, ṭṭumubilat ur nesɛi ara aẓeṭṭa zemṛent ad ddent s 100 km/h ɣef yibrida n lbaṛṛ ma ur tefki ula d yiwet n lɛalama waxxa nniḍen." },
  q17: { f: "Achal n sseṛɛa yettwasumer deg yotoṛuten?",
    e: "Sseṛɛa yettwasumer n 130 km/h d tasumert, mačči d lawamer. Maca aked ddu s uzzel akteṛ, lxuf yettazzayad." },
  q18: { f: "Tekcemeḍ ɣer tilintit war lɛalamat u war lfiṛu. Yiwen n ṭṭumubil yettaqṛab seg lyemmin. Acu yella?",
    a: ["Yessefk ad t-eǧǧeɣ ad ɛeddi zik", "Ɣur-i lḥeqq n ɛeddi", "Win yezzlen akteṛ ad ɛeddi zik"],
    e: "«Lyemmin zik»: war lɛalamat u war lfiṛu, win i d-yusan seg lyemmin ɣur-s lḥeqq n ɛeddi." },
  q19: { f: "Tzemṛeḍ ad tṭṭfeḍ ṭṭilifun deg ufus mi ara teddiḍ?",
    a: ["Ih, ma ddeɣ s unezzu", "Ala, mmenɛen", "Ih, maca kan i usawel"],
    e: "Ur tzemṛeḍ ara ad tṭṭfeḍ ṭṭilifun deg ufus mi ara teddiḍ. Asawel yettwaǧǧa kan s tmahaɛt war ufus." },
  q20: { f: "Anwa i yessefk ad yeqqen ajeṭṭa n tɣellist deg ṭṭumubil s umata?",
    a: ["Amarkub kan", "Amarkub d win yeqqimen zdat", "Meṛṛa wid yellan deg ṭṭumubil, ula d deffir"],
    e: "Meṛṛa wid yellan deg ṭṭumubil ilaq ad qqnen ajeṭṭa n tɣellist, ula d deg tkursiyin n deffir." },
  q21: { f: "Amek ilaq ad ttwaḥrezen warrac ddaw 12 n useggasen i yellan d imeẓẓyanen akteṛ n 150 cm deg ṭṭumubil?",
    a: ["Deg tkursit n warrac i yelhan", "S ujeṭṭa amagnu ɣer tkursit n zdat, war tkursit n warrac", "Ɣef tuyat n yiwen ameqqran"],
    e: "Warrac ddaw 12 n useggasen i yellan d imeẓẓyanen akteṛ n 150 cm ḥwaǧen deg ṭṭumubil anagraw n lḥerz n warrac i yelhan, d tkursit n warrac." },
  q22: { f: "Acu yella i imarkuben imaynuten deg lweqt n lmeḥna d meṛṛa imarkuben ddaw 21 n useggasen ɣef cceṛṛab?",
    a: ["0,3 deg wazal iɛebbi yettwaǧǧa", "Ur yelli cceṛṛab (0,0 deg wazal)", "0,5 deg wazal iɛebbi yettwaǧǧa"],
    e: "I imarkuben imaynuten deg lweqt n lmeḥna d imarkuben ddaw 21 n useggasen, cceṛṛab d ukanabis (THC) mmenɛen ula d yiwen asmi ttawin." },
  q23: { f: "Acḥal i yettɣimi lweqt n lmeḥna i imarkuben imaynuten?",
    a: ["6 n wayyuren", "1 n useggas", "2 n yiseggasen"],
    e: "Lweqt n lmeḥna yettɣimi 2 n yiseggasen seg wass n tefka n tsarutt n ubrid." },
  q24: { f: "Anwa i d lemsafa yelhan ɣer ṭṭumubil i yezwaren?",
    a: ["Aɣzif n yiwen n ṭṭumubil", "Meqqṛet akken ad zemṛeɣ ad ḥebseɣ deg lweqt, ula ma yefren s tazart", "Yal tikkelt 10 n tmeṭṭin akken"],
    e: "Lemsafa ilaq ad tili meqqṛet akken ad tzemṛeḍ ad tḥebseḍ deffir n ṭṭumubil i yezwaren, ula ma yefren s tazart. Ṭṭeṛiqa: lemsafa s tmeṭṭin ilaq ad tili nnefṣ n wuṭṭun n lɛaddad n sseṛɛa." },
  q25: { f: "Achal i d lemsafa n lfrinu ɣer 50 km/h s ṭṭeṛiqa lxfifa ɣef ubrid iyyuḍen?",
    e: "Lemsafa n lfrinu = (sseṛɛa : 10) × (sseṛɛa : 10). Ɣer 50 km/h d 5 × 5 = 25 m. Lemsafa n lḥebs d tameqqrant ṛṛad ɛlaḥsab lweqt n tririt." },
  q26: { f: "Teddiḍ s sseṛɛa tuzzigt snat n tikkal. Achal ara tili lemsafa n lfrinu?",
    a: ["Snat n tikkal ṭṭul", "Tlata n tikkal ṭṭul", "Ṛebɛa n tikkal ṭṭul"],
    e: "Lemsafa n lfrinu tettazzayad s ukwadṛat n sseṛɛa: sseṛɛa tuzzigt snat n tikkal tɛni lemsafa n lfrinu ṛebɛa n tikkal." },
  q27: { f: "Achal i d lemsafa n tririt ɣer 50 km/h s ṭṭeṛiqa lxfifa?",
    e: "Lemsafa n tririt = (sseṛɛa : 10) × 3. Ɣer 50 km/h d 5 × 3 = 15 m i tettɛeddiḍ uqbel ma tebdiḍ lfrinu." },
  q28: { f: "Anda ur ilaq ara ad tɛeddiḍ ula d yiwen n lweqt?",
    a: ["Uqbel n teɣrurt ur d-banen ara deg-s", "Ɣef ubrid n lbaṛṛ iqqimen d ilem", "Deg tdiwt tazelmaṭ n otoṛut"],
    e: "Tzemṛeḍ ad tɛeddiḍ kan ma tzemṛeḍ ad tẓṛeḍ abrid zdat-ek. Uqbel n teɣrurt ur d-banen ara deg-s neɣ uqbel n uqqaṛ n wayyaḍ, aɛeddi mmenɛen." },
  q29: { f: "Tɛeddiḍ amarkub n tbaskilt deg tmnaṭ yettwasken. Achal i d lemsafa tazellalt tamẓẓyant i yessefk ad teǧǧeḍ?",
    e: "Mi ara tɛeddiḍ imarkuben n tbaskilin, iẓenzuyen d iskutiren, yessefk ad teǧǧeḍ lemsafa n uzelmaḍ n 1,5 m ɣef tmnaṭ yettwasken d 2 m berra." },
  q30: { f: "Alamma d acḥal n lemtaṛ uqbel n tilintit i yettwamnɛen tpareqit, ma yella ur telli tseḍt n tbaskilin ɣer lyemmin n ubrid?",
    e: "Uqbel d deffir n tilintiyin, tpareqit mmenɛen ar 5 m i yal tama, ttwaqqsen seg tmura ɣer ara temsemlilen yiɣamen n ubrid. Ma yella tella tseḍt n tbaskilin yettwabnan ɣer lyemmin n ubrid, uqbel n tilintit d ar 8 m. 15 m i lmeḥṭat n ubbus (lɛalama 224) i d-ttwaxdment, mačči i tilintiyin." },
  q31: { f: "Achal n lemsafa, uqbel d deffir n lɛalama n lmeḥṭa n ubbus, i yettwamnɛen tpareqit?",
    e: "Ur tzemṛeḍ ara ad tparqeḍ ar 15 m uqbel d deffir n lɛalama n lmeḥṭa n ubbus (lɛalama 224)." },
  q32: { f: "Tikli n ṭṭeṛafik teqqen deg otoṛut s tlata n yiberdan deg yal tama. Anda ara tgeḍ abrid n lɛawan?",
    a: ["Ɣef tama n ubrid", "Garasen n ubrid n tlemmast d wayyaḍ n lyemmin", "Garasen n ubrid n lεecṛ d wayyaḍ n tlemmast"],
    e: "Abrid n lɛawan ibedd garasen n ubrid azelmaḍ d iberdan nniḍen: imekkinen n ubrid azelmaḍ ttadrin ɣer uzelmaḍ, meṛṛa wiyaḍ ɣer lyemmin." },
  q33: { f: "Tamṣebḥit n tallelt s lfiṛu azegzaw d usawal tettaqṛab seg deffir. Acu txedmeḍ?",
    a: ["Ad ddeɣ s uzzel akken ur tettɛeddi ara", "Ad xedmeɣ abrid fell-as sakkin", "Ad kemmleɣ ad ddeɣ am yal tikkelt"],
    e: "Mi ara d-banen lfiṛu azegzaw d usawal, yessefk ad txedmeḍ abrid sakkin, am wa ad tnezzaḥeḍ ɣer tama u ad tḥebseḍ ma yella lḥağa." },
  q34: { f: "Lfiṛu yuɣal d awraɣ u mazal tzemṛeḍ ad tḥebseḍ s leɛfu. Acu ilaq ad txedmeḍ?",
    a: ["Ad ḥebseɣ", "Ad ɛeddiɣ s uzzel", "Ad ɛeddiɣ s uzzel akteṛ"],
    e: "Awraɣ yeqqar ad tṛǧuḍ uqbel n tilintit lɛalama yeḍfaren." },
  q35: { f: "Lfiṛu d azeggaɣ, ɣer tama-s tella tfelwit s tneccabt tazegzawt ɣer lyemmin. Acu yella ma tebɣiḍ ad ddeḍ ɣer lyemmin?",
    a: ["Zemreɣ ad ddeɣ war lḥebs", "Zemreɣ ad ddeɣ kan ma lfiṛu d azegzaw", "Seld lḥebs zemreɣ ad ddeɣ ma ur ttxuṣṣeɣ ula d yiwen u ur sseɣlaɣ ula d yiwen"],
    e: "Ɣer tneccabt tazegzawt ilaq ad tḥebseḍ zik. Sakkin tzemṛeḍ ad tddeḍ ɣer lyemmin ma ur txeṣṣeḍ ula d yiwen u ur tseɣlaḍ ula d yiwen, yaṭṭan iẓenzuyen d imarkuben n tbaskilin. Tzemṛeḍ daɣen ad teṛǧuḍ alamma yuɣal lfiṛu d azegzaw." },
  q36: { f: "Yiwen n uɛasses yessefrak tilintit s uweṭṭu n ufus. Lfiṛu d azegzaw i kečč. Acu yella?",
    a: ["Lfiṛu yettwaḥḍam", "Tiwtilin n uɛasses zwaren", "Ad ɛezmeɣ s yiman-iw"],
    e: "Tiwtilin d lawamer n yiɛassasen zwaren ɣef lfiṛu d tlɛalamin n ubrid." },
  q37: { f: "Tddiḍ ɣer lyemmin. Iẓenzuyen bɣan ad ɛeddin abrid anda tkecmeḍ. Acu yella?",
    a: ["Yessefk ad ten-eǧǧeɣ ad ɛeddin u ad rǧuɣ ma yella lḥağa", "Ilaq ad rǧun acku ddeɣ", "Win i yezwaren ɣur-s lḥeqq"],
    e: "Win i yeddan yessefk ad yeǧǧ iẓenzuyen i yeɛddan abrid anda yekcem, u ad yerǧu ma yella lḥağa." },
  q38: { f: "Tebɣiḍ ad tddeḍ ɣer uzelmaḍ. Yiwen n ṭṭumubil yettaqṛab seg zdat u yedda ɣer zdat. Anwa ɣur-s lḥeqq n ɛeddi?",
    a: ["Nekk", "Ṭṭumubil i yezzlen akteṛ", "Ṭṭumubil i yeddan ɣer zdat"],
    e: "Win i yeddan ɣer uzelmaḍ yessefk ad yeǧǧ imekkinen i d-yusan seg zdat, i yeddan ɣer zdat neɣ ɣer lyemmin, ad ɛeddin zik." },
  q39: { f: "Tella deg ubrid n tazzut i ukcem ɣer otoṛut. Anwa ɣur-s lḥeqq n ɛeddi?",
    a: ["Ṭṭeṛafik n ubrid agejdan", "Nekk, acku tazzayeɣ sseṛɛa", "Win i yeddan akteṛ ɣer lyemmin"],
    e: "Deg otoṛut, win i yeddan ɣef ubrid agejdan ɣur-s lḥeqq n ɛeddi. Tesɛiḍ sseṛɛa-nnec u tkecmeḍ war ma tessḥebsed wiyaḍ." },
  q40: { f: "Ṭṭumubil-nnec yexṣa ɣef ubrid berra n tmnaṭ yettwasken. Achal ɣer deffir n ṭṭumubil ara tesbedded tahenfut n lḥezṛa?",
    e: "Berra n tmnaṭ yettwasken tesbeddeḍ tahenfut n lḥezṛa ɣer 100 m deffir n ṭṭumubil, deg tmnaṭ yettwasken ɣer 50 m, akken ad ttwalɛen imarkuben wiyaḍ zik." },
  q41: { f: "Achal n sseṛɛa i tzemṛeḍ ad ddeḍ deg tmnaṭ n ṭṭeṛafik izedgen (lɛalama 325.1)?",
    a: ["30 km/h", "50 km/h", "S sseṛɛa n lxeṭwa"],
    e: "Deg tmnaṭ n ṭṭeṛafik izedgen, sseṛɛa n lxeṭwa kan i yettwaǧǧan. Iẓenzuyen zemṛen ad sexdmen abrid meṛṛa u ur ilaq ara ad ttwasebbḥen." },
  q42: { f: "Tebdiḍ ad tddeḍ seg tama n ubrid. Acu i d ṣṣeḥ?",
    a: ["Ssusem n ṭṭuṭ i ibɣan", "Ad ɛerḍeɣ tafarat u ad ɛeqleɣ ma ur ttxuṣṣeɣ ula d yiwen", "Ṭṭeṛafik i ddan yessefk ad yeǧǧ-iyi ad kcmeɣ"],
    e: "Win i yebdan ad yedd yessefk ad yeḍmen ma ur yettxuṣṣ ula d yiwen: ad yẓeṛ deg tameṛṛit u ɣef yeɣsan-is u ad yefk tafarat." },
  q43: { f: "Melmi i d-tettwaḥesb lḥeqq n timeṭṭiyin n tegrest di Lalman?",
    a: ["Mi ara yili lekmiḍ, adfel ɣef ubrid, aɣessar, tiḥila neɣ lqerr", "Seg 1 n Wuktubeṛ ar 31 n Meɣres", "Deg idurar kan"],
    e: "Ulac lweqt yettwasbedden: mi ara yili lekmiḍ, adfel ɣef ubrid, aɣessar, tiḥila neɣ lqerr, teḥwaǧeḍ timeṭṭiyin n tegrest." },
  q44: { f: "Tzemṛeḍ ad tṭṭfeḍ lfiṛu n usuref n deffir kan ma yella ubani, s ubaḥḥu, ddaw …",
    e: "Lfiṛu n usuref n deffir yeqqim ɣef wallen n imarkuben wiyaḍ. Yessefk ad yeṭṭef kan mi ara yili ubani ddaw 50 m, sakkin ad yettwakkes." },
  q45: { f: "Acu i d-yeqqar lɛalama-a?",
    a: ["Aɛeddi mmenɛen i meṛṛa tmacinin n lmutuṛ", "Taggara n uɛeddi mmenɛen", "Aɛeddi mmenɛen kan i ikamyunen"],
    e: "Lɛalama 276 («Aɛeddi mmenɛen i meṛṛa tmacinin n lmutuṛ»): tmacinin n lmutuṛ ur zemrent ara ad ɛeddint tmacinin n lmutuṛ s waṭas n yiɣed alamma tettwaxdem lɛalama i yessewten amenɛ." },
  q46: { f: "Acu i d-ssken lɛalama-a?",
    a: ["Dagi ttfukk abrid n zzwar", "Deg tilintit i d-iteddun ilaq ad ḥebseɣ", "Deg tilintit neɣ deg umeḍḍuq i d-iteddun llan zzwar"],
    e: "Lɛalama 301 («Azwar») tesskan belli llan zzwar deg tilintit neɣ deg umeḍḍuq i d-iteddun. Lɛalama 306 («Abrid n zzwar») ɣef yimi-s, tella ɣef waṭas n tilintiyin." },
  q47: { f: "Acu i d-yeqqar lɛalama-a?",
    a: ["Iẓenzuyen d imarkuben n tbaskilin zemrent ad sxedmen abrid-a", "Iẓenzuyen kan zemrent ad sxedmen abrid-a", "Dagi ttebda tamnaḍt n iẓenzuyen"],
    e: "Lɛalama 239 («Abrid n iẓenzuyen»): abrid i yiẓenzuyen. Taɣuri-nniḍen ur tezmir ara ad t-tesxdem, ala ma tettwasireg s tneccabt n tmerniwt." },
  q48: { f: "Acu i d-yeqqar lɛalama-a?",
    a: ["Yessefk ad ɛeddiɣ ɣer lyemmin", "Dagi yessefk ad ddeɣ ɣer lyemmin", "Dagi zemreɣ ad parqeɣ ɣer lyemmin"],
    e: "Lɛalama 222 («Ɛeddi ɣer lyemmin»): yessefk ad tɛeddiḍ ɣer lyemmin n uɣellaf, amedya n tegzirt n uɣerbaz n tɣuri." },
  q49: { f: "Acu i d-yeqqar lɛalama-a?",
    a: ["Ɣer lyemmin llan zzwar", "Ɣer lyemmin abrid iɣlaq", "Zemreɣ ad ddeɣ kan ɣer lyemmin"],
    e: "Lɛalama 209 («Tagrawt yettwaḍfen: ɣer lyemmin»): dagi yessefk ad tedduḍ ɣer lyemmin. Ad tedduḍ s tidet neɣ ad tdduḍ ɣer zelmaḍ ur yettwasireg ara." },
  q50: { f: "Acu i d-yeqqar lɛalama-a?",
    a: ["Ɣur-k iḥerken: yessefk ad ṣubbeɣ s lḥeḍra yelhan u ad ḥḍureɣ i lḥebs", "Dagi yessefk ad ḥebseɣ", "Dagi iḥerken dima llan zzwar"],
    e: "Lɛalama 136 («Iḥerken») terra-d tamuɣli ɣef yiḥerken ɣef ubrid neɣ ɣer tama-s. Ddu s wudem zeɛɛuṛ u ḥḍur i lḥebs. Lɛalama ur d-tuɣal ara ad tḥebseḍ u ur tfeɣ ara zzwar i yiḥerken." },
  q51: { f: "Tebɣiḍ ad tkecmeḍ ɣer tuṭṭunt. Zdat-s llant tɛalamin «Mel zzwar» d «Tuṭṭunt». Acu yella i tɣimit n yiwen asmi tkecmeḍ?",
    a: ["Yessefk ad d-ssekneɣ ɣer lyemmin", "Ur ilaq ara ad d-ssekneɣ", "Yessefk ad d-ssekneɣ ɣer zelmaḍ"],
    e: "Asmi tkecmeḍ ɣer tuṭṭunt am tagi, aseqdec n tɣimit mmenɛen. Daymi ur ilaq ara ad d-ssekneɣ asmi tkecmeḍ." },
  q52: { f: "Achal n lemsafa uqbel n wadeg n lexṭar i ttwaḥṭen tɛalamin n lexṭar ɣer berra n tmura s wudem amatu?",
    e: "Ɣer berra n tmura, tɛalamin n lexṭar ttwaḥṭen s wudem amatu 150 ar 250 m uqbel n wadeg n lexṭar. Deg tmura ttwaḥṭen qrib uqbel n wadeg n lexṭar. Tneccabt n tmerniwt tezmer ad d-tbder lemsafa tameẓẓyant." },
  q53: { f: "Alamma d acḥal n lemtaṛ uqbel n lfiṛu ur ilaq ara ad tḥebseḍ ma yella ten-tgeḍ?",
    e: "Win i yeddan ur ilaq ara ad yeḥbes alamma d 10 m uqbel n lfiṛu ma yella tamacint tettɣaṭṭa-t. Akka meṛṛa zemrent ad walint lfiṛu." },
  q54: { f: "Ɣef ssebba n yidmaren, tamuɣli tettwaqqes ddaw 50 m. Acḥal i d azrar aɣezfan ɣef ddu?",
    e: "Ma yella tamuɣli, ɣef ssebba n yidmaren, aḍfel neɣ lehwa, ddaw 50 m, ur ilaq ara ad ddu s uzrar n akteṛ n 50 km/h, ala ma yella yeḥwaǧ azrar iẓẓayen ugar. Aṭas n tikkal ddu s wazrar iẓẓayen yelha ugar." },
  q55: { f: "Tqerbeḍ ɣer tilist n iẓenzuyen (zebra). Zdat-ek tella tamacint i yeddan s lḥeḍra. Tzemṛeḍ ad tt-tɛeddiḍ dinna?",
    a: ["Ih, ma yella ur d-banen ara iẓenzuyen", "Ih, ma sseɣɣuɣeɣ", "Ala, ur yelli uɛeddi deg tilist n iẓenzuyen"],
    e: "Ur yelli uɛeddi deg tilisin n iẓenzuyen, ula ma yella ur yelli yiwen i yeɛeddan abrid deg waghen." },
  q56: { f: "Taɣuri tesgugem. Lfiṛu-ik d azegzaw, maca deffir n tilintit ulac amkan i tmacint-ik. Acu yella?",
    a: ["Ur ilaq ara ad kecmeɣ ma yella yessefk ad rǧuɣ deg tilintit", "Kecmeɣ acku lfiṛu-iw d azegzaw", "Kecmeɣ u sseɣɣuɣeɣ akken ad ǧǧen wiyaḍ amkan"],
    e: "Ma yella taɣuri tesgugem, ur ilaq ara ad tkecmeḍ ɣer tilintit ula ma yella lfiṛu d azegzaw, ma yella tessefk ad tṛǧuḍ deg-s. Akka tilintit tqqim d tilem i taɣuri n ujerreb." },
  q57: { f: "Tedduḍ ɣef ubrid n lbaṛṛ s yiwen n uzelmaḍ ɣef yal tama. Anda ilaq ad tedduḍ s wudem amatu?",
    a: ["Deg ugraw n ubrid", "Kan asmi tella taɣuri i d-iteddun, ɣer lyemmin kra tezmeṛ", "Ɣer lyemmin kra tezmeṛ"],
    e: "Dima ilaq ad tedduḍ ɣer lyemmin kra tezmeṛ, mačči kan asmi tella taɣuri i d-iteddun, asmi ttɛeddayen-ik, ɣef uqqaṛ, deg tgemmuḍin neɣ asmi tamuɣli d tamẓẓyant." },
  q58: { f: "Anda i yettwamnɛen ula d lḥebs (mačči kan tpareqit)?",
    a: ["Ɣer yiri ayeffus n ubrid ameqqran s tmuɣli yelhan", "Deg yideggen iẓẓayen d wid n tmuɣli tameẓẓyant n ubrid", "Deg ukniwen n tpareqit yettwaqsen"],
    e: "Lḥebs yettwamnɛen, gar wid-nniḍen, deg yideggen iẓẓayen d wid n tmuɣli tameẓẓyant n ubrid, deg tgemmuḍin yeqqnen d deg yimiḍḍuqen n ubrid n tgaṛa." },
  q59: { f: "Tebɣiḍ ad tddeḍ ɣer lyemmin. Anda i tekkseḍ amkan-ik deg lweqt?",
    a: ["Ɣer lyemmin kra tezmeṛ", "Deg ugraw n ubrid", "Ɣer zelmaḍ kra tezmeṛ"],
    e: "Win ibɣan ad yedd ɣer lyemmin, yeǧǧa tamacint-is deg lweqt ɣer lyemmin kra yezmer. Win ibɣan ad yedd ɣer zelmaḍ, yeǧǧa-tt ar ugraw, deg yibraden n yiwen n unnar ɣer zelmaḍ kra yezmer." },
  q60: { f: "Tedduḍ deg yiḍ ɣef ubrid s tfeṛṛunt tamedlalt yekfan. Acu n tfeṛṛunt i tesseqdaceḍ?",
    a: ["Kan tifeṛṛunin n lmeqṛa", "Tifeṛṛunin ibeɛḍen", "Tifeṛṛunin yeqṛiben"],
    e: "Ur ilaq ara ad tedduḍ s tifeṛṛunin n lmeqṛa kan. Deg yibraden s tfeṛṛunt tamedlalt yekfan, ur ilaq ara ad tedduḍ s tifeṛṛunin ibeɛḍen daɣen. Daymi tedduḍ s tifeṛṛunin yeqṛiben." },
};
