// Srpski (latinica). Pravila su nemačka (StVO); brojevi znakova su brojevi nemačkih znakova.
export default {
  q01: { f: "Šta moraš da uradiš kod ovog znaka?",
    a: ["Da nastavim polako bez zaustavljanja", "Da stanem samo ako dolazi drugi auto", "Da stanem, čak i ako niko ne dolazi"],
    e: "Znak 206 („Stop! Propusti vozila“): moraš da staneš i propustiš vozila na putu koji se ukršta, čak i ako se ne vidi nijedno drugo vozilo." },
  q02: { f: "Šta znači ovaj znak?",
    a: ["Imam prvenstvo prolaza", "Moram da propustim vozila na putu koji se ukršta", "Ovde uvek moram da stanem"],
    e: "Znak 205 („Propusti vozila“): moraš da propustiš vozila na putu koji se ukršta. Stajati moraš samo ako je potrebno." },
  q03: { f: "Vidiš ovaj znak. Šta važi za tebe?",
    a: ["Imam prvenstvo prolaza na sledećim raskrsnicama i ukrštanjima", "Moram da čekam na sledećoj raskrsnici", "Na sledećoj raskrsnici važi pravilo desne strane"],
    e: "Znak 306 („Put sa prvenstvom prolaza“): imaš prvenstvo prolaza na sledećim raskrsnicama i ukrštanjima, sve dok znak ne ukine taj put." },
  q04: { f: "Šta znači ovaj znak?",
    a: ["Ovde imam prvenstvo prolaza", "Ovde ne smem da uđem", "Ovde smem da vozim samo polako"],
    e: "Znak 267 („Zabrana ulaska“) obično stoji na kraju ulice sa jednosmernim saobraćajem, nasuprot smeru vožnje. Ne smeš da uđeš." },
  q05: { f: "Šta važi kod ovog znaka?",
    a: ["Ovde smem da stanem do 3 minuta", "Ovde smem da parkiram, ali ne i da stanem", "Ovde ne smem da stanem"],
    e: "Znak 283 („Zabrana zaustavljanja“): tamo ne smeš da staneš, ni nakratko. Parkiranje je utoliko pre zabranjeno." },
  q06: { f: "Šta važi kod ovog znaka?",
    a: ["Ovde smem da stanem do 3 minuta, ali ne i da parkiram", "Ovde nikada ne smem da stanem", "Ovde smem da parkiram koliko god hoću"],
    e: "Znak 286 („Ograničena zabrana zaustavljanja“): tamo smeš da staneš najviše 3 minuta. Parkiranje je zabranjeno." },
  q07: { f: "Šta znači ovaj znak?",
    a: ["Najmanja brzina 30 km/h", "Kraj svih ograničenja brzine", "Početak zone sa najvećom brzinom od 30 km/h"],
    e: "Znak 274.1 („Zona 30 km/h“): u celoj zoni najveća dozvoljena brzina je 30 km/h, sve dok znak ne ukine zonu." },
  q08: { f: "Želiš da uđeš u ovaj kružni tok. Ispred njega stoji znak „Propusti vozila“. Ko ima prvenstvo prolaza?",
    a: ["Vozila koja sada žele da uđu", "Vozila koja već voze u kružnom toku", "Najveće vozilo"],
    e: "Znak 215 pokazuje kružni tok. Kada je ispred njega znak „Propusti vozila“, moraš da propustiš vozila koja su već u krugu." },
  q09: { f: "Šta znači ovaj znak?",
    a: ["Jednosmerna ulica: vozila smeju da voze samo u smeru strelice", "Put sa prvenstvom prolaza: uvek imam prvenstvo", "Ovde se ulica završava"],
    e: "Znak 220 („Jednosmerna ulica“): vozila smeju da koriste ulicu samo u smeru strelice. U suprotnom smeru je zatvorena." },
  q10: { f: "Pešak želi da pređe ulicu kod ovog znaka. Šta radiš?",
    a: ["Zatrubim da sačeka", "Prolazim prvi ako sam dovoljno brz", "Pustim ga da pređe i zaustavim se ako treba"],
    e: "Znak 350 („Pešački prelaz“): pešaci koji očigledno žele da koriste prelaz imaju prvenstvo. Moraš oprezno da se približiš i da staneš ako je potrebno." },
  q11: { f: "Šta znači ovaj znak?",
    a: ["Moram da stanem", "Opasno mesto: moram da vozim posebno pažljivo", "Imam prvenstvo prolaza"],
    e: "Znak 101 („Opasno mesto“) upozorava na opasnost. Vozi pažljivo i pogledaj dodatnu tablu koja navodi opasnost." },
  q12: { f: "Sme li auto da vozi stazom sa ovim znakom?",
    a: ["Ne, staza je za bicikliste", "Da, ako je put slobodan", "Da, ali samo sa upaljenim sva četiri migavca"],
    e: "Znak 237 („Biciklistička staza“): staza je za bicikliste. Auta tamo ne smeju da voze." },
  q13: { f: "Šta znači ovaj znak?",
    a: ["Zabrana ulaska", "Samo za stanare", "Zabrana saobraćaja za sva vozila"],
    e: "Znak 250 („Zabrana saobraćaja za sva vozila“): vozila, uključujući bicikle, ovde ne smeju da voze." },
  q14: { f: "Šta znači ovaj znak?",
    a: ["Počinje zabrana zaustavljanja", "Završavaju se sve ranije zabrane na putu", "Počinje autoput"],
    e: "Znak 282 („Kraj svih zabrana na putu“) ukida zabrane naložene ranije na deonici, na primer ograničenje brzine ili zabranu preticanja." },
  q15: { f: "Koja je najveća brzina putničkog automobila u naselju ako nijedan znak ne pokazuje drugačije?",
    e: "U naseljima putnički automobili smeju da voze 50 km/h ako znak ne nalaže drugačije." },
  q16: { f: "Koja je najveća brzina putničkog automobila bez prikolice na putu van naselja ako nijedan znak ne pokazuje drugačije?",
    e: "Van naselja putnički automobili bez prikolice smeju na običnim putevima da voze 100 km/h ako znak ne nalaže drugačije." },
  q17: { f: "Koja preporučena brzina važi na nemačkim autoputevima?",
    e: "Preporučena brzina od 130 km/h je preporuka, a ne obaveza. Ali brža vožnja povećava rizik." },
  q18: { f: "Dolaziš do raskrsnice bez znakova i bez semafora. Sa desne strane se približava auto. Šta važi?",
    a: ["Moram da ga propustim", "Imam prvenstvo prolaza", "Ko je brži, prolazi prvi"],
    e: "„Prvenstvo sa desne strane“: bez znakova i semafora prvenstvo ima onaj ko dolazi sa desne strane." },
  q19: { f: "Smeš li da uzmeš mobilni telefon u ruku tokom vožnje?",
    a: ["Da, ako vozim polako", "Ne, to je zabranjeno", "Da, ali samo da telefoniram"],
    e: "Mobilni telefon se ne sme uzeti u ruku tokom vožnje. Telefoniranje je dozvoljeno samo sa hendsfri uređajem." },
  q20: { f: "Ko u putničkom automobilu u principu mora da bude vezan pojasom?",
    a: ["Samo vozač", "Vozač i suvozač", "Svi u autu, i pozadi"],
    e: "Svi putnici moraju da se vežu sigurnosnim pojasom, i na zadnjim sedištima." },
  q21: { f: "Kako u autu moraju da budu obezbeđena deca mlađa od 12 godina, niža od 150 cm?",
    a: ["U odgovarajućem dečjem sedištu", "Običnim pojasom na prednjem sedištu, bez dečjeg sedišta", "U krilu odrasle osobe"],
    e: "Deci mlađoj od 12 godina, nižoj od 150 cm, u autu je potreban odgovarajući sistem za zadržavanje dece, to jest dečje sedište." },
  q22: { f: "Šta važi za početnike u probnom periodu i za sve vozače mlađe od 21 godine kada je reč o alkoholu?",
    a: ["Dozvoljeno je 0,3 promila", "Nikakav alkohol (0,0 promila)", "Dozvoljeno je 0,5 promila"],
    e: "Za početnike u probnom periodu i za vozače mlađe od 21 godine važi apsolutna zabrana alkohola i kanabisa (THC) tokom vožnje." },
  q23: { f: "Koliko traje probni period za vozače početnike?",
    a: ["6 meseci", "1 godinu", "2 godine"],
    e: "Probni period traje 2 godine od izdavanja vozačke dozvole." },
  q24: { f: "Koje rastojanje od vozila ispred je ispravno?",
    a: ["Dužina jednog auta", "Dovoljno veliko da mogu na vreme da stanem čak i ako ono naglo zakoči", "Uvek tačno 10 metara"],
    e: "Rastojanje mora da bude dovoljno veliko da možeš da staneš iza vozila ispred čak i ako ono naglo zakoči. Pravilo palca: rastojanje u metrima treba da bude bar polovina brzine sa brzinomera." },
  q25: { f: "Koliki je put kočenja pri 50 km/h po pravilu palca na suvom putu?",
    e: "Put kočenja = (brzina : 10) × (brzina : 10). Pri 50 km/h to je 5 × 5 = 25 m. Put zaustavljanja je duži jer se dodaje vreme reakcije." },
  q26: { f: "Voziš duplo brže. Koliki postaje put kočenja?",
    a: ["Dvostruko duži", "Trostruko duži", "Četiri puta duži"],
    e: "Put kočenja raste sa kvadratom brzine: dvostruka brzina znači četiri puta duži put kočenja." },
  q27: { f: "Koliki je put reakcije pri 50 km/h po pravilu palca?",
    e: "Put reakcije = (brzina : 10) × 3. Pri 50 km/h to je 5 × 3 = 15 m koje pređeš pre nego što počneš da kočiš." },
  q28: { f: "Gde nikako ne smeš da pretičeš?",
    a: ["Ispred krivine bez preglednosti", "Na pravom, slobodnom putu van naselja", "Na levoj traci autoputa"],
    e: "Pretiči smeš samo ako vidiš put ispred sebe. Ispred krivine bez preglednosti ili vrha uzbrdice preticanje je zabranjeno." },
  q29: { f: "Pretičeš biciklistu u naselju. Koje najmanje bočno rastojanje moraš da ostaviš?",
    e: "Pri preticanju biciklista, pešaka i električnih trotineta moraš da ostaviš bar 1,5 m u naselju i bar 2 m van naselja." },
  q30: { f: "Do koliko metara ispred raskrsnice je parkiranje zabranjeno, ako desno od kolovoza nema biciklističke staze?",
    e: "Ispred i iza raskrsnica i ukrštanja parkiranje je zabranjeno do 5 m sa svake strane, mereno od tačaka u kojima se spajaju ivice kolovoza. Ako je desno od kolovoza izgrađena biciklistička staza, to je ispred raskrsnice do 8 m. Rastojanje od 15 m važi za autobuska stajališta (znak 224), a ne za raskrsnice." },
  q31: { f: "Koliko ispred i iza znaka autobuske stanice je parkiranje zabranjeno?",
    e: "Ne smeš da parkiraš do 15 m ispred i iza znaka autobuske stanice (znak 224)." },
  q32: { f: "Na autoputu sa tri trake u svakom smeru formirala se kolona. Gde formiraš prolaz za hitne službe?",
    a: ["Na bankini", "Između srednje i desne trake", "Između leve i srednje trake"],
    e: "Prolaz za hitne službe nastaje između leve trake i ostalih traka: vozila na levoj traci se sklanjaju ulevo, sva ostala udesno." },
  q33: { f: "Pozadi se približava hitna pomoć sa plavim svetlima i sirenom. Šta radiš?",
    a: ["Vozim brže da ne bi morala da me pretiče", "Odmah joj napravim prolaz", "Vozim normalno dalje"],
    e: "Kada ima plava svetla i sirenu, moraš odmah da napraviš prolaz, na primer da se skloniš uz ivicu i staneš ako je potrebno." },
  q34: { f: "Semafor prelazi na žuto, a ti još možeš bezbedno da staneš. Šta moraš da uradiš?",
    a: ["Da stanem", "Da brzo prođem", "Da ubrzam"],
    e: "Žuto svetlo nalaže da pred raskrsnicom sačekaš sledeći signal." },
  q35: { f: "Semafor pokazuje crveno, a pored njega je tabla sa zelenom strelicom udesno. Šta važi ako želiš da skreneš udesno?",
    a: ["Smem da skrenem bez zaustavljanja", "Smem da skrenem samo na zeleno", "Posle zaustavljanja smem da skrenem ako nikoga ne ugrožavam niti ometam"],
    e: "Kod zelene strelice prvo moraš da staneš. Zatim smeš da skreneš udesno ako nikoga ne ugrožavaš niti ometaš, pre svega pešake i bicikliste. Možeš i da sačekaš da se upali zeleno." },
  q36: { f: "Policajac reguliše raskrsnicu rukama. Semafor je za tebe zelen. Šta važi?",
    a: ["Važi semafor", "Znaci policajca imaju prednost", "Odlučujem sam"],
    e: "Znaci i naređenja policajaca imaju prednost nad semaforima i saobraćajnim znacima." },
  q37: { f: "Skrećeš udesno. Pešaci žele da pređu ulicu u koju skrećeš. Šta važi?",
    a: ["Moram da ih pustim da pređu i da sačekam ako treba", "Oni moraju da čekaju jer ja skrećem", "Prvenstvo ima ko prvi stigne"],
    e: "Ko skreće, mora da pusti pešake koji prelaze ulicu u koju skreće i da sačeka ako je potrebno." },
  q38: { f: "Želiš da skreneš ulevo. Auto ti dolazi u susret i ide pravo. Ko ima prvenstvo prolaza?",
    a: ["Ja", "Brži auto", "Auto koji ide pravo"],
    e: "Ko skreće ulevo, mora prvo da propusti vozila iz suprotnog smera koja idu pravo ili skreću udesno." },
  q39: { f: "Nalaziš se na traci za ubrzavanje i uključuješ se na autoput. Ko ima prvenstvo prolaza?",
    a: ["Saobraćaj na glavnom kolovozu", "Ja, jer ubrzavam", "Ko vozi više desno"],
    e: "Na autoputu prvenstvo ima ko vozi glavnim kolovozom. Prilagodiš brzinu i uključiš se ne ometajući druge." },
  q40: { f: "Tvoj auto se pokvario na putu van naselja. Na kojoj otprilike udaljenosti iza auta postavljaš sigurnosni trougao?",
    e: "Van naselja sigurnosni trougao postavljaš oko 100 m iza vozila, u naselju oko 50 m, da bi drugi vozači bili upozoreni na vreme." },
  q41: { f: "Koliko brzo smeš da voziš u zoni smirenog saobraćaja (znak 325.1)?",
    a: ["30 km/h", "50 km/h", "Brzinom hoda"],
    e: "U zoni smirenog saobraćaja dozvoljena je samo brzina hoda. Pešaci smeju da koriste celu ulicu i ne smeju da se ometaju." },
  q42: { f: "Polaziš sa ivice kolovoza. Šta je ispravno?",
    a: ["Dovoljno je da zatrubim", "Da uključim migavac i uverim se da nikoga ne ugrožavam", "Saobraćaj koji teče mora da me pusti"],
    e: "Ko polazi, mora da se ponaša tako da druge ne ugrozi: pogleda u ogledalo i preko ramena i uključi migavac." },
  q43: { f: "Kada u Nemačkoj važi obaveza zimskih guma?",
    a: ["Kod poledice, snega na putu, bljuzgavice, leda ili mraza", "Od 1. oktobra do 31. marta", "Samo u planinama"],
    e: "Nema fiksnog perioda: kod poledice, snega na putu, bljuzgavice, leda ili mraza potrebne su ti zimske gume." },
  q44: { f: "Zadnje svetlo za maglu smeš da upališ samo ako je vidljivost zbog magle manja od …",
    e: "Zadnje svetlo za maglu zaslepljuje druge vozače. Sme da bude upaljeno samo pri vidljivosti manjoj od 50 m, a posle se mora ugasiti." },
  q45: { f: "Šta znači ovaj znak?",
    a: ["Zabrana preticanja za sva motorna vozila", "Kraj zabrane preticanja", "Zabrana preticanja samo za kamione"],
    e: "Znak 276 („Zabrana preticanja za sva motorna vozila“): motorna vozila ne smeju da preticaju višetračna motorna vozila dok znak ne ukine zabranu." },
  q46: { f: "Šta pokazuje ovaj znak?",
    a: ["Ovde se završava put sa prvenstvom prolaza", "Na sledećoj raskrsnici moram da stanem", "Na sledećoj raskrsnici ili ukrštanju imam prvenstvo prolaza"],
    e: "Znak 301 („Prvenstvo prolaza“) pokazuje da na sledećoj raskrsnici ili ukrštanju imaš prvenstvo prolaza. Znak 306 („Put sa prvenstvom prolaza“), nasuprot tome, važi preko više raskrsnica." },
  q47: { f: "Šta znači ovaj znak?",
    a: ["Pešaci i biciklisti smeju da koriste ovu stazu", "Samo pešaci smeju da koriste ovu stazu", "Ovde počinje pešačka zona"],
    e: "Znak 239 („Pešačka staza“): staza je za pešake. Drugi saobraćaj ne sme da je koristi, osim ako dodatna tabla to ne dozvoljava." },
  q48: { f: "Šta znači ovaj znak?",
    a: ["Moram da prođem sa desne strane", "Ovde moram da skrenem udesno", "Ovde smem da parkiram desno"],
    e: "Znak 222 („Obilaženje s desne strane“): prepreku, na primer ostrvo za pešake, moraš da obiđeš sa desne strane." },
  q49: { f: "Šta znači ovaj znak?",
    a: ["Udesno imam prvenstvo prolaza", "Udesno je put zatvoren", "Smem da vozim samo udesno"],
    e: "Znak 209 („Obavezan smer: udesno“): ovde moraš da voziš udesno. Vožnja pravo ili skretanje ulevo nije dozvoljeno." },
  q50: { f: "Šta znači ovaj znak?",
    a: ["Pažnja, deca: moram da vozim posebno pažljivo i budem spreman da kočim", "Ovde moram da stanem", "Deca ovde uvek imaju prvenstvo prolaza"],
    e: "Znak 136 („Deca“) upozorava na decu na putu ili pored puta. Vozi polako i budi spreman da kočiš. Znak ne zahteva zaustavljanje i ne daje deci prvenstvo prolaza." },
  q51: { f: "Želiš da uđeš u kružni tok. Ispred njega su znaci „Ustupanje prvenstva prolaza“ i „Kružni tok“. Šta važi za žmigavac pri ulasku?",
    a: ["Moram da uključim desni žmigavac", "Ne smem da uključim žmigavac", "Moram da uključim levi žmigavac"],
    e: "Pri ulasku u ovakav kružni tok korišćenje žmigavca nije dozvoljeno. Dakle, pri ulasku ne smeš da uključiš žmigavac." },
  q52: { f: "Na kom rastojanju ispred opasnog mesta obično stoje znaci opasnosti van naselja?",
    e: "Van naselja znaci opasnosti obično stoje 150 do 250 m ispred opasnog mesta. U naselju stoje neposredno ispred njega. Dodatna tabla može da navede manje rastojanje." },
  q53: { f: "Do koliko metara ispred semafora ne smeš da staneš ako ga zaklanjaš?",
    e: "Vozač ne sme da stane do 10 m ispred semafora ako ga vozilo zaklanja. Tako svi mogu da vide semafor." },
  q54: { f: "Zbog magle je vidljivost manja od 50 m. Koliko najviše smeš da voziš?",
    e: "Ako je vidljivost zbog magle, snega ili kiše manja od 50 m, ne sme se voziti brže od 50 km/h, osim ako je potrebna još manja brzina. Često je pametnije voziti sporije." },
  q55: { f: "Približavaš se pešačkom prelazu (zebri). Ispred tebe polako vozi automobil. Smeš li da ga pretekneš tu?",
    a: ["Da, ako se ne vidi nijedan pešak", "Da, ako zatrubim", "Ne, na pešačkim prelazima se ne sme preticati"],
    e: "Na pešačkim prelazima se ne sme preticati, čak i ako u tom trenutku niko ne prelazi ulicu." },
  q56: { f: "Saobraćaj stoji. Tvoj semafor je zelen, ali iza raskrsnice nema mesta za tvoj automobil. Šta važi?",
    a: ["Ne smem da uđem ako bih morao da čekam na raskrsnici", "Ulazim jer imam zeleno", "Ulazim i trubim da drugi naprave mesta"],
    e: "Ako saobraćaj stoji, ne sme se ući u raskrsnicu ni na zeleno ako bi se na njoj moralo čekati. Tako raskrsnica ostaje slobodna za poprečni saobraćaj." },
  q57: { f: "Voziš po lokalnom putu sa jednom trakom u svakom smeru. Gde u principu moraš da voziš?",
    a: ["Na sredini kolovoza", "Što više desno samo kada dolazi saobraćaj iz suprotnog smera", "Što više desno"],
    e: "Uvek se mora voziti što više desno, ne samo kada dolazi saobraćaj iz suprotnog smera, kada te pretiču, na vrhovima uspona, u krivinama ili kada je vidljivost loša." },
  q58: { f: "Gde je zabranjeno čak i zaustavljanje (a ne samo parkiranje)?",
    a: ["Na desnoj ivici široke ulice sa dobrom preglednošću", "Na uskim mestima i mestima sa lošom preglednošću", "Na obeleženoj parking traci"],
    e: "Zaustavljanje nije dozvoljeno, između ostalog, na uskim mestima i mestima sa lošom preglednošću, u oštrim krivinama i na železničkim prelazima." },
  q59: { f: "Želiš da skreneš udesno. Gde se na vreme postrojavaš?",
    a: ["Što više desno", "Na sredini kolovoza", "Što više levo"],
    e: "Ko želi da skrene udesno, na vreme postavlja vozilo što više desno. Ko želi da skrene ulevo, postavlja se do sredine, a na kolovozima za jedan smer što više levo." },
  q60: { f: "Voziš noću putem sa neprekidnim, dovoljnim osvetljenjem. Koja svetla koristiš?",
    a: ["Samo pozicijna svetla", "Dugo svetlo", "Kratko svetlo"],
    e: "Ne sme se voziti samo sa pozicionim svetlima. Na putevima sa neprekidnim, dovoljnim osvetljenjem ne sme se voziti ni sa dugim svetlom. Dakle, voziš sa kratkim svetlom." },
};
