// Türkçe. Kurallar Almanya trafik kurallarıdır (StVO); işaret numaraları Alman işaret numaralarıdır.
export default {
  q01: { f: "Bu işaretin önünde ne yapmalısın?",
    a: ["Durmadan yavaşça devam ederim", "Sadece başka bir araba gelirse dururum", "Kimse gelmese bile dururum"],
    e: "206 numaralı işaret (“Dur! Yol ver”): Başka araç görünmese bile durmalı ve kesişen yola geçiş hakkı vermelisin." },
  q02: { f: "Bu işaret ne anlama gelir?",
    a: ["Geçiş hakkı bende", "Kesişen yoldaki araçlara yol vermeliyim", "Burada her zaman durmalıyım"],
    e: "205 numaralı işaret (“Yol ver”): Kesişen yoldaki araçlara geçiş hakkı vermelisin. Sadece gerekirse durmalısın." },
  q03: { f: "Bu işareti görüyorsun. Senin için ne geçerli?",
    a: ["Sonraki kavşaklarda ve yol ayrımlarında geçiş hakkı bende", "Bir sonraki kavşakta beklemeliyim", "Bir sonraki kavşakta sağdan gelen geçer"],
    e: "306 numaralı işaret (“Ana yol”): Bir işaret ana yolu bitirene kadar sonraki kavşaklarda ve yol ayrımlarında geçiş hakkı sende." },
  q04: { f: "Bu işaret ne anlama gelir?",
    a: ["Burada geçiş hakkı bende", "Buraya girmem yasak", "Burada sadece yavaş gidebilirim"],
    e: "267 numaralı işaret (“Girilmez”) genellikle tek yönlü yolun sonunda, yönün tersine durur. Girmen yasak." },
  q05: { f: "Bu işarette ne geçerli?",
    a: ["Burada en fazla 3 dakika durabilirim", "Burada park edebilirim ama duramam", "Burada duramam"],
    e: "283 numaralı işaret (“Durmak yasak”): Orada kısa süre bile duramazsın. Park etmek zaten yasak." },
  q06: { f: "Bu işarette ne geçerli?",
    a: ["Burada en fazla 3 dakika durabilirim ama park edemem", "Burada hiç duramam", "Burada istediğim kadar park edebilirim"],
    e: "286 numaralı işaret (“Sınırlı durma yasağı”): Orada en fazla 3 dakika durabilirsin. Park etmek yasak." },
  q07: { f: "Bu işaret ne anlama gelir?",
    a: ["En düşük hız 30 km/h", "Tüm hız sınırlarının sonu", "En çok 30 km/h olan bir bölgenin başlangıcı"],
    e: "274.1 numaralı işaret (“30 km/h bölgesi”): Bir işaret bölgeyi bitirene kadar bölgenin tamamında en çok 30 km/h ile gidilir." },
  q08: { f: "Bu dönel kavşağa girmek istiyorsun. Önünde “Yol ver” işareti var. Kimin geçiş hakkı var?",
    a: ["Şimdi girmek isteyen araçların", "Dönel kavşakta zaten dolaşan araçların", "En büyük aracın"],
    e: "215 numaralı işaret dönel kavşağı gösterir. Önünde “Yol ver” işareti varsa, çemberdeki araçlara yol vermelisin." },
  q09: { f: "Bu işaret ne anlama gelir?",
    a: ["Tek yönlü yol: Araçlar sadece okun yönünde gidebilir", "Ana yol: Her zaman geçiş hakkı bende", "Yol burada biter"],
    e: "220 numaralı işaret (“Tek yönlü yol”): Araçlar yolu sadece okun yönünde kullanabilir. Ters yön kapalıdır." },
  q10: { f: "Bir yaya bu işaretin olduğu yerden karşıya geçmek istiyor. Ne yaparsın?",
    a: ["Korna çalarım ki beklesin", "Yeterince hızlıysam önce ben geçerim", "Geçmesine izin veririm, gerekirse dururum"],
    e: "350 numaralı işaret (“Yaya geçidi”): Geçidi kullanmak isteyen yayaların önceliği vardır. Dikkatlice yaklaşmalı ve gerekirse durmalısın." },
  q11: { f: "Bu işaret ne anlama gelir?",
    a: ["Durmalıyım", "Tehlikeli yer: Özellikle dikkatli gitmeliyim", "Geçiş hakkı bende"],
    e: "101 numaralı işaret (“Tehlikeli yer”) bir tehlikeye karşı uyarır. Dikkatli sür ve tehlikeyi belirten ek levhaya bak." },
  q12: { f: "Bu işaretin olduğu yolda araba gidebilir mi?",
    a: ["Hayır, yol bisikletliler için", "Evet, yol boşsa", "Evet, ama sadece dörtlü flaşörle"],
    e: "237 numaralı işaret (“Bisiklet yolu”): Yol bisikletliler içindir. Arabalar orada gidemez." },
  q13: { f: "Bu işaret ne anlama gelir?",
    a: ["Girilmez", "Sadece oturanlar girebilir", "Her türlü araca kapalı yol"],
    e: "250 numaralı işaret (“Her türlü araca kapalı yol”): Bisikletler dahil araçlar burada gidemez." },
  q14: { f: "Bu işaret ne anlama gelir?",
    a: ["Bir durma yasağı başlar", "Önceki tüm yol kısıtlamaları biter", "Otoyol başlar"],
    e: "282 numaralı işaret (“Tüm yol yasaklarının sonu”) daha önce konulan yasakları kaldırır, örneğin hız sınırını veya sollama yasağını." },
  q15: { f: "Başka bir işaret yoksa, yerleşim yerinde bir otomobil en çok kaç km/h ile gidebilir?",
    e: "Başka bir işaret yoksa yerleşim yerlerinde otomobiller için 50 km/h geçerlidir." },
  q16: { f: "Başka bir işaret yoksa, römorksuz bir otomobil yerleşim yeri dışında bir kara yolunda en çok kaç km/h ile gidebilir?",
    e: "Başka bir işaret yoksa yerleşim yeri dışında römorksuz otomobiller için kara yollarında 100 km/h geçerlidir." },
  q17: { f: "Otoyollarda hangi tavsiye hızı geçerlidir?",
    e: "130 km/h tavsiye hızı bir tavsiyedir, zorunluluk değildir. Ama daha hızlı gitmek riski artırır." },
  q18: { f: "İşaretsiz ve trafik ışığı olmayan bir kavşağa geliyorsun. Sağdan bir araba yaklaşıyor. Ne geçerli?",
    a: ["Ona yol vermeliyim", "Geçiş hakkı bende", "Hangisi daha hızlıysa önce o geçer"],
    e: "“Sağdan gelen geçer”: İşaret ve trafik ışığı yoksa sağdan gelenin geçiş hakkı vardır." },
  q19: { f: "Araç kullanırken telefonu eline alabilir misin?",
    a: ["Evet, yavaş gidiyorsam", "Hayır, yasak", "Evet, ama sadece konuşmak için"],
    e: "Araç kullanırken telefon ele alınamaz. Konuşmak sadece ahizesiz (hoparlör) sistemle olur." },
  q20: { f: "Bir otomobilde genel olarak kimler emniyet kemeri takmalıdır?",
    a: ["Sadece sürücü", "Sürücü ve ön yolcu", "Arabadaki herkes, arkadakiler de"],
    e: "Tüm yolcular emniyet kemeri takmalıdır, arka koltuklarda da." },
  q21: { f: "12 yaşından küçük ve 150 cm’den kısa çocuklar arabada nasıl korunmalıdır?",
    a: ["Uygun bir çocuk koltuğunda", "Ön koltukta normal kemerle, çocuk koltuğu olmadan", "Bir yetişkinin kucağında"],
    e: "12 yaşından küçük ve 150 cm’den kısa çocuklar için arabada uygun bir çocuk koruma sistemi, yani çocuk koltuğu gerekir." },
  q22: { f: "Deneme süresindeki yeni sürücüler ve 21 yaşından küçük tüm sürücüler için alkolde ne geçerli?",
    a: ["Binde 0,3 serbest", "Hiç alkol yok (binde 0,0)", "Binde 0,5 serbest"],
    e: "Deneme süresindeki yeni sürücüler ve 21 yaşından küçük sürücüler için araç kullanırken alkol ve esrar (THC) konusunda kesin yasak vardır." },
  q23: { f: "Yeni sürücüler için deneme süresi ne kadar sürer?",
    a: ["6 ay", "1 yıl", "2 yıl"],
    e: "Deneme süresi, ehliyetin verildiği günden itibaren 2 yıl sürer." },
  q24: { f: "Öndeki araca karşı hangi mesafe doğrudur?",
    a: ["Bir araba boyu", "Öndeki aniden frenlese bile zamanında durabileceğim kadar büyük", "Her zaman tam 10 metre"],
    e: "Mesafe, öndeki araç aniden frenlese bile arkasında durabilecek kadar büyük olmalıdır. Pratik kural: Metre cinsinden mesafe en az hız göstergesindeki değerin yarısı olmalı." },
  q25: { f: "Kuru yolda 50 km/h hızda fren mesafesi, pratik formüle göre ne kadardır?",
    e: "Fren mesafesi = (hız : 10) × (hız : 10). 50 km/h hızda bu 5 × 5 = 25 m eder. Durma mesafesi daha uzundur, çünkü tepki süresi de eklenir." },
  q26: { f: "İki kat daha hızlı gidiyorsun. Fren mesafesi ne kadar uzar?",
    a: ["İki kat", "Üç kat", "Dört kat"],
    e: "Fren mesafesi hızın karesiyle artar: Hız iki katına çıkarsa fren mesafesi dört katına çıkar." },
  q27: { f: "50 km/h hızda tepki mesafesi, pratik formüle göre ne kadardır?",
    e: "Tepki mesafesi = (hız : 10) × 3. 50 km/h hızda bu 5 × 3 = 15 m eder; frene basmadan önce bu kadar yol alırsın." },
  q28: { f: "Nerede kesinlikle sollama yapmamalısın?",
    a: ["Görüş açısı kapalı bir virajdan önce", "Düz ve boş bir kara yolunda", "Otoyolun sol şeridinde"],
    e: "Sollama için yolu görebilmen gerekir. Görüşü kapalı bir virajdan veya tepenin üstünden önce sollama yasaktır." },
  q29: { f: "Yerleşim yerinde bir bisikletliyi solluyorsun. En az ne kadar yan mesafe bırakmalısın?",
    e: "Bisikletlileri, yayaları ve e-scooter kullanıcılarını sollarken yerleşim yerinde en az 1,5 m, dışında en az 2 m yan mesafe gerekir." },
  q30: { f: "Sağ tarafta bisiklet yolu yoksa, bir kavşaktan önce en fazla kaç metreye kadar park etmek yasaktır?",
    e: "Kavşaklardan ve yol ayrımlarından önce ve sonra, kaldırım kenarlarının kesiştiği noktalardan başlayarak 5 m’ye kadar park yasaktır. Yolun sağında yapısal bir bisiklet yolu varsa, kavşaktan önce bu mesafe 8 m’ye kadardır. 15 m kuralı kavşaklar için değil, durak levhaları (224 numaralı işaret) için geçerlidir." },
  q31: { f: "Bir otobüs durağı levhasından önce ve sonra ne kadar park yasaktır?",
    e: "Durak levhasından (224 numaralı işaret) önce ve sonra 15 m’ye kadar park etmen yasaktır." },
  q32: { f: "Her yönde üç şeritli bir otoyolda trafik tıkandı. Kurtarma koridorunu nerede oluşturursun?",
    a: ["Acil durum şeridinde", "Orta şerit ile sağ şerit arasında", "Sol şerit ile orta şerit arasında"],
    e: "Kurtarma koridoru sol şerit ile diğer şeritler arasında oluşur: Sol şeritteki araçlar sola, diğerleri sağa çekilir." },
  q33: { f: "Arkandan mavi ışıklı ve sirenli bir ambulans yaklaşıyor. Ne yaparsın?",
    a: ["Sollamak zorunda kalmasın diye hızlanırım", "Hemen yol açarım", "Normal sürmeye devam ederim"],
    e: "Mavi ışık ve siren varsa hemen yol açmalısın, örneğin kenara çekilip gerekirse durarak." },
  q34: { f: "Trafik ışığı sarıya döndü ve hâlâ güvenle durabiliyorsun. Ne yapmalısın?",
    a: ["Durmalıyım", "Hızlıca geçerim", "Hızlanırım"],
    e: "Sarı ışık, kavşağın önünde bir sonraki işareti beklemeni ister." },
  q35: { f: "Trafik ışığı kırmızı, yanında sağa yeşil ok gösteren bir levha var. Sağa dönmek istiyorsan ne geçerlidir?",
    a: ["Durmadan dönebilirim", "Sadece yeşil ışıkta dönebilirim", "Durduktan sonra, kimseyi tehlikeye atmıyorsam veya engellemiyorsam dönebilirim"],
    e: "Yeşil okta önce durmalısın. Sonra kimseyi, özellikle yayaları ve bisikletlileri tehlikeye atmıyor veya engellemiyorsan sağa dönebilirsin. İstersen ışık yeşil olana kadar da bekleyebilirsin." },
  q36: { f: "Bir polis kavşağı el işaretleriyle yönetiyor. Trafik ışığı senin için yeşil. Ne geçerli?",
    a: ["Trafik ışığı geçerli", "Polisin işaretleri önce gelir", "Kendim karar veririm"],
    e: "Polislerin işaretleri ve talimatları trafik ışıklarından ve trafik işaretlerinden önce gelir." },
  q37: { f: "Sağa dönüyorsun. Yayalar girdiğin yoldan karşıya geçmek istiyor. Ne geçerli?",
    a: ["Onları geçirmeliyim, gerekirse beklemeliyim", "Ben döndüğüm için onlar beklemeli", "Önce gelenin önceliği var"],
    e: "Dönen sürücü, girdiği yolu geçen yayaları geçirmeli ve gerekirse beklemelidir." },
  q38: { f: "Sola dönmek istiyorsun. Karşından bir araba geliyor ve düz gidiyor. Geçiş hakkı kimde?",
    a: ["Bende", "Daha hızlı olan arabada", "Düz giden arabada"],
    e: "Sola dönen, karşıdan gelen ve düz giden ya da sağa dönen araçlara yol vermelidir." },
  q39: { f: "Otoyola katılmak için ivmelenme şeridindesin. Geçiş hakkı kimde?",
    a: ["Ana yoldaki trafikte", "Bende, çünkü hızlanıyorum", "Daha sağdan gidende"],
    e: "Otoyolda kesintisiz yolda giden trafiğin geçiş hakkı vardır. Hızını uydurur ve kimseyi engellemeden araya katılırsın." },
  q40: { f: "Arabanız bir kara yolunda arıza yaptı. Reflektörü arabanın yaklaşık ne kadar arkasına koyarsın?",
    e: "Yerleşim yeri dışında reflektörü aracın yaklaşık 100 m, içinde yaklaşık 50 m arkasına koyarsın; böylece diğer sürücüler yeterince erken uyarılır." },
  q41: { f: "Trafik sakinleştirilmiş bölgede (325.1 numaralı işaret) ne kadar hızlı gidebilirsin?",
    a: ["30 km/h", "50 km/h", "Yürüme hızı"],
    e: "Trafik sakinleştirilmiş bölgede sadece yürüme hızı serbesttir. Yayalar yolun tamamını kullanabilir ve engellenmemelidir." },
  q42: { f: "Yol kenarından hareket ediyorsun. Hangisi doğru?",
    a: ["Korna çalmak yeterli", "Sinyal verir ve kimseyi tehlikeye atmadığımdan emin olurum", "Akan trafik bana yol vermek zorunda"],
    e: "Hareket eden sürücü, başkalarını tehlikeye atmayacak şekilde davranmalıdır: aynaya ve omzunun üstünden arkaya bak, sinyal ver." },
  q43: { f: "Almanya’da kış lastiği zorunluluğu ne zaman geçerlidir?",
    a: ["Buzlanma, karla kaplı yol, çamurlu kar, buz veya don olduğunda", "1 Ekim’den 31 Mart’a kadar", "Sadece dağlarda"],
    e: "Sabit bir mevsim yoktur: Buzlanma, karla kaplı yol, çamurlu kar, buz veya don olduğunda kış lastiği gerekir." },
  q44: { f: "Arka sis lambasını ancak sisten dolayı görüş mesafesi … altındaysa açabilirsin.",
    e: "Arka sis lambası diğer sürücülerin gözünü alır. Sadece görüş mesafesi 50 m’nin altındayken açık olabilir, sonra kapatılmalıdır." },
  q45: { f: "Bu işaret ne anlama gelir?",
    a: ["Her türlü motorlu taşıt için sollama yasağı", "Sollama yasağının sonu", "Sadece kamyonlar için sollama yasağı"],
    e: "276 numaralı işaret (“Her türlü motorlu taşıt için sollama yasağı”): Motorlu taşıtlar, bir işaret yasağı bitirene kadar çok izli motorlu taşıtları sollayamaz." },
  q46: { f: "Bu işaret neyi gösterir?",
    a: ["Anayolun sonu", "Bir sonraki kavşakta durmam gerekir", "Bir sonraki kavşakta veya yol ayrımında geçiş hakkı bende"],
    e: "301 numaralı işaret (“Geçiş üstünlüğü”): Bir sonraki kavşakta veya yol ayrımında geçiş hakkın olduğunu gösterir. 306 numaralı işaret (“Ana yol”) ise birkaç kavşak boyunca geçerlidir." },
  q47: { f: "Bu işaret ne anlama gelir?",
    a: ["Yayalar ve bisikletliler bu yolu kullanabilir", "Bu yolu sadece yayalar kullanabilir", "Burada yaya bölgesi başlar"],
    e: "239 numaralı işaret (“Yaya yolu”): Yol yayalar içindir. Bir ek levha izin vermedikçe başka trafik bu yolu kullanamaz." },
  q48: { f: "Bu işaret ne anlama gelir?",
    a: ["Sağdan geçmem gerekir", "Burada sağa dönmem gerekir", "Burada sağa park edebilirim"],
    e: "222 numaralı işaret (“Sağdan geçiniz”): Engelin, örneğin bir refüjün, sağından geçmelisin." },
  q49: { f: "Bu işaret ne anlama gelir?",
    a: ["Sağa doğru geçiş hakkı bende", "Sağ taraftaki yol kapalı", "Sadece sağa gidebilirim"],
    e: "209 numaralı işaret (“Mecburi yön: sağ”): Burada sağa gitmelisin. Düz veya sola gitmek yasaktır." },
  q50: { f: "Bu işaret ne anlama gelir?",
    a: ["Dikkat çocuklar: Çok dikkatli sürmeli ve frene hazır olmalıyım", "Burada durmam gerekir", "Çocukların burada her zaman geçiş hakkı vardır"],
    e: "136 numaralı işaret (“Çocuklar”): Yolda veya yol kenarında çocuklar olabileceği konusunda uyarır. Yavaş git ve frene hazır ol. İşaret durmayı gerektirmez ve çocuklara geçiş hakkı vermez." },
  q51: { f: "Bir döner kavşağa girmek istiyorsun. Önünde “Yol ver” ve “Döner kavşak” işaretleri var. Girerken sinyal için ne geçerlidir?",
    a: ["Sağa sinyal vermeliyim", "Sinyal vermemeliyim", "Sola sinyal vermeliyim"],
    e: "Böyle bir döner kavşağa girerken sinyal kullanmak yasaktır. Yani girerken sinyal vermemelisin." },
  q52: { f: "Yerleşim yeri dışında tehlike işaretleri genellikle tehlike noktasından ne kadar önce konur?",
    e: "Yerleşim yeri dışında tehlike işaretleri genellikle tehlike noktasından 150 ila 250 m önce durur. Yerleşim yeri içinde tehlike noktasının hemen önünde bulunur. Bir ek levha daha kısa bir mesafeyi belirtebilir." },
  q53: { f: "Bir trafik ışığını kapatıyorsan, ondan en fazla kaç metre önce durman yasaktır?",
    e: "Bir araç trafik ışığını kapatıyorsa, ışıktan 10 m’ye kadar önünde durmak yasaktır. Böylece herkes ışığı görebilir." },
  q54: { f: "Sis nedeniyle görüş mesafesi 50 m’den azdır. En fazla ne kadar hızlı gidebilirsin?",
    e: "Sis, kar yağışı veya yağmur nedeniyle görüş mesafesi 50 m’den azsa, daha düşük bir hız gerekmedikçe 50 km/h’den hızlı gidilemez. Çoğu zaman daha yavaş gitmek daha akıllıcadır." },
  q55: { f: "Bir yaya geçidine (zebra) yaklaşıyorsun. Önünde yavaş giden bir araba var. Orada onu sollayabilir misin?",
    a: ["Evet, yaya görünmüyorsa", "Evet, korna çalarsam", "Hayır, yaya geçitlerinde sollama yapılamaz"],
    e: "Yaya geçitlerinde, o anda kimse karşıdan karşıya geçmese bile sollama yapılamaz." },
  q56: { f: "Trafik tıkanmış. Işığın yeşil ama kavşağın ötesinde arabana yer yok. Ne geçerlidir?",
    a: ["Kavşakta beklemem gerekecekse girmemeliyim", "Yeşil olduğu için girerim", "Girerim ve diğerleri yer açsın diye korna çalarım"],
    e: "Trafik tıkanmışsa, yeşil ışık olsa bile, kavşakta beklemek gerekecekse kavşağa girilmez. Böylece kavşak çapraz trafik için açık kalır." },
  q57: { f: "Her yönde tek şeridi olan bir kırsal yolda gidiyorsun. Temel kural olarak nerede gitmelisin?",
    a: ["Yolun ortasında", "Sadece karşıdan trafik varsa mümkün olduğunca sağda", "Mümkün olduğunca sağda"],
    e: "Sadece karşıdan trafik olduğunda, sollanırken, tepelerde, virajlarda veya görüş kısıtlıyken değil, her zaman mümkün olduğunca sağdan gidilmelidir." },
  q58: { f: "Sadece park etmek değil, durmak bile nerede yasaktır?",
    a: ["Geniş ve görüşün açık olduğu bir yolun sağ kenarında", "Dar ve görüşün kısıtlı olduğu yol noktalarında", "İşaretli bir park şeridinde"],
    e: "Durmak, diğer yerlerin yanı sıra dar ve görüşün kısıtlı olduğu yol noktalarında, keskin virajlarda ve demiryolu geçitlerinde yasaktır." },
  q59: { f: "Sağa dönmek istiyorsun. Zamanında nerede şeride girersin?",
    a: ["Mümkün olduğunca sağda", "Yolun ortasında", "Mümkün olduğunca solda"],
    e: "Sağa dönmek isteyen, aracını zamanında mümkün olduğunca sağa yerleştirir. Sola dönmek isteyen yol ortasına kadar yerleşir; tek yönlü yollarda mümkün olduğunca sola." },
  q60: { f: "Geceleyin kesintisiz ve yeterli aydınlatması olan bir yolda gidiyorsun. Hangi farı kullanırsın?",
    a: ["Sadece park lambasını", "Uzun farı", "Kısa farı"],
    e: "Yalnızca park lambasıyla gidilemez. Kesintisiz ve yeterli aydınlatması olan yollarda uzun farla da gidilemez. Yani kısa farla gidersin." },
};
