// Tiếng Việt. Luật là luật giao thông của Đức (StVO); số hiệu biển là số hiệu biển báo của Đức.
export default {
  q01: { f: "Bạn phải làm gì ở biển này?",
    a: ["Tiếp tục chạy chậm, không dừng lại", "Chỉ dừng lại nếu có xe khác tới", "Dừng lại, kể cả khi không có ai tới"],
    e: "Biển 206 (“Dừng lại! Nhường đường”): bạn phải dừng lại và nhường đường cho đường cắt ngang, kể cả khi không thấy xe nào khác." },
  q02: { f: "Biển này có nghĩa là gì?",
    a: ["Tôi được ưu tiên đi trước", "Tôi phải nhường đường cho xe trên đường cắt ngang", "Ở đây tôi luôn phải dừng lại"],
    e: "Biển 205 (“Nhường đường”): bạn phải để xe trên đường cắt ngang đi trước. Bạn chỉ phải dừng lại khi cần thiết." },
  q03: { f: "Bạn thấy biển này. Điều gì áp dụng cho bạn?",
    a: ["Tôi được ưu tiên ở các ngã tư và ngã ba tiếp theo", "Tôi phải chờ ở ngã tư tiếp theo", "Ở ngã tư tiếp theo áp dụng quy tắc nhường xe bên phải"],
    e: "Biển 306 (“Đường ưu tiên”): bạn được ưu tiên ở các ngã tư và ngã ba tiếp theo cho đến khi một biển báo kết thúc đường ưu tiên." },
  q04: { f: "Biển này có nghĩa là gì?",
    a: ["Ở đây tôi được ưu tiên", "Tôi không được đi vào đây", "Ở đây tôi chỉ được đi chậm"],
    e: "Biển 267 (“Cấm đi vào”) thường đặt ở cuối đường một chiều, ngược chiều xe chạy. Bạn không được đi vào." },
  q05: { f: "Ở biển này áp dụng điều gì?",
    a: ["Tôi được dừng xe ở đây tối đa 3 phút", "Tôi được đỗ xe ở đây nhưng không được dừng", "Tôi không được dừng xe ở đây"],
    e: "Biển 283 (“Cấm dừng hoàn toàn”): bạn không được dừng xe ở đó, dù chỉ một lát. Đỗ xe càng bị cấm." },
  q06: { f: "Ở biển này áp dụng điều gì?",
    a: ["Tôi được dừng xe ở đây tối đa 3 phút nhưng không được đỗ", "Tôi không bao giờ được dừng xe ở đây", "Tôi được đỗ xe ở đây bao lâu tùy thích"],
    e: "Biển 286 (“Cấm dừng có giới hạn”): bạn chỉ được dừng xe ở đó tối đa 3 phút. Đỗ xe bị cấm." },
  q07: { f: "Biển này có nghĩa là gì?",
    a: ["Tốc độ tối thiểu 30 km/h", "Hết mọi giới hạn tốc độ", "Bắt đầu khu vực có tốc độ tối đa 30 km/h"],
    e: "Biển 274.1 (“Khu vực 30 km/h”): trong cả khu vực tốc độ tối đa là 30 km/h cho đến khi một biển báo kết thúc khu vực." },
  q08: { f: "Bạn muốn vào bùng binh này. Trước đó có biển “Nhường đường”. Ai được ưu tiên?",
    a: ["Các xe đang muốn vào", "Các xe đã đang chạy trong bùng binh", "Xe to nhất"],
    e: "Biển 215 chỉ bùng binh. Khi phía trước có biển “Nhường đường”, bạn phải nhường cho các xe đang chạy trong vòng." },
  q09: { f: "Biển này có nghĩa là gì?",
    a: ["Đường một chiều: xe chỉ được chạy theo hướng mũi tên", "Đường ưu tiên: tôi luôn được ưu tiên", "Đường kết thúc ở đây"],
    e: "Biển 220 (“Đường một chiều”): xe chỉ được dùng đường theo hướng mũi tên. Hướng ngược lại bị cấm." },
  q10: { f: "Một người đi bộ muốn qua đường ở biển này. Bạn làm gì?",
    a: ["Tôi bấm còi để người đó chờ", "Tôi đi trước nếu đủ nhanh", "Tôi cho người đó qua và dừng lại nếu cần"],
    e: "Biển 350 (“Vạch qua đường cho người đi bộ”): người đi bộ rõ ràng muốn dùng vạch qua đường được ưu tiên. Bạn phải tiến lại gần cẩn thận và dừng lại nếu cần." },
  q11: { f: "Biển này có nghĩa là gì?",
    a: ["Tôi phải dừng lại", "Nơi nguy hiểm: tôi phải lái xe đặc biệt cẩn thận", "Tôi được ưu tiên"],
    e: "Biển 101 (“Nơi nguy hiểm”) cảnh báo một nguy hiểm. Hãy lái cẩn thận và chú ý biển phụ nêu rõ nguy hiểm." },
  q12: { f: "Ô tô có được đi trên con đường có biển này không?",
    a: ["Không, đường này dành cho người đi xe đạp", "Có, nếu đường trống", "Có, nhưng chỉ khi bật đèn khẩn cấp"],
    e: "Biển 237 (“Đường dành cho xe đạp”): đường này dành cho người đi xe đạp. Ô tô không được đi vào đó." },
  q13: { f: "Biển này có nghĩa là gì?",
    a: ["Cấm đi vào", "Chỉ dành cho cư dân", "Cấm mọi loại phương tiện"],
    e: "Biển 250 (“Cấm mọi loại phương tiện”): các phương tiện, kể cả xe đạp, không được đi vào đây." },
  q14: { f: "Biển này có nghĩa là gì?",
    a: ["Bắt đầu một khu vực cấm dừng", "Hết mọi lệnh cấm trước đó trên đoạn đường", "Bắt đầu đường cao tốc"],
    e: "Biển 282 (“Hết mọi lệnh cấm”) hủy các lệnh cấm đã đặt trước đó trên đoạn đường, ví dụ giới hạn tốc độ hay cấm vượt." },
  q15: { f: "Nếu không có biển nào chỉ khác, tốc độ tối đa của ô tô con trong khu dân cư là bao nhiêu?",
    e: "Trong khu dân cư, ô tô con được chạy 50 km/h nếu không có biển nào quy định khác." },
  q16: { f: "Nếu không có biển nào chỉ khác, tốc độ tối đa của ô tô con không kéo rơ-moóc trên đường ngoài khu dân cư là bao nhiêu?",
    e: "Ngoài khu dân cư, ô tô con không kéo rơ-moóc được chạy 100 km/h trên đường thường nếu không có biển nào quy định khác." },
  q17: { f: "Tốc độ khuyến nghị nào áp dụng trên đường cao tốc Autobahn?",
    e: "Tốc độ khuyến nghị 130 km/h là một lời khuyên, không phải quy định bắt buộc. Nhưng chạy nhanh hơn làm tăng rủi ro." },
  q18: { f: "Bạn đến một ngã tư không có biển báo và không có đèn giao thông. Một ô tô đang tới từ bên phải. Điều gì áp dụng?",
    a: ["Tôi phải nhường đường cho xe đó", "Tôi được ưu tiên", "Xe nào nhanh hơn thì đi trước"],
    e: "“Bên phải được ưu tiên”: khi không có biển báo và đèn giao thông, xe đến từ bên phải được ưu tiên." },
  q19: { f: "Bạn có được cầm điện thoại di động trên tay khi đang lái xe không?",
    a: ["Có, nếu tôi chạy chậm", "Không, điều đó bị cấm", "Có, nhưng chỉ để gọi điện"],
    e: "Không được cầm điện thoại di động trên tay khi đang lái xe. Chỉ được gọi điện bằng thiết bị rảnh tay." },
  q20: { f: "Nói chung, ai trong ô tô phải thắt dây an toàn?",
    a: ["Chỉ người lái xe", "Người lái xe và người ngồi ghế phụ", "Mọi người trong xe, kể cả ghế sau"],
    e: "Tất cả người ngồi trong xe phải thắt dây an toàn, kể cả ở ghế sau." },
  q21: { f: "Trẻ em dưới 12 tuổi cao dưới 150 cm phải được bảo vệ trong ô tô như thế nào?",
    a: ["Trong ghế trẻ em phù hợp", "Bằng dây an toàn thường ở ghế phụ, không có ghế trẻ em", "Ngồi trong lòng người lớn"],
    e: "Trẻ em dưới 12 tuổi cao dưới 150 cm cần một hệ thống giữ trẻ em phù hợp trong ô tô, tức là ghế trẻ em." },
  q22: { f: "Về rượu bia, điều gì áp dụng cho người mới lái trong thời gian thử việc và mọi người lái xe dưới 21 tuổi?",
    a: ["Được phép 0,3 phần nghìn", "Hoàn toàn không rượu bia (0,0 phần nghìn)", "Được phép 0,5 phần nghìn"],
    e: "Người mới lái trong thời gian thử việc và người lái xe dưới 21 tuổi bị cấm tuyệt đối rượu bia và cần sa (THC) khi lái xe." },
  q23: { f: "Thời gian thử việc của người mới lái kéo dài bao lâu?",
    a: ["6 tháng", "1 năm", "2 năm"],
    e: "Thời gian thử việc kéo dài 2 năm kể từ ngày cấp giấy phép lái xe." },
  q24: { f: "Khoảng cách nào đến xe phía trước là đúng?",
    a: ["Một thân xe", "Đủ lớn để tôi kịp dừng lại ngay cả khi xe trước phanh gấp", "Luôn đúng 10 mét"],
    e: "Khoảng cách phải đủ lớn để bạn dừng được sau xe phía trước, ngay cả khi nó phanh gấp. Quy tắc nhanh: khoảng cách tính bằng mét ít nhất bằng một nửa số chỉ trên đồng hồ tốc độ." },
  q25: { f: "Theo công thức nhanh, quãng đường phanh ở 50 km/h trên đường khô là bao nhiêu?",
    e: "Quãng đường phanh = (tốc độ : 10) × (tốc độ : 10). Ở 50 km/h là 5 × 5 = 25 m. Quãng đường dừng xe dài hơn vì còn cộng thêm thời gian phản ứng." },
  q26: { f: "Bạn chạy nhanh gấp đôi. Quãng đường phanh trở thành bao nhiêu?",
    a: ["Dài gấp đôi", "Dài gấp ba", "Dài gấp bốn"],
    e: "Quãng đường phanh tăng theo bình phương tốc độ: tốc độ gấp đôi nghĩa là quãng đường phanh dài gấp bốn." },
  q27: { f: "Theo công thức nhanh, quãng đường phản ứng ở 50 km/h là bao nhiêu?",
    e: "Quãng đường phản ứng = (tốc độ : 10) × 3. Ở 50 km/h là 5 × 3 = 15 m mà bạn đi được trước khi bắt đầu phanh." },
  q28: { f: "Bạn tuyệt đối không được vượt xe ở đâu?",
    a: ["Trước một khúc cua khuất tầm nhìn", "Trên đường thường thẳng và trống", "Ở làn trái của đường cao tốc"],
    e: "Bạn chỉ được vượt nếu nhìn thấy đoạn đường phía trước. Trước khúc cua khuất tầm nhìn hoặc đỉnh dốc, cấm vượt." },
  q29: { f: "Bạn vượt một người đi xe đạp trong khu dân cư. Khoảng cách ngang tối thiểu bạn phải giữ là bao nhiêu?",
    e: "Khi vượt người đi xe đạp, người đi bộ và xe scooter điện, bạn phải giữ khoảng cách ngang ít nhất 1,5 m trong khu dân cư và ít nhất 2 m ngoài khu dân cư." },
  q30: { f: "Cấm đỗ xe cách ngã tư tối đa bao nhiêu mét về phía trước, nếu bên phải đường không có làn xe đạp?",
    e: "Trước và sau ngã tư, ngã ba, cấm đỗ xe trong phạm vi 5 m mỗi bên, tính từ các điểm nơi mép đường gặp nhau. Nếu bên phải đường có đường xe đạp xây riêng, thì trước ngã tư là 8 m. Khoảng 15 m áp dụng cho trạm xe buýt (biển 224), không áp dụng cho ngã tư." },
  q31: { f: "Cấm đỗ xe cách biển trạm xe buýt bao xa, trước và sau?",
    e: "Bạn không được đỗ xe trong phạm vi 15 m trước và sau biển trạm xe buýt (biển 224)." },
  q32: { f: "Giao thông tắc trên đường cao tốc có ba làn mỗi chiều. Bạn tạo lối đi cho xe cứu hộ ở đâu?",
    a: ["Trên làn dừng khẩn cấp", "Giữa làn giữa và làn phải", "Giữa làn trái và làn giữa"],
    e: "Lối đi cho xe cứu hộ được tạo giữa làn trái và các làn còn lại: xe ở làn trái tránh sang trái, tất cả xe khác tránh sang phải." },
  q33: { f: "Một xe cứu thương bật đèn xanh và còi hú tiến lại từ phía sau. Bạn làm gì?",
    a: ["Tôi chạy nhanh hơn để xe đó không phải vượt", "Tôi nhường đường ngay lập tức", "Tôi chạy tiếp như bình thường"],
    e: "Khi có đèn xanh và còi hú, bạn phải nhường đường ngay lập tức, ví dụ tấp vào lề và dừng lại nếu cần." },
  q34: { f: "Đèn giao thông chuyển sang vàng và bạn vẫn có thể dừng an toàn. Bạn phải làm gì?",
    a: ["Dừng lại", "Chạy nhanh qua", "Tăng tốc"],
    e: "Đèn vàng yêu cầu chờ trước ngã tư đến tín hiệu tiếp theo." },
  q35: { f: "Đèn giao thông đỏ, bên cạnh có biển mũi tên xanh chỉ sang phải. Nếu bạn muốn rẽ phải thì điều gì áp dụng?",
    a: ["Tôi được rẽ mà không cần dừng", "Tôi chỉ được rẽ khi đèn xanh", "Sau khi dừng, tôi được rẽ nếu không gây nguy hiểm hay cản trở ai"],
    e: "Ở mũi tên xanh, bạn phải dừng lại trước. Sau đó bạn được rẽ phải nếu không gây nguy hiểm hay cản trở ai, nhất là người đi bộ và người đi xe đạp. Bạn cũng có thể chờ đến khi đèn xanh." },
  q36: { f: "Một cảnh sát điều khiển giao thông ngã tư bằng tay. Đèn giao thông là xanh với bạn. Điều gì áp dụng?",
    a: ["Đèn giao thông có hiệu lực", "Tín hiệu của cảnh sát được ưu tiên", "Tôi tự quyết định"],
    e: "Tín hiệu và chỉ dẫn của cảnh sát được ưu tiên hơn đèn giao thông và biển báo." },
  q37: { f: "Bạn rẽ phải. Người đi bộ muốn qua con đường mà bạn rẽ vào. Điều gì áp dụng?",
    a: ["Tôi phải cho họ qua và chờ nếu cần", "Họ phải chờ vì tôi đang rẽ", "Ai đến trước thì được ưu tiên"],
    e: "Người rẽ phải cho người đi bộ đang qua con đường mà mình rẽ vào đi qua, và chờ nếu cần." },
  q38: { f: "Bạn muốn rẽ trái. Một ô tô đi ngược chiều và đi thẳng. Ai được ưu tiên?",
    a: ["Tôi", "Xe nhanh hơn", "Xe đi thẳng"],
    e: "Người rẽ trái phải nhường cho xe ngược chiều đi thẳng hoặc rẽ phải." },
  q39: { f: "Bạn đang ở làn tăng tốc để nhập vào đường cao tốc. Ai được ưu tiên?",
    a: ["Xe trên đường chính", "Tôi, vì tôi đang tăng tốc", "Xe nào đi bên phải hơn"],
    e: "Trên đường cao tốc, xe chạy trên đường chính được ưu tiên. Bạn điều chỉnh tốc độ và nhập làn mà không cản trở người khác." },
  q40: { f: "Ô tô của bạn hỏng trên một con đường ngoài khu dân cư. Bạn đặt tam giác cảnh báo cách xe khoảng bao xa?",
    e: "Ngoài khu dân cư bạn đặt tam giác cảnh báo cách xe khoảng 100 m, trong khu dân cư khoảng 50 m, để các tài xế khác được cảnh báo kịp thời." },
  q41: { f: "Trong khu vực giao thông hạn chế (biển 325.1) bạn được chạy nhanh bao nhiêu?",
    a: ["30 km/h", "50 km/h", "Tốc độ đi bộ"],
    e: "Trong khu vực giao thông hạn chế chỉ được chạy với tốc độ đi bộ. Người đi bộ được dùng cả con đường và không được cản trở họ." },
  q42: { f: "Bạn xuất phát từ lề đường. Điều gì đúng?",
    a: ["Bấm còi là đủ", "Bật xi nhan và chắc chắn rằng không gây nguy hiểm cho ai", "Xe đang chạy phải nhường cho tôi"],
    e: "Người xuất phát phải cư xử sao cho không gây nguy hiểm cho người khác: nhìn gương, nhìn qua vai và bật xi nhan." },
  q43: { f: "Khi nào ở Đức bắt buộc phải dùng lốp mùa đông?",
    a: ["Khi đường có băng đen, tuyết phủ, tuyết tan nhão, băng hoặc sương giá", "Từ 1 tháng 10 đến 31 tháng 3", "Chỉ ở vùng núi"],
    e: "Không có mùa cố định: khi đường có băng đen, tuyết phủ, tuyết tan nhão, băng hoặc sương giá, bạn cần lốp mùa đông." },
  q44: { f: "Bạn chỉ được bật đèn sương mù phía sau khi tầm nhìn do sương mù dưới …",
    e: "Đèn sương mù phía sau làm lóa mắt tài xế khác. Chỉ được bật khi tầm nhìn dưới 50 m và sau đó phải tắt." },
  q45: { f: "Biển này có nghĩa là gì?",
    a: ["Cấm vượt đối với mọi phương tiện cơ giới", "Hết cấm vượt", "Cấm vượt chỉ đối với xe tải"],
    e: "Biển 276 (“Cấm vượt đối với mọi loại phương tiện cơ giới”): phương tiện cơ giới không được vượt phương tiện cơ giới nhiều bánh cho đến khi một biển chấm dứt lệnh cấm." },
  q46: { f: "Biển này cho biết điều gì?",
    a: ["Đường ưu tiên kết thúc ở đây", "Ở ngã tư tiếp theo tôi phải dừng", "Ở ngã tư hoặc ngã ba tiếp theo tôi được ưu tiên"],
    e: "Biển 301 (“Quyền ưu tiên”) cho biết bạn được ưu tiên ở ngã tư hoặc ngã ba tiếp theo. Ngược lại, biển 306 (“Đường ưu tiên”) có hiệu lực qua nhiều ngã tư." },
  q47: { f: "Biển này có nghĩa là gì?",
    a: ["Người đi bộ và người đi xe đạp được dùng lối này", "Chỉ người đi bộ được dùng lối này", "Ở đây bắt đầu khu vực dành cho người đi bộ"],
    e: "Biển 239 (“Đường dành cho người đi bộ”): lối này dành cho người đi bộ. Các phương tiện khác không được dùng, trừ khi biển phụ cho phép." },
  q48: { f: "Biển này có nghĩa là gì?",
    a: ["Tôi phải đi qua bên phải", "Ở đây tôi phải rẽ phải", "Ở đây tôi được đỗ xe bên phải"],
    e: "Biển 222 (“Đi vòng bên phải”): bạn phải đi qua chướng ngại vật, ví dụ đảo giao thông, ở phía bên phải." },
  q49: { f: "Biển này có nghĩa là gì?",
    a: ["Tôi được ưu tiên về bên phải", "Đường bên phải bị chặn", "Tôi chỉ được đi sang phải"],
    e: "Biển 209 (“Hướng đi bắt buộc: phải”): ở đây bạn phải đi sang phải. Đi thẳng hoặc rẽ trái là không được phép." },
  q50: { f: "Biển này có nghĩa là gì?",
    a: ["Chú ý trẻ em: tôi phải lái xe đặc biệt cẩn thận và sẵn sàng phanh", "Ở đây tôi phải dừng lại", "Ở đây trẻ em luôn được ưu tiên"],
    e: "Biển 136 (“Trẻ em”) cảnh báo có trẻ em trên đường hoặc bên đường. Hãy lái chậm và sẵn sàng phanh. Biển không yêu cầu dừng lại và không cho trẻ em quyền ưu tiên." },
  q51: { f: "Bạn muốn vào một vòng xuyến. Phía trước có biển “Nhường đường” và “Vòng xuyến”. Khi vào thì quy định gì áp dụng cho đèn xi-nhan?",
    a: ["Tôi phải bật xi-nhan phải", "Tôi không được bật xi-nhan", "Tôi phải bật xi-nhan trái"],
    e: "Khi vào một vòng xuyến như vậy, không được dùng đèn xi-nhan. Vì thế bạn không được bật xi-nhan khi vào." },
  q52: { f: "Ngoài khu dân cư, biển cảnh báo nguy hiểm thường đặt cách nơi nguy hiểm bao xa?",
    e: "Ngoài khu dân cư, biển cảnh báo nguy hiểm thường đặt cách nơi nguy hiểm từ 150 đến 250 m. Trong khu dân cư, biển đặt ngay trước nơi nguy hiểm. Biển phụ có thể ghi khoảng cách ngắn hơn." },
  q53: { f: "Nếu bạn che khuất đèn giao thông, cấm dừng xe cách đèn tối đa bao nhiêu mét?",
    e: "Người lái xe không được dừng xe trong phạm vi 10 m trước đèn giao thông nếu xe che khuất đèn. Như vậy ai cũng nhìn thấy đèn." },
  q54: { f: "Vì sương mù, tầm nhìn dưới 50 m. Bạn được chạy nhanh nhất là bao nhiêu?",
    e: "Nếu tầm nhìn do sương mù, tuyết hay mưa dưới 50 m, không được chạy nhanh hơn 50 km/h, trừ khi cần tốc độ thấp hơn nữa. Thường thì chạy chậm hơn là khôn ngoan hơn." },
  q55: { f: "Bạn đang đến gần vạch qua đường cho người đi bộ (vạch ngựa vằn). Phía trước có một ô tô đi chậm. Bạn có được vượt nó ở đó không?",
    a: ["Có, nếu không thấy người đi bộ", "Có, nếu tôi bấm còi", "Không, không được vượt ở vạch qua đường cho người đi bộ"],
    e: "Không được vượt ở vạch qua đường cho người đi bộ, ngay cả khi lúc đó không có ai đang qua đường." },
  q56: { f: "Giao thông bị ùn tắc. Đèn của bạn xanh, nhưng sau ngã tư không còn chỗ cho xe của bạn. Điều gì áp dụng?",
    a: ["Tôi không được vào nếu phải chờ giữa ngã tư", "Tôi vào vì đèn xanh", "Tôi vào và bấm còi để người khác nhường chỗ"],
    e: "Nếu giao thông ùn tắc, dù đèn xanh cũng không được vào ngã tư nếu phải chờ trong đó. Như vậy ngã tư luôn thông cho xe đi ngang." },
  q57: { f: "Bạn đang lái trên đường quốc lộ có một làn mỗi chiều. Theo nguyên tắc bạn phải đi ở đâu?",
    a: ["Ở giữa đường", "Chỉ khi có xe đi ngược chiều thì mới đi sát phải nhất có thể", "Sát bên phải nhất có thể"],
    e: "Luôn phải đi sát bên phải nhất có thể, không chỉ khi có xe ngược chiều, khi bị vượt, ở đỉnh dốc, ở khúc cua hay khi tầm nhìn kém." },
  q58: { f: "Ở đâu cấm cả dừng xe (không chỉ đỗ xe)?",
    a: ["Ở mép phải của một con đường rộng, tầm nhìn tốt", "Ở những đoạn đường hẹp và khuất tầm nhìn", "Trên làn đỗ xe có vạch kẻ"],
    e: "Cấm dừng xe, trong số các nơi khác, ở những đoạn đường hẹp và khuất tầm nhìn, ở khúc cua gấp và tại các điểm giao với đường sắt." },
  q59: { f: "Bạn muốn rẽ phải. Bạn vào vị trí nào từ sớm?",
    a: ["Sát bên phải nhất có thể", "Ở giữa đường", "Sát bên trái nhất có thể"],
    e: "Ai muốn rẽ phải thì đưa xe sát bên phải nhất có thể từ sớm. Ai muốn rẽ trái thì vào vị trí đến giữa đường, còn trên đường một chiều thì sát bên trái nhất có thể." },
  q60: { f: "Ban đêm bạn lái xe trên đường có chiếu sáng liên tục và đủ sáng. Bạn dùng đèn nào?",
    a: ["Chỉ đèn vị trí", "Đèn pha", "Đèn cốt"],
    e: "Không được chạy chỉ với đèn vị trí. Trên đường có chiếu sáng liên tục và đủ sáng cũng không được dùng đèn pha. Vì vậy bạn chạy với đèn cốt." },
};
