/* Texte von Spiel 10 „Duell gegen Mitschüler“ in allen 18 Sprachen (06.10.2026), Schlüssel mit Präfix du.
   Wie spiele/texte.js: fehlt ein Schlüssel, erscheint Deutsch. Einbau: in spiele/texte.js am Ende
     import { TEXTE_DUELL } from "./texte-duell.js";  und  Object.keys(TEXTE_DUELL).forEach(function (l) { Object.assign(TEXTE[l], TEXTE_DUELL[l]); });
   damit auch die Spielkarte (duName, duKurz) über k.tx() gefunden wird. Das Spiel selbst findet seine Texte auch ohne diesen Einbau.
   Zahlen/Einheiten bleiben lateinisch. Platzhalter: {n} {m} {a} {b} {name}.
   NICHT von Muttersprachlern geprüft: rif, ckb, kmr, ps, am, ti (wie bei den bisherigen Sprachpaketen). Die Fragen stehen in spiele/duell-fragen.js. */

export const TEXTE_DUELL = {
  de: {
    duName: "Duell gegen Mitschüler",
    duKurz: "Beantworte 8 Verkehrsfragen und miss dich mit einem Mitschüler. Ihr müsst nicht gleichzeitig spielen.",
    duIntro: "Du und ein Mitschüler bekommt dieselben 8 Fragen. Wer mehr Punkte hat, gewinnt. Richtig und schnell bringt die meisten Punkte. Ihr müsst nicht gleichzeitig online sein.",
    duBilanz: "Deine Bilanz",
    duSiege: "Siege",
    duUnentschieden: "Unentschieden",
    duNiederlagen: "Niederlagen",
    duBilanzFrist: "Gezählt werden die Duelle der letzten 90 Tage.",
    duNeu: "Neues Duell starten",
    duNeuHinweis: "Du spielst zuerst. Danach wartet dein Duell auf einen Mitschüler.",
    duLimit: "Du hast schon {n} laufende Duelle. Spiele sie zuerst zu Ende.",
    duLimitKurz: "Du hast schon zu viele laufende Duelle. Spiele sie zuerst zu Ende.",
    duAusgeblendet: "Du bist im Ranking ausgeblendet. Deine Herausforderung würde niemand sehen. Du kannst aber offene Herausforderungen annehmen.",
    duMeine: "Deine Duelle",
    duMeineLeer: "Du hast noch kein Duell gespielt.",
    duOffene: "Offene Herausforderungen",
    duOffeneLeer: "Gerade wartet niemand auf einen Gegner. Starte ein Duell, dann sieht es hier ein Mitschüler.",
    duVerfall: "Duelle ohne Ergebnis verfallen nach 7 Tagen. Ein angenommenes Duell musst du innerhalb von 24 Stunden starten, sonst wartet es wieder auf einen anderen Mitschüler.",
    duWeiterspielen: "Weiterspielen",
    duWeiterText: "Deine Runde ist noch offen. Du bekommst dieselben 8 Fragen noch einmal. Die Zeit seit deinem ersten Start läuft weiter, du hast insgesamt höchstens 10 Minuten.",
    duAnnehmen: "Annehmen",
    duJetztSpielen: "Jetzt spielen",
    duStDran: "Du bist dran",
    duStLaeuft: "Runde gestartet, aber nicht beendet",
    duStWartetGegner: "Wartet auf einen Mitschüler",
    duStGegnerSpielt: "Dein Gegner ist noch dran",
    duPunkteIch: "Dein Ergebnis: {n} Punkte",
    duSieg: "Gewonnen",
    duNiederlage: "Verloren",
    duSiegGross: "Gewonnen!",
    duNiederlageGross: "Verloren",
    duUnentschiedenGross: "Unentschieden",
    duMitschueler: "Mitschüler",
    duDeinDuell: "Dein Duell",
    duGegen: "gegen {name}",
    duPunkteZeile: "{a} : {b} Punkte",
    duAktualisieren: "Aktualisieren",
    duVorschau: "Duelle brauchen dein Konto. In der Vorschau kannst du sie nicht spielen.",
    duLadenFehler: "Die Duelle konnten nicht geladen werden.",
    duVorMin: "vor {n} Min.",
    duVorStd: "vor {n} Std.",
    duVorTag: "vor {n} Tg.",
    duJetzt: "gerade eben",
    duBereitTitel: "Bereit?",
    duBereitText: "8 Fragen, je höchstens 20 Sekunden. Richtig bringt 100 Punkte, schnell bis zu 50 Bonuspunkte. Du kannst die Runde nicht wiederholen und nicht unterbrechen: Wer aufhört, bekommt 0 Punkte. Nach der Runde siehst du die richtigen Antworten.",
    duLos: "Los",
    duZurueck: "Zurück",
    duFrage: "Frage {n} von {m}",
    duZeichenAlt: "Verkehrszeichen",
    duAuswerten: "Wird ausgewertet …",
    duErgebnis: "Dein Ergebnis",
    duRichtigVon: "{n} von {m} richtig",
    duWartet: "Dein Ergebnis steht. Sobald dein Gegner gespielt hat, siehst du unter „Deine Duelle“, wer gewonnen hat.",
    duGegnerPunkte: "{name}: {n} Punkte",
    duAuswertung: "Auswertung",
    duRichtigLabel: "Richtig",
    duFalschLabel: "Falsch",
    duKeineAntwort: "Keine Antwort (Zeit abgelaufen)",
    duDeineAntwort: "Deine Antwort",
    duRichtigeAntwort: "Richtige Antwort",
    duNichtGespeichert: "Dein Ergebnis konnte nicht gespeichert werden. Versuche es noch einmal.",
    duNichtGespeichertEndgueltig: "Dein Ergebnis wurde nicht gewertet. Die Runde ist abgelaufen oder die Angaben passten nicht.",
    duNochmalSenden: "Noch einmal senden",
    duSchonGespielt: "Diese Runde hast du schon gespielt. Das Ergebnis siehst du unter „Deine Duelle“.",
    duFehlerVergeben: "Dieses Duell hat schon jemand angenommen.",
    duFehlerVerfallen: "Dieses Duell gibt es nicht mehr oder es ist abgelaufen.",
    duFehlerRate: "Zu viele Anfragen. Warte kurz und versuche es noch einmal.",
    duFehlerAllgemein: "Das hat nicht geklappt. Versuche es später noch einmal.",
    duZurUebersicht: "Zur Übersicht"
  },
  tr: {
    duName: "Sınıf arkadaşıyla düello",
    duKurz: "8 trafik sorusunu yanıtla ve bir sınıf arkadaşınla yarış. Aynı anda oynamanız gerekmez.",
    duIntro: "Sen ve bir sınıf arkadaşın aynı 8 soruyu alırsınız. Daha çok puan alan kazanır. Doğru ve hızlı cevap en çok puan getirir. Aynı anda çevrimiçi olmanız gerekmez.",
    duBilanz: "Sonuçların",
    duSiege: "Galibiyet",
    duUnentschieden: "Beraberlik",
    duNiederlagen: "Mağlubiyet",
    duBilanzFrist: "Son 90 günün düelloları sayılır.",
    duNeu: "Yeni düello başlat",
    duNeuHinweis: "Önce sen oynarsın. Sonra düellon bir sınıf arkadaşını bekler.",
    duLimit: "Zaten {n} devam eden düellon var. Önce onları bitir.",
    duLimitKurz: "Çok fazla devam eden düellon var. Önce onları bitir.",
    duAusgeblendet: "Sıralamada gizlisin. Meydan okumanı kimse göremez. Ama açık meydan okumaları kabul edebilirsin.",
    duMeine: "Düelloların",
    duMeineLeer: "Henüz hiç düello oynamadın.",
    duOffene: "Açık meydan okumalar",
    duOffeneLeer: "Şu an rakip bekleyen yok. Bir düello başlat, burada bir sınıf arkadaşın görsün.",
    duVerfall: "Sonuçsuz düellolar 7 gün sonra geçersiz olur. Kabul ettiğin bir düelloyu 24 saat içinde başlatmalısın, yoksa düello yeniden başka bir sınıf arkadaşını bekler.",
    duWeiterspielen: "Devam et",
    duWeiterText: "Turun hâlâ açık. Aynı 8 soruyu bir kez daha alırsın. İlk başlangıçtan beri geçen süre işlemeye devam eder; toplam en fazla 10 dakikan var.",
    duAnnehmen: "Kabul et",
    duJetztSpielen: "Şimdi oyna",
    duStDran: "Sıra sende",
    duStLaeuft: "Tur başladı ama bitmedi",
    duStWartetGegner: "Bir sınıf arkadaşını bekliyor",
    duStGegnerSpielt: "Rakibin henüz oynamadı",
    duPunkteIch: "Sonucun: {n} puan",
    duSieg: "Kazandın",
    duNiederlage: "Kaybettin",
    duSiegGross: "Kazandın!",
    duNiederlageGross: "Kaybettin",
    duUnentschiedenGross: "Berabere",
    duMitschueler: "Sınıf arkadaşı",
    duDeinDuell: "Senin düellon",
    duGegen: "{name} ile",
    duPunkteZeile: "{a} : {b} puan",
    duAktualisieren: "Yenile",
    duVorschau: "Düello için hesabın gerekir. Önizlemede oynayamazsın.",
    duLadenFehler: "Düellolar yüklenemedi.",
    duVorMin: "{n} dk. önce",
    duVorStd: "{n} sa. önce",
    duVorTag: "{n} gün önce",
    duJetzt: "az önce",
    duBereitTitel: "Hazır mısın?",
    duBereitText: "8 soru, her biri en fazla 20 saniye. Doğru cevap 100 puan, hızlı cevap en fazla 50 bonus puan getirir. Turu tekrarlayamaz ve yarıda kesemezsin: Bırakan 0 puan alır. Turdan sonra doğru cevapları görürsün.",
    duLos: "Başla",
    duZurueck: "Geri",
    duFrage: "Soru {n} / {m}",
    duZeichenAlt: "Trafik işareti",
    duAuswerten: "Değerlendiriliyor …",
    duErgebnis: "Sonucun",
    duRichtigVon: "{m} sorudan {n} doğru",
    duWartet: "Sonucun belli. Rakibin oynadığında, kimin kazandığını “Düelloların” altında görürsün.",
    duGegnerPunkte: "{name}: {n} puan",
    duAuswertung: "Değerlendirme",
    duRichtigLabel: "Doğru",
    duFalschLabel: "Yanlış",
    duKeineAntwort: "Cevap yok (süre doldu)",
    duDeineAntwort: "Cevabın",
    duRichtigeAntwort: "Doğru cevap",
    duNichtGespeichert: "Sonucun kaydedilemedi. Lütfen tekrar dene.",
    duNichtGespeichertEndgueltig: "Sonucun sayılmadı. Tur süresi doldu ya da bilgiler uymadı.",
    duNochmalSenden: "Tekrar gönder",
    duSchonGespielt: "Bu turu zaten oynadın. Sonucu “Düelloların” altında görürsün.",
    duFehlerVergeben: "Bu düelloyu başka biri zaten kabul etti.",
    duFehlerVerfallen: "Bu düello artık yok ya da süresi doldu.",
    duFehlerRate: "Çok fazla istek. Biraz bekle ve tekrar dene.",
    duFehlerAllgemein: "Olmadı. Lütfen daha sonra tekrar dene.",
    duZurUebersicht: "Genel bakışa"
  },
  en: {
    duName: "Duel with a classmate",
    duKurz: "Answer 8 traffic questions and compete with a classmate. You do not have to play at the same time.",
    duIntro: "You and a classmate get the same 8 questions. Whoever scores more points wins. Right and fast earns the most points. You do not have to be online at the same time.",
    duBilanz: "Your record",
    duSiege: "Wins",
    duUnentschieden: "Draws",
    duNiederlagen: "Losses",
    duBilanzFrist: "Duels from the last 90 days are counted.",
    duNeu: "Start a new duel",
    duNeuHinweis: "You play first. Then your duel waits for a classmate.",
    duLimit: "You already have {n} duels in progress. Finish them first.",
    duLimitKurz: "You already have too many duels in progress. Finish them first.",
    duAusgeblendet: "You are hidden from the ranking. Nobody would see your challenge. But you can accept open challenges.",
    duMeine: "Your duels",
    duMeineLeer: "You have not played a duel yet.",
    duOffene: "Open challenges",
    duOffeneLeer: "Nobody is waiting for an opponent right now. Start a duel and a classmate will see it here.",
    duVerfall: "Duels without a result expire after 7 days. If you accept a duel, you must start it within 24 hours, otherwise it goes back to waiting for another classmate.",
    duWeiterspielen: "Keep playing",
    duWeiterText: "Your round is still open. You get the same 8 questions again. The time since your first start keeps running; you have 10 minutes in total.",
    duAnnehmen: "Accept",
    duJetztSpielen: "Play now",
    duStDran: "Your turn",
    duStLaeuft: "Round started but not finished",
    duStWartetGegner: "Waiting for a classmate",
    duStGegnerSpielt: "Your opponent has not played yet",
    duPunkteIch: "Your result: {n} points",
    duSieg: "Won",
    duNiederlage: "Lost",
    duSiegGross: "You won!",
    duNiederlageGross: "You lost",
    duUnentschiedenGross: "A draw",
    duMitschueler: "Classmate",
    duDeinDuell: "Your duel",
    duGegen: "against {name}",
    duPunkteZeile: "{a} : {b} points",
    duAktualisieren: "Refresh",
    duVorschau: "Duels need your account. You cannot play them in the preview.",
    duLadenFehler: "The duels could not be loaded.",
    duVorMin: "{n} min ago",
    duVorStd: "{n} h ago",
    duVorTag: "{n} days ago",
    duJetzt: "just now",
    duBereitTitel: "Ready?",
    duBereitText: "8 questions, 20 seconds each at most. A right answer earns 100 points, a fast one up to 50 bonus points. You cannot repeat or interrupt the round: if you stop, you get 0 points. After the round you see the right answers.",
    duLos: "Go",
    duZurueck: "Back",
    duFrage: "Question {n} of {m}",
    duZeichenAlt: "Traffic sign",
    duAuswerten: "Scoring …",
    duErgebnis: "Your result",
    duRichtigVon: "{n} of {m} right",
    duWartet: "Your result is in. As soon as your opponent has played, you will see who won under “Your duels”.",
    duGegnerPunkte: "{name}: {n} points",
    duAuswertung: "Review",
    duRichtigLabel: "Right",
    duFalschLabel: "Wrong",
    duKeineAntwort: "No answer (time ran out)",
    duDeineAntwort: "Your answer",
    duRichtigeAntwort: "Right answer",
    duNichtGespeichert: "Your result could not be saved. Please try again.",
    duNichtGespeichertEndgueltig: "Your result did not count. The round has expired or the data did not match.",
    duNochmalSenden: "Send again",
    duSchonGespielt: "You have already played this round. You will see the result under “Your duels”.",
    duFehlerVergeben: "Someone has already accepted this duel.",
    duFehlerVerfallen: "This duel no longer exists or has expired.",
    duFehlerRate: "Too many requests. Wait a moment and try again.",
    duFehlerAllgemein: "That did not work. Please try again later.",
    duZurUebersicht: "To the overview"
  },
  ar: {
    duName: "مبارزة مع زميل",
    duKurz: "أجب عن 8 أسئلة مرورية وتنافس مع زميل. لا يلزم أن تلعبا في الوقت نفسه.",
    duIntro: "أنت وزميلك تحصلان على الأسئلة الثمانية نفسها. من يجمع نقاطاً أكثر يفوز. الإجابة الصحيحة والسريعة تمنح أكبر عدد من النقاط. لا يلزم أن تكونا متصلين في الوقت نفسه.",
    duBilanz: "حصيلتك",
    duSiege: "انتصارات",
    duUnentschieden: "تعادل",
    duNiederlagen: "هزائم",
    duBilanzFrist: "تُحتسب مبارزات آخر 90 يوماً.",
    duNeu: "ابدأ مبارزة جديدة",
    duNeuHinweis: "تلعب أنت أولاً. ثم تنتظر مبارزتك زميلاً.",
    duLimit: "لديك بالفعل {n} مبارزات جارية. أنهِها أولاً.",
    duLimitKurz: "لديك مبارزات جارية كثيرة. أنهِها أولاً.",
    duAusgeblendet: "تم إخفاؤك من الترتيب. لن يرى أحد تحديك. لكن يمكنك قبول التحديات المفتوحة.",
    duMeine: "مبارزاتك",
    duMeineLeer: "لم تلعب أي مبارزة بعد.",
    duOffene: "تحديات مفتوحة",
    duOffeneLeer: "لا أحد ينتظر خصماً الآن. ابدأ مبارزة وسيراها زميل هنا.",
    duVerfall: "المبارزات بلا نتيجة تنتهي صلاحيتها بعد 7 أيام. إذا قبلت مبارزة فعليك أن تبدأها خلال 24 ساعة، وإلا فستعود لتنتظر زميلاً آخر.",
    duWeiterspielen: "تابع اللعب",
    duWeiterText: "جولتك ما زالت مفتوحة. ستحصل على الأسئلة الـ 8 نفسها مرة أخرى. الوقت منذ بدايتك الأولى يواصل الجريان، ولديك 10 دقائق كحد أقصى في المجموع.",
    duAnnehmen: "قبول",
    duJetztSpielen: "العب الآن",
    duStDran: "دورك",
    duStLaeuft: "بدأت الجولة ولم تنتهِ",
    duStWartetGegner: "تنتظر زميلاً",
    duStGegnerSpielt: "خصمك لم يلعب بعد",
    duPunkteIch: "نتيجتك: {n} نقطة",
    duSieg: "فوز",
    duNiederlage: "خسارة",
    duSiegGross: "لقد فزت!",
    duNiederlageGross: "لقد خسرت",
    duUnentschiedenGross: "تعادل",
    duMitschueler: "زميل",
    duDeinDuell: "مبارزتك",
    duGegen: "ضد {name}",
    duPunkteZeile: "{a} : {b} نقطة",
    duAktualisieren: "تحديث",
    duVorschau: "المبارزات تحتاج إلى حسابك. لا يمكنك لعبها في المعاينة.",
    duLadenFehler: "تعذّر تحميل المبارزات.",
    duVorMin: "قبل {n} د",
    duVorStd: "قبل {n} س",
    duVorTag: "قبل {n} يوم",
    duJetzt: "الآن",
    duBereitTitel: "هل نبدأ؟",
    duBereitText: "8 أسئلة، لكل سؤال 20 ثانية كحد أقصى. الإجابة الصحيحة تمنح 100 نقطة، والسريعة حتى 50 نقطة إضافية. لا يمكنك إعادة الجولة أو إيقافها: من يتوقف يحصل على 0 نقطة. بعد الجولة ترى الإجابات الصحيحة.",
    duLos: "ابدأ",
    duZurueck: "رجوع",
    duFrage: "السؤال {n} من {m}",
    duZeichenAlt: "لافتة مرورية",
    duAuswerten: "جارٍ التقييم …",
    duErgebnis: "نتيجتك",
    duRichtigVon: "{n} من {m} صحيحة",
    duWartet: "نتيجتك جاهزة. عندما يلعب خصمك سترى في «مبارزاتك» من فاز.",
    duGegnerPunkte: "{name}: {n} نقطة",
    duAuswertung: "المراجعة",
    duRichtigLabel: "صحيح",
    duFalschLabel: "خطأ",
    duKeineAntwort: "لا إجابة (انتهى الوقت)",
    duDeineAntwort: "إجابتك",
    duRichtigeAntwort: "الإجابة الصحيحة",
    duNichtGespeichert: "تعذّر حفظ نتيجتك. حاول مرة أخرى.",
    duNichtGespeichertEndgueltig: "لم تُحتسب نتيجتك. انتهت الجولة أو لم تتطابق البيانات.",
    duNochmalSenden: "أرسل مرة أخرى",
    duSchonGespielt: "لقد لعبت هذه الجولة بالفعل. سترى النتيجة في «مبارزاتك».",
    duFehlerVergeben: "قبل شخص آخر هذه المبارزة بالفعل.",
    duFehlerVerfallen: "هذه المبارزة لم تعد موجودة أو انتهت صلاحيتها.",
    duFehlerRate: "طلبات كثيرة. انتظر قليلاً وحاول مرة أخرى.",
    duFehlerAllgemein: "لم ينجح الأمر. حاول لاحقاً.",
    duZurUebersicht: "إلى النظرة العامة"
  },
  es: {
    duName: "Duelo con un compañero",
    duKurz: "Responde 8 preguntas de tráfico y mídete con un compañero. No tenéis que jugar a la vez.",
    duIntro: "Tú y un compañero recibís las mismas 8 preguntas. Gana quien tenga más puntos. Acertar rápido da más puntos. No tenéis que estar conectados a la vez.",
    duBilanz: "Tu balance",
    duSiege: "Victorias",
    duUnentschieden: "Empates",
    duNiederlagen: "Derrotas",
    duBilanzFrist: "Se cuentan los duelos de los últimos 90 días.",
    duNeu: "Empezar un duelo nuevo",
    duNeuHinweis: "Juegas tú primero. Después tu duelo espera a un compañero.",
    duLimit: "Ya tienes {n} duelos en curso. Termínalos primero.",
    duLimitKurz: "Ya tienes demasiados duelos en curso. Termínalos primero.",
    duAusgeblendet: "Estás oculto en el ranking. Nadie vería tu reto. Pero puedes aceptar retos abiertos.",
    duMeine: "Tus duelos",
    duMeineLeer: "Todavía no hay duelos jugados.",
    duOffene: "Retos abiertos",
    duOffeneLeer: "Ahora mismo nadie espera un rival. Empieza un duelo y un compañero lo verá aquí.",
    duVerfall: "Los duelos sin resultado caducan a los 7 días. Si aceptas un duelo, tienes que empezarlo en 24 horas; si no, vuelve a esperar a otro compañero.",
    duWeiterspielen: "Seguir jugando",
    duWeiterText: "Tu ronda sigue abierta. Recibes las mismas 8 preguntas otra vez. El tiempo desde tu primer inicio sigue corriendo; tienes 10 minutos en total como máximo.",
    duAnnehmen: "Aceptar",
    duJetztSpielen: "Jugar ahora",
    duStDran: "Te toca",
    duStLaeuft: "Ronda empezada pero no terminada",
    duStWartetGegner: "Espera a un compañero",
    duStGegnerSpielt: "Tu rival todavía no ha jugado",
    duPunkteIch: "Tu resultado: {n} puntos",
    duSieg: "Ganado",
    duNiederlage: "Perdido",
    duSiegGross: "¡Victoria!",
    duNiederlageGross: "Derrota",
    duUnentschiedenGross: "Empate",
    duMitschueler: "Compañero",
    duDeinDuell: "Tu duelo",
    duGegen: "contra {name}",
    duPunkteZeile: "{a} : {b} puntos",
    duAktualisieren: "Actualizar",
    duVorschau: "Los duelos necesitan tu cuenta. En la vista previa no puedes jugarlos.",
    duLadenFehler: "No se pudieron cargar los duelos.",
    duVorMin: "hace {n} min",
    duVorStd: "hace {n} h",
    duVorTag: "hace {n} días",
    duJetzt: "ahora mismo",
    duBereitTitel: "¿Empezamos?",
    duBereitText: "8 preguntas, como máximo 20 segundos cada una. Acertar da 100 puntos y responder rápido hasta 50 puntos extra. No puedes repetir ni interrumpir la ronda: quien la deja recibe 0 puntos. Después de la ronda ves las respuestas correctas.",
    duLos: "Vamos",
    duZurueck: "Atrás",
    duFrage: "Pregunta {n} de {m}",
    duZeichenAlt: "Señal de tráfico",
    duAuswerten: "Evaluando …",
    duErgebnis: "Tu resultado",
    duRichtigVon: "{n} de {m} correctas",
    duWartet: "Tu resultado ya está. En cuanto tu rival haya jugado, verás en «Tus duelos» quién ha ganado.",
    duGegnerPunkte: "{name}: {n} puntos",
    duAuswertung: "Repaso",
    duRichtigLabel: "Correcta",
    duFalschLabel: "Incorrecta",
    duKeineAntwort: "Sin respuesta (se acabó el tiempo)",
    duDeineAntwort: "Tu respuesta",
    duRichtigeAntwort: "Respuesta correcta",
    duNichtGespeichert: "No se pudo guardar tu resultado. Inténtalo otra vez.",
    duNichtGespeichertEndgueltig: "Tu resultado no se ha contado. La ronda caducó o los datos no coincidían.",
    duNochmalSenden: "Enviar otra vez",
    duSchonGespielt: "Ya has jugado esta ronda. Verás el resultado en «Tus duelos».",
    duFehlerVergeben: "Alguien ya ha aceptado este duelo.",
    duFehlerVerfallen: "Este duelo ya no existe o ha caducado.",
    duFehlerRate: "Demasiadas solicitudes. Espera un momento e inténtalo otra vez.",
    duFehlerAllgemein: "No ha funcionado. Inténtalo más tarde.",
    duZurUebersicht: "A la vista general"
  },
  ru: {
    duName: "Дуэль с одноклассником",
    duKurz: "Ответь на 8 вопросов о дорожном движении и сравни результат с одноклассником. Играть одновременно не нужно.",
    duIntro: "Ты и одноклассник получаете одни и те же 8 вопросов. Побеждает тот, у кого больше очков. Правильно и быстро — больше всего очков. Быть онлайн одновременно не нужно.",
    duBilanz: "Твой счёт",
    duSiege: "Победы",
    duUnentschieden: "Ничьи",
    duNiederlagen: "Поражения",
    duBilanzFrist: "Учитываются дуэли за последние 90 дней.",
    duNeu: "Начать новую дуэль",
    duNeuHinweis: "Ты играешь первым. Потом дуэль ждёт одноклассника.",
    duLimit: "Незавершённых дуэлей уже: {n}. Сначала закончи их.",
    duLimitKurz: "У тебя слишком много незавершённых дуэлей. Сначала закончи их.",
    duAusgeblendet: "Ты скрыт в рейтинге. Твой вызов никто не увидит. Но ты можешь принимать открытые вызовы.",
    duMeine: "Твои дуэли",
    duMeineLeer: "Сыгранных дуэлей пока нет.",
    duOffene: "Открытые вызовы",
    duOffeneLeer: "Сейчас никто не ждёт соперника. Начни дуэль — одноклассник увидит её здесь.",
    duVerfall: "Дуэли без результата истекают через 7 дней. Принятую дуэль нужно начать в течение 24 часов, иначе она снова будет ждать другого одноклассника.",
    duWeiterspielen: "Продолжить",
    duWeiterText: "Твой раунд ещё открыт. Ты получишь те же 8 вопросов ещё раз. Время с первого старта продолжает идти; всего у тебя не более 10 минут.",
    duAnnehmen: "Принять",
    duJetztSpielen: "Играть сейчас",
    duStDran: "Твой ход",
    duStLaeuft: "Раунд начат, но не завершён",
    duStWartetGegner: "Ждёт одноклассника",
    duStGegnerSpielt: "Соперник ещё не сыграл",
    duPunkteIch: "Твой результат: {n} очков",
    duSieg: "Победа",
    duNiederlage: "Поражение",
    duSiegGross: "Победа!",
    duNiederlageGross: "Поражение",
    duUnentschiedenGross: "Ничья",
    duMitschueler: "Одноклассник",
    duDeinDuell: "Твоя дуэль",
    duGegen: "против {name}",
    duPunkteZeile: "{a} : {b} очков",
    duAktualisieren: "Обновить",
    duVorschau: "Для дуэлей нужна твоя учётная запись. В режиме просмотра играть нельзя.",
    duLadenFehler: "Не удалось загрузить дуэли.",
    duVorMin: "{n} мин. назад",
    duVorStd: "{n} ч. назад",
    duVorTag: "{n} дн. назад",
    duJetzt: "только что",
    duBereitTitel: "Начинаем?",
    duBereitText: "8 вопросов, на каждый не больше 20 секунд. Правильный ответ даёт 100 очков, быстрый — до 50 бонусных. Раунд нельзя повторить или прервать: кто бросает, получает 0 очков. После раунда ты увидишь правильные ответы.",
    duLos: "Начать",
    duZurueck: "Назад",
    duFrage: "Вопрос {n} из {m}",
    duZeichenAlt: "Дорожный знак",
    duAuswerten: "Подсчёт …",
    duErgebnis: "Твой результат",
    duRichtigVon: "{n} из {m} верно",
    duWartet: "Твой результат готов. Когда соперник сыграет, ты увидишь в «Твои дуэли», кто победил.",
    duGegnerPunkte: "{name}: {n} очков",
    duAuswertung: "Разбор",
    duRichtigLabel: "Верно",
    duFalschLabel: "Неверно",
    duKeineAntwort: "Нет ответа (время вышло)",
    duDeineAntwort: "Твой ответ",
    duRichtigeAntwort: "Правильный ответ",
    duNichtGespeichert: "Не удалось сохранить твой результат. Попробуй ещё раз.",
    duNichtGespeichertEndgueltig: "Твой результат не засчитан. Раунд истёк или данные не совпали.",
    duNochmalSenden: "Отправить ещё раз",
    duSchonGespielt: "Этот раунд уже сыгран. Результат увидишь в «Твои дуэли».",
    duFehlerVergeben: "Эту дуэль уже кто-то принял.",
    duFehlerVerfallen: "Этой дуэли больше нет, или она истекла.",
    duFehlerRate: "Слишком много запросов. Подожди немного и попробуй ещё раз.",
    duFehlerAllgemein: "Не получилось. Попробуй позже.",
    duZurUebersicht: "К обзору"
  },
  sr: {
    duName: "Duel sa drugarom iz razreda",
    duKurz: "Odgovori na 8 saobraćajnih pitanja i odmeri se sa drugom iz razreda. Ne morate da igrate u isto vreme.",
    duIntro: "Ti i drug iz razreda dobijate ista 8 pitanja. Pobeđuje ko ima više poena. Tačno i brzo donosi najviše poena. Ne morate da budete na mreži u isto vreme.",
    duBilanz: "Tvoj bilans",
    duSiege: "Pobede",
    duUnentschieden: "Nerešeno",
    duNiederlagen: "Porazi",
    duBilanzFrist: "Računaju se duelji iz poslednjih 90 dana.",
    duNeu: "Započni novi duel",
    duNeuHinweis: "Ti igraš prvi. Zatim tvoj duel čeka druga iz razreda.",
    duLimit: "Već imaš {n} duela u toku. Prvo ih završi.",
    duLimitKurz: "Već imaš previše duela u toku. Prvo ih završi.",
    duAusgeblendet: "Sakriven si na rang listi. Tvoj izazov niko ne bi video. Ali možeš da prihvatiš otvorene izazove.",
    duMeine: "Tvoji duelji",
    duMeineLeer: "Još nema odigranih duela.",
    duOffene: "Otvoreni izazovi",
    duOffeneLeer: "Trenutno niko ne čeka protivnika. Započni duel, pa će ga ovde videti neko iz razreda.",
    duVerfall: "Duelji bez rezultata ističu posle 7 dana. Prihvaćeni duel moraš da započneš u roku od 24 sata, inače ponovo čeka drugog druga iz razreda.",
    duWeiterspielen: "Nastavi",
    duWeiterText: "Tvoja runda je još otvorena. Dobijaš ista 8 pitanja još jednom. Vreme od prvog početka i dalje teče; ukupno imaš najviše 10 minuta.",
    duAnnehmen: "Prihvati",
    duJetztSpielen: "Igraj sada",
    duStDran: "Ti si na redu",
    duStLaeuft: "Runda je počela, ali nije završena",
    duStWartetGegner: "Čeka druga iz razreda",
    duStGegnerSpielt: "Tvoj protivnik još nije igrao",
    duPunkteIch: "Tvoj rezultat: {n} poena",
    duSieg: "Pobeda",
    duNiederlage: "Poraz",
    duSiegGross: "Pobeda!",
    duNiederlageGross: "Poraz",
    duUnentschiedenGross: "Nerešeno",
    duMitschueler: "Drug iz razreda",
    duDeinDuell: "Tvoj duel",
    duGegen: "protiv: {name}",
    duPunkteZeile: "{a} : {b} poena",
    duAktualisieren: "Osveži",
    duVorschau: "Duelima je potreban tvoj nalog. U pregledu ih ne možeš igrati.",
    duLadenFehler: "Duelji nisu mogli da se učitaju.",
    duVorMin: "pre {n} min.",
    duVorStd: "pre {n} č.",
    duVorTag: "pre {n} d.",
    duJetzt: "upravo sada",
    duBereitTitel: "Počinjemo?",
    duBereitText: "8 pitanja, najviše 20 sekundi za svako. Tačan odgovor donosi 100 poena, brz do 50 bonus poena. Rundu ne možeš da ponoviš niti da prekineš: ko odustane, dobija 0 poena. Posle runde vidiš tačne odgovore.",
    duLos: "Kreni",
    duZurueck: "Nazad",
    duFrage: "Pitanje {n} od {m}",
    duZeichenAlt: "Saobraćajni znak",
    duAuswerten: "Ocenjuje se …",
    duErgebnis: "Tvoj rezultat",
    duRichtigVon: "{n} od {m} tačno",
    duWartet: "Tvoj rezultat je tu. Čim protivnik odigra, videćeš u „Tvoji duelji“ ko je pobedio.",
    duGegnerPunkte: "{name}: {n} poena",
    duAuswertung: "Pregled",
    duRichtigLabel: "Tačno",
    duFalschLabel: "Netačno",
    duKeineAntwort: "Bez odgovora (vreme je isteklo)",
    duDeineAntwort: "Tvoj odgovor",
    duRichtigeAntwort: "Tačan odgovor",
    duNichtGespeichert: "Tvoj rezultat nije mogao da se sačuva. Pokušaj ponovo.",
    duNichtGespeichertEndgueltig: "Tvoj rezultat nije uračunat. Runda je istekla ili se podaci nisu poklapali.",
    duNochmalSenden: "Pošalji ponovo",
    duSchonGespielt: "Ova runda je već odigrana. Rezultat vidiš u „Tvoji duelji“.",
    duFehlerVergeben: "Ovaj duel je već neko prihvatio.",
    duFehlerVerfallen: "Ovog duela više nema ili je istekao.",
    duFehlerRate: "Previše zahteva. Sačekaj malo i pokušaj ponovo.",
    duFehlerAllgemein: "Nije uspelo. Pokušaj kasnije.",
    duZurUebersicht: "Na pregled"
  },
  ckb: {
    duName: "دووێل لەگەڵ هاوپۆلێک",
    duKurz: "وەڵامی 8 پرسیاری هاتوچۆ بدەوە و خۆت لەگەڵ هاوپۆلێک بپێوە. پێویست ناکات لە یەک کاتدا یاری بکەن.",
    duIntro: "تۆ و هاوپۆلێکت هەمان 8 پرسیار وەردەگرن. ئەوەی خاڵی زیاتری هەبێت دەبات. وەڵامی ڕاست و خێرا زۆرترین خاڵ دەهێنێت. پێویست ناکات لە یەک کاتدا ئۆنلاین بن.",
    duBilanz: "ئەنجامی تۆ",
    duSiege: "بردنەوە",
    duUnentschieden: "یەکسان",
    duNiederlagen: "دۆڕان",
    duBilanzFrist: "دووێلەکانی 90 ڕۆژی ڕابردوو دەژمێردرێن.",
    duNeu: "دووێلێکی نوێ دەستپێبکە",
    duNeuHinweis: "تۆ یەکەم جار یاری دەکەیت. پاشان دووێلەکەت چاوەڕێی هاوپۆلێک دەکات.",
    duLimit: "پێشتر {n} دووێلی بەردەوامت هەیە. سەرەتا تەواویان بکە.",
    duLimitKurz: "زۆر دووێلی بەردەوامت هەیە. سەرەتا تەواویان بکە.",
    duAusgeblendet: "تۆ لە ڕیزبەندیدا شاراویتەوە. کەس تەحەدداکەت نابینێت. بەڵام دەتوانیت تەحەدداکانی کراوە قبوڵ بکەیت.",
    duMeine: "دووێلەکانت",
    duMeineLeer: "هێشتا هیچ دووێلێکت یاری نەکردووە.",
    duOffene: "تەحەدداکانی کراوە",
    duOffeneLeer: "ئێستا کەس چاوەڕێی ڕکابەرێک نییە. دووێلێک دەستپێبکە، ئینجا هاوپۆلێک لێرە دەیبینێت.",
    duVerfall: "دووێلەکانی بێ ئەنجام دوای 7 ڕۆژ بەسەردەچن. دووێلێکی قبوڵکراو دەبێت لە ماوەی 24 کاتژمێردا دەستپێبکەیت، ئەگینا دووبارە چاوەڕێی هاوپۆلێکی تر دەبێت.",
    duWeiterspielen: "بەردەوام بە",
    duWeiterText: "خولەکەت هێشتا کراوەیە. هەمان 8 پرسیار دووبارە وەردەگریت. ئەو کاتەی لە یەکەم دەستپێکەوە ڕۆیشتووە بەردەوام دەبێت؛ بە گشتی زۆرترین 10 خولەکت هەیە.",
    duAnnehmen: "قبوڵ بکە",
    duJetztSpielen: "ئێستا یاری بکە",
    duStDran: "نۆرەی تۆیە",
    duStLaeuft: "خولەکە دەستی پێکرد بەڵام تەواو نەبوو",
    duStWartetGegner: "چاوەڕێی هاوپۆلێکە",
    duStGegnerSpielt: "ڕکابەرەکەت هێشتا یاری نەکردووە",
    duPunkteIch: "ئەنجامی تۆ: {n} خاڵ",
    duSieg: "بردتەوە",
    duNiederlage: "دۆڕایت",
    duSiegGross: "بردتەوە!",
    duNiederlageGross: "دۆڕایت",
    duUnentschiedenGross: "یەکسان",
    duMitschueler: "هاوپۆل",
    duDeinDuell: "دووێلەکەت",
    duGegen: "دژی {name}",
    duPunkteZeile: "{a} : {b} خاڵ",
    duAktualisieren: "نوێکردنەوە",
    duVorschau: "دووێل پێویستی بە هەژمارەکەتە. لە پێشبینیندا ناتوانیت یاری بکەیت.",
    duLadenFehler: "دووێلەکان بار نەکران.",
    duVorMin: "پێش {n} خولەک",
    duVorStd: "پێش {n} کاتژمێر",
    duVorTag: "پێش {n} ڕۆژ",
    duJetzt: "ئێستا",
    duBereitTitel: "ئامادەیت؟",
    duBereitText: "8 پرسیار، هەریەکەیان زۆرترین 20 چرکە. وەڵامی ڕاست 100 خاڵ دەهێنێت، خێراش تا 50 خاڵی بۆنەس. ناتوانیت خولەکە دووبارە بکەیتەوە یان ڕایبگریت: ئەوەی بوەستێت 0 خاڵ وەردەگرێت. دوای خولەکە وەڵامە ڕاستەکان دەبینیت.",
    duLos: "دەستپێبکە",
    duZurueck: "گەڕانەوە",
    duFrage: "پرسیاری {n} لە {m}",
    duZeichenAlt: "نیشانەی هاتوچۆ",
    duAuswerten: "هەڵدەسەنگێنرێت …",
    duErgebnis: "ئەنجامی تۆ",
    duRichtigVon: "{n} لە {m} ڕاست",
    duWartet: "ئەنجامەکەت ئامادەیە. کاتێک ڕکابەرەکەت یاری بکات، لە «دووێلەکانت» دەبینیت کێ بردوویەتەوە.",
    duGegnerPunkte: "{name}: {n} خاڵ",
    duAuswertung: "پێداچوونەوە",
    duRichtigLabel: "ڕاست",
    duFalschLabel: "هەڵە",
    duKeineAntwort: "بێ وەڵام (کات تەواو بوو)",
    duDeineAntwort: "وەڵامی تۆ",
    duRichtigeAntwort: "وەڵامی ڕاست",
    duNichtGespeichert: "ئەنجامەکەت پاشەکەوت نەکرا. تکایە دووبارە هەوڵ بدەوە.",
    duNichtGespeichertEndgueltig: "ئەنجامەکەت نەژمێردرا. خولەکە بەسەرچوو یان زانیارییەکان نەگونجان.",
    duNochmalSenden: "دووبارە بنێرە",
    duSchonGespielt: "ئەم خولەت پێشتر یاری کردووە. ئەنجامەکە لە «دووێلەکانت» دەبینیت.",
    duFehlerVergeben: "ئەم دووێلە پێشتر کەسێک قبوڵی کردووە.",
    duFehlerVerfallen: "ئەم دووێلە ئیتر نەماوە یان بەسەرچووە.",
    duFehlerRate: "داواکاری زۆرە. کەمێک چاوەڕێ بکە و دووبارە هەوڵ بدەوە.",
    duFehlerAllgemein: "نەبوو. تکایە دواتر دووبارە هەوڵ بدەوە.",
    duZurUebersicht: "بۆ ڕوانگەی گشتی"
  },
  kmr: {
    duName: "Dûel bi hevalekî polê re",
    duKurz: "Bersiva 8 pirsên trafîkê bide û xwe bi hevalekî polê re bipîve. Pêwîst nake hûn di heman demê de bilîzin.",
    duIntro: "Tu û hevalekî polê heman 8 pirsan distînin. Yê ku bêtir xal bi dest bixe diqezenc dike. Bersiva rast û zû herî zêde xalan dide. Pêwîst nake hûn di heman demê de serhêl bin.",
    duBilanz: "Hesaba te",
    duSiege: "Serketin",
    duUnentschieden: "Wekhevî",
    duNiederlagen: "Windakirin",
    duBilanzFrist: "Dûelên 90 rojên dawî tên jimartin.",
    duNeu: "Dûeleke nû dest pê bike",
    duNeuHinweis: "Tu pêşî dilîzî. Paşê dûela te li benda hevalekî polê dimîne.",
    duLimit: "Jixwe {n} dûelên te yên domdar hene. Pêşî wan biqedîne.",
    duLimitKurz: "Jixwe gelek dûelên te yên domdar hene. Pêşî wan biqedîne.",
    duAusgeblendet: "Tu di rêzbendiyê de veşartî yî. Kes dijberiya te nabîne. Lê tu dikarî dijberiyên vekirî qebûl bikî.",
    duMeine: "Dûelên te",
    duMeineLeer: "Hê dûelek nehatiye lîstin.",
    duOffene: "Dijberiyên vekirî",
    duOffeneLeer: "Niha kes li benda dijberekî nîne. Dûeleke dest pê bike, hingê hevalekî polê wê li vir bibîne.",
    duVerfall: "Dûelên bê encam piştî 7 rojan diqedin. Dûeleke qebûlkirî divê di nav 24 saetan de dest pê bikî, wekî din dîsa li benda hevalekî din ê polê dimîne.",
    duWeiterspielen: "Berdewam bike",
    duWeiterText: "Gera te hê vekirî ye. Tu heman 8 pirsan carekê din distînî. Dema ji destpêka te ya yekem ve berdewam dibe; tevahî herî zêde 10 deqeyên te hene.",
    duAnnehmen: "Qebûl bike",
    duJetztSpielen: "Niha bilîze",
    duStDran: "Rêza te ye",
    duStLaeuft: "Gera dest pê kir lê neqediya",
    duStWartetGegner: "Li benda hevalekî polê ye",
    duStGegnerSpielt: "Dijberê te hê nelîstiye",
    duPunkteIch: "Encama te: {n} xal",
    duSieg: "Serketin",
    duNiederlage: "Windakirin",
    duSiegGross: "Serketin!",
    duNiederlageGross: "Windakirin",
    duUnentschiedenGross: "Wekhevî",
    duMitschueler: "Hevalê polê",
    duDeinDuell: "Dûela te",
    duGegen: "li dijî {name}",
    duPunkteZeile: "{a} : {b} xal",
    duAktualisieren: "Nû bike",
    duVorschau: "Dûel hesabê te hewce dikin. Di pêşdîtinê de tu nikarî wan bilîzî.",
    duLadenFehler: "Dûel nehatin barkirin.",
    duVorMin: "{n} xul. berê",
    duVorStd: "{n} saet berê",
    duVorTag: "{n} roj berê",
    duJetzt: "hema niha",
    duBereitTitel: "Em dest pê bikin?",
    duBereitText: "8 pirs, her yek herî zêde 20 çirkeyan. Bersiva rast 100 xalan dide, ya bilez heta 50 xalên bonûsê. Tu nikarî gerê dubare bikî an rawestînî: yê ku bisekine 0 xal distîne. Piştî gerê tu bersivên rast dibînî.",
    duLos: "Dest pê bike",
    duZurueck: "Vegere",
    duFrage: "Pirs {n} ji {m}",
    duZeichenAlt: "Nîşana trafîkê",
    duAuswerten: "Tê nirxandin …",
    duErgebnis: "Encama te",
    duRichtigVon: "{n} ji {m} rast",
    duWartet: "Encama te amade ye. Gava dijberê te bilîze, tu di «Dûelên te» de dibînî kê qezenc kir.",
    duGegnerPunkte: "{name}: {n} xal",
    duAuswertung: "Nirxandin",
    duRichtigLabel: "Rast",
    duFalschLabel: "Şaş",
    duKeineAntwort: "Bê bersiv (dem qediya)",
    duDeineAntwort: "Bersiva te",
    duRichtigeAntwort: "Bersiva rast",
    duNichtGespeichert: "Encama te nehat tomarkirin. Ji kerema xwe dîsa biceribîne.",
    duNichtGespeichertEndgueltig: "Encama te nehat hesibandin. Ger qediya an agahî li hev nehatin.",
    duNochmalSenden: "Dîsa bişîne",
    duSchonGespielt: "Ev ger jixwe hatiye lîstin. Tu encamê di «Dûelên te» de dibînî.",
    duFehlerVergeben: "Kesekî jixwe ev dûel qebûl kiriye.",
    duFehlerVerfallen: "Ev dûel êdî tune ye an dema wê qediyaye.",
    duFehlerRate: "Gelek daxwaz. Hinekî li bendê bimîne û dîsa biceribîne.",
    duFehlerAllgemein: "Nebû. Ji kerema xwe paşê dîsa biceribîne.",
    duZurUebersicht: "Biçe nêrîna giştî"
  },
  hi: {
    duName: "सहपाठी के साथ द्वंद्व",
    duKurz: "यातायात के 8 सवालों के जवाब दें और एक सहपाठी से मुकाबला करें। दोनों का एक ही समय पर खेलना ज़रूरी नहीं।",
    duIntro: "आपको और एक सहपाठी को वही 8 सवाल मिलते हैं। जिसके ज़्यादा अंक हों वह जीतता है। सही और तेज़ जवाब से सबसे ज़्यादा अंक मिलते हैं। दोनों का एक ही समय ऑनलाइन होना ज़रूरी नहीं।",
    duBilanz: "आपका रिकॉर्ड",
    duSiege: "जीत",
    duUnentschieden: "बराबरी",
    duNiederlagen: "हार",
    duBilanzFrist: "पिछले 90 दिनों के द्वंद्व गिने जाते हैं।",
    duNeu: "नया द्वंद्व शुरू करें",
    duNeuHinweis: "पहले आप खेलते हैं। फिर आपका द्वंद्व किसी सहपाठी का इंतज़ार करता है।",
    duLimit: "आपके पास पहले से {n} चालू द्वंद्व हैं। पहले उन्हें पूरा करें।",
    duLimitKurz: "आपके पास बहुत ज़्यादा चालू द्वंद्व हैं। पहले उन्हें पूरा करें।",
    duAusgeblendet: "आप रैंकिंग में छिपे हुए हैं। आपकी चुनौती कोई नहीं देखेगा। लेकिन आप खुली चुनौतियाँ स्वीकार कर सकते हैं।",
    duMeine: "आपके द्वंद्व",
    duMeineLeer: "अभी तक कोई द्वंद्व नहीं खेला गया।",
    duOffene: "खुली चुनौतियाँ",
    duOffeneLeer: "अभी कोई प्रतिद्वंद्वी का इंतज़ार नहीं कर रहा। एक द्वंद्व शुरू करें, फिर कोई सहपाठी उसे यहाँ देखेगा।",
    duVerfall: "बिना नतीजे वाले द्वंद्व 7 दिन बाद खत्म हो जाते हैं। स्वीकार किए गए द्वंद्व को आपको 24 घंटे के अंदर शुरू करना होगा, वरना वह फिर किसी दूसरे सहपाठी का इंतज़ार करेगा।",
    duWeiterspielen: "खेलना जारी रखें",
    duWeiterText: "आपका राउंड अभी खुला है। आपको वही 8 सवाल फिर मिलेंगे। पहली शुरुआत से समय चलता रहता है; कुल मिलाकर आपके पास ज़्यादा से ज़्यादा 10 मिनट हैं।",
    duAnnehmen: "स्वीकार करें",
    duJetztSpielen: "अभी खेलें",
    duStDran: "आपकी बारी है",
    duStLaeuft: "राउंड शुरू हुआ पर पूरा नहीं हुआ",
    duStWartetGegner: "किसी सहपाठी का इंतज़ार है",
    duStGegnerSpielt: "प्रतिद्वंद्वी ने अभी नहीं खेला",
    duPunkteIch: "आपका नतीजा: {n} अंक",
    duSieg: "जीत",
    duNiederlage: "हार",
    duSiegGross: "जीत!",
    duNiederlageGross: "हार",
    duUnentschiedenGross: "बराबरी",
    duMitschueler: "सहपाठी",
    duDeinDuell: "आपका द्वंद्व",
    duGegen: "{name} के खिलाफ",
    duPunkteZeile: "{a} : {b} अंक",
    duAktualisieren: "ताज़ा करें",
    duVorschau: "द्वंद्व के लिए आपका खाता चाहिए। प्रीव्यू में आप इन्हें नहीं खेल सकते।",
    duLadenFehler: "द्वंद्व लोड नहीं हो सके।",
    duVorMin: "{n} मिनट पहले",
    duVorStd: "{n} घंटे पहले",
    duVorTag: "{n} दिन पहले",
    duJetzt: "अभी-अभी",
    duBereitTitel: "शुरू करें?",
    duBereitText: "8 सवाल, हर एक के लिए ज़्यादा से ज़्यादा 20 सेकंड। सही जवाब से 100 अंक, तेज़ जवाब से 50 तक बोनस अंक मिलते हैं। राउंड को दोहराया या बीच में रोका नहीं जा सकता: जो छोड़ देता है उसे 0 अंक मिलते हैं। राउंड के बाद आप सही जवाब देखते हैं।",
    duLos: "शुरू",
    duZurueck: "वापस",
    duFrage: "सवाल {n} / {m}",
    duZeichenAlt: "यातायात संकेत",
    duAuswerten: "जाँच हो रही है …",
    duErgebnis: "आपका नतीजा",
    duRichtigVon: "{m} में से {n} सही",
    duWartet: "आपका नतीजा तैयार है। प्रतिद्वंद्वी के खेलते ही आप «आपके द्वंद्व» में देखेंगे कि कौन जीता।",
    duGegnerPunkte: "{name}: {n} अंक",
    duAuswertung: "समीक्षा",
    duRichtigLabel: "सही",
    duFalschLabel: "गलत",
    duKeineAntwort: "कोई जवाब नहीं (समय खत्म)",
    duDeineAntwort: "आपका जवाब",
    duRichtigeAntwort: "सही जवाब",
    duNichtGespeichert: "आपका नतीजा सेव नहीं हो सका। कृपया फिर कोशिश करें।",
    duNichtGespeichertEndgueltig: "आपका नतीजा गिना नहीं गया। राउंड का समय खत्म हो गया या जानकारी मेल नहीं खाई।",
    duNochmalSenden: "फिर भेजें",
    duSchonGespielt: "यह राउंड पहले ही खेला जा चुका है। नतीजा «आपके द्वंद्व» में दिखेगा।",
    duFehlerVergeben: "इस द्वंद्व को किसी ने पहले ही स्वीकार कर लिया है।",
    duFehlerVerfallen: "यह द्वंद्व अब मौजूद नहीं है या खत्म हो गया है।",
    duFehlerRate: "बहुत ज़्यादा अनुरोध। थोड़ा रुकें और फिर कोशिश करें।",
    duFehlerAllgemein: "नहीं हो पाया। कृपया बाद में फिर कोशिश करें।",
    duZurUebersicht: "सारांश पर"
  },
  ur: {
    duName: "ہم جماعت کے ساتھ مقابلہ",
    duKurz: "ٹریفک کے 8 سوالوں کے جواب دیں اور ایک ہم جماعت سے مقابلہ کریں۔ دونوں کا ایک ہی وقت میں کھیلنا ضروری نہیں۔",
    duIntro: "آپ اور ایک ہم جماعت کو وہی 8 سوال ملتے ہیں۔ جس کے زیادہ پوائنٹس ہوں وہ جیتتا ہے۔ درست اور تیز جواب سے سب سے زیادہ پوائنٹس ملتے ہیں۔ دونوں کا ایک ہی وقت آن لائن ہونا ضروری نہیں۔",
    duBilanz: "آپ کا ریکارڈ",
    duSiege: "جیت",
    duUnentschieden: "برابری",
    duNiederlagen: "ہار",
    duBilanzFrist: "پچھلے 90 دنوں کے مقابلے گنے جاتے ہیں۔",
    duNeu: "نیا مقابلہ شروع کریں",
    duNeuHinweis: "پہلے آپ کھیلتے ہیں۔ پھر آپ کا مقابلہ کسی ہم جماعت کا انتظار کرتا ہے۔",
    duLimit: "آپ کے پاس پہلے سے {n} جاری مقابلے ہیں۔ پہلے انہیں مکمل کریں۔",
    duLimitKurz: "آپ کے پاس بہت زیادہ جاری مقابلے ہیں۔ پہلے انہیں مکمل کریں۔",
    duAusgeblendet: "آپ رینکنگ میں چھپے ہوئے ہیں۔ آپ کا چیلنج کوئی نہیں دیکھے گا۔ لیکن آپ کھلے چیلنج قبول کر سکتے ہیں۔",
    duMeine: "آپ کے مقابلے",
    duMeineLeer: "ابھی تک کوئی مقابلہ نہیں کھیلا گیا۔",
    duOffene: "کھلے چیلنج",
    duOffeneLeer: "ابھی کوئی حریف کا انتظار نہیں کر رہا۔ ایک مقابلہ شروع کریں، پھر کوئی ہم جماعت اسے یہاں دیکھے گا۔",
    duVerfall: "بغیر نتیجے والے مقابلے 7 دن بعد ختم ہو جاتے ہیں۔ قبول کیے گئے مقابلے کو آپ کو 24 گھنٹوں کے اندر شروع کرنا ہوگا، ورنہ وہ دوبارہ کسی دوسرے ہم جماعت کا انتظار کرے گا۔",
    duWeiterspielen: "کھیلنا جاری رکھیں",
    duWeiterText: "آپ کا راؤنڈ ابھی کھلا ہے۔ آپ کو وہی 8 سوال دوبارہ ملیں گے۔ پہلی شروعات سے وقت چلتا رہتا ہے؛ کل ملا کر آپ کے پاس زیادہ سے زیادہ 10 منٹ ہیں۔",
    duAnnehmen: "قبول کریں",
    duJetztSpielen: "ابھی کھیلیں",
    duStDran: "آپ کی باری ہے",
    duStLaeuft: "راؤنڈ شروع ہوا مگر مکمل نہیں ہوا",
    duStWartetGegner: "کسی ہم جماعت کا انتظار ہے",
    duStGegnerSpielt: "حریف نے ابھی نہیں کھیلا",
    duPunkteIch: "آپ کا نتیجہ: {n} پوائنٹس",
    duSieg: "جیت",
    duNiederlage: "ہار",
    duSiegGross: "جیت!",
    duNiederlageGross: "ہار",
    duUnentschiedenGross: "برابری",
    duMitschueler: "ہم جماعت",
    duDeinDuell: "آپ کا مقابلہ",
    duGegen: "{name} کے خلاف",
    duPunkteZeile: "{a} : {b} پوائنٹس",
    duAktualisieren: "تازہ کریں",
    duVorschau: "مقابلوں کے لیے آپ کا اکاؤنٹ چاہیے۔ پیش منظر میں آپ انہیں نہیں کھیل سکتے۔",
    duLadenFehler: "مقابلے لوڈ نہیں ہو سکے۔",
    duVorMin: "{n} منٹ پہلے",
    duVorStd: "{n} گھنٹے پہلے",
    duVorTag: "{n} دن پہلے",
    duJetzt: "ابھی ابھی",
    duBereitTitel: "شروع کریں؟",
    duBereitText: "8 سوال، ہر ایک کے لیے زیادہ سے زیادہ 20 سیکنڈ۔ درست جواب سے 100 پوائنٹس، تیز جواب سے 50 تک بونس پوائنٹس ملتے ہیں۔ راؤنڈ کو دہرایا یا بیچ میں روکا نہیں جا سکتا: جو چھوڑ دے اسے 0 پوائنٹس ملتے ہیں۔ راؤنڈ کے بعد آپ درست جواب دیکھتے ہیں۔",
    duLos: "شروع",
    duZurueck: "واپس",
    duFrage: "سوال {n} / {m}",
    duZeichenAlt: "ٹریفک نشان",
    duAuswerten: "جانچ ہو رہی ہے …",
    duErgebnis: "آپ کا نتیجہ",
    duRichtigVon: "{m} میں سے {n} درست",
    duWartet: "آپ کا نتیجہ تیار ہے۔ حریف کے کھیلتے ہی آپ «آپ کے مقابلے» میں دیکھیں گے کہ کون جیتا۔",
    duGegnerPunkte: "{name}: {n} پوائنٹس",
    duAuswertung: "جائزہ",
    duRichtigLabel: "درست",
    duFalschLabel: "غلط",
    duKeineAntwort: "کوئی جواب نہیں (وقت ختم)",
    duDeineAntwort: "آپ کا جواب",
    duRichtigeAntwort: "درست جواب",
    duNichtGespeichert: "آپ کا نتیجہ محفوظ نہیں ہو سکا۔ براہ کرم دوبارہ کوشش کریں۔",
    duNichtGespeichertEndgueltig: "آپ کا نتیجہ شمار نہیں ہوا۔ راؤنڈ کا وقت ختم ہو گیا یا معلومات میل نہیں کھائیں۔",
    duNochmalSenden: "دوبارہ بھیجیں",
    duSchonGespielt: "یہ راؤنڈ پہلے ہی کھیلا جا چکا ہے۔ نتیجہ «آپ کے مقابلے» میں نظر آئے گا۔",
    duFehlerVergeben: "اس مقابلے کو کسی نے پہلے ہی قبول کر لیا ہے۔",
    duFehlerVerfallen: "یہ مقابلہ اب موجود نہیں یا ختم ہو چکا ہے۔",
    duFehlerRate: "بہت زیادہ درخواستیں۔ تھوڑا رکیں اور دوبارہ کوشش کریں۔",
    duFehlerAllgemein: "نہیں ہو سکا۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
    duZurUebersicht: "خلاصے پر"
  },
  vi: {
    duName: "Đối đầu với bạn cùng lớp",
    duKurz: "Trả lời 8 câu hỏi giao thông và so tài với một bạn cùng lớp. Hai bạn không cần chơi cùng lúc.",
    duIntro: "Bạn và một bạn cùng lớp nhận cùng 8 câu hỏi. Ai nhiều điểm hơn sẽ thắng. Đúng và nhanh được nhiều điểm nhất. Hai bạn không cần trực tuyến cùng lúc.",
    duBilanz: "Thành tích của bạn",
    duSiege: "Thắng",
    duUnentschieden: "Hòa",
    duNiederlagen: "Thua",
    duBilanzFrist: "Tính các trận trong 90 ngày gần nhất.",
    duNeu: "Bắt đầu trận mới",
    duNeuHinweis: "Bạn chơi trước. Sau đó trận của bạn chờ một bạn cùng lớp.",
    duLimit: "Bạn đã có {n} trận đang diễn ra. Hãy chơi xong chúng trước.",
    duLimitKurz: "Bạn có quá nhiều trận đang diễn ra. Hãy chơi xong chúng trước.",
    duAusgeblendet: "Bạn đang bị ẩn khỏi bảng xếp hạng. Không ai thấy lời thách đấu của bạn. Nhưng bạn có thể nhận các lời thách đấu đang mở.",
    duMeine: "Các trận của bạn",
    duMeineLeer: "Bạn chưa chơi trận nào.",
    duOffene: "Lời thách đấu đang mở",
    duOffeneLeer: "Hiện không ai đang chờ đối thủ. Hãy bắt đầu một trận, rồi một bạn cùng lớp sẽ thấy nó ở đây.",
    duVerfall: "Trận chưa có kết quả hết hạn sau 7 ngày. Trận đã nhận bạn phải bắt đầu trong vòng 24 giờ, nếu không nó lại chờ một bạn cùng lớp khác.",
    duWeiterspielen: "Chơi tiếp",
    duWeiterText: "Lượt của bạn vẫn còn mở. Bạn nhận lại đúng 8 câu hỏi đó. Thời gian tính từ lần bắt đầu đầu tiên vẫn chạy; tổng cộng bạn có tối đa 10 phút.",
    duAnnehmen: "Nhận",
    duJetztSpielen: "Chơi ngay",
    duStDran: "Đến lượt bạn",
    duStLaeuft: "Lượt đã bắt đầu nhưng chưa kết thúc",
    duStWartetGegner: "Đang chờ một bạn cùng lớp",
    duStGegnerSpielt: "Đối thủ của bạn chưa chơi",
    duPunkteIch: "Kết quả của bạn: {n} điểm",
    duSieg: "Thắng",
    duNiederlage: "Thua",
    duSiegGross: "Chiến thắng!",
    duNiederlageGross: "Thua cuộc",
    duUnentschiedenGross: "Hòa",
    duMitschueler: "Bạn cùng lớp",
    duDeinDuell: "Trận của bạn",
    duGegen: "với {name}",
    duPunkteZeile: "{a} : {b} điểm",
    duAktualisieren: "Làm mới",
    duVorschau: "Trận đối đầu cần tài khoản của bạn. Trong chế độ xem trước bạn không chơi được.",
    duLadenFehler: "Không tải được các trận.",
    duVorMin: "{n} phút trước",
    duVorStd: "{n} giờ trước",
    duVorTag: "{n} ngày trước",
    duJetzt: "vừa xong",
    duBereitTitel: "Bắt đầu nhé?",
    duBereitText: "8 câu hỏi, mỗi câu tối đa 20 giây. Đúng được 100 điểm, nhanh được thêm tối đa 50 điểm thưởng. Bạn không thể chơi lại hoặc dừng giữa chừng: ai bỏ giữa chừng nhận 0 điểm. Sau lượt chơi bạn sẽ thấy đáp án đúng.",
    duLos: "Bắt đầu",
    duZurueck: "Quay lại",
    duFrage: "Câu {n} / {m}",
    duZeichenAlt: "Biển báo giao thông",
    duAuswerten: "Đang chấm điểm …",
    duErgebnis: "Kết quả của bạn",
    duRichtigVon: "Đúng {n} / {m}",
    duWartet: "Kết quả của bạn đã có. Khi đối thủ chơi xong, bạn sẽ thấy ai thắng trong «Các trận của bạn».",
    duGegnerPunkte: "{name}: {n} điểm",
    duAuswertung: "Xem lại",
    duRichtigLabel: "Đúng",
    duFalschLabel: "Sai",
    duKeineAntwort: "Không trả lời (hết giờ)",
    duDeineAntwort: "Câu trả lời của bạn",
    duRichtigeAntwort: "Đáp án đúng",
    duNichtGespeichert: "Không lưu được kết quả của bạn. Hãy thử lại.",
    duNichtGespeichertEndgueltig: "Kết quả của bạn không được tính. Lượt chơi đã hết hạn hoặc dữ liệu không khớp.",
    duNochmalSenden: "Gửi lại",
    duSchonGespielt: "Lượt này đã được chơi rồi. Bạn sẽ thấy kết quả trong «Các trận của bạn».",
    duFehlerVergeben: "Đã có người nhận trận này.",
    duFehlerVerfallen: "Trận này không còn nữa hoặc đã hết hạn.",
    duFehlerRate: "Quá nhiều yêu cầu. Hãy chờ một chút rồi thử lại.",
    duFehlerAllgemein: "Không được. Hãy thử lại sau.",
    duZurUebersicht: "Về tổng quan"
  },
  rif: {
    duName: "Lmuwajaha d umdan n tneɣrit",
    duKurz: "Err ɣef 8 n yisteqsiyen n ṭṭeṛafik u qis iman-nnec d yiwen n umdan n tneɣrit. Ur ilaq ara ad tlɛabem deg yiwen n lweqt.",
    duIntro: "Kečč d yiwen n umdan n tneɣrit tkeffem imesteqsiyen 8 yeččuren. Win ara yesɛan aṭas n tneqqiḍin ad yerbeḥ. Tiririt tameẓẓuɣt d tazzayit tefk aṭas n tneqqiḍin. Ur ilaq ara ad tilim deg unternet deg yiwen n lweqt.",
    duBilanz: "Lḥsab-nnec",
    duSiege: "Rbeḥ",
    duUnentschieden: "Tamsawit",
    duNiederlagen: "Xsaṛ",
    duBilanzFrist: "Ttwaḥsaben imuwajahat n 90 n wussan yezrin.",
    duNeu: "Bdu amuwajah amaynut",
    duNeuHinweis: "Kečč ara yelɛben zwaṛ. Sakin amuwajah-nnec ad yerǧu amdan n tneɣrit.",
    duLimit: "Teɛdiḍ ɣur-k {n} n yimuwajahat yettwaɣeṛṛen. Fukk-itt zwaṛ.",
    duLimitKurz: "Ɣur-k aṭas n yimuwajahat yettwaɣeṛṛen. Fukk-itt zwaṛ.",
    duAusgeblendet: "Teffṛeḍ iman-nnec seg ttartib. Ula d yiwen ur yẓaṛ ttaḥaddi-nnec. Maca tzemṛeḍ ad tqebleḍ ttaḥaddiyat yeldin.",
    duMeine: "Imuwajahat-nnec",
    duMeineLeer: "Mazal ur tlɛabeḍ ula d yiwen n umuwajah.",
    duOffene: "Ttaḥaddiyat yeldin",
    duOffeneLeer: "Tura ula d yiwen ur yerǧa amdan. Bdu amuwajah, sakin amdan n tneɣrit ad t-yaf dagi.",
    duVerfall: "Imuwajahat war tigejdit ttkfan seld 7 n wussan. Amuwajah i tqebleḍ yessefk ad t-tebdueḍ deg 24 n tsaɛtin, ma ulac ad yuɣal ad yeṛǧu wayeḍ n tneɣrit.",
    duWeiterspielen: "Kemmel",
    duWeiterText: "Tura-inek mazal teldi. Ad d-tawiḍ 8 n yisteqsiyen kif-kif tikelt-nniḍen. Akud seg tazwara tamezwarut yettkemmil; tesɛiḍ akk 10 n tesdatin ugar.",
    duAnnehmen: "Qbel",
    duJetztSpielen: "Lɛeb tura",
    duStDran: "D nnuba-nnec",
    duStLaeuft: "Tura tebda ma ur tfukk ara",
    duStWartetGegner: "Terǧa amdan n tneɣrit",
    duStGegnerSpielt: "Amdan-nnec ur yelɛib ara mazal",
    duPunkteIch: "Tiririt-nnec: {n} n tneqqiḍin",
    duSieg: "Rbeḥ",
    duNiederlage: "Xsaṛ",
    duSiegGross: "Rbeḥ!",
    duNiederlageGross: "Xsaṛ",
    duUnentschiedenGross: "Tamsawit",
    duMitschueler: "Amdan n tneɣrit",
    duDeinDuell: "Amuwajah-nnec",
    duGegen: "d {name}",
    duPunkteZeile: "{a} : {b} n tneqqiḍin",
    duAktualisieren: "Ismil",
    duVorschau: "Imuwajahat ḥwaǧen amiḍan-nnec. Deg taskant ur tzemṛeḍ ara ad ten-tlɛabeḍ.",
    duLadenFehler: "Ur ttwaɣṛen ara imuwajahat.",
    duVorMin: "seg {n} n tdeqiqin",
    duVorStd: "seg {n} n tsragin",
    duVorTag: "seg {n} n wussan",
    duJetzt: "tura kan",
    duBereitTitel: "Ad nebdu?",
    duBereitText: "8 n yisteqsiyen, 20 n tswanin ar akteṛ i yal yiwen. Tiririt tuṣṣent tefk 100 n tneqqiḍin, tazzayit ar 50 n tneqqiḍin n bonus. Ur tzemṛeḍ ara ad twennaḍ neɣ ad tessḥebsed tabrat: win ara yeǧǧen ad yeṭṭef 0 n tneqqiḍin. Seld tabrat ad twaliḍ tiririn tuṣṣenin.",
    duLos: "Bdu",
    duZurueck: "Uɣal",
    duFrage: "Asteqsi {n} seg {m}",
    duZeichenAlt: "Lɛalama n ubrid",
    duAuswerten: "Ittwaḥsab …",
    duErgebnis: "Tiririt-nnec",
    duRichtigVon: "{n} seg {m} uṣṣen",
    duWartet: "Tiririt-nnec tewjed. Mi ara yelɛeb umdan-nnec, ad twaliḍ deg «Imuwajahat-nnec» anwa i yerbeḥen.",
    duGegnerPunkte: "{name}: {n} n tneqqiḍin",
    duAuswertung: "Tamyagt",
    duRichtigLabel: "Ṣṣeḥ",
    duFalschLabel: "Ɣalaṭ",
    duKeineAntwort: "War tiririt (lweqt yekfa)",
    duDeineAntwort: "Tiririt-nnec",
    duRichtigeAntwort: "Tiririt tuṣṣent",
    duNichtGespeichert: "Tiririt-nnec ur tettwasekles ara. Ɛreḍ tikkelt nniḍen.",
    duNichtGespeichertEndgueltig: "Tiririt-nnec ur tettwaḥsab ara. Tabrat tekfa neɣ isefka ur ttemẓẓiren ara.",
    duNochmalSenden: "Azen tikkelt nniḍen",
    duSchonGespielt: "Tabrat-a tlɛabeḍ-itt yakan. Ad twaliḍ tiririt deg «Imuwajahat-nnec».",
    duFehlerVergeben: "Yella win i yeqbelen amuwajah-a yakan.",
    duFehlerVerfallen: "Amuwajah-a ur yelli ara neɣ yekfa.",
    duFehlerRate: "Aṭas n yissutren. Rǧu cwiṭ u ɛreḍ tikkelt nniḍen.",
    duFehlerAllgemein: "Ur iddi ara. Ɛreḍ tikkelt nniḍen mbeɛd.",
    duZurUebersicht: "Ɣer tmuɣli tamatut"
  },
  fa: {
    duName: "دوئل با هم‌کلاسی",
    duKurz: "به 8 سؤال رانندگی پاسخ بدهید و با یک هم‌کلاسی رقابت کنید. لازم نیست هم‌زمان بازی کنید.",
    duIntro: "شما و یک هم‌کلاسی همان 8 سؤال را می‌گیرید. هر که امتیاز بیشتری داشته باشد برنده است. پاسخ درست و سریع بیشترین امتیاز را می‌دهد. لازم نیست هم‌زمان آنلاین باشید.",
    duBilanz: "نتیجه شما",
    duSiege: "برد",
    duUnentschieden: "مساوی",
    duNiederlagen: "باخت",
    duBilanzFrist: "دوئل‌های 90 روز گذشته شمرده می‌شود.",
    duNeu: "شروع دوئل جدید",
    duNeuHinweis: "اول شما بازی می‌کنید. بعد دوئل شما منتظر یک هم‌کلاسی می‌ماند.",
    duLimit: "شما همین حالا {n} دوئل در جریان دارید. اول آن‌ها را تمام کنید.",
    duLimitKurz: "شما دوئل‌های در جریان زیادی دارید. اول آن‌ها را تمام کنید.",
    duAusgeblendet: "شما در رتبه‌بندی پنهان هستید. هیچ‌کس چالش شما را نمی‌بیند. اما می‌توانید چالش‌های باز را بپذیرید.",
    duMeine: "دوئل‌های شما",
    duMeineLeer: "هنوز دوئلی بازی نشده است.",
    duOffene: "چالش‌های باز",
    duOffeneLeer: "الان کسی منتظر حریف نیست. یک دوئل شروع کنید، آن‌وقت یک هم‌کلاسی آن را اینجا می‌بیند.",
    duVerfall: "دوئل‌های بدون نتیجه بعد از 7 روز منقضی می‌شوند. دوئلی را که پذیرفته‌اید باید ظرف 24 ساعت شروع کنید، وگرنه دوباره منتظر یک هم‌کلاسی دیگر می‌ماند.",
    duWeiterspielen: "ادامه بازی",
    duWeiterText: "دور شما هنوز باز است. همان 8 سؤال را دوباره می‌گیرید. زمان از اولین شروع شما ادامه دارد؛ در مجموع حداکثر 10 دقیقه وقت دارید.",
    duAnnehmen: "پذیرفتن",
    duJetztSpielen: "همین حالا بازی کن",
    duStDran: "نوبت شماست",
    duStLaeuft: "دور شروع شده ولی تمام نشده",
    duStWartetGegner: "منتظر یک هم‌کلاسی",
    duStGegnerSpielt: "حریف شما هنوز بازی نکرده",
    duPunkteIch: "نتیجه شما: {n} امتیاز",
    duSieg: "برد",
    duNiederlage: "باخت",
    duSiegGross: "برد!",
    duNiederlageGross: "باخت",
    duUnentschiedenGross: "مساوی",
    duMitschueler: "هم‌کلاسی",
    duDeinDuell: "دوئل شما",
    duGegen: "با {name}",
    duPunkteZeile: "{a} : {b} امتیاز",
    duAktualisieren: "به‌روزرسانی",
    duVorschau: "دوئل به حساب شما نیاز دارد. در پیش‌نمایش نمی‌توانید آن را بازی کنید.",
    duLadenFehler: "دوئل‌ها بارگذاری نشدند.",
    duVorMin: "{n} دقیقه پیش",
    duVorStd: "{n} ساعت پیش",
    duVorTag: "{n} روز پیش",
    duJetzt: "همین الان",
    duBereitTitel: "شروع کنیم؟",
    duBereitText: "8 سؤال، هرکدام حداکثر 20 ثانیه. پاسخ درست 100 امتیاز و پاسخ سریع تا 50 امتیاز جایزه دارد. دور را نمی‌توان تکرار یا نیمه‌کاره رها کرد: هر که رها کند 0 امتیاز می‌گیرد. بعد از دور پاسخ‌های درست را می‌بینید.",
    duLos: "شروع",
    duZurueck: "بازگشت",
    duFrage: "سؤال {n} از {m}",
    duZeichenAlt: "علامت راهنمایی و رانندگی",
    duAuswerten: "در حال امتیازدهی …",
    duErgebnis: "نتیجه شما",
    duRichtigVon: "{n} از {m} درست",
    duWartet: "نتیجه شما ثبت شد. وقتی حریف شما بازی کند، در «دوئل‌های شما» می‌بینید چه کسی برد.",
    duGegnerPunkte: "{name}: {n} امتیاز",
    duAuswertung: "مرور",
    duRichtigLabel: "درست",
    duFalschLabel: "نادرست",
    duKeineAntwort: "بدون پاسخ (زمان تمام شد)",
    duDeineAntwort: "پاسخ شما",
    duRichtigeAntwort: "پاسخ درست",
    duNichtGespeichert: "نتیجه شما ذخیره نشد. لطفاً دوباره تلاش کنید.",
    duNichtGespeichertEndgueltig: "نتیجه شما حساب نشد. دور منقضی شد یا اطلاعات نمی‌خواند.",
    duNochmalSenden: "ارسال دوباره",
    duSchonGespielt: "این دور قبلاً بازی شده است. نتیجه را در «دوئل‌های شما» می‌بینید.",
    duFehlerVergeben: "این دوئل را قبلاً کسی پذیرفته است.",
    duFehlerVerfallen: "این دوئل دیگر وجود ندارد یا منقضی شده است.",
    duFehlerRate: "درخواست‌ها زیاد است. کمی صبر کنید و دوباره تلاش کنید.",
    duFehlerAllgemein: "نشد. لطفاً بعداً دوباره تلاش کنید.",
    duZurUebersicht: "به نمای کلی"
  },
  ps: {
    duName: "له ټولګیوال سره دوېل",
    duKurz: "د ترافیک 8 پوښتنو ته ځواب ورکړئ او له یو ټولګیوال سره سیالي وکړئ. اړینه نه ده چې په یو وخت کې ولوبوئ.",
    duIntro: "تاسو او یو ټولګیوال ورته 8 پوښتنې ترلاسه کوئ. چې ډېر نمرې ولري هغه ګټي. سم او ګړندی ځواب ډېر نمرې ورکوي. اړینه نه ده چې په یو وخت کې آنلاین اوسئ.",
    duBilanz: "ستاسو حساب",
    duSiege: "ګټنې",
    duUnentschieden: "برابري",
    duNiederlagen: "ماتې",
    duBilanzFrist: "د وروستیو 90 ورځو دوېلونه شمېرل کېږي.",
    duNeu: "نوی دوېل پیل کړئ",
    duNeuHinweis: "لومړی تاسو لوبه کوئ. بیا ستاسو دوېل د یو ټولګیوال انتظار کوي.",
    duLimit: "تاسو دمخه {n} روان دوېلونه لرئ. لومړی یې بشپړ کړئ.",
    duLimitKurz: "تاسو ډېر روان دوېلونه لرئ. لومړی یې بشپړ کړئ.",
    duAusgeblendet: "تاسو په درجه‌بندۍ کې پټ یاست. ستاسو ننګونه به هیڅوک ونه ویني. خو تاسو کولی شئ پرانیستې ننګونې ومنئ.",
    duMeine: "ستاسو دوېلونه",
    duMeineLeer: "تر اوسه هیڅ دوېل نه دی لوبول شوی.",
    duOffene: "پرانیستې ننګونې",
    duOffeneLeer: "همدا اوس هیڅوک د سیال انتظار نه کوي. یو دوېل پیل کړئ، بیا به یو ټولګیوال یې دلته ووینې.",
    duVerfall: "پرته له پایلې دوېلونه د 7 ورځو وروسته پای ته رسېږي. هغه دوېل چې منلی مو دی باید په 24 ساعتونو کې پیل کړئ، که نه بیا د بل ټولګیوال انتظار کوي.",
    duWeiterspielen: "لوبه ته دوام ورکړئ",
    duWeiterText: "ستاسو دوره لا هم پرانستې ده. هماغه 8 پوښتنې بیا ترلاسه کوئ. له لومړي پیل راهیسې وخت روان دی؛ په ټولو کې تر ټولو ډېر 10 دقیقې لرئ.",
    duAnnehmen: "منل",
    duJetztSpielen: "همدا اوس لوبه وکړئ",
    duStDran: "ستاسو وار دی",
    duStLaeuft: "دوره پیل شوه خو بشپړه نه شوه",
    duStWartetGegner: "د یو ټولګیوال انتظار کوي",
    duStGegnerSpielt: "ستاسو سیال لا نه دی لوبولی",
    duPunkteIch: "ستاسو پایله: {n} نمرې",
    duSieg: "ګټنه",
    duNiederlage: "ماتې",
    duSiegGross: "ګټنه!",
    duNiederlageGross: "ماتې",
    duUnentschiedenGross: "برابري",
    duMitschueler: "ټولګیوال",
    duDeinDuell: "ستاسو دوېل",
    duGegen: "د {name} په مقابل کې",
    duPunkteZeile: "{a} : {b} نمرې",
    duAktualisieren: "تازه کړئ",
    duVorschau: "دوېلونه ستاسو حساب ته اړتیا لري. په مخکتنه کې تاسو نشئ کولی ولوبوئ.",
    duLadenFehler: "دوېلونه ونه بارېدل.",
    duVorMin: "{n} دقیقې مخکې",
    duVorStd: "{n} ساعته مخکې",
    duVorTag: "{n} ورځې مخکې",
    duJetzt: "همدا اوس",
    duBereitTitel: "پیل کړو؟",
    duBereitText: "8 پوښتنې، هره یوه تر 20 ثانیو پورې. سم ځواب 100 نمرې ورکوي، ګړندی ځواب تر 50 بونس نمرو پورې. تاسو نشئ کولی دوره بیا وکړئ یا یې ودروئ: څوک چې پرې ږدي 0 نمرې ترلاسه کوي. د دورې وروسته تاسو سم ځوابونه وینئ.",
    duLos: "پیل",
    duZurueck: "شاته",
    duFrage: "پوښتنه {n} له {m}",
    duZeichenAlt: "د ترافیک نښه",
    duAuswerten: "ارزول کېږي …",
    duErgebnis: "ستاسو پایله",
    duRichtigVon: "{n} له {m} سم",
    duWartet: "ستاسو پایله شته. کله چې ستاسو سیال ولوبوي، تاسو به په «ستاسو دوېلونه» کې ووینئ چا وګټل.",
    duGegnerPunkte: "{name}: {n} نمرې",
    duAuswertung: "کتنه",
    duRichtigLabel: "سم",
    duFalschLabel: "غلط",
    duKeineAntwort: "ځواب نشته (وخت پای ته ورسېد)",
    duDeineAntwort: "ستاسو ځواب",
    duRichtigeAntwort: "سم ځواب",
    duNichtGespeichert: "ستاسو پایله خوندي نه شوه. مهرباني وکړئ بیا هڅه وکړئ.",
    duNichtGespeichertEndgueltig: "ستاسو پایله ونه شمېرل شوه. دوره پای ته رسېدلې یا معلومات سره نه لګېدل.",
    duNochmalSenden: "بیا ولېږئ",
    duSchonGespielt: "دا دوره دمخه لوبول شوې ده. پایله به په «ستاسو دوېلونه» کې ووینئ.",
    duFehlerVergeben: "دا دوېل مخکې یو چا منلی دی.",
    duFehlerVerfallen: "دا دوېل نور نشته یا پای ته رسېدلی دی.",
    duFehlerRate: "ډېر غوښتنې. لږ انتظار وکړئ او بیا هڅه وکړئ.",
    duFehlerAllgemein: "ونه شو. مهرباني وکړئ وروسته بیا هڅه وکړئ.",
    duZurUebersicht: "عمومي کتنې ته"
  },
  el: {
    duName: "Μονομαχία με συμμαθητή",
    duKurz: "Απάντησε σε 8 ερωτήσεις κυκλοφορίας και μετρήσου με έναν συμμαθητή. Δεν χρειάζεται να παίξετε ταυτόχρονα.",
    duIntro: "Εσύ και ένας συμμαθητής παίρνετε τις ίδιες 8 ερωτήσεις. Κερδίζει όποιος έχει περισσότερους πόντους. Σωστά και γρήγορα φέρνει τους περισσότερους πόντους. Δεν χρειάζεται να είστε online ταυτόχρονα.",
    duBilanz: "Το ιστορικό σου",
    duSiege: "Νίκες",
    duUnentschieden: "Ισοπαλίες",
    duNiederlagen: "Ήττες",
    duBilanzFrist: "Μετρούν οι μονομαχίες των τελευταίων 90 ημερών.",
    duNeu: "Ξεκίνα νέα μονομαχία",
    duNeuHinweis: "Πρώτα παίζεις εσύ. Μετά η μονομαχία σου περιμένει έναν συμμαθητή.",
    duLimit: "Έχεις ήδη {n} μονομαχίες σε εξέλιξη. Τελείωσέ τες πρώτα.",
    duLimitKurz: "Έχεις πάρα πολλές μονομαχίες σε εξέλιξη. Τελείωσέ τες πρώτα.",
    duAusgeblendet: "Είσαι κρυμμένος από την κατάταξη. Την πρόκλησή σου δεν θα τη δει κανείς. Μπορείς όμως να δεχτείς ανοιχτές προκλήσεις.",
    duMeine: "Οι μονομαχίες σου",
    duMeineLeer: "Δεν έχεις παίξει ακόμη καμία μονομαχία.",
    duOffene: "Ανοιχτές προκλήσεις",
    duOffeneLeer: "Αυτή τη στιγμή κανείς δεν περιμένει αντίπαλο. Ξεκίνα μια μονομαχία και θα τη δει εδώ ένας συμμαθητής.",
    duVerfall: "Οι μονομαχίες χωρίς αποτέλεσμα λήγουν μετά από 7 ημέρες. Μια μονομαχία που αποδέχτηκες πρέπει να την ξεκινήσεις μέσα σε 24 ώρες, αλλιώς περιμένει ξανά άλλον συμμαθητή.",
    duWeiterspielen: "Συνέχισε το παιχνίδι",
    duWeiterText: "Ο γύρος σου είναι ακόμη ανοιχτός. Παίρνεις ξανά τις ίδιες 8 ερωτήσεις. Ο χρόνος από την πρώτη εκκίνηση συνεχίζει να τρέχει· έχεις συνολικά το πολύ 10 λεπτά.",
    duAnnehmen: "Αποδοχή",
    duJetztSpielen: "Παίξε τώρα",
    duStDran: "Σειρά σου",
    duStLaeuft: "Ο γύρος ξεκίνησε αλλά δεν ολοκληρώθηκε",
    duStWartetGegner: "Περιμένει έναν συμμαθητή",
    duStGegnerSpielt: "Ο αντίπαλός σου δεν έχει παίξει ακόμη",
    duPunkteIch: "Το αποτέλεσμά σου: {n} πόντοι",
    duSieg: "Νίκη",
    duNiederlage: "Ήττα",
    duSiegGross: "Νίκη!",
    duNiederlageGross: "Ήττα",
    duUnentschiedenGross: "Ισοπαλία",
    duMitschueler: "Συμμαθητής",
    duDeinDuell: "Η μονομαχία σου",
    duGegen: "εναντίον {name}",
    duPunkteZeile: "{a} : {b} πόντοι",
    duAktualisieren: "Ανανέωση",
    duVorschau: "Οι μονομαχίες χρειάζονται τον λογαριασμό σου. Στην προεπισκόπηση δεν μπορείς να τις παίξεις.",
    duLadenFehler: "Οι μονομαχίες δεν φορτώθηκαν.",
    duVorMin: "πριν από {n} λεπτά",
    duVorStd: "πριν από {n} ώρες",
    duVorTag: "πριν από {n} ημέρες",
    duJetzt: "μόλις τώρα",
    duBereitTitel: "Ξεκινάμε;",
    duBereitText: "8 ερωτήσεις, το πολύ 20 δευτερόλεπτα η καθεμία. Σωστή απάντηση 100 πόντοι, γρήγορη έως 50 πόντοι μπόνους. Τον γύρο δεν μπορείς να τον επαναλάβεις ή να τον διακόψεις: όποιος σταματήσει παίρνει 0 πόντους. Μετά τον γύρο βλέπεις τις σωστές απαντήσεις.",
    duLos: "Πάμε",
    duZurueck: "Πίσω",
    duFrage: "Ερώτηση {n} από {m}",
    duZeichenAlt: "Πινακίδα κυκλοφορίας",
    duAuswerten: "Γίνεται βαθμολόγηση …",
    duErgebnis: "Το αποτέλεσμά σου",
    duRichtigVon: "{n} από {m} σωστές",
    duWartet: "Το αποτέλεσμά σου καταχωρίστηκε. Μόλις παίξει ο αντίπαλός σου, θα δεις στις «Οι μονομαχίες σου» ποιος κέρδισε.",
    duGegnerPunkte: "{name}: {n} πόντοι",
    duAuswertung: "Επανάληψη",
    duRichtigLabel: "Σωστό",
    duFalschLabel: "Λάθος",
    duKeineAntwort: "Καμία απάντηση (τέλος χρόνου)",
    duDeineAntwort: "Η απάντησή σου",
    duRichtigeAntwort: "Σωστή απάντηση",
    duNichtGespeichert: "Το αποτέλεσμά σου δεν αποθηκεύτηκε. Δοκίμασε ξανά.",
    duNichtGespeichertEndgueltig: "Το αποτέλεσμά σου δεν μετρήθηκε. Ο γύρος έληξε ή τα στοιχεία δεν ταίριαζαν.",
    duNochmalSenden: "Αποστολή ξανά",
    duSchonGespielt: "Αυτός ο γύρος έχει ήδη παιχτεί. Το αποτέλεσμα θα το δεις στις «Οι μονομαχίες σου».",
    duFehlerVergeben: "Αυτή τη μονομαχία την έχει ήδη δεχτεί κάποιος.",
    duFehlerVerfallen: "Αυτή η μονομαχία δεν υπάρχει πια ή έχει λήξει.",
    duFehlerRate: "Πάρα πολλά αιτήματα. Περίμενε λίγο και δοκίμασε ξανά.",
    duFehlerAllgemein: "Δεν πέτυχε. Δοκίμασε ξανά αργότερα.",
    duZurUebersicht: "Στην επισκόπηση"
  },
  am: {
    duName: "ከክፍል ጓደኛ ጋር ፍልሚያ",
    duKurz: "8 የትራፊክ ጥያቄዎችን መልሱ እና ከክፍል ጓደኛ ጋር ይወዳደሩ። በአንድ ጊዜ መጫወት አያስፈልግም።",
    duIntro: "እርስዎ እና አንድ የክፍል ጓደኛ ተመሳሳይ 8 ጥያቄዎች ይደርስዎታል። ብዙ ነጥብ ያለው ያሸንፋል። ትክክል እና ፈጣን መልስ ብዙ ነጥብ ያስገኛል። በአንድ ጊዜ መስመር ላይ መሆን አያስፈልግም።",
    duBilanz: "የእርስዎ ውጤት",
    duSiege: "ድሎች",
    duUnentschieden: "ሁለት እኩል",
    duNiederlagen: "ሽንፈቶች",
    duBilanzFrist: "የመጨረሻዎቹ 90 ቀናት ፍልሚያዎች ይቆጠራሉ።",
    duNeu: "አዲስ ፍልሚያ ጀምር",
    duNeuHinweis: "መጀመሪያ እርስዎ ይጫወታሉ። ከዚያ ፍልሚያዎ የክፍል ጓደኛን ይጠብቃል።",
    duLimit: "ቀድሞውኑ {n} በሂደት ላይ ያሉ ፍልሚያዎች አሉዎት። መጀመሪያ ያጠናቅቋቸው።",
    duLimitKurz: "በሂደት ላይ ያሉ ብዙ ፍልሚያዎች አሉዎት። መጀመሪያ ያጠናቅቋቸው።",
    duAusgeblendet: "በደረጃ ሰንጠረዡ ውስጥ ተደብቀዋል። ፈተናዎን ማንም አያይም። ግን ክፍት ፈተናዎችን መቀበል ይችላሉ።",
    duMeine: "የእርስዎ ፍልሚያዎች",
    duMeineLeer: "እስካሁን ምንም ፍልሚያ አልተጫወተም።",
    duOffene: "ክፍት ፈተናዎች",
    duOffeneLeer: "አሁን ተፎካካሪ የሚጠብቅ የለም። ፍልሚያ ይጀምሩ፣ ከዚያ አንድ የክፍል ጓደኛ እዚህ ያየዋል።",
    duVerfall: "ውጤት የሌላቸው ፍልሚያዎች ከ7 ቀን በኋላ ይጠናቀቃሉ። የተቀበሉት ፍልሚያ በ24 ሰዓት ውስጥ መጀመር አለበት፣ አለበለዚያ እንደገና ሌላ የክፍል ጓደኛ ይጠብቃል።",
    duWeiterspielen: "መጫወትዎን ይቀጥሉ",
    duWeiterText: "ዙርዎ አሁንም ክፍት ነው። ተመሳሳዩን 8 ጥያቄዎች እንደገና ያገኛሉ። ከመጀመሪያው ጅምር ጀምሮ ያለው ጊዜ መሄዱን ይቀጥላል፤ በጠቅላላው ቢበዛ 10 ደቂቃ አለዎት።",
    duAnnehmen: "ተቀበል",
    duJetztSpielen: "አሁን ተጫወት",
    duStDran: "ተራዎ ነው",
    duStLaeuft: "ዙሩ ተጀምሯል ግን አልተጠናቀቀም",
    duStWartetGegner: "የክፍል ጓደኛን እየጠበቀ ነው",
    duStGegnerSpielt: "ተፎካካሪዎ ገና አልተጫወተም",
    duPunkteIch: "የእርስዎ ውጤት፦ {n} ነጥብ",
    duSieg: "ድል",
    duNiederlage: "ሽንፈት",
    duSiegGross: "ድል!",
    duNiederlageGross: "ሽንፈት",
    duUnentschiedenGross: "ሁለት እኩል",
    duMitschueler: "የክፍል ጓደኛ",
    duDeinDuell: "የእርስዎ ፍልሚያ",
    duGegen: "ከ{name} ጋር",
    duPunkteZeile: "{a} : {b} ነጥብ",
    duAktualisieren: "አድስ",
    duVorschau: "ፍልሚያዎች መለያዎን ይፈልጋሉ። በቅድመ እይታ መጫወት አይችሉም።",
    duLadenFehler: "ፍልሚያዎቹ መጫን አልቻሉም።",
    duVorMin: "ከ{n} ደቂቃ በፊት",
    duVorStd: "ከ{n} ሰዓት በፊት",
    duVorTag: "ከ{n} ቀን በፊት",
    duJetzt: "አሁን ብቻ",
    duBereitTitel: "እንጀምር?",
    duBereitText: "8 ጥያቄዎች፣ እያንዳንዳቸው ቢበዛ 20 ሰከንድ። ትክክል መልስ 100 ነጥብ፣ ፈጣን መልስ እስከ 50 የጉርሻ ነጥብ ያስገኛል። ዙሩን መድገም ወይም ማቋረጥ አይችሉም፦ ያቋረጠ 0 ነጥብ ያገኛል። ከዙሩ በኋላ ትክክለኛዎቹን መልሶች ያያሉ።",
    duLos: "ጀምር",
    duZurueck: "ተመለስ",
    duFrage: "ጥያቄ {n} ከ{m}",
    duZeichenAlt: "የትራፊክ ምልክት",
    duAuswerten: "እየተገመገመ ነው …",
    duErgebnis: "የእርስዎ ውጤት",
    duRichtigVon: "ከ{m} {n} ትክክል",
    duWartet: "ውጤትዎ ተመዝግቧል። ተፎካካሪዎ ሲጫወት ማን እንዳሸነፈ በ«የእርስዎ ፍልሚያዎች» ውስጥ ያያሉ።",
    duGegnerPunkte: "{name}፦ {n} ነጥብ",
    duAuswertung: "ግምገማ",
    duRichtigLabel: "ትክክል",
    duFalschLabel: "ስህተት",
    duKeineAntwort: "መልስ የለም (ጊዜ አልቋል)",
    duDeineAntwort: "የእርስዎ መልስ",
    duRichtigeAntwort: "ትክክለኛ መልስ",
    duNichtGespeichert: "ውጤትዎ መቀመጥ አልቻለም። እባክዎ እንደገና ይሞክሩ።",
    duNichtGespeichertEndgueltig: "ውጤትዎ አልተቆጠረም። ዙሩ ጊዜው አልፎበታል ወይም መረጃው አልተመሳሰለም።",
    duNochmalSenden: "እንደገና ላክ",
    duSchonGespielt: "ይህ ዙር ቀድሞ ተጫውቷል። ውጤቱን በ«የእርስዎ ፍልሚያዎች» ውስጥ ያያሉ።",
    duFehlerVergeben: "ይህን ፍልሚያ ሌላ ሰው ቀድሞ ተቀብሏል።",
    duFehlerVerfallen: "ይህ ፍልሚያ ከእንግዲህ የለም ወይም ጊዜው አልፎበታል።",
    duFehlerRate: "በጣም ብዙ ጥያቄዎች። ትንሽ ጠብቀው እንደገና ይሞክሩ።",
    duFehlerAllgemein: "አልተሳካም። እባክዎ በኋላ እንደገና ይሞክሩ።",
    duZurUebersicht: "ወደ አጠቃላይ እይታ"
  },
  ti: {
    duName: "ምስ መማህርቲ ክፍሊ ሙግታ",
    duKurz: "8 ሕቶታት ትራፊክ መልሱ እሞ ምስ ሓደ መማህር ክፍሊ ተወዳደሩ። ብሓደ ግዜ ክትጻወቱ ኣየድልየኩምን።",
    duIntro: "ንስኹምን ሓደ መማህር ክፍልኹምን ሓደ ዓይነት 8 ሕቶታት ትረኽቡ። ዝበዝሐ ነጥቢ ዘለዎ የሸንፍ። ቅኑዕን ቅልጡፍን መልሲ ብዙሕ ነጥቢ የምጽእ። ብሓደ ግዜ ኣብ መስመር ክትኾኑ ኣየድልየኩምን።",
    duBilanz: "ውጽኢትኩም",
    duSiege: "ዓወታት",
    duUnentschieden: "ማዕረ ማዕረ",
    duNiederlagen: "ስዕረታት",
    duBilanzFrist: "ናይ ዝሓለፉ 90 መዓልታት ሙግታታት ይቑጸሩ።",
    duNeu: "ሓዱሽ ሙግታ ጀምሩ",
    duNeuHinweis: "መጀመርታ ንስኹም ትጻወቱ። ድሕሪኡ ሙግታኹም ሓደ መማህር ክፍሊ ይጽበ።",
    duLimit: "ድሮ {n} ዝቕጽሉ ሙግታታት ኣለዉኩም። መጀመርታ ዛዚምኩሙ።",
    duLimitKurz: "ብዙሓት ዝቕጽሉ ሙግታታት ኣለዉኩም። መጀመርታ ዛዚምኩሙ።",
    duAusgeblendet: "ኣብ ደረጃ ሰንጠረዥ ተሓቢእኩም ኣለኹም። ጸወታኹም ማንም ኣይርእዮን። ግን ክፉት ጸወታታት ክትቅበሉ ትኽእሉ።",
    duMeine: "ሙግታታትኩም",
    duMeineLeer: "ክሳብ ሕጂ ዝተጻወትኩሞ ሙግታ የለን።",
    duOffene: "ክፉት ጸወታታት",
    duOffeneLeer: "ሕጂ ተወዳዳሪ ዝጽበ የለን። ሙግታ ጀምሩ፣ ድሕሪኡ ሓደ መማህር ክፍሊ ኣብዚ ይርእዮ።",
    duVerfall: "ዘይውጽኢት ሙግታታት ድሕሪ 7 መዓልታት ይውዳእ። ዝተቐበልኩሞ ሙግታ ኣብ 24 ሰዓታት ክትጅምርዎ ኣለኩም፣ ዘይኮነ ድማ ዳግም ካልእ መማህር ክፍሊ ይጽበ።",
    duWeiterspielen: "ጻዋትኩም ቀጽሉ",
    duWeiterText: "ዙርኩም ገና ኽፉት እዩ። ተመሳሳሊ 8 ሕቶታት ዳግም ትረኽቡ። ካብ ናይ መጀመርታ ጅማሮ ዘሎ ግዜ ይቕጽል፤ ብጠቕላላ እታ ዝበዝሐ 10 ደቒቕ ኣለኩም።",
    duAnnehmen: "ተቐበሉ",
    duJetztSpielen: "ሕጂ ጻወቱ",
    duStDran: "ተራኹም እዩ",
    duStLaeuft: "ዙር ተጀሚሩ ግን ኣይተወደአን",
    duStWartetGegner: "ሓደ መማህር ክፍሊ ይጽበ",
    duStGegnerSpielt: "ተወዳዳርኹም ገና ኣይተጻወተን",
    duPunkteIch: "ውጽኢትኩም፦ {n} ነጥቢ",
    duSieg: "ዓወት",
    duNiederlage: "ስዕረት",
    duSiegGross: "ዓወት!",
    duNiederlageGross: "ስዕረት",
    duUnentschiedenGross: "ማዕረ ማዕረ",
    duMitschueler: "መማህር ክፍሊ",
    duDeinDuell: "ሙግታኹም",
    duGegen: "ምስ {name}",
    duPunkteZeile: "{a} : {b} ነጥቢ",
    duAktualisieren: "ኣሐድሱ",
    duVorschau: "ሙግታታት ኣካውንትኩም የድልዮም። ኣብ ቅድመ ትርኢት ክትጻወቱ ኣይትኽእሉን።",
    duLadenFehler: "ሙግታታት ክጽዓኑ ኣይከኣሉን።",
    duVorMin: "ቅድሚ {n} ደቒቕ",
    duVorStd: "ቅድሚ {n} ሰዓት",
    duVorTag: "ቅድሚ {n} መዓልቲ",
    duJetzt: "ሕጂ ጥራይ",
    duBereitTitel: "ንጀምር?",
    duBereitText: "8 ሕቶታት፣ ነፍሲ ወከፍ ክሳብ 20 ካልኢት። ቅኑዕ መልሲ 100 ነጥቢ፣ ቅልጡፍ መልሲ ክሳብ 50 ናይ ጉርሻ ነጥቢ የምጽእ። ንዙር ክትደግምዎ ወይ ክትቆርጽዎ ኣይትኽእሉን፦ ዝቐረጸ 0 ነጥቢ ይረክብ። ድሕሪ ዙር ቅኑዓት መልስታት ትርእዩ።",
    duLos: "ጀምሩ",
    duZurueck: "ተመለሱ",
    duFrage: "ሕቶ {n} ካብ {m}",
    duZeichenAlt: "ምልክት ትራፊክ",
    duAuswerten: "ይግመት ኣሎ …",
    duErgebnis: "ውጽኢትኩም",
    duRichtigVon: "ካብ {m} {n} ቅኑዕ",
    duWartet: "ውጽኢትኩም ተመዝጊቡ። ተወዳዳርኩም ምስ ዝጻወት ኣብ «ሙግታታትኩም» መን ከም ዘሸነፈ ትርእዩ።",
    duGegnerPunkte: "{name}፦ {n} ነጥቢ",
    duAuswertung: "ግምገማ",
    duRichtigLabel: "ቅኑዕ",
    duFalschLabel: "ጌጋ",
    duKeineAntwort: "መልሲ የለን (ግዜ ወዲኡ)",
    duDeineAntwort: "መልስኹም",
    duRichtigeAntwort: "ቅኑዕ መልሲ",
    duNichtGespeichert: "ውጽኢትኩም ክዕቀብ ኣይከኣለን። በጃኹም ደጊሞም ፈትኑ።",
    duNichtGespeichertEndgueltig: "ውጽኢትኩም ኣይተቆጸረን። እቲ ዙር ግዜኡ ኣብቂዑ ወይ ሓበሬታ ኣይተሰማምዐን።",
    duNochmalSenden: "ደጊምኩም ሰዱ",
    duSchonGespielt: "እዚ ዙር ድሮ ተጻዊቱ። ውጽኢቱ ኣብ «ሙግታታትኩም» ትርእዩ።",
    duFehlerVergeben: "እዚ ሙግታ ድሮ ሓደ ሰብ ተቐቢሉዎ።",
    duFehlerVerfallen: "እዚ ሙግታ ድሕሪ ሕጂ የለን ወይ ግዜኡ ኣብቂዑ።",
    duFehlerRate: "ብዙሓት ሕቶታት። ቁሩብ ተጸበዩ እሞ ደጊሞም ፈትኑ።",
    duFehlerAllgemein: "ኣይሰርሐን። በጃኹም ድሕሪ ሒደት ደጊሞም ፈትኑ።",
    duZurUebersicht: "ናብ ሓፈሻዊ ትርኢት"
  },
};
