/* Texte der Mini-Spiele in allen 18 Sprachen (06.10.2026).
   Eigene Datei wie bei verkehr/spieler.js: der Spiele-Bereich wird erst beim Öffnen geladen.
   Fehlt ein Schlüssel, erscheint Deutsch (wie t() in der App).
   Einheiten (km/h, ms, m) bleiben in allen Sprachen lateinisch.
   Anrede wie in der App: tr/es/ru/sr/el/ar/ckb/kmr/rif/vi du bzw. neutral; hi, ur, fa, ps, am, ti höflich.
   NICHT von Muttersprachlern geprüft: rif, ckb, kmr, ps, am, ti (wie bei den bisherigen Sprachpaketen
   bitte gegenlesen lassen). Neues Spiel = Schlüssel hier in ALLEN Sprachen ergänzen. */

export const RTL = ["ar", "ckb", "ur", "fa", "ps"];

export const TEXTE = {
  de: {
    titel: "Spiele",
    intro: "Kleine Spiele rund um den Verkehr. Miss dich mit den anderen.",
    profilName: "Dein Name im Ranking",
    profilSichtbar: "Im Ranking sichtbar",
    profilHinweis: "Andere sehen nur deinen Vornamen und einen Buchstaben. Du kannst dich jederzeit ausblenden.",
    profilAus: "Du bist ausgeblendet. Deine Zeiten siehst nur du.",
    bestzeit: "Deine Bestzeit",
    nochNicht: "Noch nicht gespielt",
    spielen: "Spielen",
    ampelName: "Ampel-Bremsweg",
    ampelKurz: "Bremse, sobald die Lichter ausgehen, und sieh, wie weit dein Auto noch rollt.",
    tempoName: "Tempo-Sprint",
    tempoKurz: "Tippe schnell, bleib unter dem Schild – und gib im Endspurt alles.",
    tempoBestwert: "Dein Höchsttempo",
    tempoNeu: "Neues Höchsttempo!",
    tempoBereit: "Tippe auf Start. Dann tippe so oft du kannst auf die große Fläche: Jedes Tippen macht dich schneller. Bleib unter dem Tempo auf dem Schild!",
    tempoGleich: "Mach dich bereit …",
    tempoTippen: "TIPPEN!",
    tempoErlaubt: "Erlaubt: {v} km/h",
    tempoNaechstes: "Gleich: {v} km/h",
    tempoNaechstesFrei: "Gleich: keine Begrenzung",
    tempoSpurt: "ENDSPURT! So schnell wie möglich!",
    tempoBlitzer: "Blitzer! Du warst zu schnell. Kurz gesperrt, Tempo weg.",
    tempoErgTipps: "Tipps im Endspurt",
    tempoErgBlitzer: "Blitzer",
    tempoHinweis: "Im echten Leben gilt auf der Autobahn die Richtgeschwindigkeit 130 km/h. Wo ein Schild eine Höchstgeschwindigkeit zeigt, musst du dich immer daran halten.",
    tempoZ274: "Verkehrszeichen 274: Höchstgeschwindigkeit {v} km/h",
    tempoZ282: "Verkehrszeichen 282: Ende aller Streckenverbote",
    vorschauMarke: "Vorschau",
    speed: "Geschwindigkeit",
    start: "Start",
    bremsen: "BREMSEN",
    bereit: "Tippe auf Start. Wenn alle Lichter ausgehen, bremse so schnell du kannst.",
    warte: "Warte … nicht zu früh!",
    jetzt: "JETZT!",
    fehlstart: "Fehlstart! Du hast gebremst, bevor die Lichter ausgingen.",
    zuLangsam: "Zu langsam. Du hast nicht rechtzeitig gebremst.",
    nochmal: "Nochmal",
    deineReaktion: "Deine Reaktion",
    ergDein: "Dein Anhalteweg",
    ergDeinSub: "mit deiner Reaktion von eben",
    ergStrasse: "Auf der Straße",
    ergStrasseSub: "Faustformel der Fahrschule",
    ergNass: "Bei Nässe",
    legReaktion: "Reaktionsweg",
    legBrems: "Bremsweg",
    hinweisStrasse: "Auf der Straße vergeht etwa 1 Sekunde, bis man wirklich bremst. Darum ist der echte Anhalteweg länger als im Spiel.",
    neuerRekord: "Neue Bestzeit!",
    platz: "Platz {n} von {m}",
    nichtGespeichert: "Dein Ergebnis konnte nicht gespeichert werden. Du kannst trotzdem weiterspielen.",
    uebung: "Übungsmodus: Dein Ergebnis wird nicht gespeichert.",
    rankingTitel: "Bestenliste",
    rankingLeer: "Noch niemand in der Bestenliste. Sei der Erste!",
    rankingFehler: "Die Bestenliste konnte nicht geladen werden.",
    du: "Du",
    laden: "Lade …",
    fehler: "Das hat nicht geklappt. Versuche es später noch einmal."
  },
  tr: {
    titel: "Oyunlar",
    intro: "Trafikle ilgili küçük oyunlar. Kendini diğerleriyle karşılaştır.",
    profilName: "Sıralamadaki adın",
    profilSichtbar: "Sıralamada görünür",
    profilHinweis: "Diğerleri yalnızca adını ve bir harf görür. İstediğin zaman gizlenebilirsin.",
    profilAus: "Gizlisin. Sürelerini yalnızca sen görürsün.",
    bestzeit: "En iyi süren",
    nochNicht: "Henüz oynanmadı",
    spielen: "Oyna",
    ampelName: "Trafik ışığı ve fren mesafesi",
    ampelKurz: "Işıklar sönünce fren yap ve aracının ne kadar gittiğini gör.",
    tempoName: "Hız Sprinti",
    tempoKurz: "Hızlı dokun, levhanın altında kal – ve son sprintte her şeyi ver.",
    tempoBestwert: "En yüksek hızın",
    tempoNeu: "Yeni en yüksek hız!",
    tempoBereit: "Başla'ya dokun. Sonra büyük alana olabildiğince sık dokun: her dokunuş seni hızlandırır. Levhadaki hızın altında kal!",
    tempoGleich: "Hazırlan …",
    tempoTippen: "DOKUN!",
    tempoErlaubt: "İzin verilen: {v} km/h",
    tempoNaechstes: "Birazdan: {v} km/h",
    tempoNaechstesFrei: "Birazdan: sınırlama yok",
    tempoSpurt: "SON SPRİNT! Olabildiğince hızlı ol!",
    tempoBlitzer: "Radar! Çok hızlıydın. Kısa süre kilitli, hız düştü.",
    tempoErgTipps: "Son sprintteki dokunuşlar",
    tempoErgBlitzer: "Radar",
    tempoHinweis: "Gerçek hayatta otoyolda tavsiye edilen hız 130 km/h'dir. Bir levha azami hız gösteriyorsa, buna her zaman uymak zorundasın.",
    tempoZ274: "Trafik işareti 274: azami hız {v} km/h",
    tempoZ282: "Trafik işareti 282: tüm yol boyu yasakların sonu",
    vorschauMarke: "Önizleme",
    speed: "Hız",
    start: "Başla",
    bremsen: "FREN",
    bereit: "Başla'ya dokun. Tüm ışıklar sönünce olabildiğince hızlı fren yap.",
    warte: "Bekle … erken değil!",
    jetzt: "ŞİMDİ!",
    fehlstart: "Erken kalkış! Işıklar sönmeden fren yaptın.",
    zuLangsam: "Çok yavaş. Zamanında fren yapmadın.",
    nochmal: "Tekrar",
    deineReaktion: "Tepki süren",
    ergDein: "Durma mesafen",
    ergDeinSub: "az önceki tepkinle",
    ergStrasse: "Yolda",
    ergStrasseSub: "Sürücü kursunun pratik formülü",
    ergNass: "Islak zeminde",
    legReaktion: "Tepki mesafesi",
    legBrems: "Fren mesafesi",
    hinweisStrasse: "Yolda gerçekten fren yapana kadar yaklaşık 1 saniye geçer. Bu yüzden gerçek durma mesafesi oyundakinden uzundur.",
    neuerRekord: "Yeni en iyi süre!",
    platz: "{n}. sıra / {m}",
    nichtGespeichert: "Sonucun kaydedilemedi. Yine de oynamaya devam edebilirsin.",
    uebung: "Alıştırma modu: Sonucun kaydedilmez.",
    rankingTitel: "Sıralama",
    rankingLeer: "Sıralamada henüz kimse yok. İlk sen ol!",
    rankingFehler: "Sıralama yüklenemedi.",
    du: "Sen",
    laden: "Yükleniyor …",
    fehler: "Olmadı. Lütfen daha sonra tekrar dene."
  },
  en: {
    titel: "Games",
    intro: "Small games about traffic. See how you compare with the others.",
    profilName: "Your name in the ranking",
    profilSichtbar: "Visible in the ranking",
    profilHinweis: "Others only see your first name and one letter. You can hide yourself at any time.",
    profilAus: "You are hidden. Only you can see your times.",
    bestzeit: "Your best time",
    nochNicht: "Not played yet",
    spielen: "Play",
    ampelName: "Traffic light braking distance",
    ampelKurz: "Brake as soon as the lights go out and see how far your car still rolls.",
    tempoName: "Speed Sprint",
    tempoKurz: "Tap fast, stay under the sign – and give it everything in the final sprint.",
    tempoBestwert: "Your top speed",
    tempoNeu: "New top speed!",
    tempoBereit: "Tap Start. Then tap the big area as often as you can: every tap makes you faster. Stay below the speed on the sign!",
    tempoGleich: "Get ready …",
    tempoTippen: "TAP!",
    tempoErlaubt: "Allowed: {v} km/h",
    tempoNaechstes: "Next: {v} km/h",
    tempoNaechstesFrei: "Next: no limit",
    tempoSpurt: "FINAL SPRINT! As fast as you can!",
    tempoBlitzer: "Speed camera! You were too fast. Locked for a moment, speed gone.",
    tempoErgTipps: "Taps in the final sprint",
    tempoErgBlitzer: "Speed cameras",
    tempoHinweis: "In real life, the recommended speed on the German Autobahn is 130 km/h. Where a sign shows a maximum speed, you must always keep to it.",
    tempoZ274: "Traffic sign 274: maximum speed {v} km/h",
    tempoZ282: "Traffic sign 282: end of all route restrictions",
    vorschauMarke: "Preview",
    speed: "Speed",
    start: "Start",
    bremsen: "BRAKE",
    bereit: "Tap Start. When all the lights go out, brake as fast as you can.",
    warte: "Wait … not too early!",
    jetzt: "NOW!",
    fehlstart: "False start! You braked before the lights went out.",
    zuLangsam: "Too slow. You did not brake in time.",
    nochmal: "Again",
    deineReaktion: "Your reaction",
    ergDein: "Your stopping distance",
    ergDeinSub: "with the reaction you just had",
    ergStrasse: "On the road",
    ergStrasseSub: "Driving school rule of thumb",
    ergNass: "On a wet road",
    legReaktion: "Reaction distance",
    legBrems: "Braking distance",
    hinweisStrasse: "On the road, about 1 second passes before you really brake. That is why the real stopping distance is longer than in the game.",
    neuerRekord: "New best time!",
    platz: "Place {n} of {m}",
    nichtGespeichert: "Your result could not be saved. You can keep playing anyway.",
    uebung: "Practice mode: your result is not saved.",
    rankingTitel: "Leaderboard",
    rankingLeer: "Nobody on the leaderboard yet. Be the first!",
    rankingFehler: "The leaderboard could not be loaded.",
    du: "You",
    laden: "Loading …",
    fehler: "That did not work. Please try again later."
  },
  ar: {
    titel: "ألعاب",
    intro: "ألعاب صغيرة عن المرور. قارن نفسك بالآخرين.",
    profilName: "اسمك في الترتيب",
    profilSichtbar: "ظاهر في الترتيب",
    profilHinweis: "يرى الآخرون اسمك الأول وحرفًا واحدًا فقط. يمكنك إخفاء نفسك في أي وقت.",
    profilAus: "أنت مخفي. لا يرى أوقاتك غيرك.",
    bestzeit: "أفضل زمن لك",
    nochNicht: "لم تلعب بعد",
    spielen: "العب",
    ampelName: "إشارة المرور ومسافة الفرملة",
    ampelKurz: "اضغط الفرامل بمجرد انطفاء الأضواء وشاهد كم تتحرك سيارتك بعد ذلك.",
    tempoName: "سباق السرعة",
    tempoKurz: "اضغط بسرعة، وابقَ تحت اللافتة، وأعطِ كل ما لديك في الاندفاعة الأخيرة.",
    tempoBestwert: "أعلى سرعة لك",
    tempoNeu: "أعلى سرعة جديدة!",
    tempoBereit: "اضغط على «ابدأ». ثم اضغط على المساحة الكبيرة بأكثر ما تستطيع: كل ضغطة تجعلك أسرع. ابقَ تحت السرعة المكتوبة على اللافتة!",
    tempoGleich: "استعد …",
    tempoTippen: "اضغط!",
    tempoErlaubt: "المسموح: {v} km/h",
    tempoNaechstes: "بعد قليل: {v} km/h",
    tempoNaechstesFrei: "بعد قليل: بلا حد للسرعة",
    tempoSpurt: "الاندفاعة الأخيرة! بأسرع ما يمكن!",
    tempoBlitzer: "رادار! كنت أسرع من اللازم. توقفت الضغطات لحظة وانخفضت سرعتك.",
    tempoErgTipps: "الضغطات في الاندفاعة الأخيرة",
    tempoErgBlitzer: "الرادار",
    tempoHinweis: "في الحياة الواقعية، السرعة الموصى بها على الأوتوبان في ألمانيا هي 130 km/h. وحيثما تُظهر اللافتة سرعة قصوى، يجب عليك الالتزام بها دائماً.",
    tempoZ274: "علامة المرور 274: السرعة القصوى {v} km/h",
    tempoZ282: "علامة المرور 282: نهاية جميع قيود الطريق",
    vorschauMarke: "معاينة",
    speed: "السرعة",
    start: "ابدأ",
    bremsen: "فرملة",
    bereit: "اضغط على «ابدأ». عندما تنطفئ كل الأضواء، اضغط الفرامل بأسرع ما يمكن.",
    warte: "انتظر … لا تتعجل!",
    jetzt: "الآن!",
    fehlstart: "انطلاقة خاطئة! ضغطت الفرامل قبل انطفاء الأضواء.",
    zuLangsam: "بطيء جدًا. لم تضغط الفرامل في الوقت المناسب.",
    nochmal: "مرة أخرى",
    deineReaktion: "ردة فعلك",
    ergDein: "مسافة توقفك",
    ergDeinSub: "بردة فعلك الآن",
    ergStrasse: "على الطريق",
    ergStrasseSub: "القاعدة التقريبية في مدرسة تعليم القيادة",
    ergNass: "على طريق مبلل",
    legReaktion: "مسافة رد الفعل",
    legBrems: "مسافة الفرملة",
    hinweisStrasse: "على الطريق يمر نحو ثانية واحدة قبل أن تضغط الفرامل فعلًا. لذلك مسافة التوقف الحقيقية أطول مما في اللعبة.",
    neuerRekord: "أفضل زمن جديد!",
    platz: "المركز {n} من {m}",
    nichtGespeichert: "تعذّر حفظ نتيجتك. يمكنك مواصلة اللعب مع ذلك.",
    uebung: "وضع التدريب: لن يتم حفظ نتيجتك.",
    rankingTitel: "قائمة الأفضل",
    rankingLeer: "لا أحد في القائمة بعد. كن الأول!",
    rankingFehler: "تعذّر تحميل القائمة.",
    du: "أنت",
    laden: "جارٍ التحميل …",
    fehler: "لم تنجح العملية. حاول مرة أخرى لاحقًا."
  },
  es: {
    titel: "Juegos",
    intro: "Pequeños juegos sobre el tráfico. Mídete con los demás.",
    profilName: "Tu nombre en la clasificación",
    profilSichtbar: "Visible en la clasificación",
    profilHinweis: "Los demás solo ven tu nombre y una letra. Puedes ocultarte cuando quieras.",
    profilAus: "Estás oculto. Solo tú ves tus tiempos.",
    bestzeit: "Tu mejor tiempo",
    nochNicht: "Aún no has jugado",
    spielen: "Jugar",
    ampelName: "Semáforo y distancia de frenado",
    ampelKurz: "Frena en cuanto se apaguen las luces y mira cuánto rueda aún tu coche.",
    tempoName: "Sprint de velocidad",
    tempoKurz: "Toca rápido, mantente por debajo de la señal y da todo en el sprint final.",
    tempoBestwert: "Tu velocidad máxima",
    tempoNeu: "¡Nueva velocidad máxima!",
    tempoBereit: "Toca Empezar. Luego toca la zona grande tantas veces como puedas: cada toque te hace más rápido. ¡Mantente por debajo de la velocidad de la señal!",
    tempoGleich: "Prepárate …",
    tempoTippen: "¡TOCA!",
    tempoErlaubt: "Permitido: {v} km/h",
    tempoNaechstes: "Pronto: {v} km/h",
    tempoNaechstesFrei: "Pronto: sin límite",
    tempoSpurt: "¡SPRINT FINAL! ¡Lo más rápido posible!",
    tempoBlitzer: "¡Radar! Ibas demasiado rápido. Bloqueado un momento y sin velocidad.",
    tempoErgTipps: "Toques en el sprint final",
    tempoErgBlitzer: "Radares",
    tempoHinweis: "En la vida real, la velocidad recomendada en la autopista alemana es de 130 km/h. Donde una señal indica una velocidad máxima, siempre debes respetarla.",
    tempoZ274: "Señal de tráfico 274: velocidad máxima {v} km/h",
    tempoZ282: "Señal de tráfico 282: fin de todas las restricciones del tramo",
    vorschauMarke: "Vista previa",
    speed: "Velocidad",
    start: "Empezar",
    bremsen: "FRENAR",
    bereit: "Toca Empezar. Cuando se apaguen todas las luces, frena lo más rápido que puedas.",
    warte: "Espera … ¡no demasiado pronto!",
    jetzt: "¡YA!",
    fehlstart: "¡Salida en falso! Frenaste antes de que se apagaran las luces.",
    zuLangsam: "Demasiado lento. No frenaste a tiempo.",
    nochmal: "Otra vez",
    deineReaktion: "Tu reacción",
    ergDein: "Tu distancia de detención",
    ergDeinSub: "con tu reacción de ahora",
    ergStrasse: "En la carretera",
    ergStrasseSub: "Regla práctica de la autoescuela",
    ergNass: "Con calzada mojada",
    legReaktion: "Distancia de reacción",
    legBrems: "Distancia de frenado",
    hinweisStrasse: "En la carretera pasa aproximadamente 1 segundo hasta que realmente frenas. Por eso la distancia de detención real es mayor que en el juego.",
    neuerRekord: "¡Nuevo mejor tiempo!",
    platz: "Puesto {n} de {m}",
    nichtGespeichert: "No se pudo guardar tu resultado. Puedes seguir jugando.",
    uebung: "Modo práctica: tu resultado no se guarda.",
    rankingTitel: "Clasificación",
    rankingLeer: "Todavía no hay nadie en la clasificación. ¡Sé el primero!",
    rankingFehler: "No se pudo cargar la clasificación.",
    du: "Tú",
    laden: "Cargando …",
    fehler: "No ha funcionado. Inténtalo de nuevo más tarde."
  },
  ru: {
    titel: "Игры",
    intro: "Небольшие игры о дорожном движении. Сравни себя с другими.",
    profilName: "Твоё имя в рейтинге",
    profilSichtbar: "Виден в рейтинге",
    profilHinweis: "Другие видят только твоё имя и одну букву. Ты можешь скрыться в любой момент.",
    profilAus: "Ты скрыт. Твои результаты видишь только ты.",
    bestzeit: "Твой лучший результат",
    nochNicht: "Ещё не играл",
    spielen: "Играть",
    ampelName: "Светофор и тормозной путь",
    ampelKurz: "Тормози, как только погаснут огни, и посмотри, как далеко ещё проедет машина.",
    tempoName: "Спринт скорости",
    tempoKurz: "Нажимай быстро, держись ниже знака — и выложись на финальном рывке.",
    tempoBestwert: "Твоя максимальная скорость",
    tempoNeu: "Новый рекорд скорости!",
    tempoBereit: "Нажми «Старт». Потом нажимай на большую область как можно чаще: каждое нажатие ускоряет тебя. Не превышай скорость на знаке!",
    tempoGleich: "Приготовься …",
    tempoTippen: "ЖМИ!",
    tempoErlaubt: "Разрешено: {v} km/h",
    tempoNaechstes: "Скоро: {v} km/h",
    tempoNaechstesFrei: "Скоро: без ограничений",
    tempoSpurt: "ФИНАЛЬНЫЙ РЫВОК! Как можно быстрее!",
    tempoBlitzer: "Радар! Ты ехал слишком быстро. Нажатия ненадолго заблокированы, скорость упала.",
    tempoErgTipps: "Нажатия в финальном рывке",
    tempoErgBlitzer: "Радары",
    tempoHinweis: "В реальной жизни на немецком автобане рекомендуемая скорость — 130 km/h. Если знак показывает максимальную скорость, её нужно соблюдать всегда.",
    tempoZ274: "Дорожный знак 274: максимальная скорость {v} km/h",
    tempoZ282: "Дорожный знак 282: конец всех зон ограничений",
    vorschauMarke: "Предпросмотр",
    speed: "Скорость",
    start: "Старт",
    bremsen: "ТОРМОЗ",
    bereit: "Нажми «Старт». Когда погаснут все огни, тормози как можно быстрее.",
    warte: "Жди … не слишком рано!",
    jetzt: "СЕЙЧАС!",
    fehlstart: "Фальстарт! Ты затормозил до того, как погасли огни.",
    zuLangsam: "Слишком медленно. Ты не затормозил вовремя.",
    nochmal: "Ещё раз",
    deineReaktion: "Твоя реакция",
    ergDein: "Твой остановочный путь",
    ergDeinSub: "с твоей реакцией сейчас",
    ergStrasse: "На дороге",
    ergStrasseSub: "Правило автошколы",
    ergNass: "На мокрой дороге",
    legReaktion: "Путь реакции",
    legBrems: "Тормозной путь",
    hinweisStrasse: "На дороге проходит около 1 секунды, прежде чем ты по-настоящему затормозишь. Поэтому настоящий остановочный путь длиннее, чем в игре.",
    neuerRekord: "Новый рекорд!",
    platz: "Место {n} из {m}",
    nichtGespeichert: "Результат не удалось сохранить. Ты можешь играть дальше.",
    uebung: "Режим тренировки: результат не сохраняется.",
    rankingTitel: "Рейтинг",
    rankingLeer: "В рейтинге пока никого нет. Будь первым!",
    rankingFehler: "Не удалось загрузить рейтинг.",
    du: "Ты",
    laden: "Загрузка …",
    fehler: "Не получилось. Попробуй ещё раз позже."
  },
  sr: {
    titel: "Igre",
    intro: "Male igre o saobraćaju. Odmeri se sa ostalima.",
    profilName: "Tvoje ime na rang listi",
    profilSichtbar: "Vidljiv na rang listi",
    profilHinweis: "Drugi vide samo tvoje ime i jedno slovo. Možeš da se sakriješ u bilo koje vreme.",
    profilAus: "Sakriven si. Tvoja vremena vidiš samo ti.",
    bestzeit: "Tvoje najbolje vreme",
    nochNicht: "Još nisi igrao",
    spielen: "Igraj",
    ampelName: "Semafor i put kočenja",
    ampelKurz: "Koči čim se svetla ugase i vidi koliko se tvoj auto još kotrlja.",
    tempoName: "Sprint brzine",
    tempoKurz: "Dodiruj brzo, ostani ispod znaka – i daj sve u završnom sprintu.",
    tempoBestwert: "Tvoja najveća brzina",
    tempoNeu: "Nova najveća brzina!",
    tempoBereit: "Dodirni Start. Zatim dodiruj veliku površinu što češće možeš: svaki dodir te ubrzava. Ostani ispod brzine na znaku!",
    tempoGleich: "Pripremi se …",
    tempoTippen: "DODIRUJ!",
    tempoErlaubt: "Dozvoljeno: {v} km/h",
    tempoNaechstes: "Uskoro: {v} km/h",
    tempoNaechstesFrei: "Uskoro: bez ograničenja",
    tempoSpurt: "ZAVRŠNI SPRINT! Što brže možeš!",
    tempoBlitzer: "Radar! Bio si prebrz. Kratko blokirano, brzina pala.",
    tempoErgTipps: "Dodiri u završnom sprintu",
    tempoErgBlitzer: "Radari",
    tempoHinweis: "U stvarnom životu, preporučena brzina na nemačkom autoputu je 130 km/h. Gde znak prikazuje najveću dozvoljenu brzinu, uvek je moraš poštovati.",
    tempoZ274: "Saobraćajni znak 274: najveća brzina {v} km/h",
    tempoZ282: "Saobraćajni znak 282: kraj svih ograničenja na deonici",
    vorschauMarke: "Pregled",
    speed: "Brzina",
    start: "Start",
    bremsen: "KOČI",
    bereit: "Dodirni Start. Kad se sva svetla ugase, koči što brže možeš.",
    warte: "Čekaj … ne prerano!",
    jetzt: "SAD!",
    fehlstart: "Pogrešan start! Kočio si pre nego što su se svetla ugasila.",
    zuLangsam: "Prespor. Nisi kočio na vreme.",
    nochmal: "Opet",
    deineReaktion: "Tvoja reakcija",
    ergDein: "Tvoj zaustavni put",
    ergDeinSub: "sa tvojom reakcijom od malopre",
    ergStrasse: "Na putu",
    ergStrasseSub: "Pravilo auto-škole",
    ergNass: "Na mokrom putu",
    legReaktion: "Put reakcije",
    legBrems: "Put kočenja",
    hinweisStrasse: "Na putu prođe oko 1 sekunde dok stvarno ne zakočiš. Zato je pravi zaustavni put duži nego u igri.",
    neuerRekord: "Novo najbolje vreme!",
    platz: "Mesto {n} od {m}",
    nichtGespeichert: "Rezultat nije mogao da se sačuva. Možeš da nastaviš da igraš.",
    uebung: "Režim vežbe: rezultat se ne čuva.",
    rankingTitel: "Rang lista",
    rankingLeer: "Još nikoga nema na listi. Budi prvi!",
    rankingFehler: "Rang lista nije mogla da se učita.",
    du: "Ti",
    laden: "Učitavanje …",
    fehler: "Nije uspelo. Pokušaj ponovo kasnije."
  },
  ckb: {
    titel: "یاریەکان",
    intro: "یاری بچووک دەربارەی هاتوچۆ. خۆت لەگەڵ ئەوانی تر بپێوە.",
    profilName: "ناوت لە ڕیزبەندیدا",
    profilSichtbar: "لە ڕیزبەندیدا دیارە",
    profilHinweis: "ئەوانی تر تەنها یەکەم ناو و یەک پیتت دەبینن. دەتوانیت هەر کاتێک خۆت بشاریتەوە.",
    profilAus: "تۆ شاراویتەوە. کاتەکانت تەنها تۆ دەیانبینیت.",
    bestzeit: "باشترین کاتت",
    nochNicht: "هێشتا یاری نەکراوە",
    spielen: "یاری بکە",
    ampelName: "ترافیک لایت و دووری برێک",
    ampelKurz: "کە چراکان کوژانەوە برێک بکە و ببینە ئۆتۆمبێلەکەت چەند دەڕوات.",
    tempoName: "ڕاکردنی خێرایی",
    tempoKurz: "بە خێرایی دابگرە، لە ژێر تابلۆکە بمێنەرەوە — و لە کۆتایی ڕاکردنەکەدا هەموو هێزت بخەرە کار.",
    tempoBestwert: "بەرزترین خێراییت",
    tempoNeu: "بەرزترین خێرایی نوێ!",
    tempoBereit: "لەسەر «دەستپێبکە» دابگرە. پاشان تا دەتوانیت لەسەر ڕووبەرە گەورەکە دابگرە: هەر دابگرتنێک خێراترت دەکات. لە ژێر خێرایی سەر تابلۆکە بمێنەرەوە!",
    tempoGleich: "ئامادە بە …",
    tempoTippen: "دابگرە!",
    tempoErlaubt: "ڕێگەپێدراو: {v} km/h",
    tempoNaechstes: "بەم زووانە: {v} km/h",
    tempoNaechstesFrei: "بەم زووانە: بێ سنوور",
    tempoSpurt: "کۆتایی ڕاکردن! هەرچی دەتوانیت خێرا!",
    tempoBlitzer: "کامێرای خێرایی! زۆر خێرا بوویت. بۆ ساتێک قوفڵ کرا و خێراییت نەما.",
    tempoErgTipps: "دابگرتنەکان لە کۆتایی ڕاکردن",
    tempoErgBlitzer: "کامێراکانی خێرایی",
    tempoHinweis: "لە ژیانی ڕاستەقینەدا خێرایی پێشنیارکراو لەسەر ئۆتۆبانی ئەڵمانیا 130 km/h ـە. لەو شوێنانەی تابلۆ بەرزترین خێرایی نیشان دەدات، هەمیشە دەبێت پابەندی بیت.",
    tempoZ274: "تابلۆی ترافیک 274: بەرزترین خێرایی {v} km/h",
    tempoZ282: "تابلۆی ترافیک 282: کۆتایی هەموو قەدەغەکانی ڕێگا",
    vorschauMarke: "پێشبینین",
    speed: "خێرایی",
    start: "دەستپێبکە",
    bremsen: "برێک",
    bereit: "لەسەر «دەستپێبکە» دابگرە. کاتێک هەموو چراکان کوژانەوە، بە خێراترین شێوە برێک بکە.",
    warte: "چاوەڕێ بکە … زوو مەکە!",
    jetzt: "ئێستا!",
    fehlstart: "دەستپێکی هەڵە! پێش کوژانەوەی چراکان برێکت کرد.",
    zuLangsam: "زۆر خاو. بە کات برێکت نەکرد.",
    nochmal: "دووبارە",
    deineReaktion: "کاردانەوەت",
    ergDein: "دووری وەستانت",
    ergDeinSub: "بە کاردانەوەی ئێستات",
    ergStrasse: "لەسەر ڕێگا",
    ergStrasseSub: "یاسای ئاسانکراوی خوێندنگەی شۆفێری",
    ergNass: "لە ڕێگای تەڕدا",
    legReaktion: "دووری کاردانەوە",
    legBrems: "دووری برێک",
    hinweisStrasse: "لەسەر ڕێگا نزیکەی یەک چرکە دەبات تا بەڕاستی برێک دەکەیت. لەبەر ئەوە دووری وەستانی ڕاستەقینە لە یارییەکە درێژترە.",
    neuerRekord: "باشترین کاتی نوێ!",
    platz: "پلەی {n} لە {m}",
    nichtGespeichert: "ئەنجامەکەت پاشەکەوت نەکرا. دەتوانیت هەر یاری بکەیت.",
    uebung: "دۆخی ڕاهێنان: ئەنجامەکەت پاشەکەوت ناکرێت.",
    rankingTitel: "لیستی باشترینەکان",
    rankingLeer: "هێشتا کەس لە لیستەکەدا نییە. تۆ یەکەم بە!",
    rankingFehler: "لیستەکە بار نەکرا.",
    du: "تۆ",
    laden: "بارکردن …",
    fehler: "سەرکەوتوو نەبوو. تکایە دواتر دووبارە هەوڵ بدەرەوە."
  },
  kmr: {
    titel: "Lîstik",
    intro: "Lîstikên biçûk li ser trafîkê. Xwe bi yên din re bipîve.",
    profilName: "Navê te di rêzbendiyê de",
    profilSichtbar: "Di rêzbendiyê de xuya ye",
    profilHinweis: "Yên din tenê navê te yê yekem û tîpek dibînin. Tu dikarî her dem xwe veşêrî.",
    profilAus: "Tu veşartî yî. Tenê tu demên xwe dibînî.",
    bestzeit: "Dema te ya herî baş",
    nochNicht: "Hê nehatiye lîstin",
    spielen: "Bilîze",
    ampelName: "Çiraya trafîkê û rêya frenê",
    ampelKurz: "Gava çira vemirin fren bike û bibîne ka erebeya te çiqas diçe.",
    tempoName: "Sprinta Lezê",
    tempoKurz: "Zû bitikîne, di bin tabloyê de bimîne – û di sprinta dawî de her tiştî bide.",
    tempoBestwert: "Leza te ya herî bilind",
    tempoNeu: "Leza herî bilind a nû!",
    tempoBereit: "Li «Dest pê bike» bitikîne. Paşê heta dikarî li ser qada mezin bitikîne: her tikandin te zûtir dike. Di bin leza li ser tabloyê de bimîne!",
    tempoGleich: "Amade be …",
    tempoTippen: "BITIKÎNE!",
    tempoErlaubt: "Destûrdayî: {v} km/h",
    tempoNaechstes: "Nêzîk: {v} km/h",
    tempoNaechstesFrei: "Nêzîk: bê sînor",
    tempoSpurt: "SPRINTA DAWÎ! Bi qasî ku dikarî zû!",
    tempoBlitzer: "Radar! Te pir zû dajot. Demekê girtî ye, lez ket.",
    tempoErgTipps: "Tikandinên sprinta dawî",
    tempoErgBlitzer: "Radar",
    tempoHinweis: "Di jiyana rastîn de li ser otobana Almanyayê leza pêşniyarkirî 130 km/h e. Li ku tabloyek leza herî zêde nîşan bide, divê her gav pê bipêwî.",
    tempoZ274: "Nîşana trafîkê 274: leza herî zêde {v} km/h",
    tempoZ282: "Nîşana trafîkê 282: dawiya hemû sînorkirinên rêyê",
    vorschauMarke: "Pêşdîtin",
    speed: "Lez",
    start: "Dest pê bike",
    bremsen: "FREN",
    bereit: "Li «Dest pê bike» bitikîne. Gava hemû çira vemirin, bi leza herî zêde fren bike.",
    warte: "Li bendê be … zû nebe!",
    jetzt: "NIHA!",
    fehlstart: "Destpêka şaş! Te beriya vemirandina çiran fren kir.",
    zuLangsam: "Pir hêdî. Te di wextê xwe de fren nekir.",
    nochmal: "Dîsa",
    deineReaktion: "Reaksiyona te",
    ergDein: "Rêya sekinîna te",
    ergDeinSub: "bi reaksiyona te ya niha",
    ergStrasse: "Li ser rê",
    ergStrasseSub: "Qaîdeya sade ya dibistana ajotinê",
    ergNass: "Li ser rêya şil",
    legReaktion: "Rêya reaksiyonê",
    legBrems: "Rêya frenê",
    hinweisStrasse: "Li ser rê nêzîkî saniyeyekê derbas dibe heta ku tu bi rastî fren dikî. Ji ber vê yekê rêya sekinîna rast ji ya di lîstikê dirêjtir e.",
    neuerRekord: "Dema herî baş a nû!",
    platz: "Cihê {n} ji {m}",
    nichtGespeichert: "Encama te nehat tomarkirin. Tu dîsa jî dikarî bidomînî.",
    uebung: "Moda pratîkê: Encama te nayê tomarkirin.",
    rankingTitel: "Lîsteya çêtirîn",
    rankingLeer: "Hê tu kes di lîsteyê de nîne. Bibe yê yekem!",
    rankingFehler: "Lîste nehat barkirin.",
    du: "Tu",
    laden: "Tê barkirin …",
    fehler: "Nebû. Ji kerema xwe paşê dîsa biceribîne."
  },
  hi: {
    titel: "खेल",
    intro: "ट्रैफ़िक पर छोटे खेल। दूसरों से अपनी तुलना कीजिए।",
    profilName: "रैंकिंग में आपका नाम",
    profilSichtbar: "रैंकिंग में दिखाई दें",
    profilHinweis: "दूसरों को सिर्फ़ आपका पहला नाम और एक अक्षर दिखता है। आप कभी भी खुद को छिपा सकते हैं।",
    profilAus: "आप छिपे हुए हैं। आपके समय सिर्फ़ आप देखते हैं।",
    bestzeit: "आपका सबसे अच्छा समय",
    nochNicht: "अभी तक नहीं खेला",
    spielen: "खेलिए",
    ampelName: "ट्रैफ़िक लाइट और ब्रेक की दूरी",
    ampelKurz: "लाइटें बुझते ही ब्रेक लगाइए और देखिए आपकी कार कितना आगे जाती है।",
    tempoName: "स्पीड स्प्रिंट",
    tempoKurz: "तेज़ी से टैप कीजिए, साइन से नीचे रहिए – और आख़िरी स्प्रिंट में पूरा ज़ोर लगाइए।",
    tempoBestwert: "आपकी सबसे ऊँची गति",
    tempoNeu: "नई सबसे ऊँची गति!",
    tempoBereit: "शुरू पर टैप कीजिए। फिर बड़े हिस्से पर जितनी बार हो सके टैप कीजिए: हर टैप आपको तेज़ करता है। साइन पर लिखी गति से नीचे रहिए!",
    tempoGleich: "तैयार हो जाइए …",
    tempoTippen: "टैप कीजिए!",
    tempoErlaubt: "अनुमति: {v} km/h",
    tempoNaechstes: "अगला: {v} km/h",
    tempoNaechstesFrei: "अगला: कोई सीमा नहीं",
    tempoSpurt: "आख़िरी स्प्रिंट! जितना तेज़ हो सके!",
    tempoBlitzer: "स्पीड कैमरा! आप बहुत तेज़ थे। कुछ देर के लिए रुका हुआ, गति गिर गई।",
    tempoErgTipps: "आख़िरी स्प्रिंट में टैप",
    tempoErgBlitzer: "स्पीड कैमरा",
    tempoHinweis: "असली ज़िंदगी में जर्मन ऑटोबान पर सुझाई गई गति 130 km/h है। जहाँ साइन अधिकतम गति दिखाए, वहाँ आपको हमेशा उसका पालन करना होता है।",
    tempoZ274: "यातायात चिह्न 274: अधिकतम गति {v} km/h",
    tempoZ282: "यातायात चिह्न 282: मार्ग की सभी पाबंदियों का अंत",
    vorschauMarke: "पूर्वावलोकन",
    speed: "गति",
    start: "शुरू",
    bremsen: "ब्रेक",
    bereit: "शुरू पर टैप कीजिए। जब सारी लाइटें बुझ जाएँ, जितना तेज़ हो सके ब्रेक लगाइए।",
    warte: "रुकिए … बहुत जल्दी नहीं!",
    jetzt: "अभी!",
    fehlstart: "ग़लत शुरुआत! लाइटें बुझने से पहले आपने ब्रेक लगा दिया।",
    zuLangsam: "बहुत धीमे। आपने समय पर ब्रेक नहीं लगाया।",
    nochmal: "फिर से",
    deineReaktion: "आपकी प्रतिक्रिया",
    ergDein: "आपकी रुकने की दूरी",
    ergDeinSub: "अभी की आपकी प्रतिक्रिया के साथ",
    ergStrasse: "सड़क पर",
    ergStrasseSub: "ड्राइविंग स्कूल का मोटा नियम",
    ergNass: "गीली सड़क पर",
    legReaktion: "प्रतिक्रिया की दूरी",
    legBrems: "ब्रेक की दूरी",
    hinweisStrasse: "सड़क पर असल में ब्रेक लगने तक लगभग 1 सेकंड बीत जाता है। इसीलिए असली रुकने की दूरी खेल से लंबी होती है।",
    neuerRekord: "नया सबसे अच्छा समय!",
    platz: "{m} में से {n}वाँ स्थान",
    nichtGespeichert: "आपका नतीजा सेव नहीं हो सका। आप फिर भी खेलते रह सकते हैं।",
    uebung: "अभ्यास मोड: आपका नतीजा सेव नहीं होगा।",
    rankingTitel: "रैंकिंग",
    rankingLeer: "रैंकिंग में अभी कोई नहीं है। पहले बनिए!",
    rankingFehler: "रैंकिंग लोड नहीं हो सकी।",
    du: "आप",
    laden: "लोड हो रहा है …",
    fehler: "यह नहीं हो पाया। कृपया बाद में फिर कोशिश कीजिए।"
  },
  ur: {
    titel: "کھیل",
    intro: "ٹریفک پر چھوٹے کھیل۔ دوسروں سے اپنا مقابلہ کریں۔",
    profilName: "رینکنگ میں آپ کا نام",
    profilSichtbar: "رینکنگ میں نظر آئیں",
    profilHinweis: "دوسروں کو صرف آپ کا پہلا نام اور ایک حرف نظر آتا ہے۔ آپ جب چاہیں خود کو چھپا سکتے ہیں۔",
    profilAus: "آپ چھپے ہوئے ہیں۔ آپ کے وقت صرف آپ دیکھتے ہیں۔",
    bestzeit: "آپ کا بہترین وقت",
    nochNicht: "ابھی تک نہیں کھیلا",
    spielen: "کھیلیں",
    ampelName: "ٹریفک سگنل اور بریک کا فاصلہ",
    ampelKurz: "لائٹیں بجھتے ہی بریک لگائیں اور دیکھیں آپ کی گاڑی کتنا آگے جاتی ہے۔",
    tempoName: "رفتار کی دوڑ",
    tempoKurz: "تیزی سے ٹیپ کریں، نشان سے نیچے رہیں – اور آخری دوڑ میں پورا زور لگائیں۔",
    tempoBestwert: "آپ کی سب سے زیادہ رفتار",
    tempoNeu: "نئی سب سے زیادہ رفتار!",
    tempoBereit: "شروع پر ٹیپ کریں۔ پھر بڑے حصے پر جتنی بار ہو سکے ٹیپ کریں: ہر ٹیپ آپ کو تیز کرتا ہے۔ نشان پر لکھی رفتار سے نیچے رہیں!",
    tempoGleich: "تیار ہو جائیں …",
    tempoTippen: "ٹیپ کریں!",
    tempoErlaubt: "اجازت: {v} km/h",
    tempoNaechstes: "آگے: {v} km/h",
    tempoNaechstesFrei: "آگے: کوئی حد نہیں",
    tempoSpurt: "آخری دوڑ! جتنا تیز ہو سکے!",
    tempoBlitzer: "اسپیڈ کیمرا! آپ بہت تیز تھے۔ کچھ دیر کے لیے بند، رفتار گر گئی۔",
    tempoErgTipps: "آخری دوڑ میں ٹیپ",
    tempoErgBlitzer: "اسپیڈ کیمرے",
    tempoHinweis: "اصل زندگی میں جرمن آٹوبان پر تجویز کردہ رفتار 130 km/h ہے۔ جہاں نشان زیادہ سے زیادہ رفتار دکھائے، وہاں آپ کو ہمیشہ اس کی پابندی کرنی ہوتی ہے۔",
    tempoZ274: "ٹریفک نشان 274: زیادہ سے زیادہ رفتار {v} km/h",
    tempoZ282: "ٹریفک نشان 282: راستے کی تمام پابندیوں کا اختتام",
    vorschauMarke: "پیش منظر",
    speed: "رفتار",
    start: "شروع",
    bremsen: "بریک",
    bereit: "شروع پر ٹیپ کریں۔ جب ساری لائٹیں بجھ جائیں تو جتنی تیزی سے ہو سکے بریک لگائیں۔",
    warte: "رکیں … بہت جلدی نہیں!",
    jetzt: "ابھی!",
    fehlstart: "غلط آغاز! لائٹیں بجھنے سے پہلے آپ نے بریک لگا دیا۔",
    zuLangsam: "بہت آہستہ۔ آپ نے وقت پر بریک نہیں لگایا۔",
    nochmal: "دوبارہ",
    deineReaktion: "آپ کا ردعمل",
    ergDein: "آپ کے رکنے کا فاصلہ",
    ergDeinSub: "ابھی کے آپ کے ردعمل کے ساتھ",
    ergStrasse: "سڑک پر",
    ergStrasseSub: "ڈرائیونگ اسکول کا موٹا اصول",
    ergNass: "گیلی سڑک پر",
    legReaktion: "ردعمل کا فاصلہ",
    legBrems: "بریک کا فاصلہ",
    hinweisStrasse: "سڑک پر حقیقت میں بریک لگنے تک تقریباً 1 سیکنڈ گزر جاتا ہے۔ اسی لیے اصل رکنے کا فاصلہ کھیل سے لمبا ہوتا ہے۔",
    neuerRekord: "نیا بہترین وقت!",
    platz: "{m} میں سے {n} واں مقام",
    nichtGespeichert: "آپ کا نتیجہ محفوظ نہیں ہو سکا۔ آپ پھر بھی کھیلتے رہ سکتے ہیں۔",
    uebung: "مشق موڈ: آپ کا نتیجہ محفوظ نہیں ہوگا۔",
    rankingTitel: "رینکنگ",
    rankingLeer: "رینکنگ میں ابھی کوئی نہیں ہے۔ پہلے بنیں!",
    rankingFehler: "رینکنگ لوڈ نہیں ہو سکی۔",
    du: "آپ",
    laden: "لوڈ ہو رہا ہے …",
    fehler: "یہ نہیں ہو سکا۔ براہِ کرم بعد میں دوبارہ کوشش کریں۔"
  },
  vi: {
    titel: "Trò chơi",
    intro: "Các trò chơi nhỏ về giao thông. Hãy so tài với những người khác.",
    profilName: "Tên của bạn trên bảng xếp hạng",
    profilSichtbar: "Hiển thị trên bảng xếp hạng",
    profilHinweis: "Người khác chỉ thấy tên và một chữ cái của bạn. Bạn có thể ẩn đi bất cứ lúc nào.",
    profilAus: "Bạn đang bị ẩn. Chỉ bạn thấy thời gian của mình.",
    bestzeit: "Thời gian tốt nhất của bạn",
    nochNicht: "Chưa chơi",
    spielen: "Chơi",
    ampelName: "Đèn giao thông và quãng đường phanh",
    ampelKurz: "Phanh ngay khi đèn tắt và xem xe của bạn còn lăn bao xa.",
    tempoName: "Chạy nước rút tốc độ",
    tempoKurz: "Chạm thật nhanh, giữ dưới biển báo – và dốc hết sức ở chặng nước rút.",
    tempoBestwert: "Tốc độ cao nhất của bạn",
    tempoNeu: "Tốc độ cao nhất mới!",
    tempoBereit: "Chạm vào Bắt đầu. Sau đó chạm vào vùng lớn càng nhiều càng tốt: mỗi lần chạm giúp bạn nhanh hơn. Hãy giữ dưới tốc độ trên biển báo!",
    tempoGleich: "Chuẩn bị nhé …",
    tempoTippen: "CHẠM!",
    tempoErlaubt: "Cho phép: {v} km/h",
    tempoNaechstes: "Sắp tới: {v} km/h",
    tempoNaechstesFrei: "Sắp tới: không giới hạn",
    tempoSpurt: "NƯỚC RÚT CUỐI! Nhanh nhất có thể!",
    tempoBlitzer: "Camera tốc độ! Bạn chạy quá nhanh. Bị khóa một lúc, tốc độ mất hết.",
    tempoErgTipps: "Số lần chạm ở nước rút",
    tempoErgBlitzer: "Camera tốc độ",
    tempoHinweis: "Ngoài đời thật, tốc độ khuyến nghị trên đường cao tốc Đức là 130 km/h. Nơi biển báo cho thấy tốc độ tối đa, bạn luôn phải tuân thủ.",
    tempoZ274: "Biển báo 274: tốc độ tối đa {v} km/h",
    tempoZ282: "Biển báo 282: hết mọi hạn chế trên đoạn đường",
    vorschauMarke: "Xem trước",
    speed: "Tốc độ",
    start: "Bắt đầu",
    bremsen: "PHANH",
    bereit: "Chạm vào Bắt đầu. Khi tất cả đèn tắt, hãy phanh nhanh nhất có thể.",
    warte: "Chờ … đừng quá sớm!",
    jetzt: "BÂY GIỜ!",
    fehlstart: "Xuất phát sớm! Bạn đã phanh trước khi đèn tắt.",
    zuLangsam: "Quá chậm. Bạn đã không phanh kịp lúc.",
    nochmal: "Chơi lại",
    deineReaktion: "Phản xạ của bạn",
    ergDein: "Quãng đường dừng của bạn",
    ergDeinSub: "với phản xạ vừa rồi của bạn",
    ergStrasse: "Trên đường",
    ergStrasseSub: "Công thức nhanh của trường lái",
    ergNass: "Khi đường ướt",
    legReaktion: "Quãng đường phản xạ",
    legBrems: "Quãng đường phanh",
    hinweisStrasse: "Trên đường, phải mất khoảng 1 giây trước khi bạn thật sự phanh. Vì vậy quãng đường dừng thực tế dài hơn trong trò chơi.",
    neuerRekord: "Thời gian tốt nhất mới!",
    platz: "Hạng {n} trên {m}",
    nichtGespeichert: "Không thể lưu kết quả của bạn. Bạn vẫn có thể tiếp tục chơi.",
    uebung: "Chế độ luyện tập: kết quả của bạn không được lưu.",
    rankingTitel: "Bảng xếp hạng",
    rankingLeer: "Chưa có ai trên bảng xếp hạng. Hãy là người đầu tiên!",
    rankingFehler: "Không thể tải bảng xếp hạng.",
    du: "Bạn",
    laden: "Đang tải …",
    fehler: "Không thành công. Vui lòng thử lại sau."
  },
  rif: {
    titel: "Lɛab",
    intro: "Lɛab imeẓẓyanen ɣef ṭṭeṛafik. Qis iman-nnec d wiyaḍ.",
    profilName: "Isem-nnec di ttartib",
    profilSichtbar: "Ibanen di ttartib",
    profilHinweis: "Wiyaḍ ẓṛan kan isem-nnec amezwaru d yiwen n usekkil. Tzemṛeḍ ad teffṛeḍ iman-nnec mala txseḍ.",
    profilAus: "Teffṛeḍ iman-nnec. Lweqt-nnec ur t-ẓṛan ara ɣir kečč.",
    bestzeit: "Lweqt-nnec yelhan",
    nochNicht: "Mazal ur tlɛabeḍ ara",
    spielen: "Lɛeb",
    ampelName: "Lfiṛu d ubrid n lfrinu",
    ampelKurz: "Fren ticki ttexsin lfiṛu u ẓeṛ achal i ggar ṭṭumubin-nnec.",
    tempoName: "Sprint n sseṛɛa",
    tempoKurz: "Ṭṭef s uzzel, qqim ddaw n lɛalama – u ssiwel kulši deg usprint n taggara.",
    tempoBestwert: "Sseṛɛa-nnec tameqqrant",
    tempoNeu: "Sseṛɛa tamaynut tameqqrant!",
    tempoBereit: "Ṭṭef ɣer «Bdu». Sakin ṭṭef ɣer tizi tameqqrant am ɣer tzemred: yal aṭṭef ak-iselhu s uzzel. Qqim ddaw n sseṛɛa n lɛalama!",
    tempoGleich: "Heyyi iman-nnec …",
    tempoTippen: "ṬṬEF!",
    tempoErlaubt: "Yettuɛṭa: {v} km/h",
    tempoNaechstes: "Qrib: {v} km/h",
    tempoNaechstesFrei: "Qrib: war talast",
    tempoSpurt: "ASPRINT N TAGGARA! S uzzel am ɣer tzemred!",
    tempoBlitzer: "Radar! Teddiḍ s uzzel aṭas. Yettwaɛṭel kra, sseṛɛa ttwaxṣer.",
    tempoErgTipps: "Iṭeffen deg usprint n taggara",
    tempoErgBlitzer: "Radar",
    tempoHinweis: "Deg tudert tideț, sseṛɛa i yettwasumer deg otoṛut n Lalman d 130 km/h. Anda ara d-banen lɛalama n sseṛɛa tameqqrant, yessefk ad tt-ḥettmeḍ yal tikkelt.",
    tempoZ274: "Lɛalama 274: sseṛɛa tameqqrant {v} km/h",
    tempoZ282: "Lɛalama 282: taggara n meṛṛa tuḥebbasin n webrid",
    vorschauMarke: "Taskant",
    speed: "Sseṛɛa",
    start: "Bdu",
    bremsen: "LFRINU",
    bereit: "Ṭṭef ɣer «Bdu». Ticki ttexsin kulši lfiṛu, fren s uzzel iwumi tzemṛeḍ.",
    warte: "Ṣber … ɛad!",
    jetzt: "Tura!",
    fehlstart: "Tebdiḍ zik! Tfrenḍ uqbel ma ttexsin lfiṛu.",
    zuLangsam: "Tɛeṭleḍ aṭas. Ur tfrenḍ ara deg lweqt.",
    nochmal: "Daɣen",
    deineReaktion: "Areddi-nnec",
    ergDein: "Abrid n lwuqquf-nnec",
    ergDeinSub: "s ureddi-nnec n tura",
    ergStrasse: "Deg ubrid",
    ergStrasseSub: "Qaɛida tabsiṭt n lmedrasa n tasuqt",
    ergNass: "Ɣef ubrid iṛṭuben",
    legReaktion: "Ubrid n ureddi",
    legBrems: "Ubrid n lfrinu",
    hinweisStrasse: "Deg ubrid yeɛdda zdat 1 n tasint ar ma tfrenḍ s tidett. Aɣilif n waya, ubrid n lwuqquf n tidett iɣezzif ɣef wid n lɛab.",
    neuerRekord: "Lweqt amaynu yelhan!",
    platz: "Amkan {n} seg {m}",
    nichtGespeichert: "Agmuḍ-nnec ur yezmir ara ad yettwaḥrez. Tzemṛeḍ ad tkemmleḍ lɛab.",
    uebung: "Askar n ussenfaṛ: agmuḍ-nnec ur yettwaḥrez ara.",
    rankingTitel: "Ttartib",
    rankingLeer: "Ur llin ara yiwen di ttartib mazal. Ili d amezwaru!",
    rankingFehler: "Ttartib ur yezmir ara ad yettwarr.",
    du: "Kečč",
    laden: "Ittwarra …",
    fehler: "Ur yelli ara. Ɛawed tteɛṭel ticki."
  },
  fa: {
    titel: "بازی‌ها",
    intro: "بازی‌های کوچک درباره‌ی ترافیک. خودتان را با دیگران بسنجید.",
    profilName: "نام شما در رتبه‌بندی",
    profilSichtbar: "نمایش در رتبه‌بندی",
    profilHinweis: "دیگران فقط نام کوچک و یک حرف از شما را می‌بینند. هر زمان می‌توانید خودتان را پنهان کنید.",
    profilAus: "شما پنهان هستید. زمان‌های شما را فقط خودتان می‌بینید.",
    bestzeit: "بهترین زمان شما",
    nochNicht: "هنوز بازی نشده",
    spielen: "بازی کنید",
    ampelName: "چراغ راهنمایی و فاصله ترمز",
    ampelKurz: "به محض خاموش شدن چراغ‌ها ترمز کنید و ببینید خودرو شما چقدر جلو می‌رود.",
    tempoName: "اسپرینت سرعت",
    tempoKurz: "سریع بزنید، زیر تابلو بمانید – و در اسپرینت پایانی تمام توانتان را بگذارید.",
    tempoBestwert: "بیشترین سرعت شما",
    tempoNeu: "بیشترین سرعت جدید!",
    tempoBereit: "روی شروع بزنید. سپس تا می‌توانید روی بخش بزرگ بزنید: هر ضربه شما را سریع‌تر می‌کند. زیر سرعت نوشته‌شده روی تابلو بمانید!",
    tempoGleich: "آماده شوید …",
    tempoTippen: "بزنید!",
    tempoErlaubt: "مجاز: {v} km/h",
    tempoNaechstes: "به‌زودی: {v} km/h",
    tempoNaechstesFrei: "به‌زودی: بدون محدودیت",
    tempoSpurt: "اسپرینت پایانی! هرچه سریع‌تر!",
    tempoBlitzer: "دوربین سرعت! بیش از حد سریع بودید. لحظه‌ای قفل شد و سرعت افتاد.",
    tempoErgTipps: "ضربه‌ها در اسپرینت پایانی",
    tempoErgBlitzer: "دوربین سرعت",
    tempoHinweis: "در زندگی واقعی، سرعت توصیه‌شده در اتوبان آلمان 130 km/h است. هر جا تابلو حداکثر سرعت را نشان دهد، همیشه باید رعایتش کنید.",
    tempoZ274: "علامت راهنمایی 274: حداکثر سرعت {v} km/h",
    tempoZ282: "علامت راهنمایی 282: پایان همه محدودیت‌های مسیر",
    vorschauMarke: "پیش‌نمایش",
    speed: "سرعت",
    start: "شروع",
    bremsen: "ترمز",
    bereit: "روی شروع بزنید. وقتی همه چراغ‌ها خاموش شد، هرچه سریع‌تر ترمز کنید.",
    warte: "صبر کنید … زود نه!",
    jetzt: "حالا!",
    fehlstart: "شروع زودهنگام! پیش از خاموش شدن چراغ‌ها ترمز کردید.",
    zuLangsam: "خیلی کند. به‌موقع ترمز نکردید.",
    nochmal: "دوباره",
    deineReaktion: "واکنش شما",
    ergDein: "فاصله توقف شما",
    ergDeinSub: "با واکنش همین الان شما",
    ergStrasse: "در جاده",
    ergStrasseSub: "قاعده سرانگشتی آموزشگاه رانندگی",
    ergNass: "روی جاده خیس",
    legReaktion: "فاصله واکنش",
    legBrems: "فاصله ترمز",
    hinweisStrasse: "در جاده حدود 1 ثانیه طول می‌کشد تا واقعاً ترمز کنید. به همین دلیل فاصله توقف واقعی بلندتر از بازی است.",
    neuerRekord: "بهترین زمان جدید!",
    platz: "رتبه {n} از {m}",
    nichtGespeichert: "نتیجه شما ذخیره نشد. باز هم می‌توانید ادامه دهید.",
    uebung: "حالت تمرین: نتیجه شما ذخیره نمی‌شود.",
    rankingTitel: "رتبه‌بندی",
    rankingLeer: "هنوز کسی در رتبه‌بندی نیست. اولین نفر باشید!",
    rankingFehler: "رتبه‌بندی بارگذاری نشد.",
    du: "شما",
    laden: "در حال بارگذاری …",
    fehler: "انجام نشد. لطفاً بعداً دوباره تلاش کنید."
  },
  ps: {
    titel: "لوبې",
    intro: "د ترافیکو په اړه وړې لوبې. ځان له نورو سره وسنجوئ.",
    profilName: "ستاسو نوم په درجه‌بندۍ کې",
    profilSichtbar: "په درجه‌بندۍ کې ښکاره",
    profilHinweis: "نور یوازې ستاسو لومړی نوم او یو توری وینې. تاسو هر وخت کولای شئ ځان پټ کړئ.",
    profilAus: "تاسو پټ یاست. ستاسو وختونه یوازې تاسو وینئ.",
    bestzeit: "ستاسو غوره وخت",
    nochNicht: "تر اوسه نه دی لوبول شوی",
    spielen: "لوبه وکړئ",
    ampelName: "ترافیکي څراغ او د بریک واټن",
    ampelKurz: "کله چې څراغونه مړه شي بریک ونیسئ او وګورئ چې ستاسو موټر څومره مخکې ځي.",
    tempoName: "د سرعت منډه",
    tempoKurz: "ګړندی کېکاږئ، د نښې لاندې پاتې شئ – او په وروستۍ منډه کې ټوله ځواک وکاروئ.",
    tempoBestwert: "ستاسو تر ټولو لوړ سرعت",
    tempoNeu: "نوی لوړ سرعت!",
    tempoBereit: "په پیل کېکاږئ. بیا په لویه برخه څومره چې کولای شئ کېکاږئ: هر ځل کېکاږل تاسو ګړندی کوي. د نښې پر سرعت لاندې پاتې شئ!",
    tempoGleich: "چمتو شئ …",
    tempoTippen: "کېکاږئ!",
    tempoErlaubt: "اجازه شوی: {v} km/h",
    tempoNaechstes: "ژر: {v} km/h",
    tempoNaechstesFrei: "ژر: پرته له حدودو",
    tempoSpurt: "وروستۍ منډه! څومره چې کېدای شي ګړندی!",
    tempoBlitzer: "د سرعت کیمره! تاسو ډېر ګړندي وئ. لږ وخت بند شو، سرعت ښکته شو.",
    tempoErgTipps: "په وروستۍ منډه کې کېکاږنې",
    tempoErgBlitzer: "د سرعت کیمرې",
    tempoHinweis: "په ریښتینې ژوندانه کې د جرمني په اتوبان کې وړاندیز شوی سرعت 130 km/h دی. چېرته چې نښه تر ټولو لوړ سرعت ښیي، تل باید ورته پام وکړئ.",
    tempoZ274: "د ترافیکي نښه 274: تر ټولو لوړ سرعت {v} km/h",
    tempoZ282: "د ترافیکي نښه 282: د لارې د ټولو بندیزونو پای",
    vorschauMarke: "مخکتنه",
    speed: "سرعت",
    start: "پیل",
    bremsen: "بریک",
    bereit: "په پیل کېکاږئ. کله چې ټول څراغونه مړه شي، څومره ژر چې کولای شئ بریک ونیسئ.",
    warte: "انتظار وکړئ … ډېر ژر نه!",
    jetzt: "اوس!",
    fehlstart: "غلط پیل! تاسو د څراغونو له مړېدو مخکې بریک ونیو.",
    zuLangsam: "ډېر ورو. تاسو په وخت بریک ونه نیو.",
    nochmal: "بیا",
    deineReaktion: "ستاسو غبرګون",
    ergDein: "ستاسو د درېدو واټن",
    ergDeinSub: "د همدا اوسني غبرګون سره",
    ergStrasse: "په سړک",
    ergStrasseSub: "د موټر چلولو ښوونځي ساده قاعده",
    ergNass: "په لنده سړک",
    legReaktion: "د غبرګون واټن",
    legBrems: "د بریک واټن",
    hinweisStrasse: "په سړک کې نږدې 1 ثانیه تېرېږي تر څو تاسو رښتیا بریک ونیسئ. له همدې امله اصلي د درېدو واټن له لوبې اوږد دی.",
    neuerRekord: "نوی غوره وخت!",
    platz: "{n} مقام له {m} څخه",
    nichtGespeichert: "ستاسو پایله خوندي نه شوه. تاسو بیا هم کولای شئ لوبه دوام ورکړئ.",
    uebung: "د تمرین حالت: ستاسو پایله خوندي نه کېږي.",
    rankingTitel: "درجه‌بندي",
    rankingLeer: "تر اوسه په لیست کې څوک نشته. لومړی کس اوسئ!",
    rankingFehler: "لیست پورته نه شو.",
    du: "تاسو",
    laden: "پورته کېږي …",
    fehler: "ونه شو. مهرباني وکړئ وروسته بیا هڅه وکړئ."
  },
  el: {
    titel: "Παιχνίδια",
    intro: "Μικρά παιχνίδια για την κυκλοφορία. Μετρήσου με τους άλλους.",
    profilName: "Το όνομά σου στην κατάταξη",
    profilSichtbar: "Ορατός στην κατάταξη",
    profilHinweis: "Οι άλλοι βλέπουν μόνο το όνομά σου και ένα γράμμα. Μπορείς να κρυφτείς όποτε θέλεις.",
    profilAus: "Είσαι κρυμμένος. Τους χρόνους σου τους βλέπεις μόνο εσύ.",
    bestzeit: "Ο καλύτερος χρόνος σου",
    nochNicht: "Δεν έχει παιχτεί ακόμα",
    spielen: "Παίξε",
    ampelName: "Φανάρι και απόσταση πέδησης",
    ampelKurz: "Φρέναρε μόλις σβήσουν τα φώτα και δες πόσο ακόμα προχωράει το αυτοκίνητό σου.",
    tempoName: "Σπριντ ταχύτητας",
    tempoKurz: "Πάτα γρήγορα, μείνε κάτω από την πινακίδα – και δώσε τα πάντα στον τελικό σπριντ.",
    tempoBestwert: "Η μέγιστη ταχύτητά σου",
    tempoNeu: "Νέα μέγιστη ταχύτητα!",
    tempoBereit: "Πάτα Εκκίνηση. Μετά πάτα τη μεγάλη επιφάνεια όσο πιο συχνά μπορείς: κάθε πάτημα σε κάνει πιο γρήγορο. Μείνε κάτω από την ταχύτητα της πινακίδας!",
    tempoGleich: "Ετοιμάσου …",
    tempoTippen: "ΠΑΤΑ!",
    tempoErlaubt: "Επιτρέπεται: {v} km/h",
    tempoNaechstes: "Σύντομα: {v} km/h",
    tempoNaechstesFrei: "Σύντομα: χωρίς όριο",
    tempoSpurt: "ΤΕΛΙΚΟ ΣΠΡΙΝΤ! Όσο πιο γρήγορα μπορείς!",
    tempoBlitzer: "Ραντάρ! Πήγαινες πολύ γρήγορα. Κλειδώθηκε για λίγο, η ταχύτητα έπεσε.",
    tempoErgTipps: "Πατήματα στο τελικό σπριντ",
    tempoErgBlitzer: "Ραντάρ",
    tempoHinweis: "Στην πραγματική ζωή, η συνιστώμενη ταχύτητα στον γερμανικό αυτοκινητόδρομο είναι 130 km/h. Όπου μια πινακίδα δείχνει μέγιστη ταχύτητα, πρέπει πάντα να την τηρείς.",
    tempoZ274: "Πινακίδα 274: μέγιστη ταχύτητα {v} km/h",
    tempoZ282: "Πινακίδα 282: τέλος όλων των περιορισμών διαδρομής",
    vorschauMarke: "Προεπισκόπηση",
    speed: "Ταχύτητα",
    start: "Εκκίνηση",
    bremsen: "ΦΡΕΝΟ",
    bereit: "Πάτα Εκκίνηση. Όταν σβήσουν όλα τα φώτα, φρέναρε όσο πιο γρήγορα μπορείς.",
    warte: "Περίμενε … όχι νωρίς!",
    jetzt: "ΤΩΡΑ!",
    fehlstart: "Εσφαλμένη εκκίνηση! Φρέναρες πριν σβήσουν τα φώτα.",
    zuLangsam: "Πολύ αργά. Δεν φρέναρες εγκαίρως.",
    nochmal: "Ξανά",
    deineReaktion: "Η αντίδρασή σου",
    ergDein: "Η απόσταση στάσης σου",
    ergDeinSub: "με την αντίδρασή σου τώρα",
    ergStrasse: "Στον δρόμο",
    ergStrasseSub: "Εμπειρικός κανόνας της σχολής οδηγών",
    ergNass: "Σε βρεγμένο δρόμο",
    legReaktion: "Απόσταση αντίδρασης",
    legBrems: "Απόσταση πέδησης",
    hinweisStrasse: "Στον δρόμο περνάει περίπου 1 δευτερόλεπτο μέχρι να φρενάρεις πραγματικά. Γι' αυτό η πραγματική απόσταση στάσης είναι μεγαλύτερη από ό,τι στο παιχνίδι.",
    neuerRekord: "Νέος καλύτερος χρόνος!",
    platz: "Θέση {n} από {m}",
    nichtGespeichert: "Το αποτέλεσμά σου δεν αποθηκεύτηκε. Μπορείς να συνεχίσεις να παίζεις.",
    uebung: "Λειτουργία εξάσκησης: το αποτέλεσμά σου δεν αποθηκεύεται.",
    rankingTitel: "Κατάταξη",
    rankingLeer: "Δεν υπάρχει ακόμα κανείς στην κατάταξη. Γίνε ο πρώτος!",
    rankingFehler: "Η κατάταξη δεν φορτώθηκε.",
    du: "Εσύ",
    laden: "Φόρτωση …",
    fehler: "Δεν πέτυχε. Δοκίμασε ξανά αργότερα."
  },
  am: {
    titel: "ጨዋታዎች",
    intro: "ስለ ትራፊክ ትናንሽ ጨዋታዎች። ራስዎን ከሌሎች ጋር ይለኩ።",
    profilName: "በደረጃ ሰንጠረዥ ውስጥ ስምዎ",
    profilSichtbar: "በደረጃ ሰንጠረዥ ውስጥ ይታይ",
    profilHinweis: "ሌሎች የመጀመሪያ ስምዎንና አንድ ፊደል ብቻ ያያሉ። በማንኛውም ጊዜ ራስዎን መደበቅ ይችላሉ።",
    profilAus: "ተደብቀዋል። ጊዜዎን እርስዎ ብቻ ያያሉ።",
    bestzeit: "ምርጥ ጊዜዎ",
    nochNicht: "እስካሁን አልተጫወተም",
    spielen: "ይጫወቱ",
    ampelName: "የትራፊክ መብራትና የፍሬን ርቀት",
    ampelKurz: "መብራቶቹ እንደጠፉ ፍሬን ይያዙና መኪናዎ ምን ያህል እንደሚሄድ ይመልከቱ።",
    tempoName: "የፍጥነት ሩጫ",
    tempoKurz: "በፍጥነት ንኩ፣ ከምልክቱ በታች ይቆዩ – በመጨረሻው ሩጫም ሁሉንም ይስጡ።",
    tempoBestwert: "ከፍተኛ ፍጥነትዎ",
    tempoNeu: "አዲስ ከፍተኛ ፍጥነት!",
    tempoBereit: "ጀምርን ይንኩ። ከዚያ ትልቁን ቦታ በተቻለ መጠን ደጋግመው ይንኩ፦ እያንዳንዱ ንክኪ ፈጣን ያደርግዎታል። በምልክቱ ላይ ካለው ፍጥነት በታች ይቆዩ!",
    tempoGleich: "ይዘጋጁ …",
    tempoTippen: "ንኩ!",
    tempoErlaubt: "የተፈቀደ፦ {v} km/h",
    tempoNaechstes: "በቅርቡ፦ {v} km/h",
    tempoNaechstesFrei: "በቅርቡ፦ ገደብ የለም",
    tempoSpurt: "የመጨረሻ ሩጫ! በተቻለ ፍጥነት!",
    tempoBlitzer: "የፍጥነት ካሜራ! በጣም ፈጥነው ነበር። ለአፍታ ተቆልፏል፣ ፍጥነትዎ ወርዷል።",
    tempoErgTipps: "በመጨረሻው ሩጫ ውስጥ ንክኪዎች",
    tempoErgBlitzer: "የፍጥነት ካሜራዎች",
    tempoHinweis: "በእውነተኛ ሕይወት በጀርመን አውቶባን ላይ የሚመከረው ፍጥነት 130 km/h ነው። ምልክት ከፍተኛ ፍጥነት ባሳየበት ቦታ ሁልጊዜ ሊከተሉት ይገባል።",
    tempoZ274: "የትራፊክ ምልክት 274፦ ከፍተኛ ፍጥነት {v} km/h",
    tempoZ282: "የትራፊክ ምልክት 282፦ የሁሉም የመንገድ ገደቦች መጨረሻ",
    vorschauMarke: "ቅድመ እይታ",
    speed: "ፍጥነት",
    start: "ጀምር",
    bremsen: "ፍሬን",
    bereit: "ጀምርን ይንኩ። ሁሉም መብራቶች ሲጠፉ በተቻለ ፍጥነት ፍሬን ይያዙ።",
    warte: "ይጠብቁ … በጣም ቶሎ አይሁን!",
    jetzt: "አሁን!",
    fehlstart: "የተሳሳተ ጅምር! መብራቶቹ ሳይጠፉ ፍሬን ያዙ።",
    zuLangsam: "በጣም ቀርፋፋ። በጊዜ ፍሬን አልያዙም።",
    nochmal: "እንደገና",
    deineReaktion: "ምላሽዎ",
    ergDein: "የማቆሚያ ርቀትዎ",
    ergDeinSub: "ከአሁኑ ምላሽዎ ጋር",
    ergStrasse: "በመንገድ ላይ",
    ergStrasseSub: "የመንዳት ትምህርት ቤት ግምታዊ ህግ",
    ergNass: "እርጥብ መንገድ ላይ",
    legReaktion: "የምላሽ ርቀት",
    legBrems: "የፍሬን ርቀት",
    hinweisStrasse: "በመንገድ ላይ በእውነት ፍሬን እስኪይዙ ድረስ ወደ 1 ሰከንድ ያህል ያልፋል። ስለዚህ እውነተኛው የማቆሚያ ርቀት ከጨዋታው ይረዝማል።",
    neuerRekord: "አዲስ ምርጥ ጊዜ!",
    platz: "ከ{m} {n}ኛ ደረጃ",
    nichtGespeichert: "ውጤትዎ ሊቀመጥ አልቻለም። ሆኖም መጫወት መቀጠል ይችላሉ።",
    uebung: "የልምምድ ሁነታ፡ ውጤትዎ አይቀመጥም።",
    rankingTitel: "የደረጃ ሰንጠረዥ",
    rankingLeer: "በሰንጠረዡ ውስጥ እስካሁን ማንም የለም። የመጀመሪያው ይሁኑ!",
    rankingFehler: "ሰንጠረዡ ሊጫን አልቻለም።",
    du: "እርስዎ",
    laden: "በመጫን ላይ …",
    fehler: "አልተሳካም። እባክዎ ቆይተው እንደገና ይሞክሩ።"
  },
  ti: {
    titel: "ጸወታታት",
    intro: "ብዛዕባ ትራፊክ ንኣሽቱ ጸወታታት። ባዕልኹም ምስ ካልኦት ተመዛዘኑ።",
    profilName: "ስምኩም ኣብ ደረጃ ዝርዝር",
    profilSichtbar: "ኣብ ደረጃ ዝርዝር ይርአ",
    profilHinweis: "ካልኦት ቀዳማይ ስምኩምን ሓደ ፊደልን ጥራሕ ይርእዩ። ኣብ ዝኾነ እዋን ባዕልኹም ክትሓብኡ ትኽእሉ ኢኹም።",
    profilAus: "ተሓቢእኩም ኣለኹም። ግዜኹም ንስኹም ጥራሕ ኢኹም እትርእዩ።",
    bestzeit: "ዝበለጸ ግዜኹም",
    nochNicht: "ገና ኣይተጻወተን",
    spielen: "ተጻወቱ",
    ampelName: "መብራህቲ ትራፊክን ርሕቀት ፍረኖን",
    ampelKurz: "መብራህቲ ምስ ጠፍኣ ፍረኖ ሓዙ፣ መኪናኹም ክሳብ ክንደይ ከም እትከይድ ርኣዩ።",
    tempoName: "ናይ ቅልጡፍነት ጉያ",
    tempoKurz: "ብቕልጡፍ ንኩሱ፣ ኣብ ትሕቲ ምልክት ኩኑ – ኣብ መወዳእታ ጉያ ድማ ኩሉ ሃቡ።",
    tempoBestwert: "ዝለዓለ ቅልጡፍነትኩም",
    tempoNeu: "ሓድሽ ዝለዓለ ቅልጡፍነት!",
    tempoBereit: "ኣብ ጀምር ንኩሱ። ድሕሪኡ ነቲ ዓቢ ቦታ ክሳብ ዝከኣል ብተደጋጋሚ ንኩሱ፦ ነፍሲ ወከፍ ንክታት ቀልጢፍኩም ይገብረኩም። ካብቲ ኣብ ምልክት ዘሎ ቅልጡፍነት ትሕቲ ኩኑ!",
    tempoGleich: "ተዳሎዉ …",
    tempoTippen: "ንኩሱ!",
    tempoErlaubt: "ዝተፈቐደ፦ {v} km/h",
    tempoNaechstes: "ቀልጢፉ፦ {v} km/h",
    tempoNaechstesFrei: "ቀልጢፉ፦ ገደብ የለን",
    tempoSpurt: "መወዳእታ ጉያ! ክሳብ ዝከኣል ቀልጢፍኩም!",
    tempoBlitzer: "ካሜራ ቅልጡፍነት! ኣዝዩ ቀልጢፍኩም ኔርኩም። ንሒደት እዋን ተዓጽዩ፣ ቅልጡፍነት ወሪዱ።",
    tempoErgTipps: "ኣብ መወዳእታ ጉያ ንክታታት",
    tempoErgBlitzer: "ካሜራታት ቅልጡፍነት",
    tempoHinweis: "ኣብ ሓቀኛ ህይወት ኣብ ናይ ጀርመን ኣውቶባን እተመሓላለፈ ቅልጡፍነት 130 km/h እዩ። ምልክት ዝለዓለ ቅልጡፍነት ዘርእየሉ ቦታ ሁሌ ክትሕልውዎ ኣለኩም።",
    tempoZ274: "ናይ ትራፊክ ምልክት 274፦ ዝለዓለ ቅልጡፍነት {v} km/h",
    tempoZ282: "ናይ ትራፊክ ምልክት 282፦ መወዳእታ ኩሉ ናይ መገዲ ገደባት",
    vorschauMarke: "ቅድሚ ምርኣይ",
    speed: "ቅልጡፍነት",
    start: "ጀምር",
    bremsen: "ፍረኖ",
    bereit: "ኣብ ጀምር ንኩሱ። ኩሎም መብራህቲ ምስ ጠፍኡ፣ ክሳብ ዝከኣል ቀልጢፍኩም ፍረኖ ሓዙ።",
    warte: "ተጸበዩ … ኣዚ ቀልጢፍኩም ኣይትኹኑ!",
    jetzt: "ሕጂ!",
    fehlstart: "ጌጋ ጅምር! መብራህቲ ከይጠፍአ ፍረኖ ሓዝኩም።",
    zuLangsam: "ኣዝዩ ዝሕመም። ብግዜኡ ፍረኖ ኣይሓዝኩምን።",
    nochmal: "ደጊም",
    deineReaktion: "ግብረ-መልሲኹም",
    ergDein: "ርሕቀት ምቑማጥኩም",
    ergDeinSub: "ምስ ሕጂ ግብረ-መልሲኹም",
    ergStrasse: "ኣብ መገዲ",
    ergStrasseSub: "ናይ ቤት ትምህርቲ ምዝዋር ተሽከርካሪ ቀላል ሕጊ",
    ergNass: "ኣብ ዝረጠበ መገዲ",
    legReaktion: "ርሕቀት ግብረ-መልሲ",
    legBrems: "ርሕቀት ፍረኖ",
    hinweisStrasse: "ኣብ መገዲ ብሓቂ ፍረኖ ክሳብ እትሓዙ ኣስታት 1 ካልኣይ ይሓልፍ። ስለዚ ሓቀኛ ርሕቀት ምቑማጥ ካብ እቲ ጸወታ ይነውሕ።",
    neuerRekord: "ሓድሽ ዝበለጸ ግዜ!",
    platz: "ካብ {m} {n} ደረጃ",
    nichtGespeichert: "ውጽኢትኩም ክዕቀብ ኣይከኣለን። ግን ክትቅጽሉ ትኽእሉ ኢኹም።",
    uebung: "ናይ ልምምድ ኩነታት፦ ውጽኢትኩም ኣይዕቀብን።",
    rankingTitel: "ደረጃ ዝርዝር",
    rankingLeer: "ኣብ ዝርዝር ገና ማንም የለን። ቀዳማይ ኩኑ!",
    rankingFehler: "ዝርዝር ክጽዓን ኣይከኣለን።",
    du: "ንስኹም",
    laden: "ይጽዓን ኣሎ …",
    fehler: "ኣይሰርሐን። በጃኹም ድሕሪ ሒደት ደጊሞም ፈትኑ።"
  }
};

/* Text holen: gewählte Sprache, sonst Deutsch, sonst der Schlüssel selbst. {n}-Platzhalter werden ersetzt. */
export function tx(sprache, schluessel, werte) {
  const t = (TEXTE[sprache] && TEXTE[sprache][schluessel]) || TEXTE.de[schluessel] || schluessel;
  if (!werte) return t;
  return Object.keys(werte).reduce(function (s, k) { return s.split("{" + k + "}").join(werte[k]); }, t);
}
