/* Texte von Spiel 9 „Schilder-Wisch“ (Id ninja) in allen 18 Sprachen (07.10.2026), Präfix ni.
   Wird von spiele/texte.js eingebunden (Hauptagent): for (sp of Object.keys(TEXTE_NINJA)) Object.assign(TEXTE[sp], TEXTE_NINJA[sp]).
   Die Namen der Schilder 101, 205, 206, 215, 237, 250, 267, 274, 274.1, 283, 286, 306, 350 stehen schon in texte.js (Schlüssel z…l);
   hier stehen die Namen der neuen Schilder (niZ…), die Kategorien nach StVO (niK…) und die Spieltexte.
   Fachbegriffe: StVO Anlage 1 = Gefahrzeichen, Anlage 2 = Vorschriftzeichen (Gebote, Verbote, Warte-/Haltgebote), Anlage 3 = Richtzeichen.
   NICHT von Muttersprachlern geprüft: rif, ckb, kmr, ps, am, ti (wie bei den bisherigen Sprachpaketen bitte gegenlesen lassen). */

export const TEXTE_NINJA = {
  de: {
    niName: "Schilder-Wisch",
    niKurz: "Wische über alle Schilder, die zur Regel passen. Falsche lässt du in Ruhe.",
    niBestwert: "Deine Bestpunktzahl",
    niNeu: "Neue Bestpunktzahl!",
    niPunkte: "Punkte",
    niBereit: "Tippe auf Start. Es gibt 3 Runden, in jeder gilt eine Regel, zum Beispiel „Wische alle Verbotsschilder“. Schilder gleiten über das Feld: Wische mit dem Finger über die passenden Schilder oder tippe sie an. Falsche Schilder lässt du in Ruhe, sie kosten Punkte. Eine Runde dauert höchstens 25 Sekunden. Danach siehst du, wie die Schilder heißen und zu welcher Gruppe sie gehören.",
    niRunde: "Runde {n} von {m}",
    niLos: "Los!",
    niRegelGefahr: "Wische alle Gefahrzeichen.",
    niRegelVerbot: "Wische alle Verbotsschilder.",
    niRegelGebot: "Wische alle Gebotsschilder.",
    niRegelVorfahrt: "Wische alle Schilder, die die Vorfahrt regeln.",
    niRegelTempo: "Wische alle Schilder, die das Tempo begrenzen.",
    niRegelHalt: "Wische alle Haltverbotsschilder.",
    niWarumGefahr: "Gefahrzeichen (Anlage 1 der StVO) warnen vor einer Gefahr. Es sind Dreiecke mit rotem Rand. Aber nicht jedes Dreieck mit rotem Rand warnt vor einer Gefahr: Zeichen 205 „Vorfahrt gewähren“ gehört nicht dazu.",
    niWarumVerbot: "Verbote sind Vorschriftzeichen (Anlage 2 der StVO): Verkehrsverbote, Geschwindigkeitsbeschränkungen, Überholverbote sowie Halt- und Parkverbote. Die meisten sind rund mit rotem Rand.",
    niWarumGebot: "Gebote sind Vorschriftzeichen (Anlage 2 der StVO). Sie schreiben vor, was du tun musst, zum Beispiel eine Fahrtrichtung einhalten oder einen Weg benutzen. Die meisten sind blau und rund.",
    niWarumVorfahrt: "Diese Schilder regeln die Vorfahrt: 205 „Vorfahrt gewähren“ und 206 „Halt! Vorfahrt gewähren“ (Vorschriftzeichen, Anlage 2) sowie 301 „Vorfahrt“ und 306 „Vorfahrtstraße“ (Richtzeichen, Anlage 3).",
    niWarumTempo: "Diese Zeichen begrenzen die Geschwindigkeit: 274 auf einer Strecke und 274.1 in einer ganzen Tempo-30-Zone. Es sind Vorschriftzeichen (Anlage 2 der StVO), genauer Verbote.",
    niWarumHalt: "Haltverbote sind Vorschriftzeichen (Anlage 2 der StVO). Bei 283 darfst du auf der Fahrbahn gar nicht halten. Bei 286 darfst du auf der Fahrbahn und bei 290.1 in der Zone höchstens 3 Minuten halten; länger nur zum Ein- oder Aussteigen und zum Be- oder Entladen.",
    niRichtigMsg: "Richtig! +{v}",
    niFalschMsg: "Falsch! −{v}",
    niVollMsg: "Alles richtig und nichts Falsches! Bonus: +{v} Punkte",
    niRundeEnde: "Runde vorbei.",
    niRundeZahlen: "{n} von {m} richtigen Schildern gewischt, {f} falsche gewischt",
    niRundePunkte: "Punkte in dieser Runde: {v}",
    niListe: "Diese Schilder waren dabei",
    niStGewischt: "gewischt",
    niStFalsch: "falsch gewischt",
    niStVerpasst: "verpasst",
    niStGemieden: "richtig gemieden",
    niWeiter: "Nächste Runde",
    niErgebnisZeigen: "Ergebnis zeigen",
    niErgRichtig: "Richtig gewischt: {n} von {m}",
    niErgFalsch: "Falsch gewischt: {n}",
    niErgVoll: "Fehlerfreie Runden: {n} von {m}",
    niHinweis: "Im echten Verkehr erkennst du Schilder an Form, Farbe und Bild. Wiederhole sie, bis du sie sicher kennst.",
    niFeldAria: "Spielfeld: Schilder gleiten vorbei. Wische oder tippe die Schilder an, die zur Regel passen.",
    niKgefahr: "Gefahrzeichen (Anlage 1 StVO)",
    niK205: "Vorschriftzeichen (Anlage 2 StVO): Wartegebot",
    niK206: "Vorschriftzeichen (Anlage 2 StVO): Haltgebot",
    niKvorrang: "Richtzeichen (Anlage 3 StVO): Vorrangzeichen",
    niKgebot: "Vorschriftzeichen (Anlage 2 StVO): Gebot",
    niKverbot: "Vorschriftzeichen (Anlage 2 StVO): Verbot",
    niKtempo: "Vorschriftzeichen (Anlage 2 StVO): Verbot, Geschwindigkeit",
    niKueberhol: "Vorschriftzeichen (Anlage 2 StVO): Verbot, Überholen",
    niKhalt: "Vorschriftzeichen (Anlage 2 StVO): Verbot, Halten",
    niKricht: "Richtzeichen (Anlage 3 StVO)",
    niZ103: "Kurve",
    niZ112: "Unebene Fahrbahn",
    niZ114: "Schleuder- oder Rutschgefahr",
    niZ133: "Fußgänger",
    niZ136: "Kinder",
    niZ142: "Wildwechsel",
    niZ209: "Vorgeschriebene Fahrtrichtung: rechts",
    niZ222: "Rechts vorbei",
    niZ239: "Gehweg",
    niZ276: "Überholverbot",
    niZ2901: "Eingeschränktes Haltverbot für eine Zone",
    niZ301: "Vorfahrt"
  },
  tr: {
    niName: "Levha Kaydır",
    niKurz: "Kurala uyan tüm levhaların üzerinden parmağını kaydır. Yanlış olanlara dokunma.",
    niBestwert: "En iyi puanın",
    niNeu: "Yeni en iyi puan!",
    niPunkte: "Puan",
    niBereit: "Başla'ya dokun. 3 tur var, her turda bir kural geçerli, örneğin “Tüm yasak levhalarını kaydır”. Levhalar alanda süzülür: parmağını uygun levhaların üzerinden kaydır ya da onlara dokun. Yanlış levhalara dokunma, puan kaybettirirler. Bir tur en fazla 25 saniye sürer. Sonra levhaların adını ve hangi gruba girdiklerini görürsün.",
    niRunde: "{n}. tur / {m}",
    niLos: "Hadi!",
    niRegelGefahr: "Tüm tehlike uyarı levhalarını kaydır.",
    niRegelVerbot: "Tüm yasak levhalarını kaydır.",
    niRegelGebot: "Tüm zorunluluk levhalarını kaydır.",
    niRegelVorfahrt: "Geçiş önceliğini düzenleyen tüm levhaları kaydır.",
    niRegelTempo: "Hızı sınırlayan tüm levhaları kaydır.",
    niRegelHalt: "Tüm durma yasağı levhalarını kaydır.",
    niWarumGefahr: "Tehlike uyarı levhaları (StVO Ek 1) bir tehlikeyi bildirir. Kırmızı kenarlı üçgenlerdir. Ama kırmızı kenarlı her üçgen bir tehlikeyi bildirmez: 205 “Yol ver” levhası bunlardan değildir.",
    niWarumVerbot: "Yasak levhaları düzenleyici levhalardır (StVO Ek 2): taşıt yasakları, hız sınırları, geçme yasakları ile durma ve park yasakları. Çoğu yuvarlaktır ve kırmızı kenarlıdır.",
    niWarumGebot: "Zorunluluk levhaları düzenleyici levhalardır (StVO Ek 2). Ne yapman gerektiğini söylerler, örneğin bir yönü izlemek ya da bir yolu kullanmak. Çoğu mavi ve yuvarlaktır.",
    niWarumVorfahrt: "Bu levhalar geçiş önceliğini düzenler: 205 “Yol ver” ve 206 “Dur, yol ver” (düzenleyici levhalar, Ek 2), ayrıca 301 “Öncelik” ve 306 “Ana yol” (Richtzeichen: bilgi ve yön levhaları, Ek 3).",
    niWarumTempo: "Bu levhalar hızı sınırlar: 274 bir yol kesiminde, 274.1 ise 30 km/h bölgesinin tamamında. Düzenleyici levhalardır (StVO Ek 2), daha doğrusu yasaklardır.",
    niWarumHalt: "Durma yasağı levhaları düzenleyici levhalardır (StVO Ek 2). 283'te taşıt yolunda hiç durmamalısın. 286'da taşıt yolunda, 290.1'de bölge içinde en fazla 3 dakika durabilirsin; daha uzun süre yalnızca araca binmek, inmek, yük yüklemek ya da boşaltmak için.",
    niRichtigMsg: "Doğru! +{v}",
    niFalschMsg: "Yanlış! −{v}",
    niVollMsg: "Hepsi doğru, hiç yanlış yok! Bonus: +{v} puan",
    niRundeEnde: "Tur bitti.",
    niRundeZahlen: "{n} / {m} doğru levha kaydırıldı, {f} yanlış levha kaydırıldı",
    niRundePunkte: "Bu turdaki puan: {v}",
    niListe: "Bu levhalar turda vardı",
    niStGewischt: "kaydırıldı",
    niStFalsch: "yanlışlıkla kaydırıldı",
    niStVerpasst: "kaçırıldı",
    niStGemieden: "doğru şekilde bırakıldı",
    niWeiter: "Sonraki tur",
    niErgebnisZeigen: "Sonucu göster",
    niErgRichtig: "Doğru kaydırılan: {n} / {m}",
    niErgFalsch: "Yanlış kaydırılan: {n}",
    niErgVoll: "Hatasız turlar: {n} / {m}",
    niHinweis: "Gerçek trafikte levhaları şekilleri, renkleri ve resimleri sayesinde tanırsın. Onları iyice öğrenene kadar tekrar et.",
    niFeldAria: "Oyun alanı: levhalar süzülerek geçer. Kurala uyan levhaların üzerinden parmağını kaydır ya da onlara dokun.",
    niKgefahr: "Tehlike uyarı levhası (StVO Ek 1)",
    niK205: "Düzenleyici levha (StVO Ek 2): bekleme zorunluluğu",
    niK206: "Düzenleyici levha (StVO Ek 2): durma zorunluluğu",
    niKvorrang: "Richtzeichen: bilgi ve yön levhası (StVO Ek 3): öncelik levhası",
    niKgebot: "Düzenleyici levha (StVO Ek 2): zorunluluk",
    niKverbot: "Düzenleyici levha (StVO Ek 2): yasak",
    niKtempo: "Düzenleyici levha (StVO Ek 2): yasak, hız",
    niKueberhol: "Düzenleyici levha (StVO Ek 2): yasak, geçme",
    niKhalt: "Düzenleyici levha (StVO Ek 2): yasak, durma",
    niKricht: "Richtzeichen: bilgi ve yön levhası (StVO Ek 3)",
    niZ103: "Viraj",
    niZ112: "Bozuk yol yüzeyi",
    niZ114: "Kayma tehlikesi",
    niZ133: "Yayalar",
    niZ136: "Çocuklar",
    niZ142: "Yaban hayvanı geçebilir",
    niZ209: "Zorunlu yön: sağ",
    niZ222: "Sağdan geç",
    niZ239: "Yaya yolu",
    niZ276: "Geçme yasağı",
    niZ2901: "Bölgesel sınırlı durma yasağı",
    niZ301: "Öncelik"
  },
  en: {
    niName: "Sign Swipe",
    niKurz: "Swipe across every sign that fits the rule. Leave the wrong ones alone.",
    niBestwert: "Your best score",
    niNeu: "New best score!",
    niPunkte: "Points",
    niBereit: "Tap Start. There are 3 rounds, and each has one rule, for example “Swipe all prohibition signs”. Signs glide across the field: swipe your finger across the right ones or tap them. Leave the wrong signs alone, they cost points. A round lasts 25 seconds at most. Afterwards you see the name and group of each sign.",
    niRunde: "Round {n} of {m}",
    niLos: "Go!",
    niRegelGefahr: "Swipe all warning signs.",
    niRegelVerbot: "Swipe all prohibition signs.",
    niRegelGebot: "Swipe all mandatory signs.",
    niRegelVorfahrt: "Swipe all signs that regulate right of way.",
    niRegelTempo: "Swipe all signs that limit speed.",
    niRegelHalt: "Swipe all no-stopping signs.",
    niWarumGefahr: "Warning signs (Annex 1 of the German road traffic regulations, StVO) warn of a danger. They are triangles with a red border. But not every triangle with a red border warns of a danger: sign 205 “Give way” is not one of them.",
    niWarumVerbot: "Prohibition signs are regulatory signs (Annex 2 StVO): traffic bans, speed limits, overtaking bans, and stopping and parking bans. Most are round with a red border.",
    niWarumGebot: "Mandatory signs are regulatory signs (Annex 2 StVO). They tell you what you must do, for example follow a direction or use a path. Most are blue and round.",
    niWarumVorfahrt: "These signs regulate right of way: 205 “Give way” and 206 “Stop and give way” (regulatory signs, Annex 2) as well as 301 “Priority” and 306 “Priority road” (Richtzeichen: information and direction signs, Annex 3).",
    niWarumTempo: "These signs limit speed: 274 on a stretch of road and 274.1 in a whole 30 zone. They are regulatory signs (Annex 2 StVO), more precisely prohibitions.",
    niWarumHalt: "No-stopping signs are regulatory signs (Annex 2 StVO). At 283 you may not stop on the carriageway at all. At 286 on the carriageway, and at 290.1 inside the zone, you may stop for 3 minutes at most; longer only to get in or out or to load or unload.",
    niRichtigMsg: "Correct! +{v}",
    niFalschMsg: "Wrong! −{v}",
    niVollMsg: "Everything right and nothing wrong! Bonus: +{v} points",
    niRundeEnde: "Round over.",
    niRundeZahlen: "{n} of {m} right signs swiped, {f} wrong signs swiped",
    niRundePunkte: "Points this round: {v}",
    niListe: "These signs were in the round",
    niStGewischt: "swiped",
    niStFalsch: "swiped by mistake",
    niStVerpasst: "missed",
    niStGemieden: "correctly left alone",
    niWeiter: "Next round",
    niErgebnisZeigen: "Show result",
    niErgRichtig: "Swiped correctly: {n} of {m}",
    niErgFalsch: "Swiped by mistake: {n}",
    niErgVoll: "Flawless rounds: {n} of {m}",
    niHinweis: "In real traffic you recognise signs by shape, colour and picture. Repeat them until you know them for sure.",
    niFeldAria: "Game field: signs glide past. Swipe or tap the signs that fit the rule.",
    niKgefahr: "Warning sign (Annex 1 StVO)",
    niK205: "Regulatory sign (Annex 2 StVO): duty to wait",
    niK206: "Regulatory sign (Annex 2 StVO): duty to stop",
    niKvorrang: "Richtzeichen (information and direction sign) (Annex 3 StVO): priority sign",
    niKgebot: "Regulatory sign (Annex 2 StVO): mandatory",
    niKverbot: "Regulatory sign (Annex 2 StVO): prohibition",
    niKtempo: "Regulatory sign (Annex 2 StVO): prohibition, speed",
    niKueberhol: "Regulatory sign (Annex 2 StVO): prohibition, overtaking",
    niKhalt: "Regulatory sign (Annex 2 StVO): prohibition, stopping",
    niKricht: "Richtzeichen (information and direction sign) (Annex 3 StVO)",
    niZ103: "Curve",
    niZ112: "Uneven road surface",
    niZ114: "Danger of skidding",
    niZ133: "Pedestrians",
    niZ136: "Children",
    niZ142: "Wild animals crossing",
    niZ209: "Mandatory direction: right",
    niZ222: "Pass on the right",
    niZ239: "Footpath",
    niZ276: "No overtaking",
    niZ2901: "Limited no-stopping zone",
    niZ301: "Priority"
  },
  ar: {
    niName: "اسحب على اللافتات",
    niKurz: "اسحب إصبعك على كل اللافتات التي تناسب القاعدة. واترك اللافتات الخاطئة.",
    niBestwert: "أفضل نتيجة لك",
    niNeu: "أفضل نتيجة جديدة!",
    niPunkte: "نقاط",
    niBereit: "اضغط على ابدأ. هناك 3 جولات، وفي كل جولة قاعدة واحدة، مثل «اسحب على كل لافتات المنع». تنزلق اللافتات عبر الحقل: اسحب إصبعك على اللافتات الصحيحة أو المسها. اترك اللافتات الخاطئة، فهي تخصم نقاطًا. تستغرق الجولة 25 ثانية على الأكثر. بعدها ترى اسم كل لافتة والمجموعة التي تنتمي إليها.",
    niRunde: "الجولة {n} من {m}",
    niLos: "هيا!",
    niRegelGefahr: "اسحب على كل علامات الخطر.",
    niRegelVerbot: "اسحب على كل لافتات المنع.",
    niRegelGebot: "اسحب على كل لافتات الإلزام.",
    niRegelVorfahrt: "اسحب على كل اللافتات التي تنظّم أولوية المرور.",
    niRegelTempo: "اسحب على كل اللافتات التي تحدّ من السرعة.",
    niRegelHalt: "اسحب على كل لافتات منع الوقوف.",
    niWarumGefahr: "علامات الخطر (الملحق 1 من قانون المرور الألماني StVO) تحذّر من خطر. وهي مثلثات بحافة حمراء. لكن ليس كل مثلث بحافة حمراء يحذّر من خطر: اللافتة 205 «أعطِ الأولوية» ليست منها.",
    niWarumVerbot: "علامات المنع هي علامات تنظيمية (الملحق 2 StVO): منع المرور، وحدود السرعة، ومنع التجاوز، ومنع الوقوف والركن. أغلبها دائري بحافة حمراء.",
    niWarumGebot: "علامات الإلزام هي علامات تنظيمية (الملحق 2 StVO). تحدد ما يجب عليك فعله، مثل اتباع اتجاه أو استخدام مسار. أغلبها زرقاء ودائرية.",
    niWarumVorfahrt: "هذه اللافتات تنظّم أولوية المرور: 205 «أعطِ الأولوية» و206 «قف وأعطِ الأولوية» (علامات تنظيمية، الملحق 2)، وكذلك 301 «أولوية» و306 «طريق ذو أولوية» (Richtzeichen: علامات المعلومات والإرشاد، الملحق 3).",
    niWarumTempo: "هذه العلامات تحدّ من السرعة: 274 على مقطع من الطريق و274.1 في منطقة 30 كاملة. وهي علامات تنظيمية (الملحق 2 StVO)، وبالتحديد علامات منع.",
    niWarumHalt: "لافتات منع الوقوف علامات تنظيمية (الملحق 2 StVO). عند 283 لا يجوز لك التوقف إطلاقًا على الطريق. عند 286 على الطريق، وعند 290.1 داخل المنطقة، يجوز التوقف 3 دقائق على الأكثر؛ وأكثر من ذلك فقط للركوب أو النزول أو للتحميل أو التفريغ.",
    niRichtigMsg: "صحيح! +{v}",
    niFalschMsg: "خطأ! −{v}",
    niVollMsg: "كل شيء صحيح ولا شيء خاطئ! مكافأة: +{v} نقطة",
    niRundeEnde: "انتهت الجولة.",
    niRundeZahlen: "سحبت على {n} من {m} لافتة صحيحة، وعلى {f} لافتة خاطئة",
    niRundePunkte: "نقاط هذه الجولة: {v}",
    niListe: "هذه اللافتات ظهرت في الجولة",
    niStGewischt: "تم السحب عليها",
    niStFalsch: "سُحب عليها بالخطأ",
    niStVerpasst: "فاتتك",
    niStGemieden: "تركتها بشكل صحيح",
    niWeiter: "الجولة التالية",
    niErgebnisZeigen: "اعرض النتيجة",
    niErgRichtig: "سحب صحيح: {n} من {m}",
    niErgFalsch: "سحب خاطئ: {n}",
    niErgVoll: "جولات بلا أخطاء: {n} من {m}",
    niHinweis: "في المرور الحقيقي تتعرف على اللافتات من شكلها ولونها وصورتها. كرّرها حتى تحفظها جيدًا.",
    niFeldAria: "ساحة اللعب: اللافتات تنزلق. اسحب أو المس اللافتات التي تناسب القاعدة.",
    niKgefahr: "علامة خطر (الملحق 1 StVO)",
    niK205: "علامة تنظيمية (الملحق 2 StVO): وجوب الانتظار",
    niK206: "علامة تنظيمية (الملحق 2 StVO): وجوب التوقف",
    niKvorrang: "Richtzeichen: علامة معلومات وإرشاد (الملحق 3 StVO): علامة أولوية",
    niKgebot: "علامة تنظيمية (الملحق 2 StVO): إلزام",
    niKverbot: "علامة تنظيمية (الملحق 2 StVO): منع",
    niKtempo: "علامة تنظيمية (الملحق 2 StVO): منع، السرعة",
    niKueberhol: "علامة تنظيمية (الملحق 2 StVO): منع، التجاوز",
    niKhalt: "علامة تنظيمية (الملحق 2 StVO): منع، الوقوف",
    niKricht: "Richtzeichen: علامة معلومات وإرشاد (الملحق 3 StVO)",
    niZ103: "منعطف",
    niZ112: "سطح طريق غير مستوٍ",
    niZ114: "خطر الانزلاق",
    niZ133: "مشاة",
    niZ136: "أطفال",
    niZ142: "عبور حيوانات برية",
    niZ209: "الاتجاه الإلزامي: يمينًا",
    niZ222: "المرور من جهة اليمين",
    niZ239: "ممر مشاة",
    niZ276: "ممنوع التجاوز",
    niZ2901: "منطقة منع الوقوف المقيّد",
    niZ301: "أولوية"
  },
  es: {
    niName: "Desliza las señales",
    niKurz: "Desliza el dedo por todas las señales que cumplan la regla. Deja en paz las incorrectas.",
    niBestwert: "Tu mejor puntuación",
    niNeu: "¡Nueva mejor puntuación!",
    niPunkte: "Puntos",
    niBereit: "Toca Empezar. Hay 3 rondas y en cada una vale una regla, por ejemplo «Desliza por todas las señales de prohibición». Las señales se deslizan por el campo: pasa el dedo por las correctas o tócalas. Deja en paz las incorrectas, te quitan puntos. Una ronda dura 25 segundos como máximo. Después ves cómo se llama cada señal y a qué grupo pertenece.",
    niRunde: "Ronda {n} de {m}",
    niLos: "¡Ya!",
    niRegelGefahr: "Desliza por todas las señales de peligro.",
    niRegelVerbot: "Desliza por todas las señales de prohibición.",
    niRegelGebot: "Desliza por todas las señales de obligación.",
    niRegelVorfahrt: "Desliza por todas las señales que regulan la prioridad.",
    niRegelTempo: "Desliza por todas las señales que limitan la velocidad.",
    niRegelHalt: "Desliza por todas las señales de parada prohibida.",
    niWarumGefahr: "Las señales de peligro (anexo 1 del reglamento alemán de tráfico, StVO) advierten de un peligro. Son triángulos con borde rojo. Pero no todo triángulo con borde rojo advierte de un peligro: la señal 205 «Ceda el paso» no es una de ellas.",
    niWarumVerbot: "Las prohibiciones son señales de reglamentación (anexo 2 StVO): prohibiciones de circular, límites de velocidad, prohibiciones de adelantar y prohibiciones de parada y estacionamiento. La mayoría son redondas con borde rojo.",
    niWarumGebot: "Las obligaciones son señales de reglamentación (anexo 2 StVO). Indican lo que debes hacer, por ejemplo seguir una dirección o usar un camino. La mayoría son azules y redondas.",
    niWarumVorfahrt: "Estas señales regulan la prioridad: 205 «Ceda el paso» y 206 «Stop» (señales de reglamentación, anexo 2), y también 301 «Prioridad» y 306 «Calle con prioridad» (Richtzeichen: señales de información y dirección, anexo 3).",
    niWarumTempo: "Estas señales limitan la velocidad: la 274 en un tramo y la 274.1 en toda una zona 30. Son señales de reglamentación (anexo 2 StVO), más exactamente prohibiciones.",
    niWarumHalt: "Las señales de parada prohibida son de reglamentación (anexo 2 StVO). Con la 283 no puedes parar en absoluto en la calzada. Con la 286 en la calzada y con la 290.1 dentro de la zona puedes parar 3 minutos como máximo; más tiempo solo para subir o bajar y para cargar o descargar.",
    niRichtigMsg: "¡Correcto! +{v}",
    niFalschMsg: "¡Incorrecto! −{v}",
    niVollMsg: "¡Todo correcto y nada incorrecto! Bonus: +{v} puntos",
    niRundeEnde: "Fin de la ronda.",
    niRundeZahlen: "{n} de {m} señales correctas, {f} incorrectas",
    niRundePunkte: "Puntos en esta ronda: {v}",
    niListe: "Estas señales han salido",
    niStGewischt: "deslizada",
    niStFalsch: "deslizada por error",
    niStVerpasst: "perdida",
    niStGemieden: "bien evitada",
    niWeiter: "Siguiente ronda",
    niErgebnisZeigen: "Ver resultado",
    niErgRichtig: "Correctas: {n} de {m}",
    niErgFalsch: "Incorrectas: {n}",
    niErgVoll: "Rondas sin errores: {n} de {m}",
    niHinweis: "En el tráfico real reconoces las señales por su forma, su color y su dibujo. Repítelas hasta conocerlas bien.",
    niFeldAria: "Campo de juego: las señales se deslizan. Desliza o toca las señales que cumplen la regla.",
    niKgefahr: "Señal de peligro (anexo 1 StVO)",
    niK205: "Señal de reglamentación (anexo 2 StVO): obligación de esperar",
    niK206: "Señal de reglamentación (anexo 2 StVO): obligación de parar",
    niKvorrang: "Richtzeichen: señal de información y dirección (anexo 3 StVO): señal de prioridad",
    niKgebot: "Señal de reglamentación (anexo 2 StVO): obligación",
    niKverbot: "Señal de reglamentación (anexo 2 StVO): prohibición",
    niKtempo: "Señal de reglamentación (anexo 2 StVO): prohibición, velocidad",
    niKueberhol: "Señal de reglamentación (anexo 2 StVO): prohibición, adelantar",
    niKhalt: "Señal de reglamentación (anexo 2 StVO): prohibición, parar",
    niKricht: "Richtzeichen: señal de información y dirección (anexo 3 StVO)",
    niZ103: "Curva",
    niZ112: "Pavimento irregular",
    niZ114: "Peligro de derrape",
    niZ133: "Peatones",
    niZ136: "Niños",
    niZ142: "Paso de animales salvajes",
    niZ209: "Sentido obligatorio: derecha",
    niZ222: "Paso obligatorio por la derecha",
    niZ239: "Camino para peatones",
    niZ276: "Adelantamiento prohibido",
    niZ2901: "Zona de parada limitada",
    niZ301: "Prioridad"
  },
  ru: {
    niName: "Проведи по знакам",
    niKurz: "Проведи пальцем по всем знакам, которые подходят к правилу. Неправильные не трогай.",
    niBestwert: "Твой лучший результат",
    niNeu: "Новый рекорд!",
    niPunkte: "Очки",
    niBereit: "Нажми «Старт». Есть 3 раунда, в каждом действует одно правило, например «Проведи по всем запрещающим знакам». Знаки плывут по полю: проведи пальцем по подходящим знакам или коснись их. Неправильные знаки не трогай, они отнимают очки. Раунд длится не дольше 25 секунд. После раунда ты увидишь название каждого знака и его группу.",
    niRunde: "Раунд {n} из {m}",
    niLos: "Поехали!",
    niRegelGefahr: "Проведи по всем предупреждающим знакам.",
    niRegelVerbot: "Проведи по всем запрещающим знакам.",
    niRegelGebot: "Проведи по всем предписывающим знакам.",
    niRegelVorfahrt: "Проведи по всем знакам, которые регулируют приоритет проезда.",
    niRegelTempo: "Проведи по всем знакам, которые ограничивают скорость.",
    niRegelHalt: "Проведи по всем знакам, запрещающим остановку.",
    niWarumGefahr: "Предупреждающие знаки (приложение 1 к правилам дорожного движения Германии, StVO) предупреждают об опасности. Это треугольники с красной каймой. Но не каждый треугольник с красной каймой предупреждает об опасности: знак 205 «Уступи дорогу» к ним не относится.",
    niWarumVerbot: "Запрещающие знаки относятся к знакам предписаний (приложение 2 StVO): запрет движения, ограничения скорости, запрет обгона, запрет остановки и стоянки. Большинство из них круглые с красной каймой.",
    niWarumGebot: "Предписывающие знаки относятся к знакам предписаний (приложение 2 StVO). Они указывают, что ты обязан сделать, например ехать в определённом направлении или пользоваться дорожкой. Большинство из них синие и круглые.",
    niWarumVorfahrt: "Эти знаки регулируют приоритет проезда: 205 «Уступи дорогу» и 206 «Стоп, уступи дорогу» (знаки предписаний, приложение 2), а также 301 «Приоритет» и 306 «Главная дорога» (Richtzeichen: информационные и указательные знаки, приложение 3).",
    niWarumTempo: "Эти знаки ограничивают скорость: 274 на участке дороги и 274.1 во всей зоне 30. Это знаки предписаний (приложение 2 StVO), точнее запреты.",
    niWarumHalt: "Знаки, запрещающие остановку, относятся к знакам предписаний (приложение 2 StVO). У знака 283 останавливаться на проезжей части нельзя совсем. У знака 286 на проезжей части и у знака 290.1 внутри зоны можно стоять не дольше 3 минут; дольше только для посадки или высадки и для погрузки или разгрузки.",
    niRichtigMsg: "Верно! +{v}",
    niFalschMsg: "Неверно! −{v}",
    niVollMsg: "Всё верно и ничего лишнего! Бонус: +{v} очков",
    niRundeEnde: "Раунд окончен.",
    niRundeZahlen: "Верных знаков: {n} из {m}, неверных: {f}",
    niRundePunkte: "Очки за этот раунд: {v}",
    niListe: "Эти знаки встретились",
    niStGewischt: "задет",
    niStFalsch: "задет по ошибке",
    niStVerpasst: "пропущен",
    niStGemieden: "правильно не тронут",
    niWeiter: "Следующий раунд",
    niErgebnisZeigen: "Показать результат",
    niErgRichtig: "Верно задето: {n} из {m}",
    niErgFalsch: "Задето по ошибке: {n}",
    niErgVoll: "Раунды без ошибок: {n} из {m}",
    niHinweis: "В реальном движении ты узнаёшь знаки по форме, цвету и рисунку. Повторяй их, пока не запомнишь надёжно.",
    niFeldAria: "Игровое поле: знаки плывут мимо. Проведи по знакам, которые подходят к правилу, или коснись их.",
    niKgefahr: "Предупреждающий знак (приложение 1 StVO)",
    niK205: "Знак предписания (приложение 2 StVO): обязанность уступить",
    niK206: "Знак предписания (приложение 2 StVO): обязанность остановиться",
    niKvorrang: "Richtzeichen: информационный и указательный знак (приложение 3 StVO): знак приоритета",
    niKgebot: "Знак предписания (приложение 2 StVO): предписание",
    niKverbot: "Знак предписания (приложение 2 StVO): запрет",
    niKtempo: "Знак предписания (приложение 2 StVO): запрет, скорость",
    niKueberhol: "Знак предписания (приложение 2 StVO): запрет, обгон",
    niKhalt: "Знак предписания (приложение 2 StVO): запрет, остановка",
    niKricht: "Richtzeichen: информационный и указательный знак (приложение 3 StVO)",
    niZ103: "Опасный поворот",
    niZ112: "Неровная дорога",
    niZ114: "Скользкая дорога",
    niZ133: "Пешеходы",
    niZ136: "Дети",
    niZ142: "Дикие животные",
    niZ209: "Движение направо",
    niZ222: "Объезд справа",
    niZ239: "Пешеходная дорожка",
    niZ276: "Обгон запрещён",
    niZ2901: "Зона ограниченного запрета остановки",
    niZ301: "Приоритет"
  },
  sr: {
    niName: "Prevuci preko znakova",
    niKurz: "Prevuci prstom preko svih znakova koji odgovaraju pravilu. Pogrešne ostavi na miru.",
    niBestwert: "Tvoj najbolji rezultat",
    niNeu: "Novi najbolji rezultat!",
    niPunkte: "Bodovi",
    niBereit: "Dodirni Start. Ima 3 runde i u svakoj važi jedno pravilo, na primer „Prevuci preko svih znakova zabrane“. Znakovi klize preko polja: prevuci prstom preko pravih ili ih dodirni. Pogrešne znakove ostavi na miru, oduzimaju bodove. Runda traje najviše 25 sekundi. Posle toga vidiš kako se koji znak zove i kojoj grupi pripada.",
    niRunde: "Runda {n} od {m}",
    niLos: "Hajde!",
    niRegelGefahr: "Prevuci preko svih znakova opasnosti.",
    niRegelVerbot: "Prevuci preko svih znakova zabrane.",
    niRegelGebot: "Prevuci preko svih znakova obaveze.",
    niRegelVorfahrt: "Prevuci preko svih znakova koji regulišu prvenstvo prolaza.",
    niRegelTempo: "Prevuci preko svih znakova koji ograničavaju brzinu.",
    niRegelHalt: "Prevuci preko svih znakova zabrane zaustavljanja.",
    niWarumGefahr: "Znakovi opasnosti (prilog 1 nemačkog pravilnika o saobraćaju, StVO) upozoravaju na opasnost. To su trouglovi sa crvenom ivicom. Ali ne upozorava svaki trougao sa crvenom ivicom na opasnost: znak 205 „Ustupi prvenstvo prolaza“ nije među njima.",
    niWarumVerbot: "Znakovi zabrane su znakovi izričitih naredbi (prilog 2 StVO): zabrane saobraćaja, ograničenja brzine, zabrane preticanja i zabrane zaustavljanja i parkiranja. Većina je okrugla sa crvenom ivicom.",
    niWarumGebot: "Znakovi obaveze su znakovi izričitih naredbi (prilog 2 StVO). Oni određuju šta moraš da uradiš, na primer da pratiš smer vožnje ili koristiš stazu. Većina je plava i okrugla.",
    niWarumVorfahrt: "Ovi znakovi regulišu prvenstvo prolaza: 205 „Ustupi prvenstvo prolaza“ i 206 „Stani, ustupi prvenstvo prolaza“ (znakovi izričitih naredbi, prilog 2), kao i 301 „Prvenstvo prolaza“ i 306 „Put sa prvenstvom prolaza“ (Richtzeichen: znakovi obaveštenja i usmeravanja, prilog 3).",
    niWarumTempo: "Ovi znakovi ograničavaju brzinu: 274 na deonici puta, a 274.1 u celoj zoni 30. To su znakovi izričitih naredbi (prilog 2 StVO), tačnije zabrane.",
    niWarumHalt: "Znakovi zabrane zaustavljanja su znakovi izričitih naredbi (prilog 2 StVO). Kod 283 uopšte ne smeš da staneš na kolovozu. Kod 286 na kolovozu i kod 290.1 u zoni smeš da staneš najviše 3 minuta; duže samo radi ulaska ili izlaska i radi utovara ili istovara.",
    niRichtigMsg: "Tačno! +{v}",
    niFalschMsg: "Pogrešno! −{v}",
    niVollMsg: "Sve tačno i ništa pogrešno! Bonus: +{v} bodova",
    niRundeEnde: "Runda je gotova.",
    niRundeZahlen: "Tačnih znakova: {n} od {m}, pogrešnih: {f}",
    niRundePunkte: "Bodovi u ovoj rundi: {v}",
    niListe: "Ovi znakovi su se pojavili",
    niStGewischt: "prevučeno",
    niStFalsch: "greškom prevučeno",
    niStVerpasst: "propušteno",
    niStGemieden: "ispravno izbegnuto",
    niWeiter: "Sledeća runda",
    niErgebnisZeigen: "Prikaži rezultat",
    niErgRichtig: "Tačno prevučeno: {n} od {m}",
    niErgFalsch: "Greškom prevučeno: {n}",
    niErgVoll: "Runde bez greške: {n} od {m}",
    niHinweis: "U pravom saobraćaju znakove prepoznaješ po obliku, boji i slici. Ponavljaj ih dok ih ne naučiš dobro.",
    niFeldAria: "Polje za igru: znakovi klize mimo. Prevuci ili dodirni znakove koji odgovaraju pravilu.",
    niKgefahr: "Znak opasnosti (prilog 1 StVO)",
    niK205: "Znak izričite naredbe (prilog 2 StVO): obaveza čekanja",
    niK206: "Znak izričite naredbe (prilog 2 StVO): obaveza zaustavljanja",
    niKvorrang: "Richtzeichen: znak obaveštenja i usmeravanja (prilog 3 StVO): znak prvenstva",
    niKgebot: "Znak izričite naredbe (prilog 2 StVO): obaveza",
    niKverbot: "Znak izričite naredbe (prilog 2 StVO): zabrana",
    niKtempo: "Znak izričite naredbe (prilog 2 StVO): zabrana, brzina",
    niKueberhol: "Znak izričite naredbe (prilog 2 StVO): zabrana, preticanje",
    niKhalt: "Znak izričite naredbe (prilog 2 StVO): zabrana, zaustavljanje",
    niKricht: "Richtzeichen: znak obaveštenja i usmeravanja (prilog 3 StVO)",
    niZ103: "Krivina",
    niZ112: "Neravan kolovoz",
    niZ114: "Opasnost od proklizavanja",
    niZ133: "Pešaci",
    niZ136: "Deca",
    niZ142: "Divlje životinje",
    niZ209: "Obavezan smer: desno",
    niZ222: "Obavezno obilaženje sa desne strane",
    niZ239: "Pešačka staza",
    niZ276: "Zabrana preticanja",
    niZ2901: "Zona ograničene zabrane zaustavljanja",
    niZ301: "Prvenstvo prolaza"
  },
  ckb: {
    niName: "تابلۆکان بخزێنە",
    niKurz: "پەنجەت بخزێنە بەسەر هەموو ئەو تابلۆیانەی لەگەڵ یاساکە دەگونجێن. ئەوانەی هەڵەن بەجێیان بهێڵە.",
    niBestwert: "باشترین خاڵی تۆ",
    niNeu: "باشترین خاڵی نوێ!",
    niPunkte: "خاڵ",
    niBereit: "کلیک لە دەستپێبکە بکە. 3 خولە هەیە و لە هەر خولێکدا یاسایەک هەیە، بۆ نموونە «هەموو تابلۆی قەدەغەکردن بخزێنە». تابلۆکان بەسەر مەیدانەکەدا دەخزێن: پەنجەت بخزێنە بەسەر ڕاستەکاندا یان دەستیان لێ بدە. تابلۆی هەڵە بەجێ بهێڵە، خاڵ لە دەست دەدەیت. هەر خولێک زۆرترین 25 چرکە دەخایەنێت. دواتر ناو و گروپی هەر تابلۆیەک دەبینیت.",
    niRunde: "خولی {n} لە {m}",
    niLos: "دەست پێبکە!",
    niRegelGefahr: "هەموو نیشانەکانی مەترسی بخزێنە.",
    niRegelVerbot: "هەموو تابلۆی قەدەغەکردن بخزێنە.",
    niRegelGebot: "هەموو تابلۆی پێویستکردن بخزێنە.",
    niRegelVorfahrt: "هەموو ئەو تابلۆیانە بخزێنە کە پێشگرتن ڕێکدەخەن.",
    niRegelTempo: "هەموو ئەو تابلۆیانە بخزێنە کە خێرایی سنووردار دەکەن.",
    niRegelHalt: "هەموو تابلۆی قەدەغەکردنی ڕاوەستان بخزێنە.",
    niWarumGefahr: "نیشانەکانی مەترسی (پاشکۆی 1ی StVO، یاسای هاتوچۆی ئەڵمانیا) ئاگاداری مەترسییەک دەکەنەوە. سێگۆشەن و لێوارێکی سووریان هەیە. بەڵام هەموو سێگۆشەیەکی لێوار سوور ئاگاداری مەترسی ناکاتەوە: نیشانەی 205 «ڕێگە بدە» لەوان نییە.",
    niWarumVerbot: "تابلۆی قەدەغەکردن نیشانەی ڕێنماییکارین (پاشکۆی 2ی StVO): قەدەغەی هاتوچۆ، سنووری خێرایی، قەدەغەی تێپەڕین و قەدەغەی ڕاوەستان و پارککردن. زۆربەیان خړن و لێوارێکی سووریان هەیە.",
    niWarumGebot: "تابلۆی پێویستکردن نیشانەی ڕێنماییکارین (پاشکۆی 2ی StVO). دیاری دەکەن چی دەبێت بیکەیت، بۆ نموونە ڕێڕەوێک بگریتەبەر یان ڕێگایەک بەکاربهێنیت. زۆربەیان شین و خړن.",
    niWarumVorfahrt: "ئەم تابلۆیانە پێشگرتن ڕێکدەخەن: 205 «ڕێگە بدە» و 206 «ڕاوەستە، ڕێگە بدە» (نیشانەی ڕێنماییکار، پاشکۆی 2)، هەروەها 301 «پێشگرتن» و 306 «ڕێگای سەرەکی» (Richtzeichen: نیشانەکانی زانیاری و ئاراستە، پاشکۆی 3).",
    niWarumTempo: "ئەم نیشانانە خێرایی سنووردار دەکەن: 274 لە بەشێکی ڕێگا و 274.1 لە هەموو ناوچەیەکی 30. نیشانەی ڕێنماییکارن (پاشکۆی 2ی StVO)، بە وردی قەدەغەن.",
    niWarumHalt: "تابلۆی قەدەغەی ڕاوەستان نیشانەی ڕێنماییکارن (پاشکۆی 2ی StVO). لە 283 ڕێگە نییە لەسەر ڕێگای ئۆتۆمبێل هیچ ڕابوەستیت. لە 286 لەسەر ڕێگا و لە 290.1 لەناو ناوچەکە زۆرترین 3 خولەک دەتوانیت ڕابوەستیت؛ زیاتر تەنها بۆ سواربوون یان دابەزین و بارکردن یان بارهەڵگرتن.",
    niRichtigMsg: "ڕاستە! +{v}",
    niFalschMsg: "هەڵەیە! −{v}",
    niVollMsg: "هەموو ڕاست و هیچ هەڵە نییە! خاڵی زیادە: +{v}",
    niRundeEnde: "خولەکە تەواو بوو.",
    niRundeZahlen: "{n} لە {m} تابلۆی ڕاست خزێنراوە، {f} تابلۆی هەڵە",
    niRundePunkte: "خاڵی ئەم خولە: {v}",
    niListe: "ئەم تابلۆیانە هاتن",
    niStGewischt: "خزێنرا",
    niStFalsch: "بە هەڵە خزێنرا",
    niStVerpasst: "بەجێ مایەوە",
    niStGemieden: "بە ڕاستی بەجێهێڵرا",
    niWeiter: "خولی داهاتوو",
    niErgebnisZeigen: "ئەنجام نیشان بدە",
    niErgRichtig: "ڕاست خزێنراو: {n} لە {m}",
    niErgFalsch: "بە هەڵە خزێنراو: {n}",
    niErgVoll: "خولی بێ هەڵە: {n} لە {m}",
    niHinweis: "لە هاتوچۆی ڕاستەقینەدا تابلۆکان بە شێوە و ڕەنگ و وێنەکەیان دەناسیتەوە. دووبارەیان بکەرەوە تا بە باشی بیانزانیت.",
    niFeldAria: "مەیدانی یاری: تابلۆکان تێدەپەڕن. ئەوانەی لەگەڵ یاساکە دەگونجێن بخزێنە یان دەستیان لێ بدە.",
    niKgefahr: "نیشانەی مەترسی (پاشکۆی 1ی StVO)",
    niK205: "نیشانەی ڕێنماییکار (پاشکۆی 2ی StVO): پێویستی چاوەڕوانی",
    niK206: "نیشانەی ڕێنماییکار (پاشکۆی 2ی StVO): پێویستی ڕاوەستان",
    niKvorrang: "Richtzeichen: نیشانەی زانیاری و ئاراستە (پاشکۆی 3ی StVO): نیشانەی پێشگرتن",
    niKgebot: "نیشانەی ڕێنماییکار (پاشکۆی 2ی StVO): پێویستکردن",
    niKverbot: "نیشانەی ڕێنماییکار (پاشکۆی 2ی StVO): قەدەغە",
    niKtempo: "نیشانەی ڕێنماییکار (پاشکۆی 2ی StVO): قەدەغە، خێرایی",
    niKueberhol: "نیشانەی ڕێنماییکار (پاشکۆی 2ی StVO): قەدەغە، تێپەڕین",
    niKhalt: "نیشانەی ڕێنماییکار (پاشکۆی 2ی StVO): قەدەغە، ڕاوەستان",
    niKricht: "Richtzeichen: نیشانەی زانیاری و ئاراستە (پاشکۆی 3ی StVO)",
    niZ103: "پێچ",
    niZ112: "ڕووی ڕێگای ناهەموار",
    niZ114: "مەترسی خزین",
    niZ133: "پیادەکان",
    niZ136: "منداڵان",
    niZ142: "پەڕینەوەی ئاژەڵی کێوی",
    niZ209: "ئاڕاستەی پێویست: ڕاست",
    niZ222: "تێپەڕین لە لای ڕاستەوە",
    niZ239: "ڕێگای پیادە",
    niZ276: "تێپەڕین قەدەغەیە",
    niZ2901: "ناوچەی قەدەغەی سنووردارکراوی ڕاوەستان",
    niZ301: "پێشگرتن"
  },
  kmr: {
    niName: "Li ser nîşanan bikişîne",
    niKurz: "Tiliya xwe li ser hemû nîşanên ku bi rêzikê re li hev tên bikişîne. Yên çewt bihêle.",
    niBestwert: "Pûana te ya herî baş",
    niNeu: "Pûana herî baş a nû!",
    niPunkte: "Pûan",
    niBereit: "Li „Dest pê bike“ bitikîne. 3 dor hene û di her dorê de rêzikek derbas dibe, mînak „Li ser hemû nîşanên qedexeyê bikişîne“. Nîşan di qadê de dişemitin: tiliya xwe li ser yên rast bikişîne an jî li wan bitikîne. Nîşanên çewt bihêle, pûanan kêm dikin. Her dor herî zêde 25 çirke dikişîne. Piştre tu dibînî ku her nîşan çi ye û ji kîjan komê ye.",
    niRunde: "Dora {n} ji {m}",
    niLos: "Here!",
    niRegelGefahr: "Li ser hemû nîşanên metirsiyê bikişîne.",
    niRegelVerbot: "Li ser hemû nîşanên qedexeyê bikişîne.",
    niRegelGebot: "Li ser hemû nîşanên mecburiyetê bikişîne.",
    niRegelVorfahrt: "Li ser hemû nîşanên ku pêşiyê rêkdixin bikişîne.",
    niRegelTempo: "Li ser hemû nîşanên ku lezê sînordar dikin bikişîne.",
    niRegelHalt: "Li ser hemû nîşanên qedexeya sekinînê bikişîne.",
    niWarumGefahr: "Nîşanên metirsiyê (pêvek 1 ya StVO, qanûna seyrûseferê ya Almanyayê) li ser metirsiyekê hişyar dikin. Sêgoşe ne û kêlekeke wan a sor heye. Lê her sêgoşeyeke bi kêlekeke sor li ser metirsiyê hişyar nake: nîşana 205 „Rê bide“ ne ji wan e.",
    niWarumVerbot: "Nîşanên qedexeyê nîşanên fermanê ne (pêvek 2 ya StVO): qedexeyên seyrûseferê, sînorên lezê, qedexeyên pêşkevtinê û qedexeyên sekinîn û parkkirinê. Piraniya wan gilover in û kêlekeke wan a sor heye.",
    niWarumGebot: "Nîşanên mecburiyetê nîşanên fermanê ne (pêvek 2 ya StVO). Dibêjin ka divê tu çi bikî, mînak ku rêyekê bigirî an riyekê bi kar bînî. Piraniya wan şîn û gilover in.",
    niWarumVorfahrt: "Ev nîşan pêşiyê rêkdixin: 205 „Rê bide“ û 206 „Raweste, rê bide“ (nîşanên fermanê, pêvek 2), her wiha 301 „Pêşî“ û 306 „Rêya sereke“ (Richtzeichen: nîşanên agahî û arastekirinê, pêvek 3).",
    niWarumTempo: "Ev nîşan lezê sînordar dikin: 274 li ser beşekî rê û 274.1 di tevahiya herêmeke 30 de. Nîşanên fermanê ne (pêvek 2 ya StVO), rasttir qedexe ne.",
    niWarumHalt: "Nîşanên qedexeya sekinînê nîşanên fermanê ne (pêvek 2 ya StVO). Li 283 qet nabe tu li ser rêyê rawestî. Li 286 li ser rê û li 290.1 di nav herêmê de tu dikarî herî zêde 3 deqeyan rawestî; ji vê zêdetir tenê ji bo siwarbûn an daketinê û ji bo barkirin an bardakirinê.",
    niRichtigMsg: "Rast! +{v}",
    niFalschMsg: "Şaş! −{v}",
    niVollMsg: "Hemû rast û tu tişt şaş nîne! Bonus: +{v} pûan",
    niRundeEnde: "Dor qediya.",
    niRundeZahlen: "{n} ji {m} nîşanên rast hatin kişandin, {f} nîşanên çewt",
    niRundePunkte: "Pûanên vê dorê: {v}",
    niListe: "Ev nîşan di dorê de bûn",
    niStGewischt: "hat kişandin",
    niStFalsch: "bi şaşî hat kişandin",
    niStVerpasst: "ji dest çû",
    niStGemieden: "rast hat hiştin",
    niWeiter: "Dora din",
    niErgebnisZeigen: "Encamê nîşan bide",
    niErgRichtig: "Rast hatin kişandin: {n} ji {m}",
    niErgFalsch: "Bi şaşî hatin kişandin: {n}",
    niErgVoll: "Dorên bê şaşî: {n} ji {m}",
    niHinweis: "Di seyrûsefera rast de tu nîşanan bi şekl, reng û wêneyê nas dikî. Wan dubare bike heta ku baş bizanî.",
    niFeldAria: "Qada lîstikê: nîşan derbas dibin. Li ser nîşanên ku bi rêzikê re li hev tên bikişîne an bitikîne.",
    niKgefahr: "Nîşana metirsiyê (pêvek 1 ya StVO)",
    niK205: "Nîşana fermanê (pêvek 2 ya StVO): mecburiyeta bendewariyê",
    niK206: "Nîşana fermanê (pêvek 2 ya StVO): mecburiyeta sekinînê",
    niKvorrang: "Richtzeichen: nîşana agahî û arastekirinê (pêvek 3 ya StVO): nîşana pêşiyê",
    niKgebot: "Nîşana fermanê (pêvek 2 ya StVO): mecburî",
    niKverbot: "Nîşana fermanê (pêvek 2 ya StVO): qedexe",
    niKtempo: "Nîşana fermanê (pêvek 2 ya StVO): qedexe, lez",
    niKueberhol: "Nîşana fermanê (pêvek 2 ya StVO): qedexe, pêşkevtin",
    niKhalt: "Nîşana fermanê (pêvek 2 ya StVO): qedexe, sekinîn",
    niKricht: "Richtzeichen: nîşana agahî û arastekirinê (pêvek 3 ya StVO)",
    niZ103: "Pêç",
    niZ112: "Rûyê rêyê yê nelihev",
    niZ114: "Metirsiya şemitînê",
    niZ133: "Peya",
    niZ136: "Zarok",
    niZ142: "Derbasbûna heywanên çolê",
    niZ209: "Arasteya mecbûrî: rast",
    niZ222: "Derbasbûn ji aliyê rastê ve",
    niZ239: "Rêya peya",
    niZ276: "Pêşkevtin qedexe ye",
    niZ2901: "Herêma qedexeya sekinînê ya sînordar",
    niZ301: "Pêşî"
  },
  hi: {
    niName: "संकेतों पर स्वाइप करें",
    niKurz: "नियम से मेल खाने वाले हर संकेत पर उंगली फेरें। गलत संकेतों को छोड़ दें।",
    niBestwert: "आपका सर्वश्रेष्ठ स्कोर",
    niNeu: "नया सर्वश्रेष्ठ स्कोर!",
    niPunkte: "अंक",
    niBereit: "“शुरू” पर टैप करें। 3 राउंड हैं और हर राउंड में एक नियम लागू होता है, जैसे “सभी निषेध संकेतों पर स्वाइप करें”। संकेत मैदान में सरकते हैं: सही संकेतों पर उंगली फेरें या उन्हें टैप करें। गलत संकेतों को छोड़ दें, वे अंक घटाते हैं। एक राउंड अधिकतम 25 सेकंड का होता है। उसके बाद आप हर संकेत का नाम और उसका समूह देखते हैं।",
    niRunde: "राउंड {n} / {m}",
    niLos: "चलो!",
    niRegelGefahr: "सभी खतरे के संकेतों पर स्वाइप करें।",
    niRegelVerbot: "सभी निषेध संकेतों पर स्वाइप करें।",
    niRegelGebot: "सभी अनिवार्य संकेतों पर स्वाइप करें।",
    niRegelVorfahrt: "रास्ते का अधिकार (वरीयता) तय करने वाले सभी संकेतों पर स्वाइप करें।",
    niRegelTempo: "गति सीमित करने वाले सभी संकेतों पर स्वाइप करें।",
    niRegelHalt: "रुकना मना करने वाले सभी संकेतों पर स्वाइप करें।",
    niWarumGefahr: "खतरे के संकेत (जर्मन यातायात नियम StVO का अनुलग्नक 1) किसी खतरे की चेतावनी देते हैं। ये लाल किनारे वाले त्रिकोण होते हैं। लेकिन लाल किनारे वाला हर त्रिकोण किसी खतरे की चेतावनी नहीं देता: संकेत 205 “रास्ता दें” उनमें नहीं आता।",
    niWarumVerbot: "निषेध संकेत आदेशात्मक संकेत हैं (StVO अनुलग्नक 2): यातायात निषेध, गति सीमाएँ, ओवरटेक निषेध तथा रुकना और पार्क करना मना। ज़्यादातर गोल होते हैं और उनका किनारा लाल होता है।",
    niWarumGebot: "अनिवार्य संकेत आदेशात्मक संकेत हैं (StVO अनुलग्नक 2)। वे बताते हैं कि आपको क्या करना है, जैसे किसी दिशा में चलना या किसी रास्ते का उपयोग करना। ज़्यादातर नीले और गोल होते हैं।",
    niWarumVorfahrt: "ये संकेत रास्ते का अधिकार तय करते हैं: 205 “रास्ता दें” और 206 “रुकें, रास्ता दें” (आदेशात्मक संकेत, अनुलग्नक 2) तथा 301 “वरीयता” और 306 “मुख्य सड़क” (Richtzeichen: सूचना और दिशा संकेत, अनुलग्नक 3)।",
    niWarumTempo: "ये संकेत गति सीमित करते हैं: 274 सड़क के एक हिस्से पर और 274.1 पूरे 30 ज़ोन में। ये आदेशात्मक संकेत हैं (StVO अनुलग्नक 2), ज़्यादा सही कहें तो निषेध।",
    niWarumHalt: "रुकना मना संकेत आदेशात्मक संकेत हैं (StVO अनुलग्नक 2)। 283 पर आप सड़क पर बिल्कुल नहीं रुक सकते। 286 पर सड़क पर और 290.1 पर ज़ोन के अंदर आप अधिकतम 3 मिनट रुक सकते हैं; इससे ज़्यादा केवल चढ़ने-उतरने या सामान चढ़ाने-उतारने के लिए।",
    niRichtigMsg: "सही! +{v}",
    niFalschMsg: "गलत! −{v}",
    niVollMsg: "सब सही और कुछ भी गलत नहीं! बोनस: +{v} अंक",
    niRundeEnde: "राउंड खत्म।",
    niRundeZahlen: "{m} में से {n} सही संकेतों पर स्वाइप किया, {f} गलत संकेतों पर",
    niRundePunkte: "इस राउंड के अंक: {v}",
    niListe: "ये संकेत आए थे",
    niStGewischt: "स्वाइप किया",
    niStFalsch: "गलती से स्वाइप किया",
    niStVerpasst: "छूट गया",
    niStGemieden: "सही छोड़ा",
    niWeiter: "अगला राउंड",
    niErgebnisZeigen: "नतीजा दिखाएँ",
    niErgRichtig: "सही स्वाइप: {m} में से {n}",
    niErgFalsch: "गलत स्वाइप: {n}",
    niErgVoll: "बिना गलती के राउंड: {m} में से {n}",
    niHinweis: "असली यातायात में आप संकेतों को उनके आकार, रंग और चित्र से पहचानते हैं। उन्हें तब तक दोहराएँ जब तक आप उन्हें पक्का न जान लें।",
    niFeldAria: "खेल का मैदान: संकेत सरकते हुए गुज़रते हैं। नियम से मेल खाने वाले संकेतों पर स्वाइप करें या उन्हें टैप करें।",
    niKgefahr: "खतरे का संकेत (StVO अनुलग्नक 1)",
    niK205: "आदेशात्मक संकेत (StVO अनुलग्नक 2): प्रतीक्षा का आदेश",
    niK206: "आदेशात्मक संकेत (StVO अनुलग्नक 2): रुकने का आदेश",
    niKvorrang: "Richtzeichen: सूचना और दिशा संकेत (StVO अनुलग्नक 3): वरीयता संकेत",
    niKgebot: "आदेशात्मक संकेत (StVO अनुलग्नक 2): अनिवार्य",
    niKverbot: "आदेशात्मक संकेत (StVO अनुलग्नक 2): निषेध",
    niKtempo: "आदेशात्मक संकेत (StVO अनुलग्नक 2): निषेध, गति",
    niKueberhol: "आदेशात्मक संकेत (StVO अनुलग्नक 2): निषेध, ओवरटेक",
    niKhalt: "आदेशात्मक संकेत (StVO अनुलग्नक 2): निषेध, रुकना",
    niKricht: "Richtzeichen: सूचना और दिशा संकेत (StVO अनुलग्नक 3)",
    niZ103: "मोड़",
    niZ112: "ऊबड़-खाबड़ सड़क",
    niZ114: "फिसलने का खतरा",
    niZ133: "पैदल यात्री",
    niZ136: "बच्चे",
    niZ142: "जंगली जानवरों का रास्ता",
    niZ209: "अनिवार्य दिशा: दाएँ",
    niZ222: "दाईं ओर से निकलें",
    niZ239: "पैदल पथ",
    niZ276: "ओवरटेक करना मना",
    niZ2901: "सीमित रुकना-मना क्षेत्र",
    niZ301: "वरीयता"
  },
  ur: {
    niName: "نشانات پر سوائپ کریں",
    niKurz: "اصول سے مطابقت رکھنے والے ہر نشان پر انگلی پھیریں۔ غلط نشانات کو چھوڑ دیں۔",
    niBestwert: "آپ کا بہترین اسکور",
    niNeu: "نیا بہترین اسکور!",
    niPunkte: "پوائنٹس",
    niBereit: "شروع پر ٹیپ کریں۔ 3 راؤنڈ ہیں اور ہر راؤنڈ میں ایک اصول لاگو ہوتا ہے، مثلاً «تمام ممانعت کے نشانات پر سوائپ کریں»۔ نشانات میدان میں سرکتے ہیں: صحیح نشانات پر انگلی پھیریں یا انہیں ٹیپ کریں۔ غلط نشانات کو چھوڑ دیں، وہ پوائنٹس کم کرتے ہیں۔ ایک راؤنڈ زیادہ سے زیادہ 25 سیکنڈ کا ہے۔ اس کے بعد آپ ہر نشان کا نام اور اس کا گروپ دیکھتے ہیں۔",
    niRunde: "راؤنڈ {n} از {m}",
    niLos: "چلیں!",
    niRegelGefahr: "تمام خطرے کے نشانات پر سوائپ کریں۔",
    niRegelVerbot: "تمام ممانعت کے نشانات پر سوائپ کریں۔",
    niRegelGebot: "تمام لازمی ہدایت کے نشانات پر سوائپ کریں۔",
    niRegelVorfahrt: "راستے کا حق طے کرنے والے تمام نشانات پر سوائپ کریں۔",
    niRegelTempo: "رفتار محدود کرنے والے تمام نشانات پر سوائپ کریں۔",
    niRegelHalt: "رکنا ممنوع قرار دینے والے تمام نشانات پر سوائپ کریں۔",
    niWarumGefahr: "خطرے کے نشانات (جرمن ٹریفک قوانین StVO کا ضمیمہ 1) کسی خطرے سے خبردار کرتے ہیں۔ یہ سرخ کنارے والی تکونیں ہیں۔ لیکن سرخ کنارے والی ہر تکون کسی خطرے سے خبردار نہیں کرتی: نشان 205 «راستہ دیں» ان میں شامل نہیں۔",
    niWarumVerbot: "ممانعت کے نشانات حکمی نشانات ہیں (StVO ضمیمہ 2): ٹریفک کی پابندیاں، رفتار کی حدیں، اوورٹیک کرنے کی ممانعت اور رکنے اور پارک کرنے کی ممانعت۔ زیادہ تر گول ہوتے ہیں اور ان کا کنارہ سرخ ہوتا ہے۔",
    niWarumGebot: "لازمی ہدایت کے نشانات حکمی نشانات ہیں (StVO ضمیمہ 2)۔ یہ بتاتے ہیں کہ آپ کو کیا کرنا ہے، مثلاً کسی سمت میں چلنا یا کوئی راستہ استعمال کرنا۔ زیادہ تر نیلے اور گول ہوتے ہیں۔",
    niWarumVorfahrt: "یہ نشانات راستے کا حق طے کرتے ہیں: 205 «راستہ دیں» اور 206 «رکیں، راستہ دیں» (حکمی نشانات، ضمیمہ 2)، نیز 301 «ترجیح» اور 306 «ترجیحی سڑک» (Richtzeichen: معلومات اور سمت کے نشانات، ضمیمہ 3)۔",
    niWarumTempo: "یہ نشانات رفتار محدود کرتے ہیں: 274 سڑک کے ایک حصے پر اور 274.1 پورے 30 زون میں۔ یہ حکمی نشانات ہیں (StVO ضمیمہ 2)، زیادہ درست طور پر ممانعتیں۔",
    niWarumHalt: "رکنا ممنوع کے نشانات حکمی نشانات ہیں (StVO ضمیمہ 2)۔ 283 پر آپ سڑک پر بالکل نہیں رک سکتے۔ 286 پر سڑک پر اور 290.1 پر زون کے اندر آپ زیادہ سے زیادہ 3 منٹ رک سکتے ہیں؛ اس سے زیادہ صرف سوار ہونے یا اترنے اور سامان چڑھانے یا اتارنے کے لیے۔",
    niRichtigMsg: "صحیح! +{v}",
    niFalschMsg: "غلط! −{v}",
    niVollMsg: "سب صحیح اور کچھ بھی غلط نہیں! بونس: +{v} پوائنٹس",
    niRundeEnde: "راؤنڈ ختم۔",
    niRundeZahlen: "{m} میں سے {n} صحیح نشانات پر سوائپ کیا، {f} غلط نشانات پر",
    niRundePunkte: "اس راؤنڈ کے پوائنٹس: {v}",
    niListe: "یہ نشانات آئے تھے",
    niStGewischt: "سوائپ کیا",
    niStFalsch: "غلطی سے سوائپ کیا",
    niStVerpasst: "رہ گیا",
    niStGemieden: "صحیح چھوڑا",
    niWeiter: "اگلا راؤنڈ",
    niErgebnisZeigen: "نتیجہ دکھائیں",
    niErgRichtig: "صحیح سوائپ: {m} میں سے {n}",
    niErgFalsch: "غلط سوائپ: {n}",
    niErgVoll: "بغیر غلطی کے راؤنڈ: {m} میں سے {n}",
    niHinweis: "اصل ٹریفک میں آپ نشانات کو ان کی شکل، رنگ اور تصویر سے پہچانتے ہیں۔ انہیں اس وقت تک دہرائیں جب تک آپ انہیں پکی طرح نہ جان لیں۔",
    niFeldAria: "کھیل کا میدان: نشانات سرکتے ہوئے گزرتے ہیں۔ اصول سے مطابقت رکھنے والے نشانات پر سوائپ کریں یا انہیں ٹیپ کریں۔",
    niKgefahr: "خطرے کا نشان (StVO ضمیمہ 1)",
    niK205: "حکمی نشان (StVO ضمیمہ 2): انتظار کا حکم",
    niK206: "حکمی نشان (StVO ضمیمہ 2): رکنے کا حکم",
    niKvorrang: "Richtzeichen: معلومات اور سمت کا نشان (StVO ضمیمہ 3): ترجیحی نشان",
    niKgebot: "حکمی نشان (StVO ضمیمہ 2): لازمی ہدایت",
    niKverbot: "حکمی نشان (StVO ضمیمہ 2): ممانعت",
    niKtempo: "حکمی نشان (StVO ضمیمہ 2): ممانعت، رفتار",
    niKueberhol: "حکمی نشان (StVO ضمیمہ 2): ممانعت، اوورٹیک",
    niKhalt: "حکمی نشان (StVO ضمیمہ 2): ممانعت، رکنا",
    niKricht: "Richtzeichen: معلومات اور سمت کا نشان (StVO ضمیمہ 3)",
    niZ103: "موڑ",
    niZ112: "ناہموار سڑک",
    niZ114: "پھسلنے کا خطرہ",
    niZ133: "پیدل چلنے والے",
    niZ136: "بچے",
    niZ142: "جنگلی جانوروں کی گزرگاہ",
    niZ209: "لازمی سمت: دائیں",
    niZ222: "دائیں طرف سے گزریں",
    niZ239: "پیدل راستہ",
    niZ276: "اوورٹیک ممنوع",
    niZ2901: "محدود رکنا ممنوع علاقہ",
    niZ301: "ترجیح"
  },
  vi: {
    niName: "Lướt qua biển báo",
    niKurz: "Lướt ngón tay qua mọi biển báo đúng với quy tắc. Biển sai thì để yên.",
    niBestwert: "Điểm cao nhất của bạn",
    niNeu: "Điểm cao nhất mới!",
    niPunkte: "Điểm",
    niBereit: "Chạm vào Bắt đầu. Có 3 vòng, mỗi vòng có một quy tắc, ví dụ “Lướt qua mọi biển cấm”. Biển báo trượt qua sân chơi: hãy lướt ngón tay qua các biển đúng hoặc chạm vào chúng. Biển sai thì để yên, chúng làm bạn mất điểm. Mỗi vòng kéo dài tối đa 25 giây. Sau đó bạn thấy tên và nhóm của từng biển.",
    niRunde: "Vòng {n}/{m}",
    niLos: "Đi nào!",
    niRegelGefahr: "Lướt qua mọi biển báo nguy hiểm.",
    niRegelVerbot: "Lướt qua mọi biển cấm.",
    niRegelGebot: "Lướt qua mọi biển hiệu lệnh.",
    niRegelVorfahrt: "Lướt qua mọi biển điều chỉnh quyền ưu tiên.",
    niRegelTempo: "Lướt qua mọi biển hạn chế tốc độ.",
    niRegelHalt: "Lướt qua mọi biển cấm dừng.",
    niWarumGefahr: "Biển báo nguy hiểm (Phụ lục 1 của luật giao thông Đức StVO) cảnh báo một mối nguy. Đó là các hình tam giác viền đỏ. Nhưng không phải tam giác viền đỏ nào cũng cảnh báo nguy hiểm: biển 205 “Nhường đường” không thuộc nhóm đó.",
    niWarumVerbot: "Biển cấm là biển quy định (Phụ lục 2 StVO): cấm đi lại, giới hạn tốc độ, cấm vượt, cấm dừng và đỗ. Phần lớn có hình tròn viền đỏ.",
    niWarumGebot: "Biển hiệu lệnh là biển quy định (Phụ lục 2 StVO). Chúng cho biết bạn phải làm gì, ví dụ đi theo một hướng hoặc dùng một lối đi. Phần lớn có màu xanh và hình tròn.",
    niWarumVorfahrt: "Các biển này điều chỉnh quyền ưu tiên: 205 “Nhường đường” và 206 “Dừng lại, nhường đường” (biển quy định, Phụ lục 2), cũng như 301 “Ưu tiên” và 306 “Đường ưu tiên” (Richtzeichen: biển thông tin và chỉ dẫn hướng, Phụ lục 3).",
    niWarumTempo: "Các biển này hạn chế tốc độ: 274 trên một đoạn đường và 274.1 trong cả khu vực 30. Đó là biển quy định (Phụ lục 2 StVO), chính xác hơn là biển cấm.",
    niWarumHalt: "Biển cấm dừng là biển quy định (Phụ lục 2 StVO). Ở biển 283 bạn hoàn toàn không được dừng trên lòng đường. Ở biển 286 trên lòng đường và ở biển 290.1 trong khu vực, bạn được dừng tối đa 3 phút; lâu hơn chỉ để lên xuống xe hoặc bốc dỡ hàng.",
    niRichtigMsg: "Đúng! +{v}",
    niFalschMsg: "Sai! −{v}",
    niVollMsg: "Đúng hết và không sai cái nào! Thưởng: +{v} điểm",
    niRundeEnde: "Hết vòng.",
    niRundeZahlen: "Đã lướt {n}/{m} biển đúng, {f} biển sai",
    niRundePunkte: "Điểm vòng này: {v}",
    niListe: "Các biển đã xuất hiện",
    niStGewischt: "đã lướt",
    niStFalsch: "lướt nhầm",
    niStVerpasst: "bỏ lỡ",
    niStGemieden: "để yên đúng",
    niWeiter: "Vòng tiếp theo",
    niErgebnisZeigen: "Xem kết quả",
    niErgRichtig: "Lướt đúng: {n}/{m}",
    niErgFalsch: "Lướt nhầm: {n}",
    niErgVoll: "Vòng không sai: {n}/{m}",
    niHinweis: "Ngoài đời thật, bạn nhận ra biển báo qua hình dạng, màu sắc và hình vẽ. Hãy ôn lại cho đến khi nhớ chắc.",
    niFeldAria: "Sân chơi: các biển báo trượt qua. Hãy lướt hoặc chạm vào các biển đúng với quy tắc.",
    niKgefahr: "Biển báo nguy hiểm (Phụ lục 1 StVO)",
    niK205: "Biển quy định (Phụ lục 2 StVO): phải chờ",
    niK206: "Biển quy định (Phụ lục 2 StVO): phải dừng",
    niKvorrang: "Richtzeichen: biển thông tin và chỉ dẫn hướng (Phụ lục 3 StVO): biển ưu tiên",
    niKgebot: "Biển quy định (Phụ lục 2 StVO): hiệu lệnh",
    niKverbot: "Biển quy định (Phụ lục 2 StVO): cấm",
    niKtempo: "Biển quy định (Phụ lục 2 StVO): cấm, tốc độ",
    niKueberhol: "Biển quy định (Phụ lục 2 StVO): cấm, vượt",
    niKhalt: "Biển quy định (Phụ lục 2 StVO): cấm, dừng",
    niKricht: "Richtzeichen: biển thông tin và chỉ dẫn hướng (Phụ lục 3 StVO)",
    niZ103: "Đường cong",
    niZ112: "Mặt đường gồ ghề",
    niZ114: "Nguy cơ trơn trượt",
    niZ133: "Người đi bộ",
    niZ136: "Trẻ em",
    niZ142: "Thú rừng băng qua",
    niZ209: "Hướng bắt buộc: rẽ phải",
    niZ222: "Đi qua bên phải",
    niZ239: "Đường đi bộ",
    niZ276: "Cấm vượt",
    niZ2901: "Khu vực hạn chế cấm dừng",
    niZ301: "Ưu tiên"
  },
  fa: {
    niName: "کشیدن روی علامت‌ها",
    niKurz: "انگشتتان را روی همهٔ علامت‌هایی بکشید که با قانون می‌خوانند. علامت‌های نادرست را رها کنید.",
    niBestwert: "بهترین امتیاز شما",
    niNeu: "بهترین امتیاز جدید!",
    niPunkte: "امتیاز",
    niBereit: "روی شروع بزنید. 3 دور وجود دارد و در هر دور یک قانون برقرار است، مثلاً «روی همهٔ علامت‌های ممنوعیت بکشید». علامت‌ها روی صفحه می‌لغزند: انگشتتان را روی علامت‌های درست بکشید یا روی آن‌ها بزنید. علامت‌های نادرست را رها کنید، امتیاز کم می‌کنند. هر دور حداکثر 25 ثانیه طول می‌کشد. بعد از آن نام و گروه هر علامت را می‌بینید.",
    niRunde: "دور {n} از {m}",
    niLos: "شروع کن!",
    niRegelGefahr: "روی همهٔ علامت‌های خطر بکشید.",
    niRegelVerbot: "روی همهٔ علامت‌های ممنوعیت بکشید.",
    niRegelGebot: "روی همهٔ علامت‌های اجباری بکشید.",
    niRegelVorfahrt: "روی همهٔ علامت‌هایی بکشید که حق تقدم را تعیین می‌کنند.",
    niRegelTempo: "روی همهٔ علامت‌هایی بکشید که سرعت را محدود می‌کنند.",
    niRegelHalt: "روی همهٔ علامت‌های ممنوعیت توقف بکشید.",
    niWarumGefahr: "علامت‌های خطر (پیوست 1 قانون راهنمایی آلمان StVO) از یک خطر هشدار می‌دهند. آن‌ها مثلث‌هایی با لبهٔ قرمز هستند. اما هر مثلثی با لبهٔ قرمز از خطر هشدار نمی‌دهد: علامت 205 «حق تقدم بدهید» جزو آن‌ها نیست.",
    niWarumVerbot: "علامت‌های ممنوعیت جزو علامت‌های مقرراتی‌اند (پیوست 2 StVO): ممنوعیت تردد، محدودیت سرعت، ممنوعیت سبقت و ممنوعیت توقف و پارک. بیشتر آن‌ها گرد و با لبهٔ قرمزند.",
    niWarumGebot: "علامت‌های اجباری جزو علامت‌های مقرراتی‌اند (پیوست 2 StVO). آن‌ها می‌گویند چه کاری باید انجام دهید، مثلاً رعایت یک جهت یا استفاده از یک مسیر. بیشتر آن‌ها آبی و گردند.",
    niWarumVorfahrt: "این علامت‌ها حق تقدم را تعیین می‌کنند: 205 «حق تقدم بدهید» و 206 «توقف کنید، حق تقدم بدهید» (علامت‌های مقرراتی، پیوست 2) و همچنین 301 «حق تقدم» و 306 «جادهٔ اصلی» (Richtzeichen: علامت‌های اطلاع‌رسانی و جهت‌یابی، پیوست 3).",
    niWarumTempo: "این علامت‌ها سرعت را محدود می‌کنند: 274 در یک قطعه از جاده و 274.1 در یک منطقهٔ کامل 30. آن‌ها علامت‌های مقرراتی‌اند (پیوست 2 StVO)، دقیق‌تر ممنوعیت.",
    niWarumHalt: "علامت‌های ممنوعیت توقف جزو علامت‌های مقرراتی‌اند (پیوست 2 StVO). در 283 اصلاً نباید روی سواره‌رو توقف کنید. در 286 روی سواره‌رو و در 290.1 داخل منطقه حداکثر 3 دقیقه می‌توانید توقف کنید؛ بیشتر از آن فقط برای سوار و پیاده شدن یا بارگیری و باراندازی.",
    niRichtigMsg: "درست! +{v}",
    niFalschMsg: "نادرست! −{v}",
    niVollMsg: "همه درست و هیچ نادرستی نیست! پاداش: +{v} امتیاز",
    niRundeEnde: "دور تمام شد.",
    niRundeZahlen: "روی {n} از {m} علامت درست و روی {f} علامت نادرست کشیدید",
    niRundePunkte: "امتیاز این دور: {v}",
    niListe: "این علامت‌ها آمدند",
    niStGewischt: "کشیده شد",
    niStFalsch: "اشتباهی کشیده شد",
    niStVerpasst: "از دست رفت",
    niStGemieden: "درست رها شد",
    niWeiter: "دور بعدی",
    niErgebnisZeigen: "نمایش نتیجه",
    niErgRichtig: "درست کشیده شده: {n} از {m}",
    niErgFalsch: "اشتباهی کشیده شده: {n}",
    niErgVoll: "دورهای بدون خطا: {n} از {m}",
    niHinweis: "در ترافیک واقعی علامت‌ها را از شکل، رنگ و تصویرشان می‌شناسید. آن‌ها را تکرار کنید تا مطمئن بشناسید.",
    niFeldAria: "صفحهٔ بازی: علامت‌ها می‌لغزند و رد می‌شوند. روی علامت‌هایی که با قانون می‌خوانند بکشید یا بزنید.",
    niKgefahr: "علامت خطر (پیوست 1 StVO)",
    niK205: "علامت مقرراتی (پیوست 2 StVO): الزام به انتظار",
    niK206: "علامت مقرراتی (پیوست 2 StVO): الزام به توقف",
    niKvorrang: "Richtzeichen: علامت اطلاع‌رسانی و جهت‌یابی (پیوست 3 StVO): علامت حق تقدم",
    niKgebot: "علامت مقرراتی (پیوست 2 StVO): اجباری",
    niKverbot: "علامت مقرراتی (پیوست 2 StVO): ممنوعیت",
    niKtempo: "علامت مقرراتی (پیوست 2 StVO): ممنوعیت، سرعت",
    niKueberhol: "علامت مقرراتی (پیوست 2 StVO): ممنوعیت، سبقت",
    niKhalt: "علامت مقرراتی (پیوست 2 StVO): ممنوعیت، توقف",
    niKricht: "Richtzeichen: علامت اطلاع‌رسانی و جهت‌یابی (پیوست 3 StVO)",
    niZ103: "پیچ",
    niZ112: "سطح ناهموار جاده",
    niZ114: "خطر لغزندگی",
    niZ133: "عابران پیاده",
    niZ136: "کودکان",
    niZ142: "عبور حیوانات وحشی",
    niZ209: "جهت اجباری: راست",
    niZ222: "عبور از سمت راست",
    niZ239: "پیاده‌رو",
    niZ276: "سبقت ممنوع",
    niZ2901: "منطقهٔ ممنوعیت محدود توقف",
    niZ301: "حق تقدم"
  },
  rif: {
    niName: "Ɛeddi ɣef lɛalamat",
    niKurz: "Ɛeddi s uḍaḍ-ik ɣef yal lɛalama i yelhan i lqaɛida. Ur d-ṭṭef ca ɣer tid n ɣelṭ.",
    niBestwert: "Nniqaṭ-ik yelhan ugar",
    niNeu: "Nniqaṭ ijdid yelhan ugar!",
    niPunkte: "Nniqaṭ",
    niBereit: "Ṭṭef ɣer «Bdu». Llan 3 n dawr, deg yal dawr tella lqaɛida, am «Ɛeddi ɣef meṛṛa lɛalamat n lmenɛ». Lɛalamat ad ɛeddint deg uzaglu: ɛeddi s uḍaḍ-ik ɣef tid yelhan neɣ ṭṭef ɣer-sent. Ur d-ṭṭef ca ɣer tid n ɣelṭ, ad kem-ssunqeṣent nniqaṭ. Dawr yettṛaǧu ugar n 25 n tswanin. Sakin ad twalaḍ isem d tagrawt n yal lɛalama.",
    niRunde: "Dawr {n} seg {m}",
    niLos: "Yalla!",
    niRegelGefahr: "Ɛeddi ɣef meṛṛa lɛalamat n lxuṭuṛa.",
    niRegelVerbot: "Ɛeddi ɣef meṛṛa lɛalamat n lmenɛ.",
    niRegelGebot: "Ɛeddi ɣef meṛṛa lɛalamat n lwajib.",
    niRegelVorfahrt: "Ɛeddi ɣef meṛṛa lɛalamat i yessuddun lḥeqq n ɛeddi.",
    niRegelTempo: "Ɛeddi ɣef meṛṛa lɛalamat i yessnḥeddan sseṛɛa.",
    niRegelHalt: "Ɛeddi ɣef meṛṛa lɛalamat n lmenɛ n ḥbes.",
    niWarumGefahr: "Lɛalamat n lxuṭuṛa (Annexe 1 n StVO, taḍsa n uɣeṛbaz n Lalmanya) ssewwaṛent ɣef lxuṭuṛa. Ttnent d tiḍḍiwin s tgemmuyt tazeggaɣt. Maca mačči yal tiḍḍiwt s tgemmuyt tazeggaɣt tessewwaṛ ɣef lxuṭuṛa: lɛalama 205 «Fsi abrid» ur d-ttili ara seg-sent.",
    niWarumVerbot: "Lɛalamat n lmenɛ ttnent d lɛalamat n lqaɛida (Annexe 2 n StVO): lmenɛ n ubrid, ḥedd n sseṛɛa, lmenɛ n usemmed, d lmenɛ n ḥbes d usewqef. Tuget-nsent tezzugurt s tgemmuyt tazeggaɣt.",
    niWarumGebot: "Lɛalamat n lwajib ttnent d lɛalamat n lqaɛida (Annexe 2 n StVO). Ttnent-ak-d ay ilaq ad txedmeḍ, am ad tḍefreḍ tanila neɣ ad tseqdceḍ abrid. Tuget-nsent tazegzawt tezzugurt.",
    niWarumVorfahrt: "Lɛalamat-agi ssuddunt lḥeqq n ɛeddi: 205 «Fsi abrid» d 206 «Ḥbes, fsi abrid» (lɛalamat n lqaɛida, Annexe 2), akked 301 «Lḥeqq n ɛeddi» d 306 «Abrid s lḥeqq n ɛeddi» (Richtzeichen: lɛalamat n talɣut d tnila, Annexe 3).",
    niWarumTempo: "Lɛalamat-agi ssnḥeddant sseṛɛa: 274 deg tkerrust n ubrid d 274.1 deg tmnaṭ 30 meṛṛa. Ttnent d lɛalamat n lqaɛida (Annexe 2 n StVO), s tidet ugar d lmenɛ.",
    niWarumHalt: "Lɛalamat n lmenɛ n ḥbes ttnent d lɛalamat n lqaɛida (Annexe 2 n StVO). Ɣer 283 ur tezmireḍ ad tḥebseḍ ca ɣef ubrid n yimekkinen. Ɣer 286 ɣef ubrid, d ɣer 290.1 deg tmnaṭ, tezmireḍ ad tḥebseḍ 3 n tisdidin ugar; ugar n waya ɣer ukeččem neɣ tuffɣa d usɛeddi n yiɣarasen.",
    niRichtigMsg: "Ṣṣeḥ! +{v}",
    niFalschMsg: "Ɣelṭ! −{v}",
    niVollMsg: "Meṛṛa ṣṣeḥ d ur llin ɣelṭ! Bonus: +{v} n nniqaṭ",
    niRundeEnde: "Yekfa dawr.",
    niRundeZahlen: "{n} seg {m} n lɛalamat ṣṣeḥ, {f} n lɛalamat ɣelṭ",
    niRundePunkte: "Nniqaṭ n dawr-agi: {v}",
    niListe: "Lɛalamat-agi llant deg dawr",
    niStGewischt: "ɛeddi ɣef-s",
    niStFalsch: "ɛeddi ɣef-s s ɣelṭ",
    niStVerpasst: "yeɛdda-d",
    niStGemieden: "yeḥra ṣṣeḥ",
    niWeiter: "Dawr i d-iteddun",
    niErgebnisZeigen: "Ssken agmuḍ",
    niErgRichtig: "Ɛeddi ṣṣeḥ: {n} seg {m}",
    niErgFalsch: "Ɛeddi s ɣelṭ: {n}",
    niErgVoll: "Dawr war ɣelṭ: {n} seg {m}",
    niHinweis: "Di tudert tideț, tessneḍ lɛalamat s uɣawas, ccbaḥa d tugna. Ɛawed-itent alamma tessneḍ-itent yelhan.",
    niFeldAria: "Azaglu n uzzuɣ: lɛalamat ttɛeddint. Ɛeddi neɣ ṭṭef ɣer lɛalamat yelhan i lqaɛida.",
    niKgefahr: "Lɛalama n lxuṭuṛa (Annexe 1 n StVO)",
    niK205: "Lɛalama n lqaɛida (Annexe 2 n StVO): lwajib n uṭṭṛaǧu",
    niK206: "Lɛalama n lqaɛida (Annexe 2 n StVO): lwajib n ḥbes",
    niKvorrang: "Richtzeichen: lɛalama n talɣut d tnila (Annexe 3 n StVO): lɛalama n lḥeqq n ɛeddi",
    niKgebot: "Lɛalama n lqaɛida (Annexe 2 n StVO): lwajib",
    niKverbot: "Lɛalama n lqaɛida (Annexe 2 n StVO): lmenɛ",
    niKtempo: "Lɛalama n lqaɛida (Annexe 2 n StVO): lmenɛ, sseṛɛa",
    niKueberhol: "Lɛalama n lqaɛida (Annexe 2 n StVO): lmenɛ, usemmed",
    niKhalt: "Lɛalama n lqaɛida (Annexe 2 n StVO): lmenɛ, ḥbes",
    niKricht: "Richtzeichen: lɛalama n talɣut d tnila (Annexe 3 n StVO)",
    niZ103: "Tinɣeḍ",
    niZ112: "Abrid arnuɣ",
    niZ114: "Lxuṭuṛa n ukeffi",
    niZ133: "Iḍaren",
    niZ136: "Arrac",
    niZ142: "Ɛeddi n iɣersiwen n lexla",
    niZ209: "Tanila tuzzlist: ɣer yefus",
    niZ222: "Ɛeddi seg yefus",
    niZ239: "Abrid n yiḍaren",
    niZ276: "Lmenɛ n usemmed",
    niZ2901: "Tamnaṭ n lmenɛ n ḥbes yettwaḥdad",
    niZ301: "Lḥeqq n ɛeddi"
  },
  ps: {
    niName: "په نښو ګوته تېره کړئ",
    niKurz: "په ټولو هغو نښو ګوته تېره کړئ چې له قاعدې سره سمون لري. ناسمې پرېږدئ.",
    niBestwert: "ستاسو غوره نمرې",
    niNeu: "نوې غوره نمرې!",
    niPunkte: "نمرې",
    niBereit: "په پیل کېکاږئ. 3 پړاوونه شته او په هر پړاو کې یو قاعده روانه ده، لکه «په ټولو د منعې نښو ګوته تېره کړئ». نښې په میدان کې خوځېږي: په سمو نښو ګوته تېره کړئ یا ورته کېکاږئ. ناسمې نښې پرېږدئ، نمرې کموي. هر پړاو تر ډېره 25 ثانیې دوام کوي. وروسته د هرې نښې نوم او ډله وینئ.",
    niRunde: "پړاو {n} له {m} څخه",
    niLos: "مخکې!",
    niRegelGefahr: "په ټولو د خطر نښو ګوته تېره کړئ.",
    niRegelVerbot: "په ټولو د منعې نښو ګوته تېره کړئ.",
    niRegelGebot: "په ټولو د اجباري حکم نښو ګوته تېره کړئ.",
    niRegelVorfahrt: "په ټولو هغو نښو ګوته تېره کړئ چې د لومړیتوب حق تنظیموي.",
    niRegelTempo: "په ټولو هغو نښو ګوته تېره کړئ چې سرعت محدودوي.",
    niRegelHalt: "په ټولو د ودرېدو د منعې نښو ګوته تېره کړئ.",
    niWarumGefahr: "د خطر نښې (د آلمان د ترافیکي قانون StVO ضمیمه 1) له یو خطر خبرداری ورکوي. دا درې‌ګوټي دي چې سور څنډه لري. خو هر درې‌ګوټی چې سور څنډه ولري له خطر خبرداری نه ورکوي: نښه 205 «لار ورکړئ» په دې کې نه شامل ده.",
    niWarumVerbot: "د منعې نښې حکمي نښې دي (StVO ضمیمه 2): د ترافیک منع، د سرعت حدونه، د تېرېدو منع او د ودرېدو او پارک منع. ډېری یې ګردې دي او سور څنډه لري.",
    niWarumGebot: "د اجباري حکم نښې حکمي نښې دي (StVO ضمیمه 2). دا وايي چې تاسو باید څه وکړئ، لکه یو لوری تعقیبول یا یوه لار کارول. ډېری یې آبي او ګردې دي.",
    niWarumVorfahrt: "دا نښې د لومړیتوب حق تنظیموي: 205 «لار ورکړئ» او 206 «ودرېږئ، لار ورکړئ» (حکمي نښې، ضمیمه 2)، همدارنګه 301 «لومړیتوب» او 306 «اصلي سړک» (Richtzeichen: د معلوماتو او لارښوونې نښې، ضمیمه 3).",
    niWarumTempo: "دا نښې سرعت محدودوي: 274 د سړک په یوه برخه کې او 274.1 په ټوله 30 سیمه کې. دا حکمي نښې دي (StVO ضمیمه 2)، په دقیق ډول منع.",
    niWarumHalt: "د ودرېدو د منعې نښې حکمي نښې دي (StVO ضمیمه 2). په 283 کې په سړک هېڅ نه شئ ودرېدلی. په 286 کې په سړک او په 290.1 کې په سیمه کې تر ډېره 3 دقیقې ودرېدلی شئ؛ له دې زیات یوازې د سورېدو یا ښکته کېدو او د بار کولو یا بار ښکته کولو لپاره.",
    niRichtigMsg: "سم! +{v}",
    niFalschMsg: "ناسم! −{v}",
    niVollMsg: "ټول سم او هېڅ ناسم نشته! بونس: +{v} نمرې",
    niRundeEnde: "پړاو پای ته ورسېد.",
    niRundeZahlen: "له {m} څخه {n} سمې نښې، {f} ناسمې نښې",
    niRundePunkte: "د دې پړاو نمرې: {v}",
    niListe: "دا نښې په پړاو کې وې",
    niStGewischt: "ګوته پرې تېره شوه",
    niStFalsch: "په ناسمه ګوته پرې تېره شوه",
    niStVerpasst: "پاتې شوه",
    niStGemieden: "سم پرېښوول شوه",
    niWeiter: "راتلونکی پړاو",
    niErgebnisZeigen: "پایله وښایاست",
    niErgRichtig: "سم تېر شوي: له {m} څخه {n}",
    niErgFalsch: "ناسم تېر شوي: {n}",
    niErgVoll: "بې‌ناسمو پړاوونه: له {m} څخه {n}",
    niHinweis: "په ریښتینې ترافیک کې تاسو نښې د هغوی له بڼې، رنګ او انځور پېژنئ. هغوی تکرار کړئ تر څو یې ښه وپېژنئ.",
    niFeldAria: "د لوبې میدان: نښې تېرېږي. په هغو نښو ګوته تېره کړئ یا ورته کېکاږئ چې له قاعدې سره سمون لري.",
    niKgefahr: "د خطر نښه (StVO ضمیمه 1)",
    niK205: "حکمي نښه (StVO ضمیمه 2): د انتظار حکم",
    niK206: "حکمي نښه (StVO ضمیمه 2): د ودرېدو حکم",
    niKvorrang: "Richtzeichen: د معلوماتو او لارښوونې نښه (StVO ضمیمه 3): د لومړیتوب نښه",
    niKgebot: "حکمي نښه (StVO ضمیمه 2): اجباري حکم",
    niKverbot: "حکمي نښه (StVO ضمیمه 2): منع",
    niKtempo: "حکمي نښه (StVO ضمیمه 2): منع، سرعت",
    niKueberhol: "حکمي نښه (StVO ضمیمه 2): منع، تېرېدل",
    niKhalt: "حکمي نښه (StVO ضمیمه 2): منع، ودرېدل",
    niKricht: "Richtzeichen: د معلوماتو او لارښوونې نښه (StVO ضمیمه 3)",
    niZ103: "کوږ ځای",
    niZ112: "ناهواره سړک",
    niZ114: "د ښويېدو خطر",
    niZ133: "پیاده خلک",
    niZ136: "ماشومان",
    niZ142: "د ځنګلي حیواناتو تېرېدل",
    niZ209: "اجباري لوری: ښي",
    niZ222: "له ښي لوري تېرېدل",
    niZ239: "د پیاده لار",
    niZ276: "د تېرېدو منع",
    niZ2901: "د محدود ودرېدو منع سیمه",
    niZ301: "لومړیتوب"
  },
  el: {
    niName: "Σύρε πάνω στις πινακίδες",
    niKurz: "Σύρε το δάχτυλό σου πάνω από όλες τις πινακίδες που ταιριάζουν στον κανόνα. Άφησε ήσυχες τις λάθος.",
    niBestwert: "Το καλύτερο σκορ σου",
    niNeu: "Νέο καλύτερο σκορ!",
    niPunkte: "Πόντοι",
    niBereit: "Πάτα Εκκίνηση. Υπάρχουν 3 γύροι και σε κάθε γύρο ισχύει ένας κανόνας, για παράδειγμα «Σύρε πάνω σε όλες τις πινακίδες απαγόρευσης». Οι πινακίδες γλιστρούν στο πεδίο: σύρε το δάχτυλό σου πάνω στις σωστές ή πάτα τις. Άφησε ήσυχες τις λάθος πινακίδες, σου κοστίζουν πόντους. Ένας γύρος διαρκεί το πολύ 25 δευτερόλεπτα. Μετά βλέπεις πώς λέγεται κάθε πινακίδα και σε ποια ομάδα ανήκει.",
    niRunde: "Γύρος {n} από {m}",
    niLos: "Πάμε!",
    niRegelGefahr: "Σύρε πάνω σε όλες τις πινακίδες κινδύνου.",
    niRegelVerbot: "Σύρε πάνω σε όλες τις πινακίδες απαγόρευσης.",
    niRegelGebot: "Σύρε πάνω σε όλες τις πινακίδες υποχρέωσης.",
    niRegelVorfahrt: "Σύρε πάνω σε όλες τις πινακίδες που ρυθμίζουν την προτεραιότητα.",
    niRegelTempo: "Σύρε πάνω σε όλες τις πινακίδες που περιορίζουν την ταχύτητα.",
    niRegelHalt: "Σύρε πάνω σε όλες τις πινακίδες απαγόρευσης στάσης.",
    niWarumGefahr: "Οι πινακίδες κινδύνου (παράρτημα 1 του γερμανικού ΚΟΚ, StVO) προειδοποιούν για έναν κίνδυνο. Είναι τρίγωνα με κόκκινο περίγραμμα. Όμως δεν προειδοποιεί για κίνδυνο κάθε τρίγωνο με κόκκινο περίγραμμα: η πινακίδα 205 «Παραχώρηση προτεραιότητας» δεν ανήκει σε αυτές.",
    niWarumVerbot: "Οι απαγορεύσεις είναι ρυθμιστικές πινακίδες (παράρτημα 2 StVO): απαγορεύσεις κυκλοφορίας, όρια ταχύτητας, απαγορεύσεις προσπέρασης και απαγορεύσεις στάσης και στάθμευσης. Οι περισσότερες είναι στρογγυλές με κόκκινο περίγραμμα.",
    niWarumGebot: "Οι υποχρεώσεις είναι ρυθμιστικές πινακίδες (παράρτημα 2 StVO). Λένε τι πρέπει να κάνεις, για παράδειγμα να ακολουθήσεις μια κατεύθυνση ή να χρησιμοποιήσεις μια διαδρομή. Οι περισσότερες είναι μπλε και στρογγυλές.",
    niWarumVorfahrt: "Αυτές οι πινακίδες ρυθμίζουν την προτεραιότητα: 205 «Παραχώρηση προτεραιότητας» και 206 «Stop, παραχώρηση προτεραιότητας» (ρυθμιστικές πινακίδες, παράρτημα 2), καθώς και 301 «Προτεραιότητα» και 306 «Δρόμος προτεραιότητας» (Richtzeichen: πινακίδες πληροφόρησης και κατεύθυνσης, παράρτημα 3).",
    niWarumTempo: "Αυτές οι πινακίδες περιορίζουν την ταχύτητα: η 274 σε ένα τμήμα του δρόμου και η 274.1 σε ολόκληρη ζώνη 30. Είναι ρυθμιστικές πινακίδες (παράρτημα 2 StVO), πιο συγκεκριμένα απαγορεύσεις.",
    niWarumHalt: "Οι πινακίδες απαγόρευσης στάσης είναι ρυθμιστικές (παράρτημα 2 StVO). Στη 283 δεν επιτρέπεται να σταματήσεις καθόλου στο οδόστρωμα. Στη 286 στο οδόστρωμα και στη 290.1 μέσα στη ζώνη επιτρέπεται να σταματήσεις το πολύ 3 λεπτά· περισσότερο μόνο για επιβίβαση ή αποβίβαση και για φόρτωση ή εκφόρτωση.",
    niRichtigMsg: "Σωστά! +{v}",
    niFalschMsg: "Λάθος! −{v}",
    niVollMsg: "Όλα σωστά και τίποτα λάθος! Μπόνους: +{v} πόντοι",
    niRundeEnde: "Ο γύρος τελείωσε.",
    niRundeZahlen: "{n} από {m} σωστές πινακίδες, {f} λάθος",
    niRundePunkte: "Πόντοι σε αυτόν τον γύρο: {v}",
    niListe: "Αυτές οι πινακίδες εμφανίστηκαν",
    niStGewischt: "σύρθηκε",
    niStFalsch: "σύρθηκε κατά λάθος",
    niStVerpasst: "χάθηκε",
    niStGemieden: "σωστά αφέθηκε",
    niWeiter: "Επόμενος γύρος",
    niErgebnisZeigen: "Εμφάνιση αποτελέσματος",
    niErgRichtig: "Σωστά: {n} από {m}",
    niErgFalsch: "Κατά λάθος: {n}",
    niErgVoll: "Γύροι χωρίς λάθος: {n} από {m}",
    niHinweis: "Στην πραγματική κυκλοφορία αναγνωρίζεις τις πινακίδες από το σχήμα, το χρώμα και την εικόνα. Επανέλαβέ τες μέχρι να τις ξέρεις καλά.",
    niFeldAria: "Πεδίο παιχνιδιού: οι πινακίδες γλιστρούν. Σύρε ή πάτα τις πινακίδες που ταιριάζουν στον κανόνα.",
    niKgefahr: "Πινακίδα κινδύνου (παράρτημα 1 StVO)",
    niK205: "Ρυθμιστική πινακίδα (παράρτημα 2 StVO): υποχρέωση αναμονής",
    niK206: "Ρυθμιστική πινακίδα (παράρτημα 2 StVO): υποχρέωση στάσης",
    niKvorrang: "Richtzeichen: πινακίδα πληροφόρησης και κατεύθυνσης (παράρτημα 3 StVO): πινακίδα προτεραιότητας",
    niKgebot: "Ρυθμιστική πινακίδα (παράρτημα 2 StVO): υποχρέωση",
    niKverbot: "Ρυθμιστική πινακίδα (παράρτημα 2 StVO): απαγόρευση",
    niKtempo: "Ρυθμιστική πινακίδα (παράρτημα 2 StVO): απαγόρευση, ταχύτητα",
    niKueberhol: "Ρυθμιστική πινακίδα (παράρτημα 2 StVO): απαγόρευση, προσπέραση",
    niKhalt: "Ρυθμιστική πινακίδα (παράρτημα 2 StVO): απαγόρευση, στάση",
    niKricht: "Richtzeichen: πινακίδα πληροφόρησης και κατεύθυνσης (παράρτημα 3 StVO)",
    niZ103: "Στροφή",
    niZ112: "Ανώμαλο οδόστρωμα",
    niZ114: "Κίνδυνος ολίσθησης",
    niZ133: "Πεζοί",
    niZ136: "Παιδιά",
    niZ142: "Διέλευση άγριων ζώων",
    niZ209: "Υποχρεωτική κατεύθυνση: δεξιά",
    niZ222: "Προσπέραση από δεξιά",
    niZ239: "Πεζόδρομος",
    niZ276: "Απαγορεύεται η προσπέραση",
    niZ2901: "Ζώνη περιορισμένης απαγόρευσης στάσης",
    niZ301: "Προτεραιότητα"
  },
  am: {
    niName: "ምልክቶችን ያንሸራትቱ",
    niKurz: "ከደንቡ ጋር በሚስማሙ ምልክቶች ሁሉ ላይ ጣትዎን ያንሸራትቱ። ትክክል ያልሆኑትን ይተዉ።",
    niBestwert: "ከፍተኛ ነጥብዎ",
    niNeu: "አዲስ ከፍተኛ ነጥብ!",
    niPunkte: "ነጥብ",
    niBereit: "ጀምርን ይንኩ። 3 ዙሮች አሉ፣ በእያንዳንዱ ዙር አንድ ደንብ ይሠራል፣ ለምሳሌ «የክልከላ ምልክቶችን ሁሉ ያንሸራትቱ»። ምልክቶች በሜዳው ላይ ይንሸራተታሉ፦ በትክክለኞቹ ላይ ጣትዎን ያንሸራትቱ ወይም ይንኳቸው። ስህተት የሆኑትን ይተዉ፣ ነጥብ ያስቀንሳሉ። አንድ ዙር ቢበዛ 25 ሰከንድ ይወስዳል። ከዚያ በኋላ የእያንዳንዱን ምልክት ስምና ቡድን ያያሉ።",
    niRunde: "ዙር {n} ከ{m}",
    niLos: "ጀምር!",
    niRegelGefahr: "የአደጋ ማስጠንቀቂያ ምልክቶችን ሁሉ ያንሸራትቱ።",
    niRegelVerbot: "የክልከላ ምልክቶችን ሁሉ ያንሸራትቱ።",
    niRegelGebot: "የግዴታ ምልክቶችን ሁሉ ያንሸራትቱ።",
    niRegelVorfahrt: "የቅድሚያ መብትን የሚወስኑ ምልክቶችን ሁሉ ያንሸራትቱ።",
    niRegelTempo: "ፍጥነትን የሚገድቡ ምልክቶችን ሁሉ ያንሸራትቱ።",
    niRegelHalt: "መቆምን የሚከለክሉ ምልክቶችን ሁሉ ያንሸራትቱ።",
    niWarumGefahr: "የአደጋ ማስጠንቀቂያ ምልክቶች (የጀርመን የትራፊክ ሕግ StVO አባሪ 1) ስለ አደጋ ያስጠነቅቃሉ። ቀይ ጠርዝ ያላቸው ሦስት ማዕዘኖች ናቸው። ነገር ግን ቀይ ጠርዝ ያለው ሦስት ማዕዘን ሁሉ ስለ አደጋ አያስጠነቅቅም፦ ምልክት 205 «መንገድ ልቀቁ» ከእነዚህ አይደለም።",
    niWarumVerbot: "የክልከላ ምልክቶች ደንብ ሰጪ ምልክቶች ናቸው (StVO አባሪ 2)፦ የትራፊክ ክልከላዎች፣ የፍጥነት ገደቦች፣ የማለፍ ክልከላዎች እንዲሁም የመቆምና የማቆም ክልከላዎች። አብዛኞቹ ክብ ሲሆኑ ቀይ ጠርዝ አላቸው።",
    niWarumGebot: "የግዴታ ምልክቶች ደንብ ሰጪ ምልክቶች ናቸው (StVO አባሪ 2)። ምን ማድረግ እንዳለብዎ ይነግራሉ፣ ለምሳሌ አንድን አቅጣጫ መከተል ወይም መንገድ መጠቀም። አብዛኞቹ ሰማያዊና ክብ ናቸው።",
    niWarumVorfahrt: "እነዚህ ምልክቶች የቅድሚያ መብትን ይወስናሉ፦ 205 «መንገድ ልቀቁ» እና 206 «ቁሙ፣ መንገድ ልቀቁ» (ደንብ ሰጪ ምልክቶች፣ አባሪ 2)፣ እንዲሁም 301 «ቅድሚያ» እና 306 «የቅድሚያ መንገድ» (Richtzeichen፦ የመረጃና የአቅጣጫ ምልክቶች፣ አባሪ 3)።",
    niWarumTempo: "እነዚህ ምልክቶች ፍጥነትን ይገድባሉ፦ 274 በአንድ የመንገድ ክፍል ላይ፣ 274.1 ደግሞ በመላው የ30 ዞን። ደንብ ሰጪ ምልክቶች ናቸው (StVO አባሪ 2)፣ በትክክል ክልከላዎች።",
    niWarumHalt: "የመቆም ክልከላ ምልክቶች ደንብ ሰጪ ምልክቶች ናቸው (StVO አባሪ 2)። በ283 ላይ በመንገዱ ላይ ጨርሶ መቆም አይፈቀድም። በ286 በመንገዱ ላይ እና በ290.1 በዞኑ ውስጥ ቢበዛ 3 ደቂቃ መቆም ይችላሉ፤ ከዚያ በላይ ለመሳፈር ወይም ለመውረድ እንዲሁም ለመጫን ወይም ለማራገፍ ብቻ።",
    niRichtigMsg: "ትክክል! +{v}",
    niFalschMsg: "ስህተት! −{v}",
    niVollMsg: "ሁሉም ትክክል፣ ምንም ስህተት የለም! ጉርሻ፦ +{v} ነጥብ",
    niRundeEnde: "ዙሩ አልቋል።",
    niRundeZahlen: "ከ{m} ትክክለኛ ምልክቶች {n} ተንሸራተዋል፣ {f} ስህተት ምልክቶች",
    niRundePunkte: "በዚህ ዙር ያገኙት ነጥብ፦ {v}",
    niListe: "እነዚህ ምልክቶች ነበሩ",
    niStGewischt: "ተንሸራቷል",
    niStFalsch: "በስህተት ተንሸራቷል",
    niStVerpasst: "ተመልጧል",
    niStGemieden: "በትክክል ተትቷል",
    niWeiter: "ቀጣይ ዙር",
    niErgebnisZeigen: "ውጤት አሳይ",
    niErgRichtig: "በትክክል የተንሸራተቱ፦ ከ{m} {n}",
    niErgFalsch: "በስህተት የተንሸራተቱ፦ {n}",
    niErgVoll: "ከስህተት ነጻ ዙሮች፦ ከ{m} {n}",
    niHinweis: "በእውነተኛ ትራፊክ ምልክቶችን በቅርጻቸው፣ በቀለማቸውና በሥዕላቸው ያውቋቸዋል። በሚገባ እስኪያውቋቸው ድረስ ይደግሟቸው።",
    niFeldAria: "የጨዋታ ሜዳ፦ ምልክቶች ይንሸራተታሉ። ከደንቡ ጋር የሚስማሙትን ምልክቶች ያንሸራትቱ ወይም ይንኩ።",
    niKgefahr: "የአደጋ ማስጠንቀቂያ ምልክት (StVO አባሪ 1)",
    niK205: "ደንብ ሰጪ ምልክት (StVO አባሪ 2)፦ የመጠበቅ ግዴታ",
    niK206: "ደንብ ሰጪ ምልክት (StVO አባሪ 2)፦ የመቆም ግዴታ",
    niKvorrang: "Richtzeichen፦ የመረጃና የአቅጣጫ ምልክት (StVO አባሪ 3)፦ የቅድሚያ ምልክት",
    niKgebot: "ደንብ ሰጪ ምልክት (StVO አባሪ 2)፦ ግዴታ",
    niKverbot: "ደንብ ሰጪ ምልክት (StVO አባሪ 2)፦ ክልከላ",
    niKtempo: "ደንብ ሰጪ ምልክት (StVO አባሪ 2)፦ ክልከላ፣ ፍጥነት",
    niKueberhol: "ደንብ ሰጪ ምልክት (StVO አባሪ 2)፦ ክልከላ፣ ማለፍ",
    niKhalt: "ደንብ ሰጪ ምልክት (StVO አባሪ 2)፦ ክልከላ፣ መቆም",
    niKricht: "Richtzeichen፦ የመረጃና የአቅጣጫ ምልክት (StVO አባሪ 3)",
    niZ103: "መታጠፊያ",
    niZ112: "ሻካራ የመንገድ ገጽ",
    niZ114: "የመንሸራተት አደጋ",
    niZ133: "እግረኞች",
    niZ136: "ልጆች",
    niZ142: "የዱር እንስሳት መሻገሪያ",
    niZ209: "የግዴታ አቅጣጫ፦ ቀኝ",
    niZ222: "በቀኝ በኩል ማለፍ",
    niZ239: "የእግረኛ መንገድ",
    niZ276: "ማለፍ ክልክል ነው",
    niZ2901: "የተገደበ የመቆም ክልከላ ዞን",
    niZ301: "ቅድሚያ"
  },
  ti: {
    niName: "ምልክታት ኣንሸራትቱ",
    niKurz: "ምስ ሕጊ ዝሰማምዑ ምልክታት ኩሎም ብጣትኩም ኣንሸራትቱ። ጌጋ ዝኾኑ ግደፉ።",
    niBestwert: "ዝለዓለ ነጥብኩም",
    niNeu: "ሓድሽ ዝለዓለ ነጥቢ!",
    niPunkte: "ነጥቢ",
    niBereit: "ኣብ ጀምር ንኩሱ። 3 ዙርያታት ኣለዉ፣ ኣብ ነፍሲ ወከፍ ዙርያ ሓደ ሕጊ ይሰርሕ፣ ንኣብነት «ናይ ክልከላ ምልክታት ኩሉ ኣንሸራትቱ»። ምልክታት ኣብ ሜዳ ይንሸራተቱ፦ ኣብ ቅኑዓት ብጣትኩም ኣንሸራትቱ ወይ ንኩሱዎም። ጌጋ ዝኾኑ ምልክታት ግደፉ፣ ነጥቢ የጉድሉ። ሓደ ዙርያ ብዝበዝሐ 25 ካልኣይ ይወስድ። ድሕሪኡ ስምን ጉጅለን ናይ ነፍሲ ወከፍ ምልክት ትርእዩ።",
    niRunde: "ዙርያ {n} ካብ {m}",
    niLos: "ጀምሩ!",
    niRegelGefahr: "ናይ ሓደጋ ጠንቀቕታ ምልክታት ኩሉ ኣንሸራትቱ።",
    niRegelVerbot: "ናይ ክልከላ ምልክታት ኩሉ ኣንሸራትቱ።",
    niRegelGebot: "ናይ ግዴታ ምልክታት ኩሉ ኣንሸራትቱ።",
    niRegelVorfahrt: "ቀዳምነት ዝውስኑ ምልክታት ኩሉ ኣንሸራትቱ።",
    niRegelTempo: "ቅልጡፍነት ዝገድቡ ምልክታት ኩሉ ኣንሸራትቱ።",
    niRegelHalt: "ደው ምባል ዝኽልክሉ ምልክታት ኩሉ ኣንሸራትቱ።",
    niWarumGefahr: "ናይ ሓደጋ ጠንቀቕታ ምልክታት (ናይ ጀርመን ሕጊ ትራፊክ StVO ተወሳኺ 1) ብዛዕባ ሓደጋ የጠንቅቁ። ቀይሕ ጫፍ ዘለዎም ሰለስተ ኩርናዓት እዮም። ግን ቀይሕ ጫፍ ዘለዎ ሰለስተ ኩርናዕ ኩሉ ብዛዕባ ሓደጋ ኣይጠንቅቕን፦ ምልክት 205 «መገዲ ሃቡ» ካብዚኣቶም ኣይኮነን።",
    niWarumVerbot: "ናይ ክልከላ ምልክታት ሕጊ ዝህቡ ምልክታት እዮም (StVO ተወሳኺ 2)፦ ናይ ትራፊክ ክልከላታት፣ ናይ ቅልጡፍነት ዶባት፣ ናይ ምሕላፍ ክልከላታትን ናይ ደው ምባልን ምቁማትን ክልከላታትን። ብዙሓት ዙርያዊ እዮም ቀይሕ ጫፍ ድማ ኣለዎም።",
    niWarumGebot: "ናይ ግዴታ ምልክታት ሕጊ ዝህቡ ምልክታት እዮም (StVO ተወሳኺ 2)። እንታይ ክትገብሩ ከምዘለኩም ይነግሩኹም፣ ንኣብነት ሓደ ኣንፈት ምስዓብ ወይ መገዲ ምጥቃም። ብዙሓት ሰማያዊን ዙርያውን እዮም።",
    niWarumVorfahrt: "እዚ ምልክታት ቀዳምነት ይውስኑ፦ 205 «መገዲ ሃቡ»፣ 206 «ደው በሉ፣ መገዲ ሃቡ» (ሕጊ ዝህቡ ምልክታት፣ ተወሳኺ 2)፣ ከምኡ እውን 301 «ቀዳምነት»፣ 306 «ናይ ቀዳምነት መገዲ» (Richtzeichen፦ ናይ ሓበሬታን ናይ ኣንፈትን ምልክታት፣ ተወሳኺ 3)።",
    niWarumTempo: "እዚ ምልክታት ቅልጡፍነት ይገድቡ፦ 274 ኣብ ሓደ ክፋል መገዲ፣ 274.1 ድማ ኣብ ምሉእ ዞባ 30። ሕጊ ዝህቡ ምልክታት እዮም (StVO ተወሳኺ 2)፣ ብቐጥታ ክልከላታት።",
    niWarumHalt: "ናይ ደው ምባል ክልከላ ምልክታት ሕጊ ዝህቡ ምልክታት እዮም (StVO ተወሳኺ 2)። ኣብ 283 ኣብ መገዲ ጨሪስኩም ደው ክትብሉ ኣይፍቀድን። ኣብ 286 ኣብ መገዲ እና ኣብ 290.1 ኣብ ዞባ ብዝበዝሐ 3 ደቒቕ ደው ክትብሉ ትኽእሉ፤ ካብኡ ንላዕሊ ንምሳፍ ወይ ንምውራድ፣ ንምጽዓን ወይ ንምራገፍ ጥራይ።",
    niRichtigMsg: "ቅኑዕ! +{v}",
    niFalschMsg: "ጌጋ! −{v}",
    niVollMsg: "ኩሉ ቅኑዕ፣ ጌጋ የለን! ቦነስ፦ +{v} ነጥቢ",
    niRundeEnde: "ዙርያ ተወዲኡ።",
    niRundeZahlen: "ካብ {m} ቅኑዓት ምልክታት {n} ተንሸራቲቶም፣ {f} ጌጋ ምልክታት",
    niRundePunkte: "ኣብዚ ዙርያ ዝረኸብኩሞ ነጥቢ፦ {v}",
    niListe: "እዞም ምልክታት ነይሮም",
    niStGewischt: "ተንሸራቲቱ",
    niStFalsch: "ብጌጋ ተንሸራቲቱ",
    niStVerpasst: "ሓሊፉ",
    niStGemieden: "ብቕኑዕ ተሓድጉ",
    niWeiter: "ዝቕጽል ዙርያ",
    niErgebnisZeigen: "ውጽኢት ርኣዩ",
    niErgRichtig: "ብቕኑዕ ዝተንሸራተቱ፦ ካብ {m} {n}",
    niErgFalsch: "ብጌጋ ዝተንሸራተቱ፦ {n}",
    niErgVoll: "ብዘይ ጌጋ ዙርያታት፦ ካብ {m} {n}",
    niHinweis: "ኣብ ሓቀኛ ትራፊክ ምልክታት ብቕርጾም፣ ብሕብርን ብስእልን ትፈልጡዎም። ብኣግባቡ ክሳብ እትፈልጡዎም ደጋግሙዎም።",
    niFeldAria: "ሜዳ ጸወታ፦ ምልክታት ይንሸራተቱ። ምስ ሕጊ ዝሰማምዑ ምልክታት ኣንሸራትቱ ወይ ንኩሱ።",
    niKgefahr: "ናይ ሓደጋ ጠንቀቕታ ምልክት (StVO ተወሳኺ 1)",
    niK205: "ሕጊ ዝህብ ምልክት (StVO ተወሳኺ 2)፦ ናይ ምጽባይ ግዴታ",
    niK206: "ሕጊ ዝህብ ምልክት (StVO ተወሳኺ 2)፦ ናይ ደው ምባል ግዴታ",
    niKvorrang: "Richtzeichen፦ ናይ ሓበሬታን ናይ ኣንፈትን ምልክት (StVO ተወሳኺ 3)፦ ናይ ቀዳምነት ምልክት",
    niKgebot: "ሕጊ ዝህብ ምልክት (StVO ተወሳኺ 2)፦ ግዴታ",
    niKverbot: "ሕጊ ዝህብ ምልክት (StVO ተወሳኺ 2)፦ ክልከላ",
    niKtempo: "ሕጊ ዝህብ ምልክት (StVO ተወሳኺ 2)፦ ክልከላ፣ ቅልጡፍነት",
    niKueberhol: "ሕጊ ዝህብ ምልክት (StVO ተወሳኺ 2)፦ ክልከላ፣ ምሕላፍ",
    niKhalt: "ሕጊ ዝህብ ምልክት (StVO ተወሳኺ 2)፦ ክልከላ፣ ደው ምባል",
    niKricht: "Richtzeichen፦ ናይ ሓበሬታን ናይ ኣንፈትን ምልክት (StVO ተወሳኺ 3)",
    niZ103: "ዕጽዋይ",
    niZ112: "ዘይማዕረ ገጽ መገዲ",
    niZ114: "ሓደጋ ምስሓት",
    niZ133: "እግረኛታት",
    niZ136: "ቆልዑ",
    niZ142: "መሸጋገሪ ኣራዊት ዱር",
    niZ209: "ግዴታዊ ኣንፈት፦ የማን",
    niZ222: "ብየማን ምሕላፍ",
    niZ239: "መገዲ እግረኛ",
    niZ276: "ምሕላፍ ክልኩል እዩ",
    niZ2901: "ዞባ ዝተገደበ ናይ ደው ምባል ክልከላ",
    niZ301: "ቀዳምነት"
  }

};
